import prettierConfig from "eslint-config-prettier";
import prettier from "eslint-plugin-prettier";

// Lint targets the editable .cjs scripts only. The managed types/ .d.ts files
// are generated by `aic script workspace update` and are not linted.

// AM scripts run on Mozilla Rhino 1.7.14 (both the legacy and next-generation
// engines). The restrictions below are RUNTIME-VERIFIED against the sandbox —
// see docs/api/12-script-bindings-matrix.md and scripts/rhino-script-tester/.
// ecmaVersion is set high enough for the parser to PRODUCE these nodes so they
// can be flagged — parsing support is not runtime permission.
//
// PARSE ERRORS are engine-level: they fail to parse regardless of script kind,
// so they're banned for every AM script. `const` inside a function works and is
// allowed; arrow functions, template literals and ES2015 methods all work.
const rhinoParseErrors = [
  {
    selector: "VariableDeclaration[kind='let']",
    message:
      "'let' is a parse error on Rhino 1.7.14 ('missing ; before statement'). Use 'var' (or 'const' inside a function).",
  },
  {
    selector: "ForStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for-loop initializer is a parse error on Rhino 1.7.14. Use 'var'.",
  },
  {
    selector: "ForInStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for...in initializer is a parse error on Rhino 1.7.14. Use 'var'.",
  },
  {
    selector: "ForOfStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for...of initializer is a parse error on Rhino 1.7.14. Use 'var'.",
  },
  {
    selector: "ObjectExpression > Property[shorthand=true]",
    message:
      "Object shorthand ({ a }) is a parse error on Rhino 1.7.14 ('missing : after property id'). Use full { a: a } syntax.",
  },
  {
    selector: "ObjectPattern",
    message:
      "Object destructuring is a parse error on Rhino 1.7.14. Assign properties explicitly.",
  },
  {
    selector: "ArrayPattern",
    message:
      "Array destructuring is a parse error on Rhino 1.7.14. Index elements explicitly.",
  },
  {
    selector: "AssignmentPattern",
    message:
      "Default parameter values are a parse error on Rhino 1.7.14. Assign defaults inside the function body.",
  },
];

// These parse fine but `const` silently reads back `undefined`. This is
// SCOPE-dependent and was only verified in scripted-decision GLOBAL scope, so it
// is applied only to the decision-node folders below — NOT to libraries (which
// are module-scoped and use top-level `const` in the real corpus) or other
// contexts, until probed. See P1 in the review + the lib-const-* probe fixtures.
const decisionConstScopeBugs = [
  {
    selector: "Program > VariableDeclaration[kind='const']",
    message:
      "Top-level 'const' parses but reads back as undefined in a scripted-decision script on Rhino 1.7.14. Use 'var' at the top level.",
  },
  {
    selector:
      ":matches(ForStatement, ForInStatement, ForOfStatement) > BlockStatement > VariableDeclaration[kind='const']",
    message:
      "'const' inside a loop body parses but reads back as undefined on Rhino 1.7.14. Use 'var'.",
  },
];

// Quality rules applied to every script. `no-undef` is OFF: TypeScript (via the
// layered types/ .d.ts files and checkJs) is the source of truth for undefined
// bindings, so we don't duplicate it here. The per-family `globals` blocks below
// document the binding set each family sees and keep tooling consistent.
const scriptRules = {
  ...prettierConfig.rules,
  "no-inner-declarations": "off",
  "no-plusplus": ["warn", { allowForLoopAfterthoughts: true }],
  "no-alert": "error",
  "no-template-curly-in-string": "error",
  "prefer-template": "warn",
  "no-implicit-coercion": "warn",
  curly: "error",
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "require-unicode-regexp": "off",
  "no-undef": "off",
  "no-restricted-syntax": ["error", ...rhinoParseErrors],
  "prettier/prettier": "error",
};

// Common bindings present in all next-generation AM scripts (verified).
const commonGlobals = {
  logger: "readonly",
  httpClient: "readonly",
  openidm: "readonly",
  utils: "readonly",
  systemEnv: "readonly",
  realm: "readonly",
  scriptName: "readonly",
};

export default [
  // All AM scripts: Rhino syntax rules + common next-gen bindings.
  {
    files: ["*/**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: { ...commonGlobals },
    },
    plugins: { prettier },
    rules: scriptRules,
  },
  // Scripted-decision scripts (global scope) additionally ban the const-value
  // bugs verified there. Not applied to libraries/other contexts (unproven).
  {
    files: ["*/decision-node/**/*.cjs", "*/decision-node-legacy/**/*.cjs"],
    rules: {
      "no-restricted-syntax": ["error", ...rhinoParseErrors, ...decisionConstScopeBugs],
    },
  },
  // Next-generation scripted decision: decision bindings + library require().
  {
    files: ["*/decision-node/**/*.cjs"],
    languageOptions: {
      globals: {
        nodeState: "readonly",
        callbacks: "readonly",
        callbacksBuilder: "readonly",
        requestHeaders: "readonly",
        requestParameters: "readonly",
        requestCookies: "readonly",
        idRepository: "readonly",
        action: "readonly",
        outcome: "writable",
        existingSession: "readonly",
        resumedFromSuspend: "readonly",
        secrets: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "writable",
      },
    },
  },
  // Legacy scripted decision: legacy state + Java interop, NO library require().
  {
    files: ["*/decision-node-legacy/**/*.cjs"],
    languageOptions: {
      globals: {
        nodeState: "readonly",
        callbacks: "readonly",
        requestHeaders: "readonly",
        requestParameters: "readonly",
        idRepository: "readonly",
        action: "readonly",
        outcome: "writable",
        existingSession: "readonly",
        sharedState: "readonly",
        transientState: "readonly",
        JavaImporter: "readonly",
      },
    },
  },
  // Library scripts: CommonJS module mechanics (next-gen only).
  {
    files: ["*/lib/**/*.cjs"],
    languageOptions: {
      globals: {
        require: "readonly",
        module: "readonly",
        exports: "writable",
      },
    },
  },
  // OIDC claims (legacy binding set).
  {
    files: ["*/oidc-claims/**/*.cjs"],
    languageOptions: {
      globals: {
        scopes: "readonly",
        claims: "readonly",
        requestedClaims: "readonly",
        claimObjects: "readonly",
        requestedTypedClaims: "readonly",
        claimsLocales: "readonly",
        requestProperties: "readonly",
        clientProperties: "readonly",
        identity: "readonly",
        session: "readonly",
        JavaImporter: "readonly",
        org: "readonly",
        java: "readonly",
      },
    },
  },
  // The managed types/ .d.ts files are tool-generated; don't lint them.
  { ignores: ["**/types/**"] },
];
