import prettierConfig from "eslint-config-prettier";
import prettier from "eslint-plugin-prettier";

// Lint targets the editable .cjs scripts only. The managed types/ .d.ts files
// are generated by `aic script workspace update` and are not linted.

// IDM scripts also run on Rhino, but their exact runtime behaviour (let/const
// support, available globals) is NOT yet verified — there is no IDM sample
// corpus and no IDM probe has run. Per the uplift plan, do NOT copy AM's
// Rhino syntax bans here: add them only once an IDM endpoint/schedule probe
// confirms them (see docs/api/12-script-bindings-matrix.md, IDM open items).
//
// `no-undef` is OFF for the same reason as AM: TypeScript (types/ + checkJs) is
// the source of truth for undefined bindings.
const scriptRules = {
  ...prettierConfig.rules,
  "no-inner-declarations": "off",
  "no-plusplus": ["warn", { allowForLoopAfterthoughts: true }],
  "no-alert": "error",
  "no-template-curly-in-string": "error",
  "prefer-template": "warn",
  "no-implicit-coercion": "warn",
  curly: "error",
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "require-unicode-regexp": "off",
  "no-undef": "off",
  "prettier/prettier": "error",
};

// Common IDM bindings (inferred from the prior template + docs; not yet probed).
const commonGlobals = {
  openidm: "readonly",
  logger: "readonly",
};

export default [
  // All IDM scripts: quality rules + common bindings.
  {
    files: ["endpoint/**/*.cjs", "schedule/**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: { ...commonGlobals },
    },
    plugins: { prettier },
    rules: scriptRules,
  },
  // Endpoint scripts additionally get the CREST request + context bindings.
  // Schedule scripts run on a trigger (no HTTP request), so they get neither —
  // see types/schedule.d.ts.
  {
    files: ["endpoint/**/*.cjs"],
    languageOptions: {
      globals: {
        request: "readonly",
        context: "readonly",
      },
    },
  },
  // The managed types/ .d.ts files are tool-generated; don't lint them.
  { ignores: ["**/types/**"] },
];
