import prettierConfig from "eslint-config-prettier";
import prettier from "eslint-plugin-prettier";

// Lint targets the editable .cjs scripts only. The managed types/ .d.ts files
// are generated by `aic script workspace update` and are not linted.

// IDM's script engine is NEWER than AM's Rhino 1.7.14 — verified 2026-06-04 by
// probing an endpoint (see docs/api/11 + docs/api/12 IDM section). It DOES
// support let, const (top-level + in-function), arrow functions, template
// literals, object shorthand, and destructuring — so AM's bans on those must
// NOT be copied here. It does NOT compile default parameters or `const` in a
// for/for-of initializer (the endpoint fails to register), so those are banned.
//
// `no-undef` is OFF for the same reason as AM: TypeScript (types/ + checkJs) is
// the source of truth for undefined bindings.
const idmSyntaxRestrictions = [
  {
    // Function-param defaults only (destructuring defaults are fine).
    selector:
      ":matches(FunctionDeclaration, FunctionExpression, ArrowFunctionExpression) > AssignmentPattern",
    message:
      "Default parameter values fail to compile on the IDM script engine (verified). Assign defaults inside the function body.",
  },
  {
    selector: "ForStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for-loop initializer fails to compile on the IDM script engine. Use 'let' or 'var'.",
  },
  {
    selector: "ForInStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for...in initializer fails to compile on the IDM script engine. Use 'let' or 'var'.",
  },
  {
    selector: "ForOfStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for...of initializer fails to compile on the IDM script engine. Use 'let' or 'var'.",
  },
];

const scriptRules = {
  ...prettierConfig.rules,
  "no-inner-declarations": "off",
  "no-plusplus": ["warn", { allowForLoopAfterthoughts: true }],
  "no-alert": "error",
  "no-template-curly-in-string": "error",
  "prefer-template": "warn",
  "no-implicit-coercion": "warn",
  curly: "error",
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "require-unicode-regexp": "off",
  "no-undef": "off",
  "no-restricted-syntax": ["error", ...idmSyntaxRestrictions],
  "prettier/prettier": "error",
};

// Common IDM bindings (inferred from the prior template + docs; not yet probed).
const commonGlobals = {
  openidm: "readonly",
  logger: "readonly",
};

export default [
  // All IDM scripts: quality rules + common bindings.
  {
    files: ["endpoint/**/*.cjs", "schedule/**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: { ...commonGlobals },
    },
    plugins: { prettier },
    rules: scriptRules,
  },
  // Endpoint scripts additionally get the CREST request + context bindings.
  // Schedule scripts run on a trigger (no HTTP request), so they get neither —
  // see types/schedule.d.ts.
  {
    files: ["endpoint/**/*.cjs"],
    languageOptions: {
      globals: {
        request: "readonly",
        context: "readonly",
      },
    },
  },
  // The managed types/ .d.ts files are tool-generated; don't lint them.
  { ignores: ["**/types/**"] },
];
