//! Pure IDM sync-mapping to TypeScript declaration generation.

use crate::Result;
use serde_json::Value;
use std::path::PathBuf;

use super::managed_types::pascal_case;

const SHARED_TYPES: &str = r#"// GENERATED by `aic workspace update` from the tenant's sync mappings.
// Do not edit; re-run workspace update to refresh.
interface ReconSummary {
  ABSENT?: number;
  CONFIRMED?: number;
  AMBIGUOUS?: number;
  FOUND?: number;
  MISSING?: number;
  UNQUALIFIED?: number;
  SOURCE_MISSING?: number;
  TARGET_IGNORED?: number;
  SOURCE_IGNORED?: number;
  UNASSIGNED?: number;
  LINK_ONLY?: number;
  ALL_GONE?: number;
  FOUND_ALREADY_LINKED?: number;
  NOTVALID?: number;
  TARGET_CHANGED?: number;
  SOURCE_TARGET_CONFLICT?: number;
  name?: string;
  processed?: number;
  startTime?: string;
  endTime?: string;
  duration?: number;
  entries?: any[];
  [key: string]: any;
}
"#;

const CATEGORIES: &[Category] = &[
    Category::Behaviour,
    Category::Result,
    Category::Transform,
    Category::Condition,
];

#[derive(Clone, Copy)]
enum Category {
    Behaviour,
    Result,
    Transform,
    Condition,
}

impl Category {
    fn as_str(self) -> &'static str {
        match self {
            Category::Behaviour => "behaviour",
            Category::Result => "result",
            Category::Transform => "transform",
            Category::Condition => "condition",
        }
    }
}

/// Workspace-relative path -> file contents for generated sync-mapping types.
/// `sync_doc` is the parsed body of `GET /openidm/config/sync`.
pub fn generate(sync_doc: &Value, _managed_schema: &Value) -> Result<Vec<(PathBuf, String)>> {
    let mut mappings = sync_doc
        .get("mappings")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|mapping| {
            let name = mapping.get("name").and_then(Value::as_str)?;
            Some((name, mapping))
        })
        .collect::<Vec<_>>();
    mappings.sort_by(|a, b| a.0.cmp(b.0));

    let mut files = vec![(
        PathBuf::from("idm/types/sync/_shared.d.ts"),
        SHARED_TYPES.to_string(),
    )];
    for (name, mapping) in mappings {
        let source_ty = record_type(mapping.get("source").and_then(Value::as_str));
        let target_ty = record_type(mapping.get("target").and_then(Value::as_str));
        for category in CATEGORIES {
            files.push((
                PathBuf::from("idm/types/sync").join(format!(
                    "{}.{}.d.ts",
                    safe_filename(name),
                    category.as_str()
                )),
                render_mapping_bindings(*category, &source_ty, &target_ty),
            ));
        }
    }
    Ok(files)
}

fn record_type(resource: Option<&str>) -> String {
    let Some(obj) = resource.and_then(|resource| resource.strip_prefix("managed/")) else {
        return "Record<string, any>".to_string();
    };
    if obj.is_empty() || obj.contains('/') {
        return "Record<string, any>".to_string();
    }
    pascal_case(obj)
}

fn safe_filename(name: &str) -> String {
    name.replace(['/', '\\'], "_")
}

fn render_mapping_bindings(category: Category, source_ty: &str, target_ty: &str) -> String {
    match category {
        Category::Behaviour => format!(
            "declare const source: {source_ty};\ndeclare const target: {target_ty};\ndeclare const oldTarget: {target_ty} | null;\ndeclare const oldSource: {source_ty} | null;\ndeclare const situation: string;\ndeclare const mappingConfig: any;\ndeclare const linkQualifier: string;\ndeclare const sync: (...args: any[]) => any;\n"
        ),
        Category::Result => {
            "declare const source: ReconSummary;\ndeclare const target: ReconSummary;\ndeclare const mappingConfig: any;\ndeclare const sync: (...args: any[]) => any;\n"
                .to_string()
        }
        Category::Transform => format!(
            "/** Attribute-mapped transforms receive the raw attribute value -- cast as needed. */\ndeclare const source: {source_ty};\ndeclare const linkQualifier: string;\ndeclare const sync: (...args: any[]) => any;\n"
        ),
        Category::Condition => format!(
            "declare const target: {target_ty};\ndeclare const object: {source_ty};\ndeclare const oldTarget: {target_ty} | null;\ndeclare const linkQualifier: string;\ndeclare const sync: (...args: any[]) => any;\n"
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn contents(files: &[(PathBuf, String)], path: &str) -> String {
        files
            .iter()
            .find(|(candidate, _)| candidate == &PathBuf::from(path))
            .unwrap_or_else(|| panic!("missing generated file: {path}"))
            .1
            .clone()
    }

    fn managed_schema() -> Value {
        json!({
            "objects": [
                {"name": "test_from", "schema": {"properties": {}}},
                {"name": "test_to", "schema": {"properties": {}}}
            ]
        })
    }

    #[test]
    fn emits_shared_and_precise_managed_mapping_bindings() {
        let files = generate(
            &json!({
                "mappings": [{
                    "name": "managedTest_from_managedTest_to",
                    "source": "managed/test_from",
                    "target": "managed/test_to"
                }]
            }),
            &managed_schema(),
        )
        .unwrap();

        assert!(contents(&files, "idm/types/sync/_shared.d.ts").contains("interface ReconSummary"));

        let behaviour = contents(
            &files,
            "idm/types/sync/managedTest_from_managedTest_to.behaviour.d.ts",
        );
        assert!(behaviour.contains("declare const source: TestFrom;"));
        assert!(behaviour.contains("declare const target: TestTo;"));
        assert!(behaviour.contains("declare const oldTarget: TestTo | null;"));
        assert!(behaviour.contains("declare const oldSource: TestFrom | null;"));

        let result = contents(
            &files,
            "idm/types/sync/managedTest_from_managedTest_to.result.d.ts",
        );
        assert!(result.contains("declare const source: ReconSummary;"));
        assert!(result.contains("declare const target: ReconSummary;"));

        let transform = contents(
            &files,
            "idm/types/sync/managedTest_from_managedTest_to.transform.d.ts",
        );
        assert!(transform.contains("declare const source: TestFrom;"));
        assert!(transform.contains("Attribute-mapped transforms receive the raw attribute value"));
        assert!(!transform.contains("declare const target:"));

        let condition = contents(
            &files,
            "idm/types/sync/managedTest_from_managedTest_to.condition.d.ts",
        );
        assert!(condition.contains("declare const target: TestTo;"));
        assert!(condition.contains("declare const object: TestFrom;"));
        assert!(condition.contains("declare const oldTarget: TestTo | null;"));
        assert!(!condition.contains("declare const source:"));
    }

    #[test]
    fn system_or_unknown_resources_are_loose_records() {
        let files = generate(
            &json!({
                "mappings": [{
                    "name": "system_to_managed",
                    "source": "system/ldap/account",
                    "target": "managed/test_to"
                }]
            }),
            &managed_schema(),
        )
        .unwrap();

        let behaviour = contents(&files, "idm/types/sync/system_to_managed.behaviour.d.ts");
        assert!(behaviour.contains("declare const source: Record<string, any>;"));
        assert!(behaviour.contains("declare const target: TestTo;"));
    }

    #[test]
    fn mappings_are_sorted_for_stable_output() {
        let files = generate(
            &json!({
                "mappings": [
                    {"name": "z_map", "source": "managed/test_from", "target": "managed/test_to"},
                    {"name": "a_map", "source": "managed/test_from", "target": "managed/test_to"}
                ]
            }),
            &managed_schema(),
        )
        .unwrap();
        let paths = files
            .iter()
            .map(|(path, _)| path.to_string_lossy().into_owned())
            .collect::<Vec<_>>();

        assert_eq!(paths[0], "idm/types/sync/_shared.d.ts");
        assert_eq!(paths[1], "idm/types/sync/a_map.behaviour.d.ts");
        assert_eq!(paths[5], "idm/types/sync/z_map.behaviour.d.ts");
    }

    #[test]
    fn shared_type_is_present_even_without_mappings() {
        let files = generate(&json!({}), &json!({})).unwrap();
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].0, PathBuf::from("idm/types/sync/_shared.d.ts"));
        assert!(files[0].1.contains("ABSENT?: number;"));
        assert!(files[0].1.contains("entries?: any[];"));
    }
}
