//! Workspace scaffolding + template versioning (kind-agnostic).
//!
//! Scaffolds a **per-tenant** workspace at `workspace/<tenant>/` covering both
//! realms: AM scripts live under `am/<realm>/<type>/` (realm-scoped), IDM
//! endpoints under `idm/endpoint/` (tenant-global, no realm). Type definitions
//! are shared at the `am/` level. Templates are embedded at compile time; a
//! [`TEMPLATES_VERSION`] lets us ship updated types/config to existing
//! workspaces via `aic workspace update`.

use crate::Result;
use crate::app::App;
use crate::app::event::ToastKind;
use crate::config::ProjectConfig;
use crate::scripts::ts_project::PROJECT_DIR;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Bump whenever an embedded template below changes. `workspace update`
/// re-copies the managed files when this exceeds a tree's recorded version.
pub const TEMPLATES_VERSION: u32 = 75;

/// Realms an AM tree is scaffolded for. AIC only has `alpha` + `bravo`.
const REALMS: &[&str] = &["alpha", "bravo"];

/// Managed files (regenerated by `workspace update`): shared type defs, base
/// tsconfig, and ESLint config for AM + IDM. Type defs are split into a layered
/// `types/` set (one Rhino interop layer + per-family overlays) — see
/// `docs/api/12-script-bindings-matrix.md` and `am::leaf_tsconfig` for how the
/// per-folder leaf tsconfigs compose them.
const MANAGED: &[(&str, &str)] = &[
    // AM shared type defs.
    (
        "am/types/rhino-1.7.14.d.ts",
        include_str!("templates/am/types/rhino-1.7.14.d.ts"),
    ),
    (
        "am/types/common.d.ts",
        include_str!("templates/am/types/common.d.ts"),
    ),
    (
        "am/types/nextgen-common.d.ts",
        include_str!("templates/am/types/nextgen-common.d.ts"),
    ),
    (
        "am/types/legacy-common.d.ts",
        include_str!("templates/am/types/legacy-common.d.ts"),
    ),
    (
        "am/types/decision-node-base.d.ts",
        include_str!("templates/am/types/decision-node-base.d.ts"),
    ),
    (
        "am/types/decision-node-next.d.ts",
        include_str!("templates/am/types/decision-node-next.d.ts"),
    ),
    (
        "am/types/decision-node-legacy.d.ts",
        include_str!("templates/am/types/decision-node-legacy.d.ts"),
    ),
    (
        "am/types/library.d.ts",
        include_str!("templates/am/types/library.d.ts"),
    ),
    (
        "am/types/oidc-claims.d.ts",
        include_str!("templates/am/types/oidc-claims.d.ts"),
    ),
    // Next-gen context overlays generated from the editor binding metadata.
    (
        "am/types/oidc-claims-ng.d.ts",
        include_str!("templates/am/types/oidc-claims-ng.d.ts"),
    ),
    (
        "am/types/device-match.d.ts",
        include_str!("templates/am/types/device-match.d.ts"),
    ),
    (
        "am/types/social-handler.d.ts",
        include_str!("templates/am/types/social-handler.d.ts"),
    ),
    (
        "am/types/saml-nameid-mapper.d.ts",
        include_str!("templates/am/types/saml-nameid-mapper.d.ts"),
    ),
    (
        "am/types/saml-sp-account-mapper.d.ts",
        include_str!("templates/am/types/saml-sp-account-mapper.d.ts"),
    ),
    (
        "am/types/oauth2-dcr.d.ts",
        include_str!("templates/am/types/oauth2-dcr.d.ts"),
    ),
    (
        "am/types/oauth2-access-token-ng.d.ts",
        include_str!("templates/am/types/oauth2-access-token-ng.d.ts"),
    ),
    (
        "am/types/oauth2-may-act-ng.d.ts",
        include_str!("templates/am/types/oauth2-may-act-ng.d.ts"),
    ),
    (
        "am/types/oauth2-jwt-issuer-ng.d.ts",
        include_str!("templates/am/types/oauth2-jwt-issuer-ng.d.ts"),
    ),
    (
        "am/types/oauth2-validate-scope-ng.d.ts",
        include_str!("templates/am/types/oauth2-validate-scope-ng.d.ts"),
    ),
    (
        "am/types/oauth2-evaluate-scope-ng.d.ts",
        include_str!("templates/am/types/oauth2-evaluate-scope-ng.d.ts"),
    ),
    (
        "am/types/oauth2-authz-data-ng.d.ts",
        include_str!("templates/am/types/oauth2-authz-data-ng.d.ts"),
    ),
    (
        "am/types/pingone-verify.d.ts",
        include_str!("templates/am/types/pingone-verify.d.ts"),
    ),
    (
        "am/tsconfig.json",
        include_str!("templates/am/tsconfig.json"),
    ),
    (
        "am/eslint.config.js",
        include_str!("templates/am/eslint.config.js"),
    ),
    // IDM shared type defs.
    (
        "idm/types/rhino-1.7.14.d.ts",
        include_str!("templates/idm/types/rhino-1.7.14.d.ts"),
    ),
    (
        "idm/types/common.d.ts",
        include_str!("templates/idm/types/common.d.ts"),
    ),
    (
        "idm/types/idm-libs.d.ts",
        include_str!("templates/idm/types/idm-libs.d.ts"),
    ),
    (
        "idm/types/endpoint.d.ts",
        include_str!("templates/idm/types/endpoint.d.ts"),
    ),
    (
        "idm/types/schedule.d.ts",
        include_str!("templates/idm/types/schedule.d.ts"),
    ),
    (
        "idm/types/managed-hook.d.ts",
        include_str!("templates/idm/types/managed-hook.d.ts"),
    ),
    (
        "idm/tsconfig.json",
        include_str!("templates/idm/tsconfig.json"),
    ),
    (
        "idm/eslint.config.js",
        include_str!("templates/idm/eslint.config.js"),
    ),
    (
        "idm/endpoint/tsconfig.json",
        include_str!("templates/idm/endpoint/tsconfig.json"),
    ),
    (
        "idm/schedule/tsconfig.json",
        include_str!("templates/idm/schedule/tsconfig.json"),
    ),
    // Tooling: per-leaf type-check runner used by `npm run type-check`.
    (
        "tools/check-types.mjs",
        include_str!("templates/tools/check-types.mjs"),
    ),
    (
        "tools/eslint-openidm-query-filter.mjs",
        include_str!("templates/tools/eslint-openidm-query-filter.mjs"),
    ),
    // The TypeScript endpoint project. Its framework + build pipeline are
    // managed; the endpoints and shared modules under `typescript/src/` are
    // user files (see TS_USER). Design: `docs/typescript-endpoints.md`.
    (
        "typescript/README.md",
        include_str!("templates/typescript/README.md"),
    ),
    (
        "typescript/tsconfig.json",
        include_str!("templates/typescript/tsconfig.json"),
    ),
    (
        "typescript/tsconfig.tests.json",
        include_str!("templates/typescript/tsconfig.tests.json"),
    ),
    (
        "typescript/eslint.config.js",
        include_str!("templates/typescript/eslint.config.js"),
    ),
    (
        "typescript/framework/index.ts",
        include_str!("templates/typescript/framework/index.ts"),
    ),
    (
        "typescript/framework/types.ts",
        include_str!("templates/typescript/framework/types.ts"),
    ),
    (
        "typescript/framework/idm-globals.d.ts",
        include_str!("templates/typescript/framework/idm-globals.d.ts"),
    ),
    (
        "typescript/framework/java-globals.d.ts",
        include_str!("templates/typescript/framework/java-globals.d.ts"),
    ),
    (
        "typescript/framework/java.ts",
        include_str!("templates/typescript/framework/java.ts"),
    ),
    (
        "typescript/framework/validate.ts",
        include_str!("templates/typescript/framework/validate.ts"),
    ),
    (
        "typescript/framework/errors.ts",
        include_str!("templates/typescript/framework/errors.ts"),
    ),
    (
        "typescript/framework/logging.ts",
        include_str!("templates/typescript/framework/logging.ts"),
    ),
    (
        "typescript/framework/router.ts",
        include_str!("templates/typescript/framework/router.ts"),
    ),
    (
        "typescript/framework/openapi.ts",
        include_str!("templates/typescript/framework/openapi.ts"),
    ),
    (
        "typescript/tools/build.mjs",
        include_str!("templates/typescript/tools/build.mjs"),
    ),
    (
        "typescript/tools/idm-runtime-bans.mjs",
        include_str!("templates/typescript/tools/idm-runtime-bans.mjs"),
    ),
    (
        "typescript/tests/harness.ts",
        include_str!("templates/typescript/tests/harness.ts"),
    ),
    (
        "typescript/tests/harness.test.ts",
        include_str!("templates/typescript/tests/harness.test.ts"),
    ),
    (
        "typescript/tests/validate.test.ts",
        include_str!("templates/typescript/tests/validate.test.ts"),
    ),
    (
        "typescript/tests/router.test.ts",
        include_str!("templates/typescript/tests/router.test.ts"),
    ),
    (
        "typescript/tests/openidm-types.test.ts",
        include_str!("templates/typescript/tests/openidm-types.test.ts"),
    ),
    (
        "typescript/tests/java.test.ts",
        include_str!("templates/typescript/tests/java.test.ts"),
    ),
    (
        "typescript/tests/errors.test.ts",
        include_str!("templates/typescript/tests/errors.test.ts"),
    ),
    (
        "typescript/tests/logging.test.ts",
        include_str!("templates/typescript/tests/logging.test.ts"),
    ),
    (
        "typescript/tests/openapi.test.ts",
        include_str!("templates/typescript/tests/openapi.test.ts"),
    ),
    (
        "typescript/tests/runtime-bans.test.mjs",
        include_str!("templates/typescript/tests/runtime-bans.test.mjs"),
    ),
    (
        "typescript/tests/openapi-meta.test.mjs",
        include_str!("templates/typescript/tests/openapi-meta.test.mjs"),
    ),
    (
        "typescript/tests/union-endpoint.ts",
        include_str!("templates/typescript/tests/union-endpoint.ts"),
    ),
    (
        "typescript/tests/framework-surface.test.mjs",
        include_str!("templates/typescript/tests/framework-surface.test.mjs"),
    ),
    (
        "typescript/tests/tsconfig-pinning.test.mjs",
        include_str!("templates/typescript/tests/tsconfig-pinning.test.mjs"),
    ),
    (
        "typescript/tests/schema-agreement.test.mjs",
        include_str!("templates/typescript/tests/schema-agreement.test.mjs"),
    ),
];

/// The TypeScript project's `package.json`. Neither managed nor user: the
/// framework's own toolchain entries are refreshed on update (a stale esbuild
/// or Babel is exactly the breakage `TEMPLATES_VERSION` exists to prevent),
/// while anything the user added survives. See [`merge_package_json`].
const TS_PACKAGE_JSON: &str = include_str!("templates/typescript/package.json");

/// Files this tool managed under older template versions that are now obsolete
/// and must be **deleted** from existing workspaces on update. Only ever list
/// files this tool itself wrote — never user scripts, tests, or package files.
const OBSOLETE: &[&str] = &[
    "am/amCommon.d.ts",
    "am/src.d.ts",
    "am/lib.d.ts",
    "am/oidc.d.ts",
    "idm/idmCommon.d.ts",
    "idm/managed/tsconfig.json",
    "idm/types/managed/openidm-overloads.d.ts",
    "idm/types/sync-mapping.d.ts",
    "am/types/managed/openidm-overloads.d.ts",
];

/// User files: seeded once on init, never overwritten (even by update).
const USER: &[(&str, &str)] = &[
    ("package.json", include_str!("templates/package.json")),
    (".prettierrc", include_str!("templates/.prettierrc")),
    ("README.md", include_str!("templates/README.md")),
    (
        "tests/example.test.ts",
        include_str!("templates/tests/example.test.ts"),
    ),
];

/// User files inside the TypeScript project. Seeded when the project tree is
/// first created — including on an `update` that introduces it to an existing
/// workspace. On later updates an **unmodified** seed (disk hash matches the
/// hash recorded when we last wrote it) is refreshed; a file the user has
/// edited, or one with no recorded hash, is left alone and reported.
///
/// The `example-*` endpoints are a worked example, not infrastructure: they
/// exercise every routing and validation feature against fixture data and are
/// meant to be deleted once you have your own. A deleted seed stays deleted.
const TS_USER: &[(&str, &str)] = &[
    (
        "typescript/src/shared/widget-key.ts",
        include_str!("templates/typescript/src/shared/widget-key.ts"),
    ),
    (
        "typescript/src/shared/audit.ts",
        include_str!("templates/typescript/src/shared/audit.ts"),
    ),
    (
        "typescript/src/shared/fixtures.ts",
        include_str!("templates/typescript/src/shared/fixtures.ts"),
    ),
    (
        "typescript/src/endpoints/example-widgets.ts",
        include_str!("templates/typescript/src/endpoints/example-widgets.ts"),
    ),
    (
        "typescript/src/endpoints/example-reports.ts",
        include_str!("templates/typescript/src/endpoints/example-reports.ts"),
    ),
    (
        "typescript/tests/demo-endpoints.test.ts",
        include_str!("templates/typescript/tests/demo-endpoints.test.ts"),
    ),
    // The two TENANT-DEPENDENT seeds. They live under `templates/typescript-seeds/`
    // rather than in the template project, mirroring their destination paths but
    // outside it, because they are the only templates that cannot compile without
    // a tenant: both lean on `src/generated/managed.ts`, which `managed_types`
    // writes per tenant and which no repo checkout has. Leaving them in
    // `templates/typescript/` made `npm run type-check` there permanently red —
    // nine errors that look like framework breakage and are not — so the project's
    // own gates could never be the dev loop for framework work. Their headers say
    // they depend on the stock `alpha_user` schema; a tenant whose schema differs
    // edits or deletes them.
    (
        "typescript/src/endpoints/example-managed-users.ts",
        include_str!("templates/typescript-seeds/src/endpoints/example-managed-users.ts"),
    ),
    (
        "typescript/tests/example-managed-users.test.ts",
        include_str!("templates/typescript-seeds/tests/example-managed-users.test.ts"),
    ),
];

/// Where the tenant-dependent seeds live, relative to `templates/`, paired with
/// the destination each is written to. Pinned by a test so the indirection above
/// cannot rot into a file no workspace receives.
#[cfg(test)]
const TENANT_SEEDS: &[(&str, &str)] = &[
    (
        "typescript-seeds/src/endpoints/example-managed-users.ts",
        "typescript/src/endpoints/example-managed-users.ts",
    ),
    (
        "typescript-seeds/tests/example-managed-users.test.ts",
        "typescript/tests/example-managed-users.test.ts",
    ),
];

/// Our own `.gitignore` (the p1-sync one references `.p1-sync/`). Ignores build
/// output and our sync state; keeps the source dirs tracked.
///
/// `typescript/openapi/` is deliberately NOT here — those
/// documents are the endpoint's published contract, and a diff on one is worth
/// reviewing. `.aic-ts-manifest.json` is: it is a build artifact regenerated
/// deterministically from `src/endpoints/`, and committing it means every branch
/// that adds an endpoint conflicts on it.
const GITIGNORE: &str = "node_modules/\ndist/\ncoverage/\n.aic-sync/\nidm/types/managed/\nidm/types/sync/\nam/types/managed/\ntypescript/src/generated/\ntypescript/.aic-ts-manifest.json\n*.log\n.DS_Store\n";

#[derive(Debug, Default, Serialize, Deserialize)]
struct WorkspaceState {
    templates_version: u32,
    /// SHA-256 (lowercase hex) of each TypeScript seed as we last wrote it,
    /// keyed by the workspace-relative path. Absent for workspaces that predate
    /// this field — those files are unverifiable, never overwritten.
    #[serde(default)]
    seed_hashes: BTreeMap<String, String>,
}

fn state_path_in(tree: &Path) -> PathBuf {
    tree.join(".aic-sync").join("state.toml")
}

fn load_state(tree: &Path) -> Result<WorkspaceState> {
    let path = state_path_in(tree);
    if !path.exists() {
        return Ok(WorkspaceState::default());
    }
    Ok(toml::from_str(&std::fs::read_to_string(&path)?)?)
}

fn save_state(tree: &Path, state: &WorkspaceState) -> Result<()> {
    let path = state_path_in(tree);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, toml::to_string_pretty(state)?)?;
    Ok(())
}

/// SHA-256 of the exact bytes we write (or read back), lowercase hex.
fn content_hash(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(digest.len() * 2);
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in digest {
        hex.push(HEX[usize::from(byte >> 4)] as char);
        hex.push(HEX[usize::from(byte & 0x0f)] as char);
    }
    hex
}

/// Detect a pre-redesign **per-realm** workspace
/// (`workspace/<tenant>/<realm>/.aic-sync`). The layout is now per-tenant
/// (`am/<realm>/…`), so the old `.aic-sync` is ignored — returning the old
/// realm dir lets callers refuse rather than silently auto-init over it and
/// strand local edits.
pub fn legacy_layout(tenant: &str) -> Option<PathBuf> {
    let tree = ProjectConfig::workspace_tree(tenant);
    REALMS
        .iter()
        .map(|r| tree.join(r))
        .find(|dir| dir.join(".aic-sync").is_dir())
}

/// Templates version recorded for a tenant's workspace (0 if uninitialised).
pub fn applied_version(tenant: &str) -> Result<u32> {
    Ok(load_state(&ProjectConfig::workspace_tree(tenant))?.templates_version)
}

/// Shared first-use workspace guard for scripts-adjacent verticals.
/// Callers use it before any operation that writes into the local workspace;
/// it refuses legacy per-realm layouts and auto-initializes a fresh tree.
pub fn ensure_workspace_ready(app: &mut App, tenant: &str) -> bool {
    if let Some(dir) = legacy_layout(tenant) {
        app.push_toast(
            ToastKind::Error,
            format!(
                "old per-realm workspace at {} -- migrate via the CLI first",
                dir.display()
            ),
        );
        return false;
    }
    match applied_version(tenant) {
        Ok(0) => match init(tenant) {
            Ok(result) => {
                app.push_toast(
                    ToastKind::Info,
                    format!(
                        "initialised workspace at {} — run `npm install` there for lint/type-check",
                        result.tree.display()
                    ),
                );
                true
            }
            Err(error) => {
                app.push_toast(ToastKind::Error, format!("workspace init failed: {error}"));
                false
            }
        },
        Ok(_) => true,
        Err(error) => {
            app.push_toast(ToastKind::Error, format!("workspace check failed: {error}"));
            false
        }
    }
}

/// Merge the framework's `package.json` into whatever is already on disk.
///
/// Neither "always overwrite" nor "seed once" is right here. Overwriting drops
/// a dependency the user's own endpoints need; seeding once strands the build
/// pipeline on the esbuild/Babel versions of whenever the workspace was
/// created, and the two-step build is precisely a place where a stale
/// toolchain fails confusingly. So the framework owns its own keys and the
/// user keeps everything else: per-key, the template wins where it has an
/// opinion, and the user's extra scripts and dependencies ride along.
fn merge_package_json(existing: &str, template: &str) -> Result<String> {
    use serde_json::{Map, Value};

    let template: Value = serde_json::from_str(template)?;
    let Ok(Value::Object(mut merged)) = serde_json::from_str::<Value>(existing) else {
        // Unparseable (or not an object): the user has no structure worth
        // preserving, so take the template rather than refusing to scaffold.
        return Ok(format!("{}\n", serde_json::to_string_pretty(&template)?));
    };
    let Value::Object(template) = template else {
        return Ok(existing.to_string());
    };

    for (key, value) in template {
        // The user's `name`/`version`/`description` are theirs to set.
        let user_owned = matches!(key.as_str(), "name" | "version" | "description");
        if user_owned && merged.contains_key(&key) {
            continue;
        }
        // Object-valued sections (scripts, devDependencies) merge key-by-key:
        // the template wins where it has an opinion, extras ride along.
        if let (Some(Value::Object(mine)), Value::Object(theirs)) = (merged.get(&key), &value) {
            let mut combined: Map<String, Value> = mine.clone();
            for (inner_key, inner_value) in theirs {
                combined.insert(inner_key.clone(), inner_value.clone());
            }
            merged.insert(key, Value::Object(combined));
            continue;
        }
        merged.insert(key, value);
    }
    Ok(format!(
        "{}\n",
        serde_json::to_string_pretty(&Value::Object(merged))?
    ))
}

/// Write the TypeScript project's `package.json`, merging with any existing one.
fn write_ts_package_json(tree: &Path, report: &mut WorkspaceReport) -> Result<()> {
    let path = tree.join(PROJECT_DIR).join("package.json");
    let contents = match std::fs::read_to_string(&path) {
        Ok(existing) => merge_package_json(&existing, TS_PACKAGE_JSON)?,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => TS_PACKAGE_JSON.to_string(),
        Err(error) => return Err(error.into()),
    };
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, contents)?;
    report.written.push(path);
    Ok(())
}

fn write_if(path: &Path, contents: &str, overwrite: bool) -> Result<bool> {
    if path.exists() && !overwrite {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    Ok(true)
}

/// What a scaffolding run wrote (and, on update, removed or left).
#[derive(Debug, Default)]
pub struct WorkspaceReport {
    pub written: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
    /// Seeds the user has edited: left on disk, named so they know `src/`
    /// may no longer compile against the framework.
    pub drifted: Vec<PathBuf>,
    /// Seeds on disk with no recorded hash. Predate this tracking; not
    /// overwritten, because we cannot tell a stale demo from their endpoint.
    pub unverifiable: Vec<PathBuf>,
    pub tree: PathBuf,
}

/// Create the per-tenant workspace tree (both realms + IDM): directories,
/// embedded templates (managed always; user files only if missing),
/// `.gitignore`, and the recorded templates version.
pub fn init(tenant: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, false)
}

/// Refresh the managed template files (types / tsconfig / eslint) to the
/// current [`TEMPLATES_VERSION`]. Unmodified TypeScript seeds are repaired;
/// edited or unverifiable seeds are left alone and reported.
pub fn update(tenant: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, true)
}

fn scaffold(tenant: &str, is_update: bool) -> Result<WorkspaceReport> {
    let tree = ProjectConfig::workspace_tree(tenant);
    scaffold_at(&tree, is_update)
}

/// Scaffold into an explicit `tree` dir (no tenant state). Split out from
/// [`scaffold`] so it can be exercised against a temp dir in tests.
fn scaffold_at(tree: &Path, is_update: bool) -> Result<WorkspaceReport> {
    let mut report = WorkspaceReport {
        tree: tree.to_path_buf(),
        ..Default::default()
    };
    let mut state = load_state(tree)?;

    // An update that first introduces the TypeScript project still has to seed
    // its user files — otherwise an existing workspace gets a framework with no
    // `src/` to build, and `npm run build` reports "nothing to build" forever.
    let typescript_is_new = !tree.join(PROJECT_DIR).join("src").exists();

    // AM script folders are created per type on pull (each gets its own leaf
    // `tsconfig.json` then — see `am::extra_files`), so we only scaffold the
    // shared `am/` defs here. IDM folders are fixed, so create them up front.
    std::fs::create_dir_all(tree.join("am"))?;
    std::fs::create_dir_all(tree.join("idm").join("endpoint"))?;
    std::fs::create_dir_all(tree.join("idm").join("managed"))?;
    std::fs::create_dir_all(tree.join("idm").join("schedule"))?;
    std::fs::create_dir_all(tree.join("idm").join("sync"))?;
    std::fs::create_dir_all(tree.join("tests"))?;
    for sub in ["src/endpoints", "src/shared", "src/generated", "tests"] {
        std::fs::create_dir_all(tree.join(PROJECT_DIR).join(sub))?;
    }

    // Managed shared files (always (re)written).
    for (rel, contents) in MANAGED {
        let path = tree.join(rel);
        if write_if(&path, contents, true)? {
            report.written.push(path);
        }
    }
    // User files: seed once, never touched on update.
    if !is_update {
        for (rel, contents) in USER {
            let path = tree.join(rel);
            if write_if(&path, contents, false)? {
                report.written.push(path);
            }
        }
    }
    seed_typescript_user_files(tree, typescript_is_new, &mut state, &mut report)?;
    // Persist the seed hashes before the fallible writes below. They describe
    // bytes already on disk, so losing them to a later error would leave a
    // tool-written seed looking user-edited — and a seed reported as drifted is
    // never refreshed again. `templates_version` is deliberately still the old
    // value here, so a failed run retries the whole update rather than
    // recording work it did not finish.
    save_state(tree, &state)?;
    write_ts_package_json(tree, &mut report)?;
    // `.gitignore` is managed (always refreshed).
    let gi = tree.join(".gitignore");
    if write_if(&gi, GITIGNORE, true)? {
        report.written.push(gi);
    }

    // Delete obsolete managed files left over from older template versions. The
    // OBSOLETE list only ever names files this tool wrote, so this never touches
    // user scripts. (No-op on a fresh init — none exist yet.)
    for rel in OBSOLETE {
        let path = tree.join(rel);
        if path.exists() {
            std::fs::remove_file(&path)?;
            report.removed.push(path);
        }
    }

    // Leaf `tsconfig.json` files are normally (re)written per script folder on
    // pull (`am::extra_files`). Renaming the shared type files means existing,
    // already-pulled folders would point at deleted defs until their next pull,
    // so an update refreshes every already-pulled AM leaf in place.
    for realm in REALMS {
        let realm_dir = tree.join("am").join(realm);
        let Ok(entries) = std::fs::read_dir(&realm_dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let dir = entry.path();
            let leaf = dir.join("tsconfig.json");
            if dir.is_dir() && leaf.exists() {
                let slug = entry.file_name().to_string_lossy().into_owned();
                std::fs::write(&leaf, super::am::leaf_tsconfig(&slug))?;
                report.written.push(leaf);
            }
        }
    }

    // Managed hooks also use one leaf project per object so each folder sees
    // only its own generated `object` binding.
    let managed_dir = tree.join("idm").join("managed");
    if let Ok(entries) = std::fs::read_dir(&managed_dir) {
        for entry in entries.flatten() {
            let dir = entry.path();
            let leaf = dir.join("tsconfig.json");
            if dir.is_dir() && leaf.exists() {
                let object = entry.file_name().to_string_lossy().into_owned();
                std::fs::write(&leaf, super::managed_hooks::leaf_tsconfig(&object))?;
                report.written.push(leaf);
            }
        }
    }

    state.templates_version = TEMPLATES_VERSION;
    save_state(tree, &state)?;
    Ok(report)
}

/// Write or refresh one TypeScript seed according to its provenance.
///
/// - missing, never recorded (or the project is new): write it
/// - missing, hash recorded: the user deleted it — leave it
/// - disk hash matches the recorded seed hash: they never touched it — refresh
/// - disk hash differs: they own it — leave it, report drifted
/// - no recorded hash: do not guess — leave it, report unverifiable
/// - disk already equals the current seed and we have no hash: start tracking
fn seed_typescript_user_files(
    tree: &Path,
    typescript_is_new: bool,
    state: &mut WorkspaceState,
    report: &mut WorkspaceReport,
) -> Result<()> {
    for (rel, contents) in TS_USER {
        seed_one(tree, rel, contents, typescript_is_new, state, report)?;
    }
    state
        .seed_hashes
        .retain(|rel, _| TS_USER.iter().any(|(known, _)| known == rel));
    Ok(())
}

fn seed_one(
    tree: &Path,
    rel: &str,
    contents: &str,
    typescript_is_new: bool,
    state: &mut WorkspaceState,
    report: &mut WorkspaceReport,
) -> Result<()> {
    let path = tree.join(rel);
    let wanted = content_hash(contents.as_bytes());

    if !path.exists() {
        // A missing `src/` is "the project is new", not "the user deleted
        // every seed": re-seed. A missing file next to a live `src/` whose
        // hash we recorded is a deletion — the README told them to do that.
        if !typescript_is_new && state.seed_hashes.contains_key(rel) {
            return Ok(());
        }
        if write_if(&path, contents, true)? {
            report.written.push(path);
        }
        state.seed_hashes.insert(rel.to_string(), wanted);
        return Ok(());
    }

    let on_disk = std::fs::read(&path)?;
    let disk_hash = content_hash(&on_disk);
    match state.seed_hashes.get(rel) {
        Some(recorded) if recorded == &disk_hash => {
            if disk_hash != wanted && write_if(&path, contents, true)? {
                report.written.push(path);
            }
            state.seed_hashes.insert(rel.to_string(), wanted);
        }
        Some(_) => report.drifted.push(path),
        None if disk_hash == wanted => {
            state.seed_hashes.insert(rel.to_string(), wanted);
        }
        None => report.unverifiable.push(path),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn templates_all_embed() {
        for (rel, contents) in MANAGED.iter().chain(USER) {
            assert!(!contents.is_empty(), "empty template: {rel}");
        }
        // The layered type set replaced the old root `*.d.ts` files.
        assert!(MANAGED.iter().any(|(r, _)| *r == "am/types/common.d.ts"));
        assert!(
            MANAGED
                .iter()
                .any(|(r, _)| *r == "am/types/decision-node-base.d.ts")
        );
        assert!(MANAGED.iter().any(|(r, _)| *r == "idm/types/endpoint.d.ts"));
        assert!(USER.iter().any(|(r, _)| *r == "package.json"));
    }

    #[test]
    fn base_tsconfigs_pin_runtime_available_standard_libraries() {
        // Do not widen these umbrella libs: they declare JS globals absent from
        // the AM/IDM script engines and make runtime-impossible scripts type-check.
        let am = MANAGED
            .iter()
            .find(|(rel, _)| *rel == "am/tsconfig.json")
            .unwrap()
            .1;
        assert!(am.contains("\"lib\": [\"ES5\", \"ES2015.Core\", \"ES2016.Array.Include\"]"));
        assert!(!am.contains("\"ES2015\""));

        let idm = MANAGED
            .iter()
            .find(|(rel, _)| *rel == "idm/tsconfig.json")
            .unwrap()
            .1;
        for lib in [
            "ES5",
            "ES2015.Core",
            "ES2015.Collection",
            "ES2015.Iterable",
            "ES2015.Symbol",
            "ES2015.Symbol.WellKnown",
            "ES2015.Promise",
            "ES2016.Array.Include",
        ] {
            assert!(
                idm.contains(&format!("\"{lib}\"")),
                "missing IDM lib: {lib}"
            );
        }
        assert!(!idm.contains("\"ES2015\""));
        assert!(!idm.contains("ES2015.Proxy"));
        assert!(!idm.contains("ES2015.Reflect"));
        assert!(!idm.contains("ES2015.Generator"));
    }

    #[test]
    fn eslint_templates_reject_runtime_absent_syntax_and_globals() {
        let am = MANAGED
            .iter()
            .find(|(rel, _)| *rel == "am/eslint.config.js")
            .unwrap()
            .1;
        // The whole statement is banned, not only its `const` form: for...of is a
        // parse error on Rhino in any form (probed 2026-07-30).
        assert!(am.contains("selector: \"ForOfStatement\""));
        assert!(!am.contains("ForOfStatement > VariableDeclaration"));
        // Each global carries its own substitute hint, so assert the table entry
        // rather than a generated `name:` key.
        assert!(am.contains("\"no-restricted-globals\": [\"error\", ...rhinoMissingGlobals]"));
        for global in [
            "Map", "Set", "WeakMap", "WeakSet", "Symbol", "Promise", "Proxy", "Reflect",
        ] {
            assert!(
                am.contains(&format!("\"{global}\",")),
                "missing AM global: {global}"
            );
        }

        let idm = MANAGED
            .iter()
            .find(|(rel, _)| *rel == "idm/eslint.config.js")
            .unwrap()
            .1;
        assert!(idm.contains("\"no-restricted-globals\": [\"error\", ...idmMissingGlobals]"));
        for global in ["Proxy", "Reflect"] {
            assert!(
                idm.contains(&format!("\"{global}\",")),
                "missing IDM global: {global}"
            );
        }
        // IDM has these at runtime; banning them here would be wrong.
        for present in ["Map", "Set", "Symbol", "Promise"] {
            assert!(
                !idm.contains(&format!("\"{present}\",")),
                "IDM must not restrict {present}"
            );
        }
    }

    #[test]
    fn obsolete_files_are_cleanly_retired() {
        // Obsolete files must not also be (re)written as managed, or update would
        // delete-then-recreate them.
        for rel in OBSOLETE {
            assert!(
                !MANAGED.iter().any(|(r, _)| r == rel),
                "obsolete file still in MANAGED: {rel}"
            );
        }
        // The old root type defs are scheduled for cleanup on update.
        assert!(OBSOLETE.contains(&"am/src.d.ts"));
        assert!(OBSOLETE.contains(&"idm/idmCommon.d.ts"));
        assert!(OBSOLETE.contains(&"idm/managed/tsconfig.json"));
        assert!(OBSOLETE.contains(&"idm/types/sync-mapping.d.ts"));
        assert!(
            !MANAGED
                .iter()
                .any(|(rel, _)| *rel == "idm/managed/tsconfig.json")
        );
        assert!(
            !MANAGED
                .iter()
                .any(|(rel, _)| *rel == "idm/types/sync-mapping.d.ts")
        );
    }

    /// The tenant-dependent seeds live outside the template project, so nothing
    /// type-checks them in this repo and nothing but this test notices if the
    /// indirection breaks. Assert both ends: the source file is really there, and
    /// the destination is really seeded.
    #[test]
    fn tenant_dependent_seeds_are_registered_and_live_outside_the_project() {
        let templates = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("src")
            .join("scripts")
            .join("templates");
        for (source, destination) in TENANT_SEEDS {
            assert!(
                templates.join(source).is_file(),
                "seed source missing: {source}"
            );
            assert!(
                TS_USER.iter().any(|(r, _)| r == destination),
                "seed not registered in TS_USER: {destination}"
            );
            assert!(
                !templates
                    .join("typescript")
                    .join(
                        destination
                            .strip_prefix("typescript/")
                            .expect("destinations are project-relative")
                    )
                    .exists(),
                "{destination} is BOTH a seed and in the template project — the \
                 project's own type-check will go red on it"
            );
        }
        // Nothing else may hide out there: a file in the seeds tree that no
        // TS_USER row names would reach no workspace at all.
        let mut found = Vec::new();
        fn walk(dir: &Path, root: &Path, found: &mut Vec<String>) {
            for entry in std::fs::read_dir(dir).expect("readable").flatten() {
                let path = entry.path();
                if path.is_dir() {
                    walk(&path, root, found);
                } else {
                    let rel = path.strip_prefix(root).expect("under root");
                    found.push(format!("typescript-seeds/{}", rel.display()));
                }
            }
        }
        let root = templates.join("typescript-seeds");
        walk(&root, &root, &mut found);
        assert!(!found.is_empty(), "found no seed files to check");
        for rel in found {
            assert!(
                TENANT_SEEDS.iter().any(|(source, _)| *source == rel),
                "{rel} is in the seeds tree but no workspace will ever receive it"
            );
        }
    }

    #[test]
    fn typescript_project_ships_its_framework_managed_and_its_endpoints_user() {
        // The framework must be refreshable (a stale router is a silent bug);
        // the endpoints must not be (they are the user's code).
        for rel in [
            "typescript/framework/router.ts",
            "typescript/framework/validate.ts",
            "typescript/framework/openapi.ts",
            "typescript/tools/build.mjs",
            "typescript/tools/idm-runtime-bans.mjs",
            "typescript/tsconfig.json",
            "typescript/eslint.config.js",
        ] {
            assert!(MANAGED.iter().any(|(r, _)| *r == rel), "not managed: {rel}");
        }
        for rel in [
            "typescript/src/shared/widget-key.ts",
            "typescript/src/endpoints/example-widgets.ts",
        ] {
            assert!(TS_USER.iter().any(|(r, _)| *r == rel), "not seeded: {rel}");
            assert!(
                !MANAGED.iter().any(|(r, _)| *r == rel),
                "user file also managed: {rel}"
            );
        }
        // `package.json` is neither — it is merged (see merge_package_json).
        assert!(
            !MANAGED
                .iter()
                .chain(TS_USER)
                .any(|(r, _)| *r == "typescript/package.json")
        );
    }

    /// A template file that nothing registers is invisible: it ships inside the
    /// crate, so every check here and in CI passes, and it still never reaches a
    /// workspace — a test in that state has silently stopped guarding anything.
    /// `tests/openapi-meta.test.mjs` sat unregistered from the day it was
    /// written until the v0.8.0 release rehearsal (2026-08-14) noticed the
    /// scaffolded tree was one file short of the template tree.
    #[test]
    fn every_typescript_template_file_is_registered_somewhere() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("src/scripts/templates/typescript");

        // Local artifacts of running the project's own gates in place — the dev
        // loop for framework changes is `npm install && npm run type-check` right
        // here — not templates. Kept in step with `src/scripts/templates/.gitignore`.
        const LOCAL_ARTIFACTS: &[&str] = &[
            "node_modules",
            "package-lock.json",
            "dist",
            "openapi",
            ".aic-ts-manifest.json",
        ];

        fn walk(dir: &std::path::Path, root: &std::path::Path, found: &mut Vec<String>) {
            for entry in std::fs::read_dir(dir).expect("template dir is readable") {
                let path = entry.expect("readable entry").path();
                if path
                    .file_name()
                    .is_some_and(|n| LOCAL_ARTIFACTS.iter().any(|a| n == *a))
                {
                    continue;
                }
                if path.is_dir() {
                    walk(&path, root, found);
                } else {
                    let rel = path.strip_prefix(root).expect("under root");
                    found.push(format!("typescript/{}", rel.display()));
                }
            }
        }

        let mut on_disk = Vec::new();
        walk(&root, &root, &mut on_disk);
        assert!(!on_disk.is_empty(), "found no template files to check");

        for rel in on_disk {
            let registered = MANAGED.iter().chain(TS_USER).any(|(r, _)| *r == rel)
                || rel == "typescript/package.json"; // merged, not copied
            assert!(
                registered,
                "{rel} is in the template tree but no workspace will ever receive it — \
                 add it to MANAGED or TS_USER, or delete it"
            );
        }
    }

    /// The `fields` projection machinery is duplicated across the three surfaces
    /// that declare `openidm` — the IDM ambient types, the AM next-gen ambient
    /// types, and the module-form TypeScript project. They cannot share a file:
    /// `am/` and `idm/` are separate leaf programs and the third is a module
    /// graph. So this asserts the load-bearing declarations stay identical in all
    /// three, because a projection that silently differs per surface is worse
    /// than one that does not exist. Change one, change all three.
    #[test]
    fn the_fields_projection_is_identical_on_every_openidm_surface() {
        let surfaces = [
            (
                "idm/types/common.d.ts",
                include_str!("templates/idm/types/common.d.ts"),
            ),
            (
                "am/types/nextgen-common.d.ts",
                include_str!("templates/am/types/nextgen-common.d.ts"),
            ),
            (
                "typescript/framework/idm-globals.d.ts",
                include_str!("templates/typescript/framework/idm-globals.d.ts"),
            ),
        ];

        // One line per declaration whose SHAPE decides what a projection means.
        // Whitespace is normalised because the module-form file is nested inside
        // `declare global`, so every line there carries two extra spaces.
        let required = [
            "type Projected<T, F extends string> = string extends F",
            "? StoredRecord<T>",
            ": StoredRecord<",
            "(\"*\" extends F ? T : SelectedMembers<T, F>) & {",
            "type SelectedMembers<T, F extends string> = {",
            "[K in Extract<F, keyof T>]-?: undefined extends T[K]",
            "? NonNullable<T[K]> | null",
            "[K in Extract<PathParentOf<F>, keyof T>]: ExpansionOf<T[K]>;",
            "type ExpansionOf<D> = NonNullable<D> extends readonly unknown[]",
            "? RelationshipExpansion[]",
            ": RelationshipExpansion | null;",
            "} & MetaMemberOf<F>",
            "type PathParentOf<F extends string> = F extends `${infer P}/${string}`",
            "Extract<F, \"_meta\" | `_meta/${string}`>,",
            "interface RelationshipExpansion {",
            "_refResourceRev?: string;",
            "[member: string]: unknown;",
            ": readonly ManagedField<T>[];",
        ];

        for (name, contents) in surfaces {
            let normalised = contents
                .lines()
                .map(str::trim)
                .collect::<Vec<_>>()
                .join("\n");
            for line in required {
                assert!(
                    normalised.contains(line),
                    "{name} is missing the projection declaration `{line}` — the \
                     three openidm surfaces have drifted"
                );
            }
        }
    }

    #[test]
    fn typescript_tsconfig_pins_the_idm_runtime_lib_set() {
        // Same rule as the `.cjs` workspace: widening these makes code that
        // cannot run on IDM type-check. Reflect in particular is absent.
        let config = MANAGED
            .iter()
            .find(|(rel, _)| *rel == "typescript/tsconfig.json")
            .unwrap()
            .1;
        for lib in ["ES5", "ES2015.Core", "ES2015.Collection", "ES2015.Promise"] {
            assert!(config.contains(&format!("\"{lib}\"")), "missing lib: {lib}");
        }
        assert!(!config.contains("ES2015.Reflect"));
        assert!(!config.contains("ES2015.Proxy"));
        assert!(config.contains("\"strict\": true"));
    }

    #[test]
    fn idm_lint_reads_the_typescript_ownership_manifest() {
        // Generated bundles must escape `prettier/prettier` yet still be held
        // to the runtime bans — both halves come from the manifest.
        let config = MANAGED
            .iter()
            .find(|(rel, _)| *rel == "idm/eslint.config.js")
            .unwrap()
            .1;
        assert!(config.contains("../typescript/.aic-ts-manifest.json"));
        assert!(config.contains("ignores: generated"));
        assert!(config.contains("files: generated"));
    }

    #[test]
    fn merge_keeps_user_dependencies_and_refreshes_framework_ones() {
        let existing = r#"{
          "name": "my-endpoints",
          "version": "3.0.0",
          "type": "module",
          "scripts": { "build": "stale", "deploy": "./deploy.sh" },
          "devDependencies": { "esbuild": "0.0.1", "zod": "^3.0.0" },
          "dependencies": { "left-pad": "1.0.0" }
        }"#;
        let merged = merge_package_json(existing, TS_PACKAGE_JSON).unwrap();
        let value: serde_json::Value = serde_json::from_str(&merged).unwrap();

        // The user's identity survives.
        assert_eq!(value["name"], "my-endpoints");
        assert_eq!(value["version"], "3.0.0");
        // Their own scripts and dependencies survive.
        assert_eq!(value["scripts"]["deploy"], "./deploy.sh");
        assert_eq!(value["devDependencies"]["zod"], "^3.0.0");
        assert_eq!(value["dependencies"]["left-pad"], "1.0.0");
        // The framework's own entries are refreshed, not left stale.
        assert_eq!(value["scripts"]["build"], "node tools/build.mjs");
        assert_ne!(value["devDependencies"]["esbuild"], "0.0.1");
        assert!(value["devDependencies"]["@babel/preset-env"].is_string());
    }

    /// `npm test` feeds `.ts` straight to `node --test`, so the project only
    /// works on a runtime with type stripping on by default. That floor is
    /// declared in `engines`, and the merge must keep re-asserting it: a
    /// workspace that predates the declaration has no `engines` key at all, and
    /// one whose owner pinned an older floor would otherwise keep it forever.
    #[test]
    fn merge_asserts_the_node_floor_over_a_workspace_that_lacks_or_lowers_it() {
        let template: serde_json::Value = serde_json::from_str(TS_PACKAGE_JSON).unwrap();
        let floor = template["engines"]["node"].as_str().unwrap().to_string();
        assert!(!floor.is_empty(), "the template must declare a node floor");

        for existing in [
            r#"{ "name": "mine", "type": "module" }"#,
            r#"{ "name": "mine", "engines": { "node": ">=18" } }"#,
            r#"{ "name": "mine", "engines": { "node": ">=18", "npm": ">=9" } }"#,
        ] {
            let merged = merge_package_json(existing, TS_PACKAGE_JSON).unwrap();
            let value: serde_json::Value = serde_json::from_str(&merged).unwrap();
            assert_eq!(value["engines"]["node"], floor);
        }

        // An engine the framework has no opinion about rides along.
        let merged = merge_package_json(
            r#"{ "name": "mine", "engines": { "node": ">=18", "npm": ">=9" } }"#,
            TS_PACKAGE_JSON,
        )
        .unwrap();
        let value: serde_json::Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(value["engines"]["npm"], ">=9");
    }

    #[test]
    fn merge_falls_back_to_the_template_when_the_file_is_unusable() {
        for broken in ["{ not json", "[]", "\"a string\""] {
            let merged = merge_package_json(broken, TS_PACKAGE_JSON).unwrap();
            let value: serde_json::Value = serde_json::from_str(&merged).unwrap();
            assert_eq!(value["name"], "aic-typescript-endpoints");
        }
    }

    #[test]
    fn generated_tenant_types_are_gitignored() {
        assert!(GITIGNORE.lines().any(|line| line == "idm/types/managed/"));
        assert!(GITIGNORE.lines().any(|line| line == "idm/types/sync/"));
        assert!(GITIGNORE.lines().any(|line| line == "am/types/managed/"));
        assert!(
            GITIGNORE
                .lines()
                .any(|line| line == "typescript/src/generated/")
        );
    }

    #[test]
    fn idm_leaf_templates_load_managed_types_after_common() {
        for rel in ["idm/endpoint/tsconfig.json", "idm/schedule/tsconfig.json"] {
            let contents = MANAGED
                .iter()
                .find(|(candidate, _)| *candidate == rel)
                .unwrap()
                .1;
            assert!(
                contents.find("../types/common.d.ts").unwrap()
                    < contents.find("../types/managed/*.d.ts").unwrap(),
                "{rel} managed types must follow common"
            );
        }
    }

    fn temp_tree() -> PathBuf {
        std::env::temp_dir().join(format!("aic-ws-test-{}", uuid::Uuid::new_v4()))
    }

    #[test]
    fn init_writes_managed_and_user_files() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        // Layered managed type defs + tooling are written.
        assert!(tree.join("am/types/common.d.ts").exists());
        assert!(tree.join("am/types/decision-node-next.d.ts").exists());
        assert!(tree.join("idm/types/endpoint.d.ts").exists());
        assert!(tree.join("idm/sync").is_dir());
        assert!(tree.join("tools/check-types.mjs").exists());
        assert!(tree.join("tools/eslint-openidm-query-filter.mjs").exists());
        assert!(tree.join("am/eslint.config.js").exists());
        // User files seeded on init.
        assert!(tree.join("package.json").exists());
        // The TypeScript project: framework, tooling, and a seeded example.
        assert!(tree.join("typescript/framework/router.ts").exists());
        assert!(tree.join("typescript/tools/build.mjs").exists());
        assert!(tree.join("typescript/package.json").exists());
        assert!(tree.join("typescript/src/generated").is_dir());
        assert!(
            tree.join("typescript/src/endpoints/example-widgets.ts")
                .exists()
        );

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_seeds_the_typescript_project_into_an_older_workspace() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        // Simulate a workspace scaffolded before the TypeScript project existed.
        std::fs::remove_dir_all(tree.join("typescript")).unwrap();

        scaffold_at(&tree, true).unwrap();
        assert!(tree.join("typescript/framework/router.ts").exists());
        assert!(
            tree.join("typescript/src/endpoints/example-widgets.ts")
                .exists(),
            "an update that introduces the project must seed its user files too"
        );

        // A second update leaves the user's edits alone.
        let endpoint = tree.join("typescript/src/endpoints/example-widgets.ts");
        std::fs::write(&endpoint, "// mine now\n").unwrap();
        scaffold_at(&tree, true).unwrap();
        assert_eq!(std::fs::read_to_string(&endpoint).unwrap(), "// mine now\n");

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_refreshes_the_framework_but_not_the_users_endpoints() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let framework = tree.join("typescript/framework/router.ts");
        let mine = tree.join("typescript/src/shared/widget-key.ts");
        std::fs::write(&framework, "// stale\n").unwrap();
        std::fs::write(&mine, "// mine\n").unwrap();

        scaffold_at(&tree, true).unwrap();

        assert_ne!(std::fs::read_to_string(&framework).unwrap(), "// stale\n");
        assert_eq!(std::fs::read_to_string(&mine).unwrap(), "// mine\n");

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn decision_node_identity_type_has_documented_methods() {
        let identity = include_str!("templates/am/types/decision-node-base.d.ts");
        for signature in [
            "getAttributeValues(attributeName: string): JavaArray<string>;",
            "getName(): string;",
            "getUniversalId(): string;",
            "setAttribute(attributeName: string, attributeValues: string[]): void;",
            "addAttribute(attributeName: string, attributeValue: string): void;",
            "store(): void;",
            "exists(): boolean;",
        ] {
            assert!(
                identity.contains(signature),
                "missing ScriptedIdentity method: {signature}"
            );
        }
    }

    #[test]
    fn update_deletes_obsolete_managed_files() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        // Simulate a pre-v6 workspace carrying an old managed type def.
        let stale = tree.join("am/src.d.ts");
        std::fs::write(&stale, "// old managed file\n").unwrap();
        assert!(stale.exists());
        let stale_idm = tree.join("idm/types/managed/openidm-overloads.d.ts");
        std::fs::create_dir_all(stale_idm.parent().unwrap()).unwrap();
        std::fs::write(&stale_idm, "// old overload file\n").unwrap();
        assert!(stale_idm.exists());

        let report = scaffold_at(&tree, true).unwrap();
        assert!(!stale.exists(), "obsolete file should be deleted on update");
        assert!(report.removed.iter().any(|p| p.ends_with("am/src.d.ts")));
        assert!(
            !stale_idm.exists(),
            "obsolete managed overload file should be deleted on update"
        );
        assert!(
            report
                .removed
                .iter()
                .any(|p| p.ends_with("idm/types/managed/openidm-overloads.d.ts"))
        );

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_regenerates_existing_leaf_tsconfig() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        // A previously-pulled folder with a stale leaf tsconfig (old type path).
        let folder = tree.join("am/alpha/decision-node");
        std::fs::create_dir_all(&folder).unwrap();
        let leaf = folder.join("tsconfig.json");
        std::fs::write(&leaf, "{ \"include\": [\"../../src.d.ts\"] }").unwrap();

        scaffold_at(&tree, true).unwrap();

        let refreshed = std::fs::read_to_string(&leaf).unwrap();
        assert!(refreshed.contains("../../types/decision-node-next.d.ts"));
        assert!(refreshed.contains("../../types/managed/*.d.ts"));
        assert!(!refreshed.contains("src.d.ts"));

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_regenerates_existing_managed_leaf_tsconfig() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        let folder = tree.join("idm/managed/alpha_user");
        std::fs::create_dir_all(&folder).unwrap();
        let leaf = folder.join("tsconfig.json");
        std::fs::write(&leaf, "{ \"include\": [\"../types/managed-hook.d.ts\"] }").unwrap();

        scaffold_at(&tree, true).unwrap();

        let refreshed = std::fs::read_to_string(&leaf).unwrap();
        assert!(refreshed.contains("../../types/managed/*.d.ts"));
        assert!(refreshed.contains("../../types/managed/hooks/alpha_user.d.ts"));
        assert!(refreshed.contains("../../types/managed-hook.d.ts"));

        std::fs::remove_dir_all(&tree).ok();
    }

    const WIDGETS_SEED: &str = "typescript/src/endpoints/example-widgets.ts";

    fn seed_body(rel: &str) -> &'static str {
        TS_USER
            .iter()
            .find(|(candidate, _)| *candidate == rel)
            .expect("rel is a TypeScript seed")
            .1
    }

    fn report_has(paths: &[PathBuf], rel: &str) -> bool {
        paths.iter().any(|path| path.ends_with(rel))
    }

    #[test]
    fn init_records_a_hash_for_every_typescript_seed() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let state = load_state(&tree).unwrap();
        for (rel, contents) in TS_USER {
            let path = tree.join(rel);
            assert!(path.exists(), "seed missing: {rel}");
            assert_eq!(
                state.seed_hashes.get(*rel).map(String::as_str),
                Some(content_hash(contents.as_bytes()).as_str()),
                "init must record the hash of what it wrote: {rel}"
            );
        }
        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_repairs_an_unmodified_stale_seed() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let path = tree.join(WIDGETS_SEED);
        std::fs::write(&path, "// old seed\n").unwrap();
        let mut state = load_state(&tree).unwrap();
        state
            .seed_hashes
            .insert(WIDGETS_SEED.to_string(), content_hash(b"// old seed\n"));
        save_state(&tree, &state).unwrap();

        let report = scaffold_at(&tree, true).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            seed_body(WIDGETS_SEED)
        );
        assert!(report_has(&report.written, WIDGETS_SEED));
        assert!(!report_has(&report.drifted, WIDGETS_SEED));
        assert!(!report_has(&report.unverifiable, WIDGETS_SEED));
        let state = load_state(&tree).unwrap();
        assert_eq!(
            state.seed_hashes.get(WIDGETS_SEED).map(String::as_str),
            Some(content_hash(seed_body(WIDGETS_SEED).as_bytes()).as_str())
        );

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_preserves_and_reports_a_modified_seed() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let path = tree.join(WIDGETS_SEED);
        std::fs::write(&path, "// mine now\n").unwrap();

        let report = scaffold_at(&tree, true).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "// mine now\n");
        assert!(report_has(&report.drifted, WIDGETS_SEED));
        assert!(!report_has(&report.written, WIDGETS_SEED));
        assert!(!report_has(&report.unverifiable, WIDGETS_SEED));

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_writes_an_absent_seed_that_was_never_recorded() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let path = tree.join(WIDGETS_SEED);
        std::fs::remove_file(&path).unwrap();
        let mut state = load_state(&tree).unwrap();
        state.seed_hashes.remove(WIDGETS_SEED);
        save_state(&tree, &state).unwrap();

        let report = scaffold_at(&tree, true).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            seed_body(WIDGETS_SEED)
        );
        assert!(report_has(&report.written, WIDGETS_SEED));

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_leaves_a_user_deleted_seed_gone() {
        // Distinct from "absent and never recorded": the README tells the user
        // to delete the demos, and putting them back on every update would
        // undo that. The recorded hash is the tombstone.
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let path = tree.join(WIDGETS_SEED);
        std::fs::remove_file(&path).unwrap();

        let report = scaffold_at(&tree, true).unwrap();
        assert!(!path.exists(), "a deleted seed must stay deleted");
        assert!(!report_has(&report.written, WIDGETS_SEED));
        assert!(!report_has(&report.drifted, WIDGETS_SEED));
        assert!(
            load_state(&tree)
                .unwrap()
                .seed_hashes
                .contains_key(WIDGETS_SEED)
        );

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_preserves_and_reports_an_unverifiable_seed() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let path = tree.join(WIDGETS_SEED);
        std::fs::write(&path, "// maybe mine\n").unwrap();
        let mut state = load_state(&tree).unwrap();
        state.seed_hashes.remove(WIDGETS_SEED);
        save_state(&tree, &state).unwrap();

        let report = scaffold_at(&tree, true).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "// maybe mine\n");
        assert!(report_has(&report.unverifiable, WIDGETS_SEED));
        assert!(!report_has(&report.written, WIDGETS_SEED));
        assert!(!report_has(&report.drifted, WIDGETS_SEED));

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_starts_tracking_an_unhashed_seed_that_already_matches() {
        // A workspace whose seed happens to equal the current template (fresh
        // init from this version, or they copied the new file by hand) is not
        // unverifiable — we can start hashing it without writing.
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();
        let mut state = load_state(&tree).unwrap();
        state.seed_hashes.remove(WIDGETS_SEED);
        save_state(&tree, &state).unwrap();

        let report = scaffold_at(&tree, true).unwrap();
        assert!(!report_has(&report.unverifiable, WIDGETS_SEED));
        assert!(!report_has(&report.written, WIDGETS_SEED));
        assert_eq!(
            std::fs::read_to_string(tree.join(WIDGETS_SEED)).unwrap(),
            seed_body(WIDGETS_SEED)
        );
        assert_eq!(
            load_state(&tree)
                .unwrap()
                .seed_hashes
                .get(WIDGETS_SEED)
                .map(String::as_str),
            Some(content_hash(seed_body(WIDGETS_SEED).as_bytes()).as_str())
        );

        std::fs::remove_dir_all(&tree).ok();
    }
}
