// Type-check each per-folder leaf tsconfig.
//
// The base am/tsconfig.json and idm/tsconfig.json are `extends` targets, not
// standalone programs: a single program can't include every family's .d.ts
// (they declare overlapping globals with deliberately different shapes — e.g.
// the next-gen vs legacy-OIDC `logger`), so each script folder has its own leaf
// tsconfig and we check them one at a time. Folders appear dynamically as
// scripts are pulled, so we discover them rather than hard-coding a list.
//
// Managed file — regenerated by `aic script workspace update`.
import { readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

function leafTsconfigs() {
  const out = [];
  if (existsSync("am")) {
    for (const realm of readdirSync("am", { withFileTypes: true })) {
      if (!realm.isDirectory() || realm.name === "types") continue;
      const realmDir = join("am", realm.name);
      for (const slug of readdirSync(realmDir, { withFileTypes: true })) {
        if (!slug.isDirectory()) continue;
        const tc = join(realmDir, slug.name, "tsconfig.json");
        if (existsSync(tc)) out.push(tc);
      }
    }
  }
  for (const family of ["endpoint", "schedule"]) {
    const tc = join("idm", family, "tsconfig.json");
    if (existsSync(tc)) out.push(tc);
  }
  return out;
}

const tsc = join("node_modules", ".bin", "tsc");
const configs = leafTsconfigs();
if (configs.length === 0) {
  console.log("No script folders to type-check yet.");
  process.exit(0);
}

let failed = false;
for (const config of configs) {
  const result = spawnSync(tsc, ["--noEmit", "-p", config], { stdio: "inherit" });
  if (result.status !== 0) {
    failed = true;
    console.error(`type-check FAILED: ${config}`);
  }
}
process.exit(failed ? 1 : 0);
