/**
 * A 0.1.2-shaped consumer, compiled against HEAD by `npm run typecheck`.
 *
 * `v0.1.2/` is the declaration output of tag `script-tester-v0.1.2`, vendored
 * unchanged. Every line below takes a value typed by 0.1.2 and hands it to the
 * current export of the same name: every exported function and method is
 * called with 0.1.2's parameter list, and every exported interface and type
 * (callback interfaces included) is assigned from its 0.1.2 shape. A
 * compile error here is a source break for a 0.1.2 consumer. Nothing in this
 * file runs; it is not a `*.test.ts`.
 *
 * Generic parameters are filled with `any`, so this checks each type's
 * structure rather than its schema-specific inference.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
import type * as OldHarness from "./v0.1.2/src/harness/index.ts";
import type * as OldCase from "./v0.1.2/src/case/index.ts";
import type * as OldAic from "./v0.1.2/src/aic/index.ts";
import type * as OldBindings from "./v0.1.2/src/bindings/index.ts";
import type * as OldRunner from "./v0.1.2/src/runner.ts";
import type * as OldProfile from "./v0.1.2/src/profile/index.ts";
import type * as OldDiagnostics from "./v0.1.2/src/diagnostics.ts";
import * as NewHarness from "../../src/harness/index.ts";
import * as NewCase from "../../src/case/index.ts";
import * as NewAic from "../../src/aic/index.ts";
import * as NewBindings from "../../src/bindings/index.ts";
import * as NewRunner from "../../src/runner.ts";
import * as NewProfile from "../../src/profile/index.ts";
import * as NewDiagnostics from "../../src/diagnostics.ts";

// src/harness/index
declare const Harness_defineSuite: Parameters<typeof OldHarness.defineSuite>;
void NewHarness.defineSuite(...Harness_defineSuite);
declare const Harness_Lease__new: ConstructorParameters<typeof OldHarness.Lease>;
void new NewHarness.Lease(...Harness_Lease__new);
declare const Harness_Lease__inst: NewHarness.Lease<any>;
declare const Harness_Lease__open: Parameters<OldHarness.Lease<any>["open"]>;
void Harness_Lease__inst.open(...Harness_Lease__open);
declare const Harness_Lease__run: Parameters<OldHarness.Lease<any>["run"]>;
void Harness_Lease__inst.run(...Harness_Lease__run);
declare const Harness_Lease__endTest: Parameters<OldHarness.Lease<any>["endTest"]>;
void Harness_Lease__inst.endTest(...Harness_Lease__endTest);
declare const Harness_Lease__close: Parameters<OldHarness.Lease<any>["close"]>;
void Harness_Lease__inst.close(...Harness_Lease__close);
declare const Harness_Lease__ledger: Parameters<OldHarness.Lease<any>["ledger"]>;
void Harness_Lease__inst.ledger(...Harness_Lease__ledger);
declare const Harness_Lease__execute: Parameters<OldHarness.Lease<any>["execute"]>;
void Harness_Lease__inst.execute(...Harness_Lease__execute);
declare const Harness_managed: Parameters<typeof OldHarness.managed>;
void NewHarness.managed(...Harness_managed);
declare const Harness_RunBuilder__new: ConstructorParameters<typeof OldHarness.RunBuilder>;
void new NewHarness.RunBuilder(...Harness_RunBuilder__new);
declare const Harness_RunBuilder__inst: NewHarness.RunBuilder<any>;
declare const Harness_RunBuilder__state: Parameters<OldHarness.RunBuilder<any>["state"]>;
void Harness_RunBuilder__inst.state(...Harness_RunBuilder__state);
declare const Harness_RunBuilder__esv: Parameters<OldHarness.RunBuilder<any>["esv"]>;
void Harness_RunBuilder__inst.esv(...Harness_RunBuilder__esv);
declare const Harness_RunBuilder__headers: Parameters<OldHarness.RunBuilder<any>["headers"]>;
void Harness_RunBuilder__inst.headers(...Harness_RunBuilder__headers);
declare const Harness_RunBuilder__params: Parameters<OldHarness.RunBuilder<any>["params"]>;
void Harness_RunBuilder__inst.params(...Harness_RunBuilder__params);
declare const Harness_RunBuilder__session: Parameters<OldHarness.RunBuilder<any>["session"]>;
void Harness_RunBuilder__inst.session(...Harness_RunBuilder__session);
declare const Harness_RunBuilder__step: Parameters<OldHarness.RunBuilder<any>["step"]>;
void Harness_RunBuilder__inst.step(...Harness_RunBuilder__step);
declare const Harness_RunBuilder__steps: Parameters<OldHarness.RunBuilder<any>["steps"]>;
void Harness_RunBuilder__inst.steps(...Harness_RunBuilder__steps);
declare const Harness_RunBuilder__check: Parameters<OldHarness.RunBuilder<any>["check"]>;
void Harness_RunBuilder__inst.check(...Harness_RunBuilder__check);
declare const Harness_RunBuilder__expect: Parameters<OldHarness.RunBuilder<any>["expect"]>;
void Harness_RunBuilder__inst.expect(...Harness_RunBuilder__expect);
declare const Harness_LeaseOptions: OldHarness.LeaseOptions;
export const Harness_LeaseOptions_ok: NewHarness.LeaseOptions = Harness_LeaseOptions;
declare const Harness_LeaseLane: OldHarness.LeaseLane;
export const Harness_LeaseLane_ok: NewHarness.LeaseLane = Harness_LeaseLane;
declare const Harness_LeaseLaneRunRequest: OldHarness.LeaseLaneRunRequest;
export const Harness_LeaseLaneRunRequest_ok: NewHarness.LeaseLaneRunRequest = Harness_LeaseLaneRunRequest;
declare const Harness_RunResult: OldHarness.RunResult;
export const Harness_RunResult_ok: NewHarness.RunResult = Harness_RunResult;
declare const Harness_StepResult: OldHarness.StepResult;
export const Harness_StepResult_ok: NewHarness.StepResult = Harness_StepResult;
declare const Harness_Suite: OldHarness.Suite<any>;
export const Harness_Suite_ok: NewHarness.Suite<any> = Harness_Suite;
declare const Harness_CheckContext: OldHarness.CheckContext<any>;
export const Harness_CheckContext_ok: NewHarness.CheckContext<any> = Harness_CheckContext;
declare const Harness_Check: OldHarness.Check<any>;
export const Harness_Check_ok: NewHarness.Check<any> = Harness_Check;
declare const Harness_LeaseLaneCheck: OldHarness.LeaseLaneCheck;
export const Harness_LeaseLaneCheck_ok: NewHarness.LeaseLaneCheck = Harness_LeaseLaneCheck;
declare const Harness_LeaseLaneHooks: OldHarness.LeaseLaneHooks;
export const Harness_LeaseLaneHooks_ok: NewHarness.LeaseLaneHooks = Harness_LeaseLaneHooks;
declare const Harness_carryGiven: Parameters<typeof OldHarness.carryGiven>;
void NewHarness.carryGiven(...Harness_carryGiven);
declare const Harness_submittedCallbacks: Parameters<typeof OldHarness.submittedCallbacks>;
void NewHarness.submittedCallbacks(...Harness_submittedCallbacks);
declare const Harness_CallbackReply: OldHarness.CallbackReply;
export const Harness_CallbackReply_ok: NewHarness.CallbackReply = Harness_CallbackReply;
declare const Harness_StepContext: OldHarness.StepContext<any>;
export const Harness_StepContext_ok: NewHarness.StepContext<any> = Harness_StepContext;
declare const Harness_StepExpect: OldHarness.StepExpect;
export const Harness_StepExpect_ok: NewHarness.StepExpect = Harness_StepExpect;
declare const Harness_StepSpec: OldHarness.StepSpec<any>;
export const Harness_StepSpec_ok: NewHarness.StepSpec<any> = Harness_StepSpec;
declare const Harness_aicWhenEnabled: Parameters<typeof OldHarness.aicWhenEnabled>;
void NewHarness.aicWhenEnabled(...Harness_aicWhenEnabled);
export const Harness_AIC_LANE_ENV_ok: typeof OldHarness.AIC_LANE_ENV = NewHarness.AIC_LANE_ENV;
declare const Harness_useLease: Parameters<typeof OldHarness.useLease>;
void NewHarness.useLease(...Harness_useLease);
declare const Harness_UseLeaseAicOptions: OldHarness.UseLeaseAicOptions;
export const Harness_UseLeaseAicOptions_ok: NewHarness.UseLeaseAicOptions = Harness_UseLeaseAicOptions;
declare const Harness_UseLeaseOptions: OldHarness.UseLeaseOptions;
export const Harness_UseLeaseOptions_ok: NewHarness.UseLeaseOptions = Harness_UseLeaseOptions;
declare const Harness_localIdmHandle: Parameters<typeof OldHarness.localIdmHandle>;
void NewHarness.localIdmHandle(...Harness_localIdmHandle);
declare const Harness_ledgerToManaged: Parameters<typeof OldHarness.ledgerToManaged>;
void NewHarness.ledgerToManaged(...Harness_ledgerToManaged);
declare const Harness_splitResource: Parameters<typeof OldHarness.splitResource>;
void NewHarness.splitResource(...Harness_splitResource);
declare const Harness_describeResidue: Parameters<typeof OldHarness.describeResidue>;
void NewHarness.describeResidue(...Harness_describeResidue);
declare const Harness_findResidue: Parameters<typeof OldHarness.findResidue>;
void NewHarness.findResidue(...Harness_findResidue);
declare const Harness_ResidueEntry: OldHarness.ResidueEntry;
export const Harness_ResidueEntry_ok: NewHarness.ResidueEntry = Harness_ResidueEntry;
declare const Harness_applyInputsAndEsv: Parameters<typeof OldHarness.applyInputsAndEsv>;
void NewHarness.applyInputsAndEsv(...Harness_applyInputsAndEsv);
declare const Harness_caseWithGiven: Parameters<typeof OldHarness.caseWithGiven>;
void NewHarness.caseWithGiven(...Harness_caseWithGiven);
export const Harness_ESV_STATE_PREFIX_ok: typeof OldHarness.ESV_STATE_PREFIX = NewHarness.ESV_STATE_PREFIX;
declare const Harness_mergeChannels: Parameters<typeof OldHarness.mergeChannels>;
void NewHarness.mergeChannels(...Harness_mergeChannels);
declare const Harness_normaliseWire: Parameters<typeof OldHarness.normaliseWire>;
void NewHarness.normaliseWire(...Harness_normaliseWire);
declare const Harness_parseInputs: Parameters<typeof OldHarness.parseInputs>;
void NewHarness.parseInputs(...Harness_parseInputs);
declare const Harness_toCase: Parameters<typeof OldHarness.toCase>;
void NewHarness.toCase(...Harness_toCase);
declare const Harness_toGiven: Parameters<typeof OldHarness.toGiven>;
void NewHarness.toGiven(...Harness_toGiven);
declare const Harness_WireValue: OldHarness.WireValue;
export const Harness_WireValue_ok: NewHarness.WireValue = Harness_WireValue;
declare const Harness_WireMap: OldHarness.WireMap;
export const Harness_WireMap_ok: NewHarness.WireMap = Harness_WireMap;
declare const Harness_StateChannels: OldHarness.StateChannels;
export const Harness_StateChannels_ok: NewHarness.StateChannels = Harness_StateChannels;
declare const Harness_Channels: OldHarness.Channels;
export const Harness_Channels_ok: NewHarness.Channels = Harness_Channels;
declare const Harness_RequestDraft: OldHarness.RequestDraft;
export const Harness_RequestDraft_ok: NewHarness.RequestDraft = Harness_RequestDraft;
declare const Harness_FixtureSpec: OldHarness.FixtureSpec;
export const Harness_FixtureSpec_ok: NewHarness.FixtureSpec = Harness_FixtureSpec;
declare const Harness_BeforeRunContext: OldHarness.BeforeRunContext<any>;
export const Harness_BeforeRunContext_ok: NewHarness.BeforeRunContext<any> = Harness_BeforeRunContext;
declare const Harness_FixtureCreator: OldHarness.FixtureCreator;
export const Harness_FixtureCreator_ok: NewHarness.FixtureCreator = Harness_FixtureCreator;
declare const Harness_IdmHandle: OldHarness.IdmHandle;
export const Harness_IdmHandle_ok: NewHarness.IdmHandle = Harness_IdmHandle;
declare const Harness_CleanupContext: OldHarness.CleanupContext<any>;
export const Harness_CleanupContext_ok: NewHarness.CleanupContext<any> = Harness_CleanupContext;
declare const Harness_SuiteSpec: OldHarness.SuiteSpec<any>;
export const Harness_SuiteSpec_ok: NewHarness.SuiteSpec<any> = Harness_SuiteSpec;
declare const Harness_RunOverrides: OldHarness.RunOverrides;
export const Harness_RunOverrides_ok: NewHarness.RunOverrides = Harness_RunOverrides;
declare const Harness_Expect: OldHarness.Expect;
export const Harness_Expect_ok: NewHarness.Expect = Harness_Expect;
declare const Harness_Given: OldHarness.Given;
export const Harness_Given_ok: NewHarness.Given = Harness_Given;
declare const Harness_JsonObject: OldHarness.JsonObject;
export const Harness_JsonObject_ok: NewHarness.JsonObject = Harness_JsonObject;
declare const Harness_JsonValue: OldHarness.JsonValue;
export const Harness_JsonValue_ok: NewHarness.JsonValue = Harness_JsonValue;

// src/case/index
declare const Case_isPortable: Parameters<typeof OldCase.isPortable>;
void NewCase.isPortable(...Case_isPortable);
declare const Case_defineCase: Parameters<typeof OldCase.defineCase>;
void NewCase.defineCase(...Case_defineCase);
declare const Case_validateCase: Parameters<typeof OldCase.validateCase>;
void NewCase.validateCase(...Case_validateCase);
declare const Case_judge: Parameters<typeof OldCase.judge>;
void NewCase.judge(...Case_judge);
export const Case_ALLOW_UNDECLARED_CHANNELS_ok: typeof OldCase.ALLOW_UNDECLARED_CHANNELS = NewCase.ALLOW_UNDECLARED_CHANNELS;
export const Case_CASE_KEYS_ok: typeof OldCase.CASE_KEYS = NewCase.CASE_KEYS;
export const Case_CHANNELS_ok: typeof OldCase.CHANNELS = NewCase.CHANNELS;
export const Case_DEFAULT_ALLOW_UNDECLARED_ok: typeof OldCase.DEFAULT_ALLOW_UNDECLARED = NewCase.DEFAULT_ALLOW_UNDECLARED;
export const Case_ENGINES_ok: typeof OldCase.ENGINES = NewCase.ENGINES;
export const Case_ENV_INPUT_KEYS_ok: typeof OldCase.ENV_INPUT_KEYS = NewCase.ENV_INPUT_KEYS;
export const Case_EXPECT_KEYS_ok: typeof OldCase.EXPECT_KEYS = NewCase.EXPECT_KEYS;
export const Case_GIVEN_BINDING_SEEDS_ok: typeof OldCase.GIVEN_BINDING_SEEDS = NewCase.GIVEN_BINDING_SEEDS;
export const Case_GIVEN_KEYS_ok: typeof OldCase.GIVEN_KEYS = NewCase.GIVEN_KEYS;
export const Case_LOG_LEVELS_ok: typeof OldCase.LOG_LEVELS = NewCase.LOG_LEVELS;
export const Case_OPENIDM_METHODS_ok: typeof OldCase.OPENIDM_METHODS = NewCase.OPENIDM_METHODS;
export const Case_OPENIDM_READ_METHODS_ok: typeof OldCase.OPENIDM_READ_METHODS = NewCase.OPENIDM_READ_METHODS;
export const Case_OPENIDM_WRITE_METHODS_ok: typeof OldCase.OPENIDM_WRITE_METHODS = NewCase.OPENIDM_WRITE_METHODS;
export const Case_STATE_DIFF_KEYS_ok: typeof OldCase.STATE_DIFF_KEYS = NewCase.STATE_DIFF_KEYS;
export const Case_STATE_CHANNELS_ok: typeof OldCase.STATE_CHANNELS = NewCase.STATE_CHANNELS;
declare const Case_AllowUndeclared: OldCase.AllowUndeclared;
export const Case_AllowUndeclared_ok: NewCase.AllowUndeclared = Case_AllowUndeclared;
declare const Case_AllowUndeclaredChannel: OldCase.AllowUndeclaredChannel;
export const Case_AllowUndeclaredChannel_ok: NewCase.AllowUndeclaredChannel = Case_AllowUndeclaredChannel;
declare const Case_CallbackEffect: OldCase.CallbackEffect;
export const Case_CallbackEffect_ok: NewCase.CallbackEffect = Case_CallbackEffect;
declare const Case_CallbackExpect: OldCase.CallbackExpect;
export const Case_CallbackExpect_ok: NewCase.CallbackExpect = Case_CallbackExpect;
declare const Case_Case: OldCase.Case;
export const Case_Case_ok: NewCase.Case = Case_Case;
declare const Case_CaseInit: OldCase.CaseInit;
export const Case_CaseInit_ok: NewCase.CaseInit = Case_CaseInit;
declare const Case_Channel: OldCase.Channel;
export const Case_Channel_ok: NewCase.Channel = Case_Channel;
declare const Case_EvidenceChannel: OldCase.EvidenceChannel;
export const Case_EvidenceChannel_ok: NewCase.EvidenceChannel = Case_EvidenceChannel;
declare const Case_Engine: OldCase.Engine;
export const Case_Engine_ok: NewCase.Engine = Case_Engine;
declare const Case_EnvInputKey: OldCase.EnvInputKey;
export const Case_EnvInputKey_ok: NewCase.EnvInputKey = Case_EnvInputKey;
declare const Case_Expect: OldCase.Expect;
export const Case_Expect_ok: NewCase.Expect = Case_Expect;
declare const Case_ExpectedObject: OldCase.ExpectedObject;
export const Case_ExpectedObject_ok: NewCase.ExpectedObject = Case_ExpectedObject;
declare const Case_ExpectedValue: OldCase.ExpectedValue;
export const Case_ExpectedValue_ok: NewCase.ExpectedValue = Case_ExpectedValue;
declare const Case_Given: OldCase.Given;
export const Case_Given_ok: NewCase.Given = Case_Given;
declare const Case_HttpEffect: OldCase.HttpEffect;
export const Case_HttpEffect_ok: NewCase.HttpEffect = Case_HttpEffect;
declare const Case_HttpExpect: OldCase.HttpExpect;
export const Case_HttpExpect_ok: NewCase.HttpExpect = Case_HttpExpect;
declare const Case_HttpMatch: OldCase.HttpMatch;
export const Case_HttpMatch_ok: NewCase.HttpMatch = Case_HttpMatch;
declare const Case_HttpReply: OldCase.HttpReply;
export const Case_HttpReply_ok: NewCase.HttpReply = Case_HttpReply;
declare const Case_HttpStub: OldCase.HttpStub;
export const Case_HttpStub_ok: NewCase.HttpStub = Case_HttpStub;
declare const Case_JsonObject: OldCase.JsonObject;
export const Case_JsonObject_ok: NewCase.JsonObject = Case_JsonObject;
declare const Case_JsonPrimitive: OldCase.JsonPrimitive;
export const Case_JsonPrimitive_ok: NewCase.JsonPrimitive = Case_JsonPrimitive;
declare const Case_JsonValue: OldCase.JsonValue;
export const Case_JsonValue_ok: NewCase.JsonValue = Case_JsonValue;
declare const Case_LogEffect: OldCase.LogEffect;
export const Case_LogEffect_ok: NewCase.LogEffect = Case_LogEffect;
declare const Case_LogExpect: OldCase.LogExpect;
export const Case_LogExpect_ok: NewCase.LogExpect = Case_LogExpect;
declare const Case_LogLevel: OldCase.LogLevel;
export const Case_LogLevel_ok: NewCase.LogLevel = Case_LogLevel;
declare const Case_Mismatch: OldCase.Mismatch;
export const Case_Mismatch_ok: NewCase.Mismatch = Case_Mismatch;
declare const Case_OpenidmEffect: OldCase.OpenidmEffect;
export const Case_OpenidmEffect_ok: NewCase.OpenidmEffect = Case_OpenidmEffect;
declare const Case_OpenidmExpect: OldCase.OpenidmExpect;
export const Case_OpenidmExpect_ok: NewCase.OpenidmExpect = Case_OpenidmExpect;
declare const Case_OpenidmMethod: OldCase.OpenidmMethod;
export const Case_OpenidmMethod_ok: NewCase.OpenidmMethod = Case_OpenidmMethod;
declare const Case_OpenidmReadMethod: OldCase.OpenidmReadMethod;
export const Case_OpenidmReadMethod_ok: NewCase.OpenidmReadMethod = Case_OpenidmReadMethod;
declare const Case_OpenidmWriteMethod: OldCase.OpenidmWriteMethod;
export const Case_OpenidmWriteMethod_ok: NewCase.OpenidmWriteMethod = Case_OpenidmWriteMethod;
declare const Case_Pattern: OldCase.Pattern;
export const Case_Pattern_ok: NewCase.Pattern = Case_Pattern;
declare const Case_RecordingEvidence: OldCase.RecordingEvidence;
export const Case_RecordingEvidence_ok: NewCase.RecordingEvidence = Case_RecordingEvidence;
declare const Case_RecordedEffects: OldCase.RecordedEffects;
export const Case_RecordedEffects_ok: NewCase.RecordedEffects = Case_RecordedEffects;
declare const Case_StateBucket: OldCase.StateBucket;
export const Case_StateBucket_ok: NewCase.StateBucket = Case_StateBucket;
declare const Case_StateChannel: OldCase.StateChannel;
export const Case_StateChannel_ok: NewCase.StateChannel = Case_StateChannel;
declare const Case_StateDiff: OldCase.StateDiff;
export const Case_StateDiff_ok: NewCase.StateDiff = Case_StateDiff;
declare const Case_StateMutation: OldCase.StateMutation;
export const Case_StateMutation_ok: NewCase.StateMutation = Case_StateMutation;
declare const Case_StandardSchema: OldCase.StandardSchema;
export const Case_StandardSchema_ok: NewCase.StandardSchema = Case_StandardSchema;
declare const Case_UnbucketedStateMutation: OldCase.UnbucketedStateMutation;
export const Case_UnbucketedStateMutation_ok: NewCase.UnbucketedStateMutation = Case_UnbucketedStateMutation;
declare const Case_Unverified: OldCase.Unverified;
export const Case_Unverified_ok: NewCase.Unverified = Case_Unverified;
declare const Case_Verdict: OldCase.Verdict;
export const Case_Verdict_ok: NewCase.Verdict = Case_Verdict;

// src/aic/index
export const Aic_HARNESS_CALLBACK_ID_ok: typeof OldAic.HARNESS_CALLBACK_ID = NewAic.HARNESS_CALLBACK_ID;
export const Aic_FAILURE_NODE_ID_ok: typeof OldAic.FAILURE_NODE_ID = NewAic.FAILURE_NODE_ID;
export const Aic_SUCCESS_NODE_ID_ok: typeof OldAic.SUCCESS_NODE_ID = NewAic.SUCCESS_NODE_ID;
declare const Aic_parseAuthenticateCallbacks: Parameters<typeof OldAic.parseAuthenticateCallbacks>;
void NewAic.parseAuthenticateCallbacks(...Aic_parseAuthenticateCallbacks);
declare const Aic_AuthenticateCallbacks: OldAic.AuthenticateCallbacks;
export const Aic_AuthenticateCallbacks_ok: NewAic.AuthenticateCallbacks = Aic_AuthenticateCallbacks;
declare const Aic_chainFromRunResult: Parameters<typeof OldAic.chainFromRunResult>;
void NewAic.chainFromRunResult(...Aic_chainFromRunResult);
declare const Aic_conform: Parameters<typeof OldAic.conform>;
void NewAic.conform(...Aic_conform);
declare const Aic_conformChain: Parameters<typeof OldAic.conformChain>;
void NewAic.conformChain(...Aic_conformChain);
declare const Aic_AicChainRunner: OldAic.AicChainRunner;
export const Aic_AicChainRunner_ok: NewAic.AicChainRunner = Aic_AicChainRunner;
declare const Aic_ChainConformanceInput: OldAic.ChainConformanceInput;
export const Aic_ChainConformanceInput_ok: NewAic.ChainConformanceInput = Aic_ChainConformanceInput;
declare const Aic_ChainConformanceReport: OldAic.ChainConformanceReport;
export const Aic_ChainConformanceReport_ok: NewAic.ChainConformanceReport = Aic_ChainConformanceReport;
declare const Aic_ChainPassReport: OldAic.ChainPassReport;
export const Aic_ChainPassReport_ok: NewAic.ChainPassReport = Aic_ChainPassReport;
declare const Aic_ConformanceInput: OldAic.ConformanceInput;
export const Aic_ConformanceInput_ok: NewAic.ConformanceInput = Aic_ConformanceInput;
declare const Aic_ConformanceReport: OldAic.ConformanceReport;
export const Aic_ConformanceReport_ok: NewAic.ConformanceReport = Aic_ConformanceReport;
declare const Aic_LaneResult: OldAic.LaneResult;
export const Aic_LaneResult_ok: NewAic.LaneResult = Aic_LaneResult;
declare const Aic_LaneRunner: OldAic.LaneRunner;
export const Aic_LaneRunner_ok: NewAic.LaneRunner = Aic_LaneRunner;
declare const Aic_LocalChainResult: OldAic.LocalChainResult;
export const Aic_LocalChainResult_ok: NewAic.LocalChainResult = Aic_LocalChainResult;
declare const Aic_diffRecordedEffects: Parameters<typeof OldAic.diffRecordedEffects>;
void NewAic.diffRecordedEffects(...Aic_diffRecordedEffects);
declare const Aic_judgeBoth: Parameters<typeof OldAic.judgeBoth>;
void NewAic.judgeBoth(...Aic_judgeBoth);
declare const Aic_EffectsComparison: OldAic.EffectsComparison;
export const Aic_EffectsComparison_ok: NewAic.EffectsComparison = Aic_EffectsComparison;
declare const Aic_EffectsDisagreement: OldAic.EffectsDisagreement;
export const Aic_EffectsDisagreement_ok: NewAic.EffectsDisagreement = Aic_EffectsDisagreement;
declare const Aic_ObservationGap: OldAic.ObservationGap;
export const Aic_ObservationGap_ok: NewAic.ObservationGap = Aic_ObservationGap;
declare const Aic_emitLeasedJourney: Parameters<typeof OldAic.emitLeasedJourney>;
void NewAic.emitLeasedJourney(...Aic_emitLeasedJourney);
declare const Aic_emitWrapperJourney: Parameters<typeof OldAic.emitWrapperJourney>;
void NewAic.emitWrapperJourney(...Aic_emitWrapperJourney);
declare const Aic_subjectOutcomes: Parameters<typeof OldAic.subjectOutcomes>;
void NewAic.subjectOutcomes(...Aic_subjectOutcomes);
declare const Aic_EmitJourneyOptions: OldAic.EmitJourneyOptions;
export const Aic_EmitJourneyOptions_ok: NewAic.EmitJourneyOptions = Aic_EmitJourneyOptions;
declare const Aic_LeasedJourneyOptions: OldAic.LeasedJourneyOptions;
export const Aic_LeasedJourneyOptions_ok: NewAic.LeasedJourneyOptions = Aic_LeasedJourneyOptions;
declare const Aic_NodeResource: OldAic.NodeResource;
export const Aic_NodeResource_ok: NewAic.NodeResource = Aic_NodeResource;
declare const Aic_ScriptResource: OldAic.ScriptResource;
export const Aic_ScriptResource_ok: NewAic.ScriptResource = Aic_ScriptResource;
declare const Aic_WrapperInvoke: OldAic.WrapperInvoke;
export const Aic_WrapperInvoke_ok: NewAic.WrapperInvoke = Aic_WrapperInvoke;
declare const Aic_WrapperJourney: OldAic.WrapperJourney;
export const Aic_WrapperJourney_ok: NewAic.WrapperJourney = Aic_WrapperJourney;
export const Aic_AIC_LEASE_NAMESPACE_ok: typeof OldAic.AIC_LEASE_NAMESPACE = NewAic.AIC_LEASE_NAMESPACE;
declare const Aic_createLeaseIdentity: Parameters<typeof OldAic.createLeaseIdentity>;
void NewAic.createLeaseIdentity(...Aic_createLeaseIdentity);
declare const Aic_normalizedLeaseOutcomes: Parameters<typeof OldAic.normalizedLeaseOutcomes>;
void NewAic.normalizedLeaseOutcomes(...Aic_normalizedLeaseOutcomes);
declare const Aic_sha256: Parameters<typeof OldAic.sha256>;
void NewAic.sha256(...Aic_sha256);
declare const Aic_uuidV5: Parameters<typeof OldAic.uuidV5>;
void NewAic.uuidV5(...Aic_uuidV5);
declare const Aic_LeaseIdentity: OldAic.LeaseIdentity;
export const Aic_LeaseIdentity_ok: NewAic.LeaseIdentity = Aic_LeaseIdentity;
declare const Aic_LeaseIdentityOptions: OldAic.LeaseIdentityOptions;
export const Aic_LeaseIdentityOptions_ok: NewAic.LeaseIdentityOptions = Aic_LeaseIdentityOptions;
declare const Aic_LeaseResourceIds: OldAic.LeaseResourceIds;
export const Aic_LeaseResourceIds_ok: NewAic.LeaseResourceIds = Aic_LeaseResourceIds;
declare const Aic_emitResultScript: Parameters<typeof OldAic.emitResultScript>;
void NewAic.emitResultScript(...Aic_emitResultScript);
declare const Aic_emitLeasedSessionJourney: Parameters<typeof OldAic.emitLeasedSessionJourney>;
void NewAic.emitLeasedSessionJourney(...Aic_emitLeasedSessionJourney);
declare const Aic_instrumentSubject: Parameters<typeof OldAic.instrumentSubject>;
void NewAic.instrumentSubject(...Aic_instrumentSubject);
declare const Aic_InstrumentedSubject: OldAic.InstrumentedSubject;
export const Aic_InstrumentedSubject_ok: NewAic.InstrumentedSubject = Aic_InstrumentedSubject;
declare const Aic_ManagedFixture: OldAic.ManagedFixture;
export const Aic_ManagedFixture_ok: NewAic.ManagedFixture = Aic_ManagedFixture;
declare const Aic_AicFileLease__new: ConstructorParameters<typeof OldAic.AicFileLease>;
void new NewAic.AicFileLease(...Aic_AicFileLease__new);
declare const Aic_AicFileLease__inst: NewAic.AicFileLease;
declare const Aic_AicFileLease__open: Parameters<OldAic.AicFileLease["open"]>;
void Aic_AicFileLease__inst.open(...Aic_AicFileLease__open);
declare const Aic_AicFileLease__run: Parameters<OldAic.AicFileLease["run"]>;
void Aic_AicFileLease__inst.run(...Aic_AicFileLease__run);
declare const Aic_AicFileLease__endTest: Parameters<OldAic.AicFileLease["endTest"]>;
void Aic_AicFileLease__inst.endTest(...Aic_AicFileLease__endTest);
declare const Aic_AicFileLease__close: Parameters<OldAic.AicFileLease["close"]>;
void Aic_AicFileLease__inst.close(...Aic_AicFileLease__close);
declare const Aic_AicFileLeaseOptions: OldAic.AicFileLeaseOptions;
export const Aic_AicFileLeaseOptions_ok: NewAic.AicFileLeaseOptions = Aic_AicFileLeaseOptions;
declare const Aic_AicLeaseRunRequest: OldAic.AicLeaseRunRequest;
export const Aic_AicLeaseRunRequest_ok: NewAic.AicLeaseRunRequest = Aic_AicLeaseRunRequest;
declare const Aic_acquireLeaseLock: Parameters<typeof OldAic.acquireLeaseLock>;
void NewAic.acquireLeaseLock(...Aic_acquireLeaseLock);
declare const Aic_addJournalFixture: Parameters<typeof OldAic.addJournalFixture>;
void NewAic.addJournalFixture(...Aic_addJournalFixture);
declare const Aic_addJournalResources: Parameters<typeof OldAic.addJournalResources>;
void NewAic.addJournalResources(...Aic_addJournalResources);
declare const Aic_leaseStatePaths: Parameters<typeof OldAic.leaseStatePaths>;
void NewAic.leaseStatePaths(...Aic_leaseStatePaths);
declare const Aic_newLeaseJournal: Parameters<typeof OldAic.newLeaseJournal>;
void NewAic.newLeaseJournal(...Aic_newLeaseJournal);
declare const Aic_readLeaseJournal: Parameters<typeof OldAic.readLeaseJournal>;
void NewAic.readLeaseJournal(...Aic_readLeaseJournal);
declare const Aic_removeJournalFixture: Parameters<typeof OldAic.removeJournalFixture>;
void NewAic.removeJournalFixture(...Aic_removeJournalFixture);
declare const Aic_removeLeaseJournal: Parameters<typeof OldAic.removeLeaseJournal>;
void NewAic.removeLeaseJournal(...Aic_removeLeaseJournal);
declare const Aic_writeLeaseJournal: Parameters<typeof OldAic.writeLeaseJournal>;
void NewAic.writeLeaseJournal(...Aic_writeLeaseJournal);
declare const Aic_LeaseJournal: OldAic.LeaseJournal;
export const Aic_LeaseJournal_ok: NewAic.LeaseJournal = Aic_LeaseJournal;
declare const Aic_LeaseLock: OldAic.LeaseLock;
export const Aic_LeaseLock_ok: NewAic.LeaseLock = Aic_LeaseLock;
declare const Aic_LeaseStatePaths: OldAic.LeaseStatePaths;
export const Aic_LeaseStatePaths_ok: NewAic.LeaseStatePaths = Aic_LeaseStatePaths;
declare const Aic_confirmResourceSnapshot: Parameters<typeof OldAic.confirmResourceSnapshot>;
void NewAic.confirmResourceSnapshot(...Aic_confirmResourceSnapshot);
declare const Aic_nodeRequestProjection: Parameters<typeof OldAic.nodeRequestProjection>;
void NewAic.nodeRequestProjection(...Aic_nodeRequestProjection);
declare const Aic_resourceRequestProjection: Parameters<typeof OldAic.resourceRequestProjection>;
void NewAic.resourceRequestProjection(...Aic_resourceRequestProjection);
declare const Aic_AicResourceKind: OldAic.AicResourceKind;
export const Aic_AicResourceKind_ok: NewAic.AicResourceKind = Aic_AicResourceKind;
declare const Aic_assembleEffects: Parameters<typeof OldAic.assembleEffects>;
void NewAic.assembleEffects(...Aic_assembleEffects);
declare const Aic_classifyFinal: Parameters<typeof OldAic.classifyFinal>;
void NewAic.classifyFinal(...Aic_classifyFinal);
declare const Aic_parseSubjectDump: Parameters<typeof OldAic.parseSubjectDump>;
void NewAic.parseSubjectDump(...Aic_parseSubjectDump);
declare const Aic_SubjectDump: OldAic.SubjectDump;
export const Aic_SubjectDump_ok: NewAic.SubjectDump = Aic_SubjectDump;
declare const Aic_runAicChain: Parameters<typeof OldAic.runAicChain>;
void NewAic.runAicChain(...Aic_runAicChain);
declare const Aic_runAicLane: Parameters<typeof OldAic.runAicLane>;
void NewAic.runAicLane(...Aic_runAicLane);
declare const Aic_validateAicRun: Parameters<typeof OldAic.validateAicRun>;
void NewAic.validateAicRun(...Aic_validateAicRun);
declare const Aic_AicReply: OldAic.AicReply;
export const Aic_AicReply_ok: NewAic.AicReply = Aic_AicReply;
declare const Aic_AicRunValidation: OldAic.AicRunValidation;
export const Aic_AicRunValidation_ok: NewAic.AicRunValidation = Aic_AicRunValidation;
declare const Aic_RunAicOptions: OldAic.RunAicOptions;
export const Aic_RunAicOptions_ok: NewAic.RunAicOptions = Aic_RunAicOptions;
declare const Aic_AicLaneError__new: ConstructorParameters<typeof OldAic.AicLaneError>;
void new NewAic.AicLaneError(...Aic_AicLaneError__new);
declare const Aic_AicLaneError__inst: NewAic.AicLaneError;
export const Aic_AM_CONFIG_API_VERSION_ok: typeof OldAic.AM_CONFIG_API_VERSION = NewAic.AM_CONFIG_API_VERSION;
declare const Aic_amConfigHeaders: Parameters<typeof OldAic.amConfigHeaders>;
void NewAic.amConfigHeaders(...Aic_amConfigHeaders);
declare const Aic_aicCliProvider: Parameters<typeof OldAic.aicCliProvider>;
void NewAic.aicCliProvider(...Aic_aicCliProvider);
declare const Aic_connectTenant: Parameters<typeof OldAic.connectTenant>;
void NewAic.connectTenant(...Aic_connectTenant);
declare const Aic_defaultAicIo: Parameters<typeof OldAic.defaultAicIo>;
void NewAic.defaultAicIo(...Aic_defaultAicIo);
declare const Aic_resolveTenantProvider: Parameters<typeof OldAic.resolveTenantProvider>;
void NewAic.resolveTenantProvider(...Aic_resolveTenantProvider);
declare const Aic_AicIo: OldAic.AicIo;
export const Aic_AicIo_ok: NewAic.AicIo = Aic_AicIo;
declare const Aic_ConnectOptions: OldAic.ConnectOptions;
export const Aic_ConnectOptions_ok: NewAic.ConnectOptions = Aic_ConnectOptions;
declare const Aic_TenantSession: OldAic.TenantSession;
export const Aic_TenantSession_ok: NewAic.TenantSession = Aic_TenantSession;
declare const Aic_checkTenantDescription: Parameters<typeof OldAic.checkTenantDescription>;
void NewAic.checkTenantDescription(...Aic_checkTenantDescription);
declare const Aic_configuredTenantProvider: Parameters<typeof OldAic.configuredTenantProvider>;
void NewAic.configuredTenantProvider(...Aic_configuredTenantProvider);
export const Aic_DEFAULT_SERVICE_ACCOUNT_SCOPE_ok: typeof OldAic.DEFAULT_SERVICE_ACCOUNT_SCOPE = NewAic.DEFAULT_SERVICE_ACCOUNT_SCOPE;
declare const Aic_logKeysReader: Parameters<typeof OldAic.logKeysReader>;
void NewAic.logKeysReader(...Aic_logKeysReader);
declare const Aic_providerFromEnv: Parameters<typeof OldAic.providerFromEnv>;
void NewAic.providerFromEnv(...Aic_providerFromEnv);
declare const Aic_serviceAccountProvider: Parameters<typeof OldAic.serviceAccountProvider>;
void NewAic.serviceAccountProvider(...Aic_serviceAccountProvider);
declare const Aic_setTenantProvider: Parameters<typeof OldAic.setTenantProvider>;
void NewAic.setTenantProvider(...Aic_setTenantProvider);
export const Aic_TENANT_ENV_ok: typeof OldAic.TENANT_ENV = NewAic.TENANT_ENV;
declare const Aic_tokenCallbackProvider: Parameters<typeof OldAic.tokenCallbackProvider>;
void NewAic.tokenCallbackProvider(...Aic_tokenCallbackProvider);
declare const Aic_TenantProviderError__new: ConstructorParameters<typeof OldAic.TenantProviderError>;
void new NewAic.TenantProviderError(...Aic_TenantProviderError__new);
declare const Aic_TenantProviderError__inst: NewAic.TenantProviderError;
declare const Aic_HttpSend: OldAic.HttpSend;
export const Aic_HttpSend_ok: NewAic.HttpSend = Aic_HttpSend;
declare const Aic_LogKeys: OldAic.LogKeys;
export const Aic_LogKeys_ok: NewAic.LogKeys = Aic_LogKeys;
declare const Aic_LogReader: OldAic.LogReader;
export const Aic_LogReader_ok: NewAic.LogReader = Aic_LogReader;
declare const Aic_ServiceAccountOptions: OldAic.ServiceAccountOptions;
export const Aic_ServiceAccountOptions_ok: NewAic.ServiceAccountOptions = Aic_ServiceAccountOptions;
declare const Aic_TenantDescription: OldAic.TenantDescription;
export const Aic_TenantDescription_ok: NewAic.TenantDescription = Aic_TenantDescription;
declare const Aic_TenantProvider: OldAic.TenantProvider;
export const Aic_TenantProvider_ok: NewAic.TenantProvider = Aic_TenantProvider;
declare const Aic_TokenCallbackOptions: OldAic.TokenCallbackOptions;
export const Aic_TokenCallbackOptions_ok: NewAic.TokenCallbackOptions = Aic_TokenCallbackOptions;
declare const Aic_TokenRequest: OldAic.TokenRequest;
export const Aic_TokenRequest_ok: NewAic.TokenRequest = Aic_TokenRequest;
declare const Aic_aicUnsupportedReason: Parameters<typeof OldAic.aicUnsupportedReason>;
void NewAic.aicUnsupportedReason(...Aic_aicUnsupportedReason);

// src/bindings/index
declare const Bindings_parseHarvest: Parameters<typeof OldBindings.parseHarvest>;
void NewBindings.parseHarvest(...Bindings_parseHarvest);
declare const Bindings_mockPreamble: Parameters<typeof OldBindings.mockPreamble>;
void NewBindings.mockPreamble(...Bindings_mockPreamble);
declare const Bindings_withHarvest: Parameters<typeof OldBindings.withHarvest>;
void NewBindings.withHarvest(...Bindings_withHarvest);
declare const Bindings_runCase: Parameters<typeof OldBindings.runCase>;
void NewBindings.runCase(...Bindings_runCase);
declare const Bindings_CaseRun: OldBindings.CaseRun;
export const Bindings_CaseRun_ok: NewBindings.CaseRun = Bindings_CaseRun;
declare const Bindings_RunCaseOptions: OldBindings.RunCaseOptions;
export const Bindings_RunCaseOptions_ok: NewBindings.RunCaseOptions = Bindings_RunCaseOptions;

// src/runner
declare const Runner_RhinoRunnerExitError__new: ConstructorParameters<typeof OldRunner.RhinoRunnerExitError>;
void new NewRunner.RhinoRunnerExitError(...Runner_RhinoRunnerExitError__new);
declare const Runner_RhinoRunnerExitError__inst: NewRunner.RhinoRunnerExitError;
declare const Runner_LaneDivergenceError__new: ConstructorParameters<typeof OldRunner.LaneDivergenceError>;
void new NewRunner.LaneDivergenceError(...Runner_LaneDivergenceError__new);
declare const Runner_LaneDivergenceError__inst: NewRunner.LaneDivergenceError;
declare const Runner_SpawnRunnerOptions: OldRunner.SpawnRunnerOptions;
export const Runner_SpawnRunnerOptions_ok: NewRunner.SpawnRunnerOptions = Runner_SpawnRunnerOptions;
declare const Runner_RhinoRunner__inst: NewRunner.RhinoRunner;
declare const Runner_RhinoRunner__eval: Parameters<OldRunner.RhinoRunner["eval"]>;
void Runner_RhinoRunner__inst.eval(...Runner_RhinoRunner__eval);
declare const Runner_RhinoRunner__close: Parameters<OldRunner.RhinoRunner["close"]>;
void Runner_RhinoRunner__inst.close(...Runner_RhinoRunner__close);
declare const Runner_RhinoRunner__kill: Parameters<OldRunner.RhinoRunner["kill"]>;
void Runner_RhinoRunner__inst.kill(...Runner_RhinoRunner__kill);
declare const Runner_RhinoRunner__s_spawn: Parameters<typeof OldRunner.RhinoRunner["spawn"]>;
void NewRunner.RhinoRunner.spawn(...Runner_RhinoRunner__s_spawn);

// src/profile/index
export const Profile_MANAGED_CONFIG_ENDPOINT_ok: typeof OldProfile.MANAGED_CONFIG_ENDPOINT = NewProfile.MANAGED_CONFIG_ENDPOINT;
declare const Profile_pullProfile: Parameters<typeof OldProfile.pullProfile>;
void NewProfile.pullProfile(...Profile_pullProfile);
declare const Profile_PullOptions: OldProfile.PullOptions;
export const Profile_PullOptions_ok: NewProfile.PullOptions = Profile_PullOptions;
declare const Profile_parseProfile: Parameters<typeof OldProfile.parseProfile>;
void NewProfile.parseProfile(...Profile_parseProfile);
declare const Profile_profilePath: Parameters<typeof OldProfile.profilePath>;
void NewProfile.profilePath(...Profile_profilePath);
declare const Profile_readProfile: Parameters<typeof OldProfile.readProfile>;
void NewProfile.readProfile(...Profile_readProfile);
declare const Profile_tryReadProfile: Parameters<typeof OldProfile.tryReadProfile>;
void NewProfile.tryReadProfile(...Profile_tryReadProfile);
declare const Profile_writeProfile: Parameters<typeof OldProfile.writeProfile>;
void NewProfile.writeProfile(...Profile_writeProfile);
declare const Profile_ProfileShapeError__new: ConstructorParameters<typeof OldProfile.ProfileShapeError>;
void new NewProfile.ProfileShapeError(...Profile_ProfileShapeError__new);
declare const Profile_ProfileShapeError__inst: NewProfile.ProfileShapeError;
declare const Profile_EnvProfile: OldProfile.EnvProfile;
export const Profile_EnvProfile_ok: NewProfile.EnvProfile = Profile_EnvProfile;
declare const Profile_ObjectSchema: OldProfile.ObjectSchema;
export const Profile_ObjectSchema_ok: NewProfile.ObjectSchema = Profile_ObjectSchema;
declare const Profile_PropertySchema: OldProfile.PropertySchema;
export const Profile_PropertySchema_ok: NewProfile.PropertySchema = Profile_PropertySchema;

// src/diagnostics
declare const Diagnostics_readFailures: Parameters<typeof OldDiagnostics.readFailures>;
void NewDiagnostics.readFailures(...Diagnostics_readFailures);
declare const Diagnostics_sortNewestFirst: Parameters<typeof OldDiagnostics.sortNewestFirst>;
void NewDiagnostics.sortNewestFirst(...Diagnostics_sortNewestFirst);
declare const Diagnostics_FailureRecord: OldDiagnostics.FailureRecord;
export const Diagnostics_FailureRecord_ok: NewDiagnostics.FailureRecord = Diagnostics_FailureRecord;
declare const Diagnostics_createDefaultIo: Parameters<typeof OldDiagnostics.createDefaultIo>;
void NewDiagnostics.createDefaultIo(...Diagnostics_createDefaultIo);
declare const Diagnostics_runShowLog: Parameters<typeof OldDiagnostics.runShowLog>;
void NewDiagnostics.runShowLog(...Diagnostics_runShowLog);
declare const Diagnostics_ShowLogIo: OldDiagnostics.ShowLogIo;
export const Diagnostics_ShowLogIo_ok: NewDiagnostics.ShowLogIo = Diagnostics_ShowLogIo;
declare const Diagnostics_ShowLogOptions: OldDiagnostics.ShowLogOptions;
export const Diagnostics_ShowLogOptions_ok: NewDiagnostics.ShowLogOptions = Diagnostics_ShowLogOptions;
declare const Diagnostics_loadProviderModule: Parameters<typeof OldDiagnostics.loadProviderModule>;
void NewDiagnostics.loadProviderModule(...Diagnostics_loadProviderModule);
declare const Diagnostics_projectRoot: Parameters<typeof OldDiagnostics.projectRoot>;
void NewDiagnostics.projectRoot(...Diagnostics_projectRoot);
declare const Diagnostics_stateDir: Parameters<typeof OldDiagnostics.stateDir>;
void NewDiagnostics.stateDir(...Diagnostics_stateDir);
export const Diagnostics_PROJECT_ENV_ok: typeof OldDiagnostics.PROJECT_ENV = NewDiagnostics.PROJECT_ENV;
export const Diagnostics_STATE_DIR_ENV_ok: typeof OldDiagnostics.STATE_DIR_ENV = NewDiagnostics.STATE_DIR_ENV;
