/**
 * A 0.1.2-shaped consumer, compiled against HEAD by `npm run typecheck`.
 *
 * `v0.1.2/` is the declaration output of tag `script-tester-v0.1.2`, vendored
 * as built apart from the lines marked `compat-accepted`. Every line below
 * takes a value typed by 0.1.2 and hands it to the
 * current export of the same name: every exported function and method is
 * called with 0.1.2's parameter list, and every exported interface and type
 * (callback interfaces included) is assigned from its 0.1.2 shape. A
 * compile error here is a source break for a 0.1.2 consumer. Nothing in this
 * file runs; it is not a `*.test.ts`.
 *
 * Types only the harness builds (OUTPUTS in generate.mjs) are checked the
 * other way, HEAD -> 0.1.2: a richer value is fine there. Lines marked
 * `compat-accepted` in v0.1.2/ are the deliberate source changes since 0.1.2,
 * each documented in the README. Regenerate with `generate.mjs`.
 *
 * Generic parameters are filled with `any`, so this checks each type's
 * structure rather than its schema-specific inference.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
import type * as OldHarness from "./v0.1.2/src/harness/index.ts";
import type * as OldCase from "./v0.1.2/src/case/index.ts";
import type * as OldAic from "./v0.1.2/src/aic/index.ts";
import type * as OldBindings from "./v0.1.2/src/bindings/index.ts";
import type * as OldRunner from "./v0.1.2/src/runner.ts";
import type * as OldProfile from "./v0.1.2/src/profile/index.ts";
import type * as OldDiagnostics from "./v0.1.2/src/diagnostics.ts";
import * as NewHarness from "../../src/harness/index.ts";
import * as NewCase from "../../src/case/index.ts";
import * as NewAic from "../../src/aic/index.ts";
import * as NewBindings from "../../src/bindings/index.ts";
import * as NewRunner from "../../src/runner.ts";
import * as NewProfile from "../../src/profile/index.ts";
import * as NewDiagnostics from "../../src/diagnostics.ts";

type Keeps<O, N> = O extends readonly unknown[]
  ? N extends readonly unknown[] ? (O[number] extends N[number] ? true : false) : false
  : N extends O ? true : false;

// src/harness/index
declare const _Harness_defineSuite: Parameters<typeof OldHarness.defineSuite>;
void NewHarness.defineSuite(..._Harness_defineSuite);
declare const _Harness_Lease__new: ConstructorParameters<typeof OldHarness.Lease>;
void new NewHarness.Lease(..._Harness_Lease__new);
declare const _Harness_Lease__inst: NewHarness.Lease<any>;
declare const _Harness_Lease__open: Parameters<OldHarness.Lease<any>["open"]>;
void _Harness_Lease__inst.open(..._Harness_Lease__open);
declare const _Harness_Lease__run: Parameters<OldHarness.Lease<any>["run"]>;
void _Harness_Lease__inst.run(..._Harness_Lease__run);
declare const _Harness_Lease__endTest: Parameters<OldHarness.Lease<any>["endTest"]>;
void _Harness_Lease__inst.endTest(..._Harness_Lease__endTest);
declare const _Harness_Lease__close: Parameters<OldHarness.Lease<any>["close"]>;
void _Harness_Lease__inst.close(..._Harness_Lease__close);
declare const _Harness_Lease__ledger: Parameters<OldHarness.Lease<any>["ledger"]>;
void _Harness_Lease__inst.ledger(..._Harness_Lease__ledger);
declare const _Harness_Lease__execute: Parameters<OldHarness.Lease<any>["execute"]>;
void _Harness_Lease__inst.execute(..._Harness_Lease__execute);
declare const _Harness_managed: Parameters<typeof OldHarness.managed>;
void NewHarness.managed(..._Harness_managed);
declare const _Harness_RunBuilder__new: ConstructorParameters<typeof OldHarness.RunBuilder>;
void new NewHarness.RunBuilder(..._Harness_RunBuilder__new);
declare const _Harness_RunBuilder__inst: NewHarness.RunBuilder<any>;
declare const _Harness_RunBuilder__state: Parameters<OldHarness.RunBuilder<any>["state"]>;
void _Harness_RunBuilder__inst.state(..._Harness_RunBuilder__state);
declare const _Harness_RunBuilder__esv: Parameters<OldHarness.RunBuilder<any>["esv"]>;
void _Harness_RunBuilder__inst.esv(..._Harness_RunBuilder__esv);
declare const _Harness_RunBuilder__headers: Parameters<OldHarness.RunBuilder<any>["headers"]>;
void _Harness_RunBuilder__inst.headers(..._Harness_RunBuilder__headers);
declare const _Harness_RunBuilder__params: Parameters<OldHarness.RunBuilder<any>["params"]>;
void _Harness_RunBuilder__inst.params(..._Harness_RunBuilder__params);
declare const _Harness_RunBuilder__session: Parameters<OldHarness.RunBuilder<any>["session"]>;
void _Harness_RunBuilder__inst.session(..._Harness_RunBuilder__session);
declare const _Harness_RunBuilder__step: Parameters<OldHarness.RunBuilder<any>["step"]>;
void _Harness_RunBuilder__inst.step(..._Harness_RunBuilder__step);
declare const _Harness_RunBuilder__steps: Parameters<OldHarness.RunBuilder<any>["steps"]>;
void _Harness_RunBuilder__inst.steps(..._Harness_RunBuilder__steps);
declare const _Harness_RunBuilder__check: Parameters<OldHarness.RunBuilder<any>["check"]>;
void _Harness_RunBuilder__inst.check(..._Harness_RunBuilder__check);
declare const _Harness_RunBuilder__expect: Parameters<OldHarness.RunBuilder<any>["expect"]>;
void _Harness_RunBuilder__inst.expect(..._Harness_RunBuilder__expect);
declare const _Harness_LeaseOptions: OldHarness.LeaseOptions;
export const _Harness_LeaseOptions_ok: NewHarness.LeaseOptions = _Harness_LeaseOptions;
declare const _Harness_LeaseLane: OldHarness.LeaseLane;
export const _Harness_LeaseLane_ok: NewHarness.LeaseLane = _Harness_LeaseLane;
declare const _Harness_LeaseLaneRunRequest: NewHarness.LeaseLaneRunRequest;
export const _Harness_LeaseLaneRunRequest_ok: OldHarness.LeaseLaneRunRequest = _Harness_LeaseLaneRunRequest;
declare const _Harness_RunResult: NewHarness.RunResult;
export const _Harness_RunResult_ok: OldHarness.RunResult = _Harness_RunResult;
declare const _Harness_StepResult: NewHarness.StepResult;
export const _Harness_StepResult_ok: OldHarness.StepResult = _Harness_StepResult;
declare const _Harness_Suite: OldHarness.Suite<any>;
export const _Harness_Suite_ok: NewHarness.Suite<any> = _Harness_Suite;
declare const _Harness_CheckContext: NewHarness.CheckContext<any>;
export const _Harness_CheckContext_ok: OldHarness.CheckContext<any> = _Harness_CheckContext;
declare const _Harness_Check: OldHarness.Check<any>;
export const _Harness_Check_ok: NewHarness.Check<any> = _Harness_Check;
declare const _Harness_LeaseLaneCheck: OldHarness.LeaseLaneCheck;
export const _Harness_LeaseLaneCheck_ok: NewHarness.LeaseLaneCheck = _Harness_LeaseLaneCheck;
declare const _Harness_LeaseLaneHooks: OldHarness.LeaseLaneHooks;
export const _Harness_LeaseLaneHooks_ok: NewHarness.LeaseLaneHooks = _Harness_LeaseLaneHooks;
declare const _Harness_carryGiven: Parameters<typeof OldHarness.carryGiven>;
void NewHarness.carryGiven(..._Harness_carryGiven);
declare const _Harness_submittedCallbacks: Parameters<typeof OldHarness.submittedCallbacks>;
void NewHarness.submittedCallbacks(..._Harness_submittedCallbacks);
declare const _Harness_CallbackReply: OldHarness.CallbackReply;
export const _Harness_CallbackReply_ok: NewHarness.CallbackReply = _Harness_CallbackReply;
declare const _Harness_StepContext: NewHarness.StepContext<any>;
export const _Harness_StepContext_ok: OldHarness.StepContext<any> = _Harness_StepContext;
declare const _Harness_StepExpect: OldHarness.StepExpect;
export const _Harness_StepExpect_ok: NewHarness.StepExpect = _Harness_StepExpect;
declare const _Harness_StepSpec: OldHarness.StepSpec<any>;
export const _Harness_StepSpec_ok: NewHarness.StepSpec<any> = _Harness_StepSpec;
declare const _Harness_aicWhenEnabled: Parameters<typeof OldHarness.aicWhenEnabled>;
void NewHarness.aicWhenEnabled(..._Harness_aicWhenEnabled);
export const _Harness_AIC_LANE_ENV_ok: Keeps<typeof OldHarness.AIC_LANE_ENV, typeof NewHarness.AIC_LANE_ENV> = true;
declare const _Harness_useLease: Parameters<typeof OldHarness.useLease>;
void NewHarness.useLease(..._Harness_useLease);
declare const _Harness_UseLeaseAicOptions: OldHarness.UseLeaseAicOptions;
export const _Harness_UseLeaseAicOptions_ok: NewHarness.UseLeaseAicOptions = _Harness_UseLeaseAicOptions;
declare const _Harness_UseLeaseOptions: OldHarness.UseLeaseOptions;
export const _Harness_UseLeaseOptions_ok: NewHarness.UseLeaseOptions = _Harness_UseLeaseOptions;
declare const _Harness_localIdmHandle: Parameters<typeof OldHarness.localIdmHandle>;
void NewHarness.localIdmHandle(..._Harness_localIdmHandle);
declare const _Harness_ledgerToManaged: Parameters<typeof OldHarness.ledgerToManaged>;
void NewHarness.ledgerToManaged(..._Harness_ledgerToManaged);
declare const _Harness_splitResource: Parameters<typeof OldHarness.splitResource>;
void NewHarness.splitResource(..._Harness_splitResource);
declare const _Harness_describeResidue: Parameters<typeof OldHarness.describeResidue>;
void NewHarness.describeResidue(..._Harness_describeResidue);
declare const _Harness_findResidue: Parameters<typeof OldHarness.findResidue>;
void NewHarness.findResidue(..._Harness_findResidue);
declare const _Harness_ResidueEntry: OldHarness.ResidueEntry;
export const _Harness_ResidueEntry_ok: NewHarness.ResidueEntry = _Harness_ResidueEntry;
declare const _Harness_applyInputsAndEsv: Parameters<typeof OldHarness.applyInputsAndEsv>;
void NewHarness.applyInputsAndEsv(..._Harness_applyInputsAndEsv);
declare const _Harness_caseWithGiven: Parameters<typeof OldHarness.caseWithGiven>;
void NewHarness.caseWithGiven(..._Harness_caseWithGiven);
export const _Harness_ESV_STATE_PREFIX_ok: Keeps<typeof OldHarness.ESV_STATE_PREFIX, typeof NewHarness.ESV_STATE_PREFIX> = true;
declare const _Harness_mergeChannels: Parameters<typeof OldHarness.mergeChannels>;
void NewHarness.mergeChannels(..._Harness_mergeChannels);
declare const _Harness_normaliseWire: Parameters<typeof OldHarness.normaliseWire>;
void NewHarness.normaliseWire(..._Harness_normaliseWire);
declare const _Harness_parseInputs: Parameters<typeof OldHarness.parseInputs>;
void NewHarness.parseInputs(..._Harness_parseInputs);
declare const _Harness_toCase: Parameters<typeof OldHarness.toCase>;
void NewHarness.toCase(..._Harness_toCase);
declare const _Harness_toGiven: Parameters<typeof OldHarness.toGiven>;
void NewHarness.toGiven(..._Harness_toGiven);
declare const _Harness_WireValue: OldHarness.WireValue;
export const _Harness_WireValue_ok: NewHarness.WireValue = _Harness_WireValue;
declare const _Harness_WireMap: OldHarness.WireMap;
export const _Harness_WireMap_ok: NewHarness.WireMap = _Harness_WireMap;
declare const _Harness_StateChannels: OldHarness.StateChannels;
export const _Harness_StateChannels_ok: NewHarness.StateChannels = _Harness_StateChannels;
declare const _Harness_Channels: OldHarness.Channels;
export const _Harness_Channels_ok: NewHarness.Channels = _Harness_Channels;
declare const _Harness_RequestDraft: OldHarness.RequestDraft;
export const _Harness_RequestDraft_ok: NewHarness.RequestDraft = _Harness_RequestDraft;
declare const _Harness_FixtureSpec: OldHarness.FixtureSpec;
export const _Harness_FixtureSpec_ok: NewHarness.FixtureSpec = _Harness_FixtureSpec;
declare const _Harness_BeforeRunContext: NewHarness.BeforeRunContext<any>;
export const _Harness_BeforeRunContext_ok: OldHarness.BeforeRunContext<any> = _Harness_BeforeRunContext;
declare const _Harness_FixtureCreator: OldHarness.FixtureCreator;
export const _Harness_FixtureCreator_ok: NewHarness.FixtureCreator = _Harness_FixtureCreator;
declare const _Harness_IdmHandle: OldHarness.IdmHandle;
export const _Harness_IdmHandle_ok: NewHarness.IdmHandle = _Harness_IdmHandle;
declare const _Harness_CleanupContext: OldHarness.CleanupContext<any>;
export const _Harness_CleanupContext_ok: NewHarness.CleanupContext<any> = _Harness_CleanupContext;
declare const _Harness_SuiteSpec: OldHarness.SuiteSpec<any>;
export const _Harness_SuiteSpec_ok: NewHarness.SuiteSpec<any> = _Harness_SuiteSpec;
declare const _Harness_RunOverrides: OldHarness.RunOverrides;
export const _Harness_RunOverrides_ok: NewHarness.RunOverrides = _Harness_RunOverrides;
declare const _Harness_Expect: OldHarness.Expect;
export const _Harness_Expect_ok: NewHarness.Expect = _Harness_Expect;
declare const _Harness_Given: OldHarness.Given;
export const _Harness_Given_ok: NewHarness.Given = _Harness_Given;
declare const _Harness_JsonObject: OldHarness.JsonObject;
export const _Harness_JsonObject_ok: NewHarness.JsonObject = _Harness_JsonObject;
declare const _Harness_JsonValue: OldHarness.JsonValue;
export const _Harness_JsonValue_ok: NewHarness.JsonValue = _Harness_JsonValue;

// src/case/index
declare const _Case_isPortable: Parameters<typeof OldCase.isPortable>;
void NewCase.isPortable(..._Case_isPortable);
declare const _Case_defineCase: Parameters<typeof OldCase.defineCase>;
void NewCase.defineCase(..._Case_defineCase);
declare const _Case_validateCase: Parameters<typeof OldCase.validateCase>;
void NewCase.validateCase(..._Case_validateCase);
declare const _Case_judge: Parameters<typeof OldCase.judge>;
void NewCase.judge(..._Case_judge);
export const _Case_ALLOW_UNDECLARED_CHANNELS_ok: Keeps<typeof OldCase.ALLOW_UNDECLARED_CHANNELS, typeof NewCase.ALLOW_UNDECLARED_CHANNELS> = true;
export const _Case_CASE_KEYS_ok: Keeps<typeof OldCase.CASE_KEYS, typeof NewCase.CASE_KEYS> = true;
export const _Case_CHANNELS_ok: Keeps<typeof OldCase.CHANNELS, typeof NewCase.CHANNELS> = true;
export const _Case_DEFAULT_ALLOW_UNDECLARED_ok: Keeps<typeof OldCase.DEFAULT_ALLOW_UNDECLARED, typeof NewCase.DEFAULT_ALLOW_UNDECLARED> = true;
export const _Case_ENGINES_ok: Keeps<typeof OldCase.ENGINES, typeof NewCase.ENGINES> = true;
export const _Case_ENV_INPUT_KEYS_ok: Keeps<typeof OldCase.ENV_INPUT_KEYS, typeof NewCase.ENV_INPUT_KEYS> = true;
export const _Case_EXPECT_KEYS_ok: Keeps<typeof OldCase.EXPECT_KEYS, typeof NewCase.EXPECT_KEYS> = true;
export const _Case_GIVEN_BINDING_SEEDS_ok: Keeps<typeof OldCase.GIVEN_BINDING_SEEDS, typeof NewCase.GIVEN_BINDING_SEEDS> = true;
export const _Case_GIVEN_KEYS_ok: Keeps<typeof OldCase.GIVEN_KEYS, typeof NewCase.GIVEN_KEYS> = true;
export const _Case_LOG_LEVELS_ok: Keeps<typeof OldCase.LOG_LEVELS, typeof NewCase.LOG_LEVELS> = true;
export const _Case_OPENIDM_METHODS_ok: Keeps<typeof OldCase.OPENIDM_METHODS, typeof NewCase.OPENIDM_METHODS> = true;
export const _Case_OPENIDM_READ_METHODS_ok: Keeps<typeof OldCase.OPENIDM_READ_METHODS, typeof NewCase.OPENIDM_READ_METHODS> = true;
export const _Case_OPENIDM_WRITE_METHODS_ok: Keeps<typeof OldCase.OPENIDM_WRITE_METHODS, typeof NewCase.OPENIDM_WRITE_METHODS> = true;
export const _Case_STATE_DIFF_KEYS_ok: Keeps<typeof OldCase.STATE_DIFF_KEYS, typeof NewCase.STATE_DIFF_KEYS> = true;
export const _Case_STATE_CHANNELS_ok: Keeps<typeof OldCase.STATE_CHANNELS, typeof NewCase.STATE_CHANNELS> = true;
declare const _Case_AllowUndeclared: OldCase.AllowUndeclared;
export const _Case_AllowUndeclared_ok: NewCase.AllowUndeclared = _Case_AllowUndeclared;
declare const _Case_AllowUndeclaredChannel: OldCase.AllowUndeclaredChannel;
export const _Case_AllowUndeclaredChannel_ok: NewCase.AllowUndeclaredChannel = _Case_AllowUndeclaredChannel;
declare const _Case_CallbackEffect: OldCase.CallbackEffect;
export const _Case_CallbackEffect_ok: NewCase.CallbackEffect = _Case_CallbackEffect;
declare const _Case_CallbackExpect: OldCase.CallbackExpect;
export const _Case_CallbackExpect_ok: NewCase.CallbackExpect = _Case_CallbackExpect;
declare const _Case_Case: OldCase.Case;
export const _Case_Case_ok: NewCase.Case = _Case_Case;
declare const _Case_CaseInit: OldCase.CaseInit;
export const _Case_CaseInit_ok: NewCase.CaseInit = _Case_CaseInit;
declare const _Case_Channel: OldCase.Channel;
export const _Case_Channel_ok: NewCase.Channel = _Case_Channel;
declare const _Case_EvidenceChannel: OldCase.EvidenceChannel;
export const _Case_EvidenceChannel_ok: NewCase.EvidenceChannel = _Case_EvidenceChannel;
declare const _Case_Engine: OldCase.Engine;
export const _Case_Engine_ok: NewCase.Engine = _Case_Engine;
declare const _Case_EnvInputKey: OldCase.EnvInputKey;
export const _Case_EnvInputKey_ok: NewCase.EnvInputKey = _Case_EnvInputKey;
declare const _Case_Expect: OldCase.Expect;
export const _Case_Expect_ok: NewCase.Expect = _Case_Expect;
declare const _Case_ExpectedObject: OldCase.ExpectedObject;
export const _Case_ExpectedObject_ok: NewCase.ExpectedObject = _Case_ExpectedObject;
declare const _Case_ExpectedValue: OldCase.ExpectedValue;
export const _Case_ExpectedValue_ok: NewCase.ExpectedValue = _Case_ExpectedValue;
declare const _Case_Given: OldCase.Given;
export const _Case_Given_ok: NewCase.Given = _Case_Given;
declare const _Case_HttpEffect: OldCase.HttpEffect;
export const _Case_HttpEffect_ok: NewCase.HttpEffect = _Case_HttpEffect;
declare const _Case_HttpExpect: OldCase.HttpExpect;
export const _Case_HttpExpect_ok: NewCase.HttpExpect = _Case_HttpExpect;
declare const _Case_HttpMatch: OldCase.HttpMatch;
export const _Case_HttpMatch_ok: NewCase.HttpMatch = _Case_HttpMatch;
declare const _Case_HttpReply: OldCase.HttpReply;
export const _Case_HttpReply_ok: NewCase.HttpReply = _Case_HttpReply;
declare const _Case_HttpStub: OldCase.HttpStub;
export const _Case_HttpStub_ok: NewCase.HttpStub = _Case_HttpStub;
declare const _Case_JsonObject: OldCase.JsonObject;
export const _Case_JsonObject_ok: NewCase.JsonObject = _Case_JsonObject;
declare const _Case_JsonPrimitive: OldCase.JsonPrimitive;
export const _Case_JsonPrimitive_ok: NewCase.JsonPrimitive = _Case_JsonPrimitive;
declare const _Case_JsonValue: OldCase.JsonValue;
export const _Case_JsonValue_ok: NewCase.JsonValue = _Case_JsonValue;
declare const _Case_LogEffect: OldCase.LogEffect;
export const _Case_LogEffect_ok: NewCase.LogEffect = _Case_LogEffect;
declare const _Case_LogExpect: OldCase.LogExpect;
export const _Case_LogExpect_ok: NewCase.LogExpect = _Case_LogExpect;
declare const _Case_LogLevel: OldCase.LogLevel;
export const _Case_LogLevel_ok: NewCase.LogLevel = _Case_LogLevel;
declare const _Case_Mismatch: OldCase.Mismatch;
export const _Case_Mismatch_ok: NewCase.Mismatch = _Case_Mismatch;
declare const _Case_OpenidmEffect: OldCase.OpenidmEffect;
export const _Case_OpenidmEffect_ok: NewCase.OpenidmEffect = _Case_OpenidmEffect;
declare const _Case_OpenidmExpect: OldCase.OpenidmExpect;
export const _Case_OpenidmExpect_ok: NewCase.OpenidmExpect = _Case_OpenidmExpect;
declare const _Case_OpenidmMethod: OldCase.OpenidmMethod;
export const _Case_OpenidmMethod_ok: NewCase.OpenidmMethod = _Case_OpenidmMethod;
declare const _Case_OpenidmReadMethod: OldCase.OpenidmReadMethod;
export const _Case_OpenidmReadMethod_ok: NewCase.OpenidmReadMethod = _Case_OpenidmReadMethod;
declare const _Case_OpenidmWriteMethod: OldCase.OpenidmWriteMethod;
export const _Case_OpenidmWriteMethod_ok: NewCase.OpenidmWriteMethod = _Case_OpenidmWriteMethod;
declare const _Case_Pattern: OldCase.Pattern;
export const _Case_Pattern_ok: NewCase.Pattern = _Case_Pattern;
declare const _Case_RecordingEvidence: OldCase.RecordingEvidence;
export const _Case_RecordingEvidence_ok: NewCase.RecordingEvidence = _Case_RecordingEvidence;
declare const _Case_RecordedEffects: OldCase.RecordedEffects;
export const _Case_RecordedEffects_ok: NewCase.RecordedEffects = _Case_RecordedEffects;
declare const _Case_StateBucket: OldCase.StateBucket;
export const _Case_StateBucket_ok: NewCase.StateBucket = _Case_StateBucket;
declare const _Case_StateChannel: OldCase.StateChannel;
export const _Case_StateChannel_ok: NewCase.StateChannel = _Case_StateChannel;
declare const _Case_StateDiff: OldCase.StateDiff;
export const _Case_StateDiff_ok: NewCase.StateDiff = _Case_StateDiff;
declare const _Case_StateMutation: OldCase.StateMutation;
export const _Case_StateMutation_ok: NewCase.StateMutation = _Case_StateMutation;
declare const _Case_StandardSchema: OldCase.StandardSchema;
export const _Case_StandardSchema_ok: NewCase.StandardSchema = _Case_StandardSchema;
declare const _Case_UnbucketedStateMutation: OldCase.UnbucketedStateMutation;
export const _Case_UnbucketedStateMutation_ok: NewCase.UnbucketedStateMutation = _Case_UnbucketedStateMutation;
declare const _Case_Unverified: OldCase.Unverified;
export const _Case_Unverified_ok: NewCase.Unverified = _Case_Unverified;
declare const _Case_Verdict: OldCase.Verdict;
export const _Case_Verdict_ok: NewCase.Verdict = _Case_Verdict;

// src/aic/index
export const _Aic_HARNESS_CALLBACK_ID_ok: Keeps<typeof OldAic.HARNESS_CALLBACK_ID, typeof NewAic.HARNESS_CALLBACK_ID> = true;
export const _Aic_FAILURE_NODE_ID_ok: Keeps<typeof OldAic.FAILURE_NODE_ID, typeof NewAic.FAILURE_NODE_ID> = true;
export const _Aic_SUCCESS_NODE_ID_ok: Keeps<typeof OldAic.SUCCESS_NODE_ID, typeof NewAic.SUCCESS_NODE_ID> = true;
declare const _Aic_parseAuthenticateCallbacks: Parameters<typeof OldAic.parseAuthenticateCallbacks>;
void NewAic.parseAuthenticateCallbacks(..._Aic_parseAuthenticateCallbacks);
declare const _Aic_AuthenticateCallbacks: OldAic.AuthenticateCallbacks;
export const _Aic_AuthenticateCallbacks_ok: NewAic.AuthenticateCallbacks = _Aic_AuthenticateCallbacks;
declare const _Aic_chainFromRunResult: Parameters<typeof OldAic.chainFromRunResult>;
void NewAic.chainFromRunResult(..._Aic_chainFromRunResult);
declare const _Aic_conform: Parameters<typeof OldAic.conform>;
void NewAic.conform(..._Aic_conform);
declare const _Aic_conformChain: Parameters<typeof OldAic.conformChain>;
void NewAic.conformChain(..._Aic_conformChain);
declare const _Aic_AicChainRunner: OldAic.AicChainRunner;
export const _Aic_AicChainRunner_ok: NewAic.AicChainRunner = _Aic_AicChainRunner;
declare const _Aic_ChainConformanceInput: OldAic.ChainConformanceInput;
export const _Aic_ChainConformanceInput_ok: NewAic.ChainConformanceInput = _Aic_ChainConformanceInput;
declare const _Aic_ChainConformanceReport: OldAic.ChainConformanceReport;
export const _Aic_ChainConformanceReport_ok: NewAic.ChainConformanceReport = _Aic_ChainConformanceReport;
declare const _Aic_ChainPassReport: OldAic.ChainPassReport;
export const _Aic_ChainPassReport_ok: NewAic.ChainPassReport = _Aic_ChainPassReport;
declare const _Aic_ConformanceInput: OldAic.ConformanceInput;
export const _Aic_ConformanceInput_ok: NewAic.ConformanceInput = _Aic_ConformanceInput;
declare const _Aic_ConformanceReport: OldAic.ConformanceReport;
export const _Aic_ConformanceReport_ok: NewAic.ConformanceReport = _Aic_ConformanceReport;
declare const _Aic_LaneResult: OldAic.LaneResult;
export const _Aic_LaneResult_ok: NewAic.LaneResult = _Aic_LaneResult;
declare const _Aic_LaneRunner: OldAic.LaneRunner;
export const _Aic_LaneRunner_ok: NewAic.LaneRunner = _Aic_LaneRunner;
declare const _Aic_LocalChainResult: OldAic.LocalChainResult;
export const _Aic_LocalChainResult_ok: NewAic.LocalChainResult = _Aic_LocalChainResult;
declare const _Aic_diffRecordedEffects: Parameters<typeof OldAic.diffRecordedEffects>;
void NewAic.diffRecordedEffects(..._Aic_diffRecordedEffects);
declare const _Aic_judgeBoth: Parameters<typeof OldAic.judgeBoth>;
void NewAic.judgeBoth(..._Aic_judgeBoth);
declare const _Aic_EffectsComparison: OldAic.EffectsComparison;
export const _Aic_EffectsComparison_ok: NewAic.EffectsComparison = _Aic_EffectsComparison;
declare const _Aic_EffectsDisagreement: OldAic.EffectsDisagreement;
export const _Aic_EffectsDisagreement_ok: NewAic.EffectsDisagreement = _Aic_EffectsDisagreement;
declare const _Aic_ObservationGap: OldAic.ObservationGap;
export const _Aic_ObservationGap_ok: NewAic.ObservationGap = _Aic_ObservationGap;
declare const _Aic_emitLeasedJourney: Parameters<typeof OldAic.emitLeasedJourney>;
void NewAic.emitLeasedJourney(..._Aic_emitLeasedJourney);
declare const _Aic_emitWrapperJourney: Parameters<typeof OldAic.emitWrapperJourney>;
void NewAic.emitWrapperJourney(..._Aic_emitWrapperJourney);
declare const _Aic_subjectOutcomes: Parameters<typeof OldAic.subjectOutcomes>;
void NewAic.subjectOutcomes(..._Aic_subjectOutcomes);
declare const _Aic_EmitJourneyOptions: OldAic.EmitJourneyOptions;
export const _Aic_EmitJourneyOptions_ok: NewAic.EmitJourneyOptions = _Aic_EmitJourneyOptions;
declare const _Aic_LeasedJourneyOptions: OldAic.LeasedJourneyOptions;
export const _Aic_LeasedJourneyOptions_ok: NewAic.LeasedJourneyOptions = _Aic_LeasedJourneyOptions;
declare const _Aic_NodeResource: OldAic.NodeResource;
export const _Aic_NodeResource_ok: NewAic.NodeResource = _Aic_NodeResource;
declare const _Aic_ScriptResource: OldAic.ScriptResource;
export const _Aic_ScriptResource_ok: NewAic.ScriptResource = _Aic_ScriptResource;
declare const _Aic_WrapperInvoke: OldAic.WrapperInvoke;
export const _Aic_WrapperInvoke_ok: NewAic.WrapperInvoke = _Aic_WrapperInvoke;
declare const _Aic_WrapperJourney: OldAic.WrapperJourney;
export const _Aic_WrapperJourney_ok: NewAic.WrapperJourney = _Aic_WrapperJourney;
export const _Aic_AIC_LEASE_NAMESPACE_ok: Keeps<typeof OldAic.AIC_LEASE_NAMESPACE, typeof NewAic.AIC_LEASE_NAMESPACE> = true;
declare const _Aic_createLeaseIdentity: Parameters<typeof OldAic.createLeaseIdentity>;
void NewAic.createLeaseIdentity(..._Aic_createLeaseIdentity);
declare const _Aic_normalizedLeaseOutcomes: Parameters<typeof OldAic.normalizedLeaseOutcomes>;
void NewAic.normalizedLeaseOutcomes(..._Aic_normalizedLeaseOutcomes);
declare const _Aic_sha256: Parameters<typeof OldAic.sha256>;
void NewAic.sha256(..._Aic_sha256);
declare const _Aic_uuidV5: Parameters<typeof OldAic.uuidV5>;
void NewAic.uuidV5(..._Aic_uuidV5);
declare const _Aic_LeaseIdentity: OldAic.LeaseIdentity;
export const _Aic_LeaseIdentity_ok: NewAic.LeaseIdentity = _Aic_LeaseIdentity;
declare const _Aic_LeaseIdentityOptions: OldAic.LeaseIdentityOptions;
export const _Aic_LeaseIdentityOptions_ok: NewAic.LeaseIdentityOptions = _Aic_LeaseIdentityOptions;
declare const _Aic_LeaseResourceIds: OldAic.LeaseResourceIds;
export const _Aic_LeaseResourceIds_ok: NewAic.LeaseResourceIds = _Aic_LeaseResourceIds;
declare const _Aic_emitResultScript: Parameters<typeof OldAic.emitResultScript>;
void NewAic.emitResultScript(..._Aic_emitResultScript);
declare const _Aic_emitLeasedSessionJourney: Parameters<typeof OldAic.emitLeasedSessionJourney>;
void NewAic.emitLeasedSessionJourney(..._Aic_emitLeasedSessionJourney);
declare const _Aic_instrumentSubject: Parameters<typeof OldAic.instrumentSubject>;
void NewAic.instrumentSubject(..._Aic_instrumentSubject);
declare const _Aic_InstrumentedSubject: OldAic.InstrumentedSubject;
export const _Aic_InstrumentedSubject_ok: NewAic.InstrumentedSubject = _Aic_InstrumentedSubject;
declare const _Aic_ManagedFixture: OldAic.ManagedFixture;
export const _Aic_ManagedFixture_ok: NewAic.ManagedFixture = _Aic_ManagedFixture;
declare const _Aic_AicFileLease__new: ConstructorParameters<typeof OldAic.AicFileLease>;
void new NewAic.AicFileLease(..._Aic_AicFileLease__new);
declare const _Aic_AicFileLease__inst: NewAic.AicFileLease;
declare const _Aic_AicFileLease__open: Parameters<OldAic.AicFileLease["open"]>;
void _Aic_AicFileLease__inst.open(..._Aic_AicFileLease__open);
declare const _Aic_AicFileLease__run: Parameters<OldAic.AicFileLease["run"]>;
void _Aic_AicFileLease__inst.run(..._Aic_AicFileLease__run);
declare const _Aic_AicFileLease__endTest: Parameters<OldAic.AicFileLease["endTest"]>;
void _Aic_AicFileLease__inst.endTest(..._Aic_AicFileLease__endTest);
declare const _Aic_AicFileLease__close: Parameters<OldAic.AicFileLease["close"]>;
void _Aic_AicFileLease__inst.close(..._Aic_AicFileLease__close);
declare const _Aic_AicFileLeaseOptions: OldAic.AicFileLeaseOptions;
export const _Aic_AicFileLeaseOptions_ok: NewAic.AicFileLeaseOptions = _Aic_AicFileLeaseOptions;
declare const _Aic_AicLeaseRunRequest: OldAic.AicLeaseRunRequest;
export const _Aic_AicLeaseRunRequest_ok: NewAic.AicLeaseRunRequest = _Aic_AicLeaseRunRequest;
declare const _Aic_acquireLeaseLock: Parameters<typeof OldAic.acquireLeaseLock>;
void NewAic.acquireLeaseLock(..._Aic_acquireLeaseLock);
declare const _Aic_addJournalFixture: Parameters<typeof OldAic.addJournalFixture>;
void NewAic.addJournalFixture(..._Aic_addJournalFixture);
declare const _Aic_addJournalResources: Parameters<typeof OldAic.addJournalResources>;
void NewAic.addJournalResources(..._Aic_addJournalResources);
declare const _Aic_leaseStatePaths: Parameters<typeof OldAic.leaseStatePaths>;
void NewAic.leaseStatePaths(..._Aic_leaseStatePaths);
declare const _Aic_newLeaseJournal: Parameters<typeof OldAic.newLeaseJournal>;
void NewAic.newLeaseJournal(..._Aic_newLeaseJournal);
declare const _Aic_readLeaseJournal: Parameters<typeof OldAic.readLeaseJournal>;
void NewAic.readLeaseJournal(..._Aic_readLeaseJournal);
declare const _Aic_removeJournalFixture: Parameters<typeof OldAic.removeJournalFixture>;
void NewAic.removeJournalFixture(..._Aic_removeJournalFixture);
declare const _Aic_removeLeaseJournal: Parameters<typeof OldAic.removeLeaseJournal>;
void NewAic.removeLeaseJournal(..._Aic_removeLeaseJournal);
declare const _Aic_writeLeaseJournal: Parameters<typeof OldAic.writeLeaseJournal>;
void NewAic.writeLeaseJournal(..._Aic_writeLeaseJournal);
declare const _Aic_LeaseJournal: OldAic.LeaseJournal;
export const _Aic_LeaseJournal_ok: NewAic.LeaseJournal = _Aic_LeaseJournal;
declare const _Aic_LeaseLock: OldAic.LeaseLock;
export const _Aic_LeaseLock_ok: NewAic.LeaseLock = _Aic_LeaseLock;
declare const _Aic_LeaseStatePaths: OldAic.LeaseStatePaths;
export const _Aic_LeaseStatePaths_ok: NewAic.LeaseStatePaths = _Aic_LeaseStatePaths;
declare const _Aic_confirmResourceSnapshot: Parameters<typeof OldAic.confirmResourceSnapshot>;
void NewAic.confirmResourceSnapshot(..._Aic_confirmResourceSnapshot);
declare const _Aic_nodeRequestProjection: Parameters<typeof OldAic.nodeRequestProjection>;
void NewAic.nodeRequestProjection(..._Aic_nodeRequestProjection);
declare const _Aic_resourceRequestProjection: Parameters<typeof OldAic.resourceRequestProjection>;
void NewAic.resourceRequestProjection(..._Aic_resourceRequestProjection);
declare const _Aic_AicResourceKind: OldAic.AicResourceKind;
export const _Aic_AicResourceKind_ok: NewAic.AicResourceKind = _Aic_AicResourceKind;
declare const _Aic_assembleEffects: Parameters<typeof OldAic.assembleEffects>;
void NewAic.assembleEffects(..._Aic_assembleEffects);
declare const _Aic_classifyFinal: Parameters<typeof OldAic.classifyFinal>;
void NewAic.classifyFinal(..._Aic_classifyFinal);
declare const _Aic_parseSubjectDump: Parameters<typeof OldAic.parseSubjectDump>;
void NewAic.parseSubjectDump(..._Aic_parseSubjectDump);
declare const _Aic_SubjectDump: OldAic.SubjectDump;
export const _Aic_SubjectDump_ok: NewAic.SubjectDump = _Aic_SubjectDump;
declare const _Aic_runAicChain: Parameters<typeof OldAic.runAicChain>;
void NewAic.runAicChain(..._Aic_runAicChain);
declare const _Aic_runAicLane: Parameters<typeof OldAic.runAicLane>;
void NewAic.runAicLane(..._Aic_runAicLane);
declare const _Aic_validateAicRun: Parameters<typeof OldAic.validateAicRun>;
void NewAic.validateAicRun(..._Aic_validateAicRun);
declare const _Aic_AicReply: OldAic.AicReply;
export const _Aic_AicReply_ok: NewAic.AicReply = _Aic_AicReply;
declare const _Aic_AicRunValidation: OldAic.AicRunValidation;
export const _Aic_AicRunValidation_ok: NewAic.AicRunValidation = _Aic_AicRunValidation;
declare const _Aic_RunAicOptions: OldAic.RunAicOptions;
export const _Aic_RunAicOptions_ok: NewAic.RunAicOptions = _Aic_RunAicOptions;
declare const _Aic_AicLaneError__new: ConstructorParameters<typeof OldAic.AicLaneError>;
void new NewAic.AicLaneError(..._Aic_AicLaneError__new);
declare const _Aic_AicLaneError__inst: NewAic.AicLaneError;
export const _Aic_AM_CONFIG_API_VERSION_ok: Keeps<typeof OldAic.AM_CONFIG_API_VERSION, typeof NewAic.AM_CONFIG_API_VERSION> = true;
declare const _Aic_amConfigHeaders: Parameters<typeof OldAic.amConfigHeaders>;
void NewAic.amConfigHeaders(..._Aic_amConfigHeaders);
declare const _Aic_aicCliProvider: Parameters<typeof OldAic.aicCliProvider>;
void NewAic.aicCliProvider(..._Aic_aicCliProvider);
declare const _Aic_connectTenant: Parameters<typeof OldAic.connectTenant>;
void NewAic.connectTenant(..._Aic_connectTenant);
declare const _Aic_defaultAicIo: Parameters<typeof OldAic.defaultAicIo>;
void NewAic.defaultAicIo(..._Aic_defaultAicIo);
declare const _Aic_resolveTenantProvider: Parameters<typeof OldAic.resolveTenantProvider>;
void NewAic.resolveTenantProvider(..._Aic_resolveTenantProvider);
declare const _Aic_AicIo: OldAic.AicIo;
export const _Aic_AicIo_ok: NewAic.AicIo = _Aic_AicIo;
declare const _Aic_ConnectOptions: OldAic.ConnectOptions;
export const _Aic_ConnectOptions_ok: NewAic.ConnectOptions = _Aic_ConnectOptions;
declare const _Aic_TenantSession: OldAic.TenantSession;
export const _Aic_TenantSession_ok: NewAic.TenantSession = _Aic_TenantSession;
declare const _Aic_checkTenantDescription: Parameters<typeof OldAic.checkTenantDescription>;
void NewAic.checkTenantDescription(..._Aic_checkTenantDescription);
declare const _Aic_configuredTenantProvider: Parameters<typeof OldAic.configuredTenantProvider>;
void NewAic.configuredTenantProvider(..._Aic_configuredTenantProvider);
export const _Aic_DEFAULT_SERVICE_ACCOUNT_SCOPE_ok: Keeps<typeof OldAic.DEFAULT_SERVICE_ACCOUNT_SCOPE, typeof NewAic.DEFAULT_SERVICE_ACCOUNT_SCOPE> = true;
declare const _Aic_logKeysReader: Parameters<typeof OldAic.logKeysReader>;
void NewAic.logKeysReader(..._Aic_logKeysReader);
declare const _Aic_providerFromEnv: Parameters<typeof OldAic.providerFromEnv>;
void NewAic.providerFromEnv(..._Aic_providerFromEnv);
declare const _Aic_serviceAccountProvider: Parameters<typeof OldAic.serviceAccountProvider>;
void NewAic.serviceAccountProvider(..._Aic_serviceAccountProvider);
declare const _Aic_setTenantProvider: Parameters<typeof OldAic.setTenantProvider>;
void NewAic.setTenantProvider(..._Aic_setTenantProvider);
export const _Aic_TENANT_ENV_ok: Keeps<typeof OldAic.TENANT_ENV, typeof NewAic.TENANT_ENV> = true;
declare const _Aic_tokenCallbackProvider: Parameters<typeof OldAic.tokenCallbackProvider>;
void NewAic.tokenCallbackProvider(..._Aic_tokenCallbackProvider);
declare const _Aic_TenantProviderError__new: ConstructorParameters<typeof OldAic.TenantProviderError>;
void new NewAic.TenantProviderError(..._Aic_TenantProviderError__new);
declare const _Aic_TenantProviderError__inst: NewAic.TenantProviderError;
declare const _Aic_HttpSend: OldAic.HttpSend;
export const _Aic_HttpSend_ok: NewAic.HttpSend = _Aic_HttpSend;
declare const _Aic_LogKeys: OldAic.LogKeys;
export const _Aic_LogKeys_ok: NewAic.LogKeys = _Aic_LogKeys;
declare const _Aic_LogReader: OldAic.LogReader;
export const _Aic_LogReader_ok: NewAic.LogReader = _Aic_LogReader;
declare const _Aic_ServiceAccountOptions: OldAic.ServiceAccountOptions;
export const _Aic_ServiceAccountOptions_ok: NewAic.ServiceAccountOptions = _Aic_ServiceAccountOptions;
declare const _Aic_TenantDescription: OldAic.TenantDescription;
export const _Aic_TenantDescription_ok: NewAic.TenantDescription = _Aic_TenantDescription;
declare const _Aic_TenantProvider: OldAic.TenantProvider;
export const _Aic_TenantProvider_ok: NewAic.TenantProvider = _Aic_TenantProvider;
declare const _Aic_TokenCallbackOptions: OldAic.TokenCallbackOptions;
export const _Aic_TokenCallbackOptions_ok: NewAic.TokenCallbackOptions = _Aic_TokenCallbackOptions;
declare const _Aic_TokenRequest: OldAic.TokenRequest;
export const _Aic_TokenRequest_ok: NewAic.TokenRequest = _Aic_TokenRequest;
declare const _Aic_aicUnsupportedReason: Parameters<typeof OldAic.aicUnsupportedReason>;
void NewAic.aicUnsupportedReason(..._Aic_aicUnsupportedReason);

// src/bindings/index
declare const _Bindings_parseHarvest: Parameters<typeof OldBindings.parseHarvest>;
void NewBindings.parseHarvest(..._Bindings_parseHarvest);
declare const _Bindings_mockPreamble: Parameters<typeof OldBindings.mockPreamble>;
void NewBindings.mockPreamble(..._Bindings_mockPreamble);
declare const _Bindings_withHarvest: Parameters<typeof OldBindings.withHarvest>;
void NewBindings.withHarvest(..._Bindings_withHarvest);
declare const _Bindings_runCase: Parameters<typeof OldBindings.runCase>;
void NewBindings.runCase(..._Bindings_runCase);
declare const _Bindings_CaseRun: NewBindings.CaseRun;
export const _Bindings_CaseRun_ok: OldBindings.CaseRun = _Bindings_CaseRun;
declare const _Bindings_RunCaseOptions: OldBindings.RunCaseOptions;
export const _Bindings_RunCaseOptions_ok: NewBindings.RunCaseOptions = _Bindings_RunCaseOptions;

// src/runner
declare const _Runner_RhinoRunnerExitError__new: ConstructorParameters<typeof OldRunner.RhinoRunnerExitError>;
void new NewRunner.RhinoRunnerExitError(..._Runner_RhinoRunnerExitError__new);
declare const _Runner_RhinoRunnerExitError__inst: NewRunner.RhinoRunnerExitError;
declare const _Runner_LaneDivergenceError__new: ConstructorParameters<typeof OldRunner.LaneDivergenceError>;
void new NewRunner.LaneDivergenceError(..._Runner_LaneDivergenceError__new);
declare const _Runner_LaneDivergenceError__inst: NewRunner.LaneDivergenceError;
declare const _Runner_SpawnRunnerOptions: OldRunner.SpawnRunnerOptions;
export const _Runner_SpawnRunnerOptions_ok: NewRunner.SpawnRunnerOptions = _Runner_SpawnRunnerOptions;
declare const _Runner_RhinoRunner__inst: NewRunner.RhinoRunner;
declare const _Runner_RhinoRunner__eval: Parameters<OldRunner.RhinoRunner["eval"]>;
void _Runner_RhinoRunner__inst.eval(..._Runner_RhinoRunner__eval);
declare const _Runner_RhinoRunner__close: Parameters<OldRunner.RhinoRunner["close"]>;
void _Runner_RhinoRunner__inst.close(..._Runner_RhinoRunner__close);
declare const _Runner_RhinoRunner__kill: Parameters<OldRunner.RhinoRunner["kill"]>;
void _Runner_RhinoRunner__inst.kill(..._Runner_RhinoRunner__kill);
declare const _Runner_RhinoRunner__s_spawn: Parameters<typeof OldRunner.RhinoRunner["spawn"]>;
void NewRunner.RhinoRunner.spawn(..._Runner_RhinoRunner__s_spawn);

// src/profile/index
export const _Profile_MANAGED_CONFIG_ENDPOINT_ok: Keeps<typeof OldProfile.MANAGED_CONFIG_ENDPOINT, typeof NewProfile.MANAGED_CONFIG_ENDPOINT> = true;
declare const _Profile_pullProfile: Parameters<typeof OldProfile.pullProfile>;
void NewProfile.pullProfile(..._Profile_pullProfile);
declare const _Profile_PullOptions: OldProfile.PullOptions;
export const _Profile_PullOptions_ok: NewProfile.PullOptions = _Profile_PullOptions;
declare const _Profile_parseProfile: Parameters<typeof OldProfile.parseProfile>;
void NewProfile.parseProfile(..._Profile_parseProfile);
declare const _Profile_profilePath: Parameters<typeof OldProfile.profilePath>;
void NewProfile.profilePath(..._Profile_profilePath);
declare const _Profile_readProfile: Parameters<typeof OldProfile.readProfile>;
void NewProfile.readProfile(..._Profile_readProfile);
declare const _Profile_tryReadProfile: Parameters<typeof OldProfile.tryReadProfile>;
void NewProfile.tryReadProfile(..._Profile_tryReadProfile);
declare const _Profile_writeProfile: Parameters<typeof OldProfile.writeProfile>;
void NewProfile.writeProfile(..._Profile_writeProfile);
declare const _Profile_ProfileShapeError__new: ConstructorParameters<typeof OldProfile.ProfileShapeError>;
void new NewProfile.ProfileShapeError(..._Profile_ProfileShapeError__new);
declare const _Profile_ProfileShapeError__inst: NewProfile.ProfileShapeError;
declare const _Profile_EnvProfile: OldProfile.EnvProfile;
export const _Profile_EnvProfile_ok: NewProfile.EnvProfile = _Profile_EnvProfile;
declare const _Profile_ObjectSchema: OldProfile.ObjectSchema;
export const _Profile_ObjectSchema_ok: NewProfile.ObjectSchema = _Profile_ObjectSchema;
declare const _Profile_PropertySchema: OldProfile.PropertySchema;
export const _Profile_PropertySchema_ok: NewProfile.PropertySchema = _Profile_PropertySchema;

// src/diagnostics
declare const _Diagnostics_readFailures: Parameters<typeof OldDiagnostics.readFailures>;
void NewDiagnostics.readFailures(..._Diagnostics_readFailures);
declare const _Diagnostics_sortNewestFirst: Parameters<typeof OldDiagnostics.sortNewestFirst>;
void NewDiagnostics.sortNewestFirst(..._Diagnostics_sortNewestFirst);
declare const _Diagnostics_FailureRecord: OldDiagnostics.FailureRecord;
export const _Diagnostics_FailureRecord_ok: NewDiagnostics.FailureRecord = _Diagnostics_FailureRecord;
declare const _Diagnostics_createDefaultIo: Parameters<typeof OldDiagnostics.createDefaultIo>;
void NewDiagnostics.createDefaultIo(..._Diagnostics_createDefaultIo);
declare const _Diagnostics_runShowLog: Parameters<typeof OldDiagnostics.runShowLog>;
void NewDiagnostics.runShowLog(..._Diagnostics_runShowLog);
declare const _Diagnostics_ShowLogIo: OldDiagnostics.ShowLogIo;
export const _Diagnostics_ShowLogIo_ok: NewDiagnostics.ShowLogIo = _Diagnostics_ShowLogIo;
declare const _Diagnostics_ShowLogOptions: OldDiagnostics.ShowLogOptions;
export const _Diagnostics_ShowLogOptions_ok: NewDiagnostics.ShowLogOptions = _Diagnostics_ShowLogOptions;
declare const _Diagnostics_loadProviderModule: Parameters<typeof OldDiagnostics.loadProviderModule>;
void NewDiagnostics.loadProviderModule(..._Diagnostics_loadProviderModule);
declare const _Diagnostics_projectRoot: Parameters<typeof OldDiagnostics.projectRoot>;
void NewDiagnostics.projectRoot(..._Diagnostics_projectRoot);
declare const _Diagnostics_stateDir: Parameters<typeof OldDiagnostics.stateDir>;
void NewDiagnostics.stateDir(..._Diagnostics_stateDir);
export const _Diagnostics_PROJECT_ENV_ok: Keeps<typeof OldDiagnostics.PROJECT_ENV, typeof NewDiagnostics.PROJECT_ENV> = true;
export const _Diagnostics_STATE_DIR_ENV_ok: Keeps<typeof OldDiagnostics.STATE_DIR_ENV, typeof NewDiagnostics.STATE_DIR_ENV> = true;
