// The two-step build: type-check -> esbuild bundle -> Babel downlevel -> emit.
//
// WHY TWO TOOLS. esbuild cannot target ES5 at all ("Transforming const to the
// configured target environment (es5) is not supported yet", probed
// 2026-08-13), and Babel has no bundler. So esbuild resolves the module graph
// into one IIFE at ES2020, and Babel downlevels that single file to ES5 with
// `@babel/preset-env`. Babel 8 removed `loose`, so the size/shape savings come
// from `assumptions` instead.
//
// NOTHING IS EMITTED UNLESS EVERY STEP SUCCEEDS FOR EVERY ENDPOINT. A broken
// build must not leave a half-updated `.cjs` for `aic script watch` to push.
//
// Managed file — regenerated by `aic workspace update`.

import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import * as babel from "@babel/core";
import * as esbuild from "esbuild";

import { findRuntimeBanViolations } from "./idm-runtime-bans.mjs";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(projectRoot, "..");
const endpointsDir = join(projectRoot, "src", "endpoints");
const outputDir = join(workspaceRoot, "idm", "endpoint");
const openapiDir = join(projectRoot, "openapi");
const distDir = join(projectRoot, "dist");
const manifestPath = join(projectRoot, ".aic-ts-manifest.json");

/** The IIFE binding the emitted file's final expression statement calls. */
const GLOBAL_NAME = "__aicMain";

const argv = process.argv.slice(2);
const watchMode = argv.includes("--watch");
const skipTypeCheck = argv.includes("--no-type-check");
let atomicSequence = 0;

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

function typeCheck() {
  const tsc = join(projectRoot, "node_modules", ".bin", "tsc");
  if (!existsSync(tsc)) {
    throw new Error("typescript is not installed — run `npm install` here");
  }
  for (const config of ["tsconfig.json", "tsconfig.tests.json"]) {
    const result = spawnSync(
      tsc,
      ["--noEmit", "-p", join(projectRoot, config)],
      {
        stdio: "inherit",
        cwd: projectRoot,
      }
    );
    if (result.status !== 0) {
      throw new Error("type-check failed (" + config + ")");
    }
  }
}

function entryPoints() {
  if (!existsSync(endpointsDir)) {
    return [];
  }
  return readdirSync(endpointsDir)
    .filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts"))
    .sort()
    .map((name) => join(endpointsDir, name));
}

async function bundle(entry, format, globalName) {
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    format,
    ...(globalName === undefined ? {} : { globalName }),
    // ES5 is Babel's job — esbuild refuses to transform `const` to ES5.
    target: "es2020",
    platform: "neutral",
    charset: "utf8",
    legalComments: "none",
    logLevel: "silent",
  });
  return result.outputFiles[0].text;
}

/**
 * Read the endpoint's declaration by importing it. Bundling to ESM first means
 * the tool never has to care how the source is split up or whether node can
 * strip its types.
 */
async function readDefinition(entry, name) {
  const esm = await bundle(entry, "esm", undefined);
  mkdirSync(join(distDir, "meta"), { recursive: true });
  const metaPath = join(distDir, "meta", name + ".mjs");
  writeFileSync(metaPath, esm, "utf8");
  const module = await import(
    pathToFileURL(metaPath).href + "?t=" + Date.now()
  );
  const main = module.default;
  if (typeof main !== "function" || typeof main.definition !== "object") {
    throw new Error(
      relative(projectRoot, entry) +
        ": default export must be the value returned by defineEndpoint()"
    );
  }
  return main.definition;
}

function downlevel(code, name) {
  const result = babel.transformSync(code, {
    filename: name + ".bundle.js",
    babelrc: false,
    configFile: false,
    sourceType: "script",
    compact: false,
    comments: false,
    assumptions: {
      constantSuper: true,
      noClassCalls: true,
      setClassMethods: true,
      superIsCallableConstructor: true,
      noDocumentAll: true,
    },
    presets: [
      [
        "@babel/preset-env",
        {
          targets: { ie: "11" },
          modules: false,
          // Rhino has Map/Set/Symbol/Promise natively; a core-js polyfill would
          // be dead weight and cannot be installed on IDM anyway.
          useBuiltIns: false,
        },
      ],
    ],
  });
  if (result === null || typeof result.code !== "string") {
    throw new Error(name + ": Babel produced no output");
  }
  return result.code;
}

function banner(name, sourceRelative) {
  return [
    "// @generated by `npm run build` in workspace/<tenant>/typescript — DO NOT EDIT.",
    "// @ts-nocheck",
    "//",
    "// Source:  " + sourceRelative,
    "// Rebuild: (cd ../../typescript && npm run build)",
    "//",
    "// Bundled with esbuild (es2020) then downlevelled to ES5 by Babel. Edit the",
    "// TypeScript, never this file: the next build overwrites it.",
    "",
  ].join("\n");
}

function footer() {
  // The endpoint's HTTP response body is the script's COMPLETION VALUE, so the
  // file must end with an expression statement (verified 2026-08-13).
  return "\n" + GLOBAL_NAME + ".default();\n";
}

async function buildEndpoint(entry) {
  const fileName = basename(entry, ".ts");
  const definition = await readDefinition(entry, fileName);
  if (definition.name !== fileName) {
    throw new Error(
      relative(projectRoot, entry) +
        ': endpoint name "' +
        definition.name +
        '" must match the file name "' +
        fileName +
        '" — the file name is what `aic script watch` pushes'
    );
  }
  const iife = await bundle(entry, "iife", GLOBAL_NAME);
  const code = downlevel(iife, fileName);
  const violations = findRuntimeBanViolations(code);
  if (violations.length > 0) {
    const lines = violations.map(
      (violation) =>
        "  line " +
        violation.line +
        " [" +
        violation.rule +
        "] " +
        violation.message
    );
    throw new Error(
      fileName +
        ": generated bundle breaks IDM runtime rules\n" +
        lines.join("\n")
    );
  }
  const sourceRelative = "typescript/" + relative(projectRoot, entry);
  return {
    name: definition.name,
    entry,
    sourceRelative,
    definition,
    code: banner(definition.name, sourceRelative) + code + footer(),
  };
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

/** Publish a complete file in one rename so watchers never see partial data. */
function atomicWrite(path, content) {
  const temporary = join(
    dirname(path),
    "." + basename(path) + "." + process.pid + "." + atomicSequence++ + ".tmp"
  );
  try {
    writeFileSync(temporary, content, "utf8");
    renameSync(temporary, path);
  } finally {
    rmSync(temporary, { force: true });
  }
}

function writeManifest(built) {
  const manifest = {
    version: 1,
    // Consumed by `aic script watch`: an endpoint listed here that has no sync
    // snapshot yet is CREATED on the tenant rather than skipped as untracked.
    endpoints: built.map((endpoint) => ({
      name: endpoint.name,
      file: "idm/endpoint/" + endpoint.name + ".cjs",
      source: endpoint.sourceRelative,
      routes: endpoint.definition.routes.map((route) => ({
        method: route.method,
        path: route.path,
        ...(route.action === undefined ? {} : { action: route.action }),
      })),
    })),
  };
  atomicWrite(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
}

function previouslyOwnedEndpointNames() {
  if (!existsSync(manifestPath)) {
    return [];
  }
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    if (!Array.isArray(manifest.endpoints)) {
      return [];
    }
    return manifest.endpoints
      .map((endpoint) => endpoint?.name)
      .filter(
        (name) =>
          typeof name === "string" &&
          name !== "." &&
          name !== ".." &&
          /^[A-Za-z0-9._-]+$/.test(name)
      );
  } catch {
    // A malformed generated manifest must not authorize deleting arbitrary
    // workspace files. The new manifest will repair it on this build.
    return [];
  }
}

function retireRemovedEndpoints(previousNames, built) {
  const current = new Set(built.map((endpoint) => endpoint.name));
  for (const name of previousNames) {
    if (!current.has(name)) {
      rmSync(join(outputDir, name + ".cjs"), { force: true });
      rmSync(join(openapiDir, name + ".openapi.json"), { force: true });
    }
  }
}

const PRETTIER_MARKER = "# --- generated by the TypeScript endpoint build ---";

/**
 * Keep the emitted bundles out of the workspace's prettier run. Everything
 * above the marker is the user's; everything below is rewritten each build.
 */
function prettierIgnoreContent(built) {
  const path = join(workspaceRoot, ".prettierignore");
  let head = "";
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    const index = existing.indexOf(PRETTIER_MARKER);
    head = index < 0 ? existing.trimEnd() + "\n" : existing.slice(0, index);
  }
  const generated = [
    PRETTIER_MARKER,
    "typescript/dist/",
    "typescript/node_modules/",
    "typescript/openapi/",
    ...built.map((endpoint) => "idm/endpoint/" + endpoint.name + ".cjs"),
    "",
  ].join("\n");
  return { path, content: head + generated };
}

function openApiOutputs(built, toOpenApi) {
  return built.map((endpoint) => {
    const document = toOpenApi(endpoint.definition, {
      title: endpoint.definition.summary ?? endpoint.name,
    });
    return {
      path: join(openapiDir, endpoint.name + ".openapi.json"),
      content: JSON.stringify(document, null, 2) + "\n",
    };
  });
}

async function run() {
  const entries = entryPoints();
  const previousNames = previouslyOwnedEndpointNames();
  // AN ABSENT `src/endpoints` IS NOT AN EMPTY ONE. Retirement deletes every
  // bundle the previous manifest owned, so it must be driven by a project that
  // says "no endpoints", not by a directory that happens not to be there right
  // now — a branch switch, an interrupted move, or a watch tick mid-rename would
  // otherwise wipe the lot and empty the manifest, silently and with exit 0.
  if (!skipTypeCheck) {
    typeCheck();
  }
  if (!existsSync(endpointsDir)) {
    console.log(
      "src/endpoints does not exist — kept the previous manifest and bundles; " +
        "create the directory (even empty) to retire them"
    );
    return;
  }

  // Build everything into memory first: a failure in the last endpoint must
  // not leave the earlier ones half-written on disk.
  const built = [];
  for (const entry of entries) {
    built.push(await buildEndpoint(entry));
  }

  const toOpenApi = await loadOpenApiGenerator();

  // Prepare every fallible transformation before publishing any watched
  // output. Publication itself is a sequence of same-directory atomic renames;
  // the manifest is the final commit marker for the generation.
  const openApi = openApiOutputs(built, toOpenApi);
  const prettierIgnore = prettierIgnoreContent(built);

  mkdirSync(outputDir, { recursive: true });
  mkdirSync(openapiDir, { recursive: true });
  for (const endpoint of built) {
    atomicWrite(join(outputDir, endpoint.name + ".cjs"), endpoint.code);
  }
  for (const output of openApi) {
    atomicWrite(output.path, output.content);
  }
  atomicWrite(prettierIgnore.path, prettierIgnore.content);
  retireRemovedEndpoints(previousNames, built);
  writeManifest(built);

  if (built.length === 0) {
    console.log("no endpoints in src/endpoints — retired generated endpoints");
  }

  for (const endpoint of built) {
    const bytes = Buffer.byteLength(endpoint.code, "utf8");
    console.log(
      "built " +
        endpoint.name +
        " (" +
        endpoint.definition.routes.length +
        " routes, " +
        Math.round(bytes / 1024) +
        " KB) -> idm/endpoint/" +
        endpoint.name +
        ".cjs"
    );
  }
}

/** Bundle the framework's OpenAPI generator so this tool can call it. */
async function loadOpenApiGenerator() {
  const source = join(projectRoot, "framework", "openapi.ts");
  const esm = await bundle(source, "esm", undefined);
  mkdirSync(join(distDir, "meta"), { recursive: true });
  const path = join(distDir, "meta", "__openapi.mjs");
  writeFileSync(path, esm, "utf8");
  const module = await import(pathToFileURL(path).href + "?t=" + Date.now());
  return module.toOpenApi;
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

async function once() {
  try {
    await run();
    return true;
  } catch (error) {
    console.error(
      "build failed: " + (error instanceof Error ? error.message : error)
    );
    return false;
  }
}

if (watchMode) {
  const { watch } = await import("node:fs");
  let pending = null;
  let building = false;
  let rerun = false;
  const buildLatest = async () => {
    if (building) {
      rerun = true;
      return;
    }
    building = true;
    try {
      do {
        rerun = false;
        await once();
      } while (rerun);
    } finally {
      building = false;
    }
  };
  const trigger = () => {
    if (pending !== null) {
      clearTimeout(pending);
    }
    pending = setTimeout(() => {
      pending = null;
      void buildLatest();
    }, 250);
  };
  await buildLatest();
  for (const dir of ["src", "framework"]) {
    const target = join(projectRoot, dir);
    if (existsSync(target)) {
      watch(target, { recursive: true }, trigger);
    }
  }
  console.log("watching src/ and framework/ — Ctrl-C to stop");
} else {
  rmSync(join(distDir, "meta"), { recursive: true, force: true });
  const ok = await once();
  process.exit(ok ? 0 : 1);
}
