import { randomUUID } from "node:crypto";
import {
  AM_OWNED_SESSION_SET,
  DEFAULT_SESSION_PRINCIPAL,
} from "../case/session.ts";
import { RESOURCE_PREFIX, SUCCESS_NODE_ID } from "./constants.ts";
import type { NodeResource, ScriptResource, WrapperJourney } from "./emit-journey.ts";
import type { LeaseIdentity } from "./lease-identity.ts";
import { jsStringLiteral } from "./js.ts";

/**
 * A journey whose only job is to end, so that AM issues a session.
 *
 * There is no other way: a session exists only once a journey has run to
 * completion (`docs/api/09-journeys.md` → "Minting a session for a test").
 * Measured 2026-09-14 — the tree needs no Identify Existing User node, the
 * principal need not exist as a managed object, and the journey that later
 * *consumes* the session needs no configuration at all.
 *
 * AM-owned properties are dropped rather than sent. `putSessionProperty` does
 * not override them; the whole login fails with a bare `401 Unauthorized`
 * naming nothing, so sending one would turn a harness bug into an unexplained
 * authentication failure. The five AM derives from the principal arrive by
 * authenticating AS that principal instead.
 */
export function emitSessionJourney(
  session: Record<string, string>,
  options: { runId: string; realm: string }
): WrapperJourney {
  const principal = session.UserId ?? DEFAULT_SESSION_PRINCIPAL;
  const custom = Object.entries(session).filter(
    ([key]) => !AM_OWNED_SESSION_SET.has(key)
  );
  const treeName = `${RESOURCE_PREFIX}-${options.runId}-session`;
  const lines = [
    "// Generated by rhino-local AIC lane: mints a session for the subject",
    "// journey, which cannot seed `existingSession` any other way.",
    `nodeState.putShared("username", ${jsStringLiteral(principal)});`,
    'action.goTo("true")',
  ];
  for (const [key, value] of custom) {
    lines.push(
      `  .putSessionProperty(${jsStringLiteral(key)}, ${jsStringLiteral(value)})`
    );
  }
  lines.push(";", "");

  const script: ScriptResource = {
    id: randomUUID(),
    name: `${treeName}-mint`,
    source: lines.join("\n"),
    role: "subject",
  };
  const node: NodeResource = {
    id: randomUUID(),
    displayName: "mint session",
    scriptId: script.id,
    outcomes: ["true"],
    connections: { true: SUCCESS_NODE_ID },
    x: 80,
    y: 100,
  };
  return {
    treeName,
    realm: options.realm,
    identityResource: `managed/${options.realm}_user`,
    scripts: [script],
    nodes: [node],
    treeBody: {
      identityResource: `managed/${options.realm}_user`,
      entryNodeId: node.id,
      innerTreeOnly: false,
      description: "rhino-local AIC lane throwaway. Safe to delete.",
      noSession: false,
      mustRun: false,
      enabled: true,
      transactionalOnly: false,
      uiConfig: { categories: '["Test"]' },
      nodes: {
        [node.id]: {
          connections: node.connections,
          displayName: node.displayName,
          nodeType: "ScriptedDecisionNode",
          version: "1.0",
          x: node.x,
          y: node.y,
        },
      },
    },
    nodeBodies: {
      [node.id]: {
        _id: node.id,
        _type: {
          _id: "ScriptedDecisionNode",
          collection: true,
          name: "Scripted Decision",
        },
        _outcomes: [{ id: "true", displayName: "true" }],
        inputs: ["*"],
        outputs: ["*"],
        outcomes: ["true"],
        script: script.id,
      },
    },
    subjectOutcomes: ["true"],
    invoke: { headers: {}, parameters: {}, cookies: {} },
  };
}

/** Deterministic session-minter resources owned by a file lease. */
export function emitLeasedSessionJourney(
  session: Record<string, string>,
  options: { identity: LeaseIdentity; realm: string }
): WrapperJourney {
  const emitted = emitSessionJourney(session, {
    runId: options.identity.idHash,
    realm: options.realm,
  });
  const script = emitted.scripts[0] as ScriptResource;
  const node = emitted.nodes[0] as NodeResource;
  script.id = options.identity.ids.sessionScript;
  script.name = `${options.identity.ids.sessionTree}-mint`;
  script.source = `// ${options.identity.marker}\n${script.source}`;
  node.id = options.identity.ids.sessionNode;
  node.scriptId = script.id;
  emitted.treeName = options.identity.ids.sessionTree;
  emitted.treeBody = {
    ...emitted.treeBody,
    entryNodeId: node.id,
    description: options.identity.marker,
    nodes: {
      [node.id]: {
        connections: node.connections,
        displayName: node.displayName,
        nodeType: "ScriptedDecisionNode",
        x: node.x,
        y: node.y,
      },
    },
  };
  emitted.nodeBodies = {
    [node.id]: {
      inputs: ["*"],
      outputs: ["*"],
      outcomes: node.outcomes,
      script: script.id,
    },
  };
  return emitted;
}
