import type { Given, JsonObject } from "../case/types.ts";
import { jsonParseCall } from "./js.ts";

const HEADER = `\
// Generated by rhino-local AIC lane from case.given. Safe to delete.
// Seeds nodeState only. Request headers/parameters/cookies are sent on the
// authenticate HTTP request — a setup script cannot assign those bindings.
`;

const HELPERS = `\
function __rhinoLocalSeed(map, put) {
  var keys = Object.keys(map);
  var i;
  var key;
  for (i = 0; i < keys.length; i += 1) {
    key = keys[i];
    put(key, map[key]);
  }
}
`;

/**
 * Next-gen scripted-decision source that writes `given.sharedState` /
 * `given.transientState` into `nodeState` and `goTo("true")`.
 *
 * Request headers, parameters and cookies are NOT seeded here: they arrive
 * on the `/authenticate` call. See `WrapperJourney.invoke`.
 */
export function emitSetupScript(given: Given): string {
  const shared = given.sharedState ?? {};
  const transient = given.transientState ?? {};
  const lines = [
    HEADER,
    HELPERS,
    `var __shared = ${jsonParseCall(shared)};`,
    `var __transient = ${jsonParseCall(transient)};`,
    `__rhinoLocalSeed(__shared, function (key, value) {`,
    `  nodeState.putShared(key, value);`,
    `});`,
    `__rhinoLocalSeed(__transient, function (key, value) {`,
    `  nodeState.putTransient(key, value);`,
    `});`,
    `action.goTo("true");`,
    ``,
  ];
  return lines.join("\n");
}

/** JSON objects the setup script will put, for tests and invoke classification. */
export function seededState(given: Given): {
  shared: JsonObject;
  transient: JsonObject;
} {
  return {
    shared: given.sharedState ?? {},
    transient: given.transientState ?? {},
  };
}
