import type { Given, JsonObject } from "../case/types.ts";
import { jsonParseCall, jsStringLiteral } from "./js.ts";

const BINDING_PREFIX = "__rhinoLocalHarness_";
const SNAPSHOT_KEY_PREFIX = "__rhino_local_snapshot_";

const HELPERS = `\
function keys(ns) {
  var raw = ns.keys();
  var out = [];
  var i;
  var it;
  var k;
  if (raw === null || raw === undefined) {
    return out;
  }
  if (typeof raw.length === "number" && typeof raw !== "string") {
    for (i = 0; i < raw.length; i += 1) {
      out.push(String(raw[i]));
    }
    return out;
  }
  if (typeof raw.toArray === "function") {
    raw = raw.toArray();
    for (i = 0; i < raw.length; i += 1) {
      out.push(String(raw[i]));
    }
    return out;
  }
  if (typeof raw.iterator === "function") {
    it = raw.iterator();
    while (it.hasNext()) {
      out.push(String(it.next()));
    }
    return out;
  }
  if (typeof raw.size === "function" && typeof raw.get === "function" && typeof raw.keySet !== "function") {
    for (i = 0; i < raw.size(); i += 1) {
      out.push(String(raw.get(i)));
    }
    return out;
  }
  for (k in raw) {
    if (Object.prototype.hasOwnProperty.call(raw, k) && typeof raw[k] !== "function") {
      out.push(String(raw[k]));
    }
  }
  return out;
}

function valueToJson(value) {
  var t;
  var i;
  var k;
  var out;
  var mapKeys;
  var arr;
  if (value === null || value === undefined) {
    return null;
  }
  t = typeof value;
  if (t === "string" || t === "number" || t === "boolean") {
    return value;
  }
  if (typeof Array.isArray === "function" && Array.isArray(value)) {
    out = [];
    for (i = 0; i < value.length; i += 1) {
      out.push(valueToJson(value[i]));
    }
    return out;
  }
  if (typeof value.keySet === "function" && typeof value.get === "function") {
    out = {};
    mapKeys = value.keySet();
    if (typeof mapKeys.toArray === "function") {
      arr = mapKeys.toArray();
      for (i = 0; i < arr.length; i += 1) {
        out[String(arr[i])] = valueToJson(value.get(arr[i]));
      }
      return out;
    }
  }
  if (typeof value.size === "function" && typeof value.get === "function") {
    out = [];
    for (i = 0; i < value.size(); i += 1) {
      out.push(valueToJson(value.get(i)));
    }
    return out;
  }
  if (t === "object") {
    out = {};
    for (k in value) {
      if (Object.prototype.hasOwnProperty.call(value, k) && typeof value[k] !== "function") {
        out[String(k)] = valueToJson(value[k]);
      }
    }
    return out;
  }
  return String(value);
}

function seed(map, put) {
  var names = Object.keys(map);
  var i;
  for (i = 0; i < names.length; i += 1) {
    put(names[i], map[names[i]]);
  }
}

function snapshot(ns) {
  var names = keys(ns);
  var out = {};
  var i;
  var key;
  for (i = 0; i < names.length; i += 1) {
    key = names[i];
    out[key] = valueToJson(ns.get(key));
  }
  return out;
}
`;

export interface InstrumentedSubject {
  source: string;
  bindingName: string;
  snapshotKey: string;
}

/**
 * Seed `nodeState`, then capture it immediately before and after the author
 * source.
 *
 * The author source stays at top level: wrapping it in a function or block
 * changes AM's already-unusual top-level `const` behaviour. One generated
 * binding is therefore visible to global enumeration. Its identifier and the
 * state key written after the author source are chosen not to occur anywhere
 * in the original source; helper names are private inside the binding's IIFE.
 *
 * The seed lives here rather than in a preceding setup node, and rather than
 * in a query parameter. Measured 2026-09-13: state seeded in the subject, in
 * a preceding node, and with the subject as the entry node all produced
 * byte-identical results, so the extra node bought nothing. A query parameter
 * would have been worse than useless — `requestParameters` is a binding the
 * corpus measures, so harness data sitting in it is observable to the very
 * scripts under test.
 *
 * The seed is applied BEFORE the `before` snapshot, matching what the setup
 * node did: seeded values are the script's starting state, not a mutation it
 * made. It is applied only on the node's FIRST pass — see the guard below.
 */
export function instrumentSubject(
  authorSource: string,
  runId: string,
  given: Given = {}
): InstrumentedSubject {
  const token = runId.replace(/-/g, "_");
  const bindingName = unused(`${BINDING_PREFIX}${token}`, authorSource);
  const snapshotKey = unused(`${SNAPSHOT_KEY_PREFIX}${runId}`, authorSource);
  const keyLit = jsStringLiteral(snapshotKey);
  const body = authorSource.endsWith("\n") ? authorSource : `${authorSource}\n`;
  return {
    bindingName,
    snapshotKey,
    source: [
      "// Generated by rhino-local AIC lane. Seed and instrumentation precede",
      "// the author source; request headers/parameters/cookies are sent on the",
      "// authenticate call instead, because no script can assign those bindings.",
      `var ${bindingName} = (function () {`,
      HELPERS,
      `return { snapshot: snapshot, seed: seed };`,
      `}());`,
      `// Seed once. A node that sends callbacks re-executes from the top when`,
      `// the client answers, and re-seeding there would overwrite whatever the`,
      `// earlier pass left in state with the request's original values — the`,
      `// chain would silently restart from the top on every step.`,
      `if (callbacks.isEmpty()) {`,
      `  ${bindingName}.seed(${jsonParseCall(given.sharedState ?? {})}, function (k, v) {`,
      `    nodeState.putShared(k, v);`,
      `  });`,
      `  ${bindingName}.seed(${jsonParseCall(given.transientState ?? {})}, function (k, v) {`,
      `    nodeState.putTransient(k, v);`,
      `  });`,
      `}`,
      `${bindingName}.before = ${bindingName}.snapshot(nodeState);`,
      `// rhino-local author source begins`,
      body,
      `// rhino-local author source ends`,
      `${bindingName}.final = ${bindingName}.snapshot(nodeState);`,
      `nodeState.putTransient(${keyLit}, JSON.stringify({`,
      `  before: ${bindingName}.before,`,
      `  final: ${bindingName}.final`,
      `}));`,
      "",
    ].join("\n"),
  };
}

/** JSON objects the subject will seed, for tests and invoke classification. */
export function seededState(given: Given): {
  shared: JsonObject;
  transient: JsonObject;
} {
  return {
    shared: given.sharedState ?? {},
    transient: given.transientState ?? {},
  };
}

function unused(seed: string, source: string): string {
  let candidate = seed;
  while (source.includes(candidate)) {
    candidate += "_";
  }
  return candidate;
}
