import { jsStringLiteral } from "./js.ts";

const BINDING_PREFIX = "__rhinoLocalHarness_";
const SNAPSHOT_KEY_PREFIX = "__rhino_local_snapshot_";

const HELPERS = `\
function keys(ns) {
  var raw = ns.keys();
  var out = [];
  var i;
  var it;
  var k;
  if (raw === null || raw === undefined) {
    return out;
  }
  if (typeof raw.length === "number" && typeof raw !== "string") {
    for (i = 0; i < raw.length; i += 1) {
      out.push(String(raw[i]));
    }
    return out;
  }
  if (typeof raw.toArray === "function") {
    raw = raw.toArray();
    for (i = 0; i < raw.length; i += 1) {
      out.push(String(raw[i]));
    }
    return out;
  }
  if (typeof raw.iterator === "function") {
    it = raw.iterator();
    while (it.hasNext()) {
      out.push(String(it.next()));
    }
    return out;
  }
  if (typeof raw.size === "function" && typeof raw.get === "function" && typeof raw.keySet !== "function") {
    for (i = 0; i < raw.size(); i += 1) {
      out.push(String(raw.get(i)));
    }
    return out;
  }
  for (k in raw) {
    if (Object.prototype.hasOwnProperty.call(raw, k) && typeof raw[k] !== "function") {
      out.push(String(raw[k]));
    }
  }
  return out;
}

function valueToJson(value) {
  var t;
  var i;
  var k;
  var out;
  var mapKeys;
  var arr;
  if (value === null || value === undefined) {
    return null;
  }
  t = typeof value;
  if (t === "string" || t === "number" || t === "boolean") {
    return value;
  }
  if (typeof Array.isArray === "function" && Array.isArray(value)) {
    out = [];
    for (i = 0; i < value.length; i += 1) {
      out.push(valueToJson(value[i]));
    }
    return out;
  }
  if (typeof value.keySet === "function" && typeof value.get === "function") {
    out = {};
    mapKeys = value.keySet();
    if (typeof mapKeys.toArray === "function") {
      arr = mapKeys.toArray();
      for (i = 0; i < arr.length; i += 1) {
        out[String(arr[i])] = valueToJson(value.get(arr[i]));
      }
      return out;
    }
  }
  if (typeof value.size === "function" && typeof value.get === "function") {
    out = [];
    for (i = 0; i < value.size(); i += 1) {
      out.push(valueToJson(value.get(i)));
    }
    return out;
  }
  if (t === "object") {
    out = {};
    for (k in value) {
      if (Object.prototype.hasOwnProperty.call(value, k) && typeof value[k] !== "function") {
        out[String(k)] = valueToJson(value[k]);
      }
    }
    return out;
  }
  return String(value);
}

function snapshot(ns) {
  var names = keys(ns);
  var out = {};
  var i;
  var key;
  for (i = 0; i < names.length; i += 1) {
    key = names[i];
    out[key] = valueToJson(ns.get(key));
  }
  return out;
}
`;

export interface InstrumentedSubject {
  source: string;
  bindingName: string;
  snapshotKey: string;
}

/**
 * Capture unified nodeState immediately before and after the author source.
 *
 * The author source stays at top level: wrapping it in a function or block
 * changes AM's already-unusual top-level `const` behaviour. One generated
 * binding is therefore visible to global enumeration. Its identifier and the
 * state key written after the author source are chosen not to occur anywhere
 * in the original source; helper names are private inside the binding's IIFE.
 */
export function instrumentSubject(
  authorSource: string,
  runId: string
): InstrumentedSubject {
  const token = runId.replace(/-/g, "_");
  const bindingName = unused(`${BINDING_PREFIX}${token}`, authorSource);
  const snapshotKey = unused(`${SNAPSHOT_KEY_PREFIX}${runId}`, authorSource);
  const keyLit = jsStringLiteral(snapshotKey);
  const body = authorSource.endsWith("\n") ? authorSource : `${authorSource}\n`;
  return {
    bindingName,
    snapshotKey,
    source: [
      "// Generated by rhino-local AIC lane. Instrumentation precedes the author source.",
      `var ${bindingName} = (function () {`,
      HELPERS,
      `return { snapshot: snapshot };`,
      `}());`,
      `${bindingName}.before = ${bindingName}.snapshot(nodeState);`,
      `// rhino-local author source begins`,
      body,
      `// rhino-local author source ends`,
      `${bindingName}.final = ${bindingName}.snapshot(nodeState);`,
      `nodeState.putTransient(${keyLit}, JSON.stringify({`,
      `  before: ${bindingName}.before,`,
      `  final: ${bindingName}.final`,
      `}));`,
      "",
    ].join("\n"),
  };
}

function unused(seed: string, source: string): string {
  let candidate = seed;
  while (source.includes(candidate)) {
    candidate += "_";
  }
  return candidate;
}
