//! Workspace scaffolding + template versioning (kind-agnostic).
//!
//! Scaffolds a **per-tenant** workspace at `workspace/<tenant>/` covering both
//! realms: AM scripts live under `am/<realm>/<type>/` (realm-scoped), IDM
//! endpoints under `idm/endpoint/` (tenant-global, no realm). Type definitions
//! are shared at the `am/` level. Templates are embedded at compile time; a
//! [`TEMPLATES_VERSION`] lets us ship updated types/config to existing
//! workspaces via `aic script workspace update`.

use crate::config::ProjectConfig;
use crate::Result;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Bump whenever an embedded template below changes. `workspace update`
/// re-copies the managed files when this exceeds a tree's recorded version.
pub const TEMPLATES_VERSION: u32 = 16;

/// Realms an AM tree is scaffolded for. AIC only has `alpha` + `bravo`.
const REALMS: &[&str] = &["alpha", "bravo"];

/// Managed files (regenerated by `workspace update`): shared type defs, base
/// tsconfig, and ESLint config for AM + IDM. Type defs are split into a layered
/// `types/` set (one Rhino interop layer + per-family overlays) — see
/// `docs/api/12-script-bindings-matrix.md` and `am::leaf_tsconfig` for how the
/// per-folder leaf tsconfigs compose them.
const MANAGED: &[(&str, &str)] = &[
    // AM shared type defs.
    ("am/types/rhino-1.7.14.d.ts", include_str!("templates/am/types/rhino-1.7.14.d.ts")),
    ("am/types/common.d.ts", include_str!("templates/am/types/common.d.ts")),
    ("am/types/nextgen-common.d.ts", include_str!("templates/am/types/nextgen-common.d.ts")),
    ("am/types/legacy-common.d.ts", include_str!("templates/am/types/legacy-common.d.ts")),
    ("am/types/decision-node-base.d.ts", include_str!("templates/am/types/decision-node-base.d.ts")),
    ("am/types/decision-node-next.d.ts", include_str!("templates/am/types/decision-node-next.d.ts")),
    ("am/types/decision-node-legacy.d.ts", include_str!("templates/am/types/decision-node-legacy.d.ts")),
    ("am/types/library.d.ts", include_str!("templates/am/types/library.d.ts")),
    ("am/types/oidc-claims.d.ts", include_str!("templates/am/types/oidc-claims.d.ts")),
    // Next-gen context overlays generated from the editor binding metadata.
    ("am/types/oidc-claims-ng.d.ts", include_str!("templates/am/types/oidc-claims-ng.d.ts")),
    ("am/types/device-match.d.ts", include_str!("templates/am/types/device-match.d.ts")),
    ("am/types/social-handler.d.ts", include_str!("templates/am/types/social-handler.d.ts")),
    ("am/types/saml-nameid-mapper.d.ts", include_str!("templates/am/types/saml-nameid-mapper.d.ts")),
    ("am/types/saml-sp-account-mapper.d.ts", include_str!("templates/am/types/saml-sp-account-mapper.d.ts")),
    ("am/types/oauth2-dcr.d.ts", include_str!("templates/am/types/oauth2-dcr.d.ts")),
    ("am/types/pingone-verify.d.ts", include_str!("templates/am/types/pingone-verify.d.ts")),
    ("am/tsconfig.json", include_str!("templates/am/tsconfig.json")),
    ("am/eslint.config.js", include_str!("templates/am/eslint.config.js")),
    // IDM shared type defs.
    ("idm/types/rhino-1.7.14.d.ts", include_str!("templates/idm/types/rhino-1.7.14.d.ts")),
    ("idm/types/common.d.ts", include_str!("templates/idm/types/common.d.ts")),
    ("idm/types/endpoint.d.ts", include_str!("templates/idm/types/endpoint.d.ts")),
    ("idm/types/schedule.d.ts", include_str!("templates/idm/types/schedule.d.ts")),
    ("idm/tsconfig.json", include_str!("templates/idm/tsconfig.json")),
    ("idm/eslint.config.js", include_str!("templates/idm/eslint.config.js")),
    ("idm/endpoint/tsconfig.json", include_str!("templates/idm/endpoint/tsconfig.json")),
    ("idm/schedule/tsconfig.json", include_str!("templates/idm/schedule/tsconfig.json")),
    // Tooling: per-leaf type-check runner used by `npm run type-check`.
    ("tools/check-types.mjs", include_str!("templates/tools/check-types.mjs")),
];

/// Files this tool managed under older template versions that are now obsolete
/// and must be **deleted** from existing workspaces on update (replaced by the
/// `am/types/` + `idm/types/` layout in `TEMPLATES_VERSION` 6). Only ever list
/// files this tool itself wrote — never user scripts, tests, or package files.
const OBSOLETE: &[&str] = &[
    "am/amCommon.d.ts",
    "am/src.d.ts",
    "am/lib.d.ts",
    "am/oidc.d.ts",
    "idm/idmCommon.d.ts",
];

/// User files: seeded once on init, never overwritten (even by update).
const USER: &[(&str, &str)] = &[
    ("package.json", include_str!("templates/package.json")),
    (".prettierrc", include_str!("templates/.prettierrc")),
    ("README.md", include_str!("templates/README.md")),
    ("tests/example.test.ts", include_str!("templates/tests/example.test.ts")),
];

/// Our own `.gitignore` (the p1-sync one references `.p1-sync/`). Ignores build
/// output and our sync state; keeps the source dirs tracked.
const GITIGNORE: &str = "node_modules/\ndist/\ncoverage/\n.aic-sync/\n*.log\n.DS_Store\n";

#[derive(Debug, Default, Serialize, Deserialize)]
struct WorkspaceState {
    templates_version: u32,
}

fn state_path(tenant: &str) -> PathBuf {
    ProjectConfig::aic_sync_dir(tenant).join("state.toml")
}

/// Detect a pre-redesign **per-realm** workspace
/// (`workspace/<tenant>/<realm>/.aic-sync`). The layout is now per-tenant
/// (`am/<realm>/…`), so the old `.aic-sync` is ignored — returning the old
/// realm dir lets callers refuse rather than silently auto-init over it and
/// strand local edits.
pub fn legacy_layout(tenant: &str) -> Option<PathBuf> {
    let tree = ProjectConfig::workspace_tree(tenant);
    REALMS
        .iter()
        .map(|r| tree.join(r))
        .find(|dir| dir.join(".aic-sync").is_dir())
}

/// Templates version recorded for a tenant's workspace (0 if uninitialised).
pub fn applied_version(tenant: &str) -> Result<u32> {
    let path = state_path(tenant);
    if !path.exists() {
        return Ok(0);
    }
    let state: WorkspaceState = toml::from_str(&std::fs::read_to_string(&path)?)?;
    Ok(state.templates_version)
}

fn record_version(tenant: &str) -> Result<()> {
    let dir = ProjectConfig::aic_sync_dir(tenant);
    std::fs::create_dir_all(&dir)?;
    let state = WorkspaceState { templates_version: TEMPLATES_VERSION };
    std::fs::write(state_path(tenant), toml::to_string_pretty(&state)?)?;
    Ok(())
}

fn write_if(path: &Path, contents: &str, overwrite: bool) -> Result<bool> {
    if path.exists() && !overwrite {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    Ok(true)
}

/// What a scaffolding run wrote (and, on update, removed).
#[derive(Debug, Default)]
pub struct WorkspaceReport {
    pub written: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
    pub tree: PathBuf,
}

/// Create the per-tenant workspace tree (both realms + IDM): directories,
/// embedded templates (managed always; user files only if missing),
/// `.gitignore`, and the recorded templates version.
pub fn init(tenant: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, false)
}

/// Refresh the managed template files (types / tsconfig / eslint) to the
/// current [`TEMPLATES_VERSION`], leaving user files untouched.
pub fn update(tenant: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, true)
}

fn scaffold(tenant: &str, is_update: bool) -> Result<WorkspaceReport> {
    let tree = ProjectConfig::workspace_tree(tenant);
    let report = scaffold_at(&tree, is_update)?;
    record_version(tenant)?;
    Ok(report)
}

/// Scaffold into an explicit `tree` dir (no tenant state). Split out from
/// [`scaffold`] so it can be exercised against a temp dir in tests.
fn scaffold_at(tree: &Path, is_update: bool) -> Result<WorkspaceReport> {
    let mut report = WorkspaceReport { tree: tree.to_path_buf(), ..Default::default() };

    // AM script folders are created per type on pull (each gets its own leaf
    // `tsconfig.json` then — see `am::extra_files`), so we only scaffold the
    // shared `am/` defs here. IDM folders are fixed, so create them up front.
    std::fs::create_dir_all(tree.join("am"))?;
    std::fs::create_dir_all(tree.join("idm").join("endpoint"))?;
    std::fs::create_dir_all(tree.join("idm").join("schedule"))?;
    std::fs::create_dir_all(tree.join("tests"))?;

    // Managed shared files (always (re)written).
    for (rel, contents) in MANAGED {
        let path = tree.join(rel);
        if write_if(&path, contents, true)? {
            report.written.push(path);
        }
    }
    // User files: seed once, never touched on update.
    if !is_update {
        for (rel, contents) in USER {
            let path = tree.join(rel);
            if write_if(&path, contents, false)? {
                report.written.push(path);
            }
        }
    }
    // `.gitignore` is managed (always refreshed).
    let gi = tree.join(".gitignore");
    if write_if(&gi, GITIGNORE, true)? {
        report.written.push(gi);
    }

    // Delete obsolete managed files left over from older template versions. The
    // OBSOLETE list only ever names files this tool wrote, so this never touches
    // user scripts. (No-op on a fresh init — none exist yet.)
    for rel in OBSOLETE {
        let path = tree.join(rel);
        if path.exists() {
            std::fs::remove_file(&path)?;
            report.removed.push(path);
        }
    }

    // Leaf `tsconfig.json` files are normally (re)written per script folder on
    // pull (`am::extra_files`). Renaming the shared type files means existing,
    // already-pulled folders would point at deleted defs until their next pull,
    // so an update refreshes every already-pulled AM leaf in place.
    for realm in REALMS {
        let realm_dir = tree.join("am").join(realm);
        let Ok(entries) = std::fs::read_dir(&realm_dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let dir = entry.path();
            let leaf = dir.join("tsconfig.json");
            if dir.is_dir() && leaf.exists() {
                let slug = entry.file_name().to_string_lossy().into_owned();
                std::fs::write(&leaf, super::am::leaf_tsconfig(&slug))?;
                report.written.push(leaf);
            }
        }
    }

    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn templates_all_embed() {
        for (rel, contents) in MANAGED.iter().chain(USER) {
            assert!(!contents.is_empty(), "empty template: {rel}");
        }
        // The layered type set replaced the old root `*.d.ts` files.
        assert!(MANAGED.iter().any(|(r, _)| *r == "am/types/common.d.ts"));
        assert!(MANAGED.iter().any(|(r, _)| *r == "am/types/decision-node-base.d.ts"));
        assert!(MANAGED.iter().any(|(r, _)| *r == "idm/types/endpoint.d.ts"));
        assert!(USER.iter().any(|(r, _)| *r == "package.json"));
    }

    #[test]
    fn obsolete_files_are_cleanly_retired() {
        // Obsolete files must not also be (re)written as managed, or update would
        // delete-then-recreate them.
        for rel in OBSOLETE {
            assert!(
                !MANAGED.iter().any(|(r, _)| r == rel),
                "obsolete file still in MANAGED: {rel}"
            );
        }
        // The old root type defs are scheduled for cleanup on update.
        assert!(OBSOLETE.contains(&"am/src.d.ts"));
        assert!(OBSOLETE.contains(&"idm/idmCommon.d.ts"));
    }

    fn temp_tree() -> PathBuf {
        std::env::temp_dir().join(format!("aic-ws-test-{}", uuid::Uuid::new_v4()))
    }

    #[test]
    fn init_writes_managed_and_user_files() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        // Layered managed type defs + tooling are written.
        assert!(tree.join("am/types/common.d.ts").exists());
        assert!(tree.join("am/types/decision-node-next.d.ts").exists());
        assert!(tree.join("idm/types/endpoint.d.ts").exists());
        assert!(tree.join("tools/check-types.mjs").exists());
        assert!(tree.join("am/eslint.config.js").exists());
        // User files seeded on init.
        assert!(tree.join("package.json").exists());

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_deletes_obsolete_managed_files() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        // Simulate a pre-v6 workspace carrying an old managed type def.
        let stale = tree.join("am/src.d.ts");
        std::fs::write(&stale, "// old managed file\n").unwrap();
        assert!(stale.exists());

        let report = scaffold_at(&tree, true).unwrap();
        assert!(!stale.exists(), "obsolete file should be deleted on update");
        assert!(report.removed.iter().any(|p| p.ends_with("am/src.d.ts")));

        std::fs::remove_dir_all(&tree).ok();
    }

    #[test]
    fn update_regenerates_existing_leaf_tsconfig() {
        let tree = temp_tree();
        scaffold_at(&tree, false).unwrap();

        // A previously-pulled folder with a stale leaf tsconfig (old type path).
        let folder = tree.join("am/alpha/decision-node");
        std::fs::create_dir_all(&folder).unwrap();
        let leaf = folder.join("tsconfig.json");
        std::fs::write(&leaf, "{ \"include\": [\"../../src.d.ts\"] }").unwrap();

        scaffold_at(&tree, true).unwrap();

        let refreshed = std::fs::read_to_string(&leaf).unwrap();
        assert!(refreshed.contains("../../types/decision-node-next.d.ts"));
        assert!(!refreshed.contains("src.d.ts"));

        std::fs::remove_dir_all(&tree).ok();
    }
}
