//! Workspace scaffolding + template versioning (kind-agnostic).
//!
//! Scaffolds a **per-tenant** workspace at `workspace/<tenant>/` covering both
//! realms: AM scripts live under `am/<realm>/<type>/` (realm-scoped), IDM
//! endpoints under `idm/endpoint/` (tenant-global, no realm). Type definitions
//! are shared at the `am/` level. Templates are embedded at compile time; a
//! [`TEMPLATES_VERSION`] lets us ship updated types/config to existing
//! workspaces via `aic script workspace update`.

use crate::config::ProjectConfig;
use crate::Result;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Bump whenever an embedded template below changes. `workspace update`
/// re-copies the managed files when this exceeds a tree's recorded version.
pub const TEMPLATES_VERSION: u32 = 2;

/// Realms an AM tree is scaffolded for. AIC only has `alpha` + `bravo`.
const REALMS: &[&str] = &["alpha", "bravo"];

/// Per-type leaf `tsconfig.json` written into each `am/<realm>/<type>/`.
const AM_LEAF_TSCONFIGS: &[(&str, &str)] = &[
    ("src", include_str!("templates/am/src/tsconfig.json")),
    ("lib", include_str!("templates/am/lib/tsconfig.json")),
    ("oidc", include_str!("templates/am/oidc/tsconfig.json")),
];

/// Managed files (regenerated by `workspace update`): shared type defs, base
/// tsconfig, and ESLint config for AM + IDM.
const MANAGED: &[(&str, &str)] = &[
    ("am/amCommon.d.ts", include_str!("templates/am/amCommon.d.ts")),
    ("am/src.d.ts", include_str!("templates/am/src.d.ts")),
    ("am/lib.d.ts", include_str!("templates/am/lib.d.ts")),
    ("am/oidc.d.ts", include_str!("templates/am/oidc.d.ts")),
    ("am/tsconfig.json", include_str!("templates/am/tsconfig.json")),
    ("am/eslint.config.js", include_str!("templates/am/eslint.config.js")),
    ("idm/idmCommon.d.ts", include_str!("templates/idm/idmCommon.d.ts")),
    ("idm/tsconfig.json", include_str!("templates/idm/tsconfig.json")),
    ("idm/eslint.config.js", include_str!("templates/idm/eslint.config.js")),
    ("idm/endpoint/tsconfig.json", include_str!("templates/idm/endpoint/tsconfig.json")),
];

/// User files: seeded once on init, never overwritten (even by update).
const USER: &[(&str, &str)] = &[
    ("package.json", include_str!("templates/package.json")),
    (".prettierrc", include_str!("templates/.prettierrc")),
    ("README.md", include_str!("templates/README.md")),
    ("tests/example.test.ts", include_str!("templates/tests/example.test.ts")),
];

/// Our own `.gitignore` (the p1-sync one references `.p1-sync/`). Ignores build
/// output and our sync state; keeps the source dirs tracked.
const GITIGNORE: &str = "node_modules/\ndist/\ncoverage/\n.aic-sync/\n*.log\n.DS_Store\n";

#[derive(Debug, Default, Serialize, Deserialize)]
struct WorkspaceState {
    templates_version: u32,
}

fn state_path(tenant: &str) -> PathBuf {
    ProjectConfig::aic_sync_dir(tenant).join("state.toml")
}

/// Templates version recorded for a tenant's workspace (0 if uninitialised).
pub fn applied_version(tenant: &str) -> Result<u32> {
    let path = state_path(tenant);
    if !path.exists() {
        return Ok(0);
    }
    let state: WorkspaceState = toml::from_str(&std::fs::read_to_string(&path)?)?;
    Ok(state.templates_version)
}

fn record_version(tenant: &str) -> Result<()> {
    let dir = ProjectConfig::aic_sync_dir(tenant);
    std::fs::create_dir_all(&dir)?;
    let state = WorkspaceState { templates_version: TEMPLATES_VERSION };
    std::fs::write(state_path(tenant), toml::to_string_pretty(&state)?)?;
    Ok(())
}

fn write_if(path: &Path, contents: &str, overwrite: bool) -> Result<bool> {
    if path.exists() && !overwrite {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    Ok(true)
}

/// What a scaffolding run wrote.
#[derive(Debug, Default)]
pub struct WorkspaceReport {
    pub written: Vec<PathBuf>,
    pub tree: PathBuf,
}

/// Create the per-tenant workspace tree (both realms + IDM): directories,
/// embedded templates (managed always; user files only if missing),
/// `.gitignore`, and the recorded templates version.
pub fn init(tenant: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, false)
}

/// Refresh the managed template files (types / tsconfig / eslint) to the
/// current [`TEMPLATES_VERSION`], leaving user files untouched.
pub fn update(tenant: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, true)
}

fn scaffold(tenant: &str, is_update: bool) -> Result<WorkspaceReport> {
    let tree = ProjectConfig::workspace_tree(tenant);
    let mut report = WorkspaceReport { tree: tree.clone(), ..Default::default() };

    // Directories: am/<realm>/<type> for both realms, idm/endpoint, tests.
    for realm in REALMS {
        for (ty, _) in AM_LEAF_TSCONFIGS {
            std::fs::create_dir_all(tree.join("am").join(realm).join(ty))?;
        }
    }
    std::fs::create_dir_all(tree.join("idm").join("endpoint"))?;
    std::fs::create_dir_all(tree.join("tests"))?;

    // Managed shared files (always (re)written).
    for (rel, contents) in MANAGED {
        let path = tree.join(rel);
        if write_if(&path, contents, true)? {
            report.written.push(path);
        }
    }
    // Per-realm/type leaf tsconfigs (managed).
    for realm in REALMS {
        for (ty, contents) in AM_LEAF_TSCONFIGS {
            let path = tree.join("am").join(realm).join(ty).join("tsconfig.json");
            if write_if(&path, contents, true)? {
                report.written.push(path);
            }
        }
    }
    // User files: seed once, never touched on update.
    if !is_update {
        for (rel, contents) in USER {
            let path = tree.join(rel);
            if write_if(&path, contents, false)? {
                report.written.push(path);
            }
        }
    }
    // `.gitignore` is managed (always refreshed).
    let gi = tree.join(".gitignore");
    if write_if(&gi, GITIGNORE, true)? {
        report.written.push(gi);
    }

    record_version(tenant)?;
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn templates_all_embed() {
        for (rel, contents) in MANAGED.iter().chain(USER) {
            assert!(!contents.is_empty(), "empty template: {rel}");
        }
        for (ty, contents) in AM_LEAF_TSCONFIGS {
            assert!(!contents.is_empty(), "empty leaf tsconfig: {ty}");
            // Leaf tsconfigs sit two levels below am/, so they reach shared defs via ../../.
            assert!(contents.contains("../../"), "leaf {ty} tsconfig should reference ../../");
        }
        assert!(MANAGED.iter().any(|(r, _)| *r == "am/src.d.ts"));
        assert!(USER.iter().any(|(r, _)| *r == "package.json"));
    }
}
