//! Workspace scaffolding + template versioning (kind-agnostic).
//!
//! Reproduces the p1aic-script-editor workspace layout (typed `.d.ts`, per-dir
//! `tsconfig.json`, ESLint/Prettier config) under `workspace/<tenant>/<realm>/`
//! so the user's editor gives full IntelliSense on synced scripts. Templates
//! are embedded at compile time; a [`TEMPLATES_VERSION`] lets us ship updated
//! types/config to existing workspaces via `aic script workspace update`.

use crate::config::ProjectConfig;
use crate::Result;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Bump whenever an embedded template below changes. `workspace update`
/// re-copies the managed files when this exceeds the version recorded in a
/// tree's `.aic-sync/state.toml`.
pub const TEMPLATES_VERSION: u32 = 1;

/// A template file: workspace-relative path, contents, and whether it's
/// **managed** (regenerated by us — overwritten on update) or a **user** file
/// (seeded once, never clobbered).
struct TemplateFile {
    rel: &'static str,
    contents: &'static str,
    managed: bool,
}

/// The embedded template set (the p1-sync template tree, verbatim). Managed =
/// types + tsconfig + eslint (safe to regenerate). User = package.json /
/// prettier / README / tests (seeded once).
const TEMPLATES: &[TemplateFile] = &[
    // --- managed: AM ---
    TemplateFile { rel: "am/tsconfig.json", contents: include_str!("templates/am/tsconfig.json"), managed: true },
    TemplateFile { rel: "am/eslint.config.js", contents: include_str!("templates/am/eslint.config.js"), managed: true },
    TemplateFile { rel: "am/amCommon.d.ts", contents: include_str!("templates/am/amCommon.d.ts"), managed: true },
    TemplateFile { rel: "am/src/src.d.ts", contents: include_str!("templates/am/src/src.d.ts"), managed: true },
    TemplateFile { rel: "am/src/tsconfig.json", contents: include_str!("templates/am/src/tsconfig.json"), managed: true },
    TemplateFile { rel: "am/lib/lib.d.ts", contents: include_str!("templates/am/lib/lib.d.ts"), managed: true },
    TemplateFile { rel: "am/lib/tsconfig.json", contents: include_str!("templates/am/lib/tsconfig.json"), managed: true },
    TemplateFile { rel: "am/oidc/oidc.d.ts", contents: include_str!("templates/am/oidc/oidc.d.ts"), managed: true },
    TemplateFile { rel: "am/oidc/tsconfig.json", contents: include_str!("templates/am/oidc/tsconfig.json"), managed: true },
    // --- managed: IDM ---
    TemplateFile { rel: "idm/tsconfig.json", contents: include_str!("templates/idm/tsconfig.json"), managed: true },
    TemplateFile { rel: "idm/eslint.config.js", contents: include_str!("templates/idm/eslint.config.js"), managed: true },
    TemplateFile { rel: "idm/idmCommon.d.ts", contents: include_str!("templates/idm/idmCommon.d.ts"), managed: true },
    TemplateFile { rel: "idm/endpoint/tsconfig.json", contents: include_str!("templates/idm/endpoint/tsconfig.json"), managed: true },
    // --- user: seeded once, never overwritten ---
    TemplateFile { rel: "package.json", contents: include_str!("templates/package.json"), managed: false },
    TemplateFile { rel: ".prettierrc", contents: include_str!("templates/.prettierrc"), managed: false },
    TemplateFile { rel: "README.md", contents: include_str!("templates/README.md"), managed: false },
    TemplateFile { rel: "tests/example.test.ts", contents: include_str!("templates/tests/example.test.ts"), managed: false },
];

/// Our own `.gitignore` (the p1-sync one references `.p1-sync/`). Ignores build
/// output and our sync state; keeps the source dirs tracked.
const GITIGNORE: &str = "node_modules/\ndist/\ncoverage/\n.aic-sync/\n*.log\n.DS_Store\n";

#[derive(Debug, Default, Serialize, Deserialize)]
struct WorkspaceState {
    templates_version: u32,
}

fn state_path(tenant: &str, realm: &str) -> PathBuf {
    ProjectConfig::aic_sync_dir(tenant, realm).join("state.toml")
}

/// Templates version recorded in a tree (0 if uninitialised).
pub fn applied_version(tenant: &str, realm: &str) -> Result<u32> {
    let path = state_path(tenant, realm);
    if !path.exists() {
        return Ok(0);
    }
    let state: WorkspaceState = toml::from_str(&std::fs::read_to_string(&path)?)?;
    Ok(state.templates_version)
}

fn record_version(tenant: &str, realm: &str) -> Result<()> {
    let dir = ProjectConfig::aic_sync_dir(tenant, realm);
    std::fs::create_dir_all(&dir)?;
    let state = WorkspaceState { templates_version: TEMPLATES_VERSION };
    std::fs::write(state_path(tenant, realm), toml::to_string_pretty(&state)?)?;
    Ok(())
}

fn write_if(path: &Path, contents: &str, overwrite: bool) -> Result<bool> {
    if path.exists() && !overwrite {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    Ok(true)
}

/// What a scaffolding run wrote.
#[derive(Debug, Default)]
pub struct WorkspaceReport {
    pub written: Vec<PathBuf>,
    pub tree: PathBuf,
}

/// Create the workspace tree for `tenant`/`realm`: directories, embedded
/// templates (managed files always; user files only if missing), `.gitignore`,
/// and the recorded templates version.
pub fn init(tenant: &str, realm: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, realm, false)
}

/// Refresh the managed template files (types / tsconfig / eslint) to the
/// current [`TEMPLATES_VERSION`], leaving user files untouched.
pub fn update(tenant: &str, realm: &str) -> Result<WorkspaceReport> {
    scaffold(tenant, realm, true)
}

fn scaffold(tenant: &str, realm: &str, is_update: bool) -> Result<WorkspaceReport> {
    let tree = ProjectConfig::workspace_tree(tenant, realm);
    let mut report = WorkspaceReport { tree: tree.clone(), ..Default::default() };

    for dir in ["am/src", "am/lib", "am/oidc", "idm/endpoint", "tests"] {
        std::fs::create_dir_all(tree.join(dir))?;
    }

    for f in TEMPLATES {
        // Managed files are always (re)written; user files only when missing.
        // On update we never touch user files.
        let overwrite = f.managed;
        if is_update && !f.managed {
            continue;
        }
        let path = tree.join(f.rel);
        if write_if(&path, f.contents, overwrite)? {
            report.written.push(path);
        }
    }

    // `.gitignore` is managed (always refreshed).
    let gi = tree.join(".gitignore");
    if write_if(&gi, GITIGNORE, true)? {
        report.written.push(gi);
    }

    record_version(tenant, realm)?;
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn templates_all_embed() {
        // include_str! would fail the build if a path were wrong; this just
        // guards against an empty template sneaking in.
        for f in TEMPLATES {
            assert!(!f.contents.is_empty(), "empty template: {}", f.rel);
        }
        assert!(TEMPLATES.iter().any(|f| f.rel == "am/amCommon.d.ts" && f.managed));
        assert!(TEMPLATES.iter().any(|f| f.rel == "package.json" && !f.managed));
    }
}
