// Guards the shape of the framework's public surface against a regression that
// no other gate can see: a namespace re-export in `framework/index.ts` costs
// every endpoint the whole re-exported module.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const FRAMEWORK_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "framework"
);

function frameworkSources() {
  return readdirSync(FRAMEWORK_DIR)
    .filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts"))
    .sort()
    .map((name) => ({
      name,
      code: readFileSync(join(FRAMEWORK_DIR, name), "utf8"),
    }));
}

test("no framework module re-exports a namespace", () => {
  // `export * as ns from "./other.ts"` materialises an object holding every
  // export of `other.ts`, so esbuild can no longer prove any member unused and
  // retains all of them. `v` was re-exported this way and cost each demo
  // endpoint 4-7 KB of unreachable validators. Endpoints import the namespace
  // directly instead (`import * as v from "../../framework/validate.ts"`),
  // which tree-shakes because every use is a static property access.
  const offenders = frameworkSources()
    .filter(({ code }) => /^\s*export \* as \w+ from/m.test(code))
    .map(({ name }) => name);
  assert.deepEqual(
    offenders,
    [],
    "re-export the names, or have endpoints import the namespace directly: " +
      offenders.join(", ")
  );
});

test("the guard sees a namespace re-export when there is one", () => {
  // Otherwise the assertion above could pass because the pattern never matches.
  assert.match(
    'export * as v from "./validate.ts";',
    /^\s*export \* as \w+ from/m
  );
});
