// The `managedStore` double's own gate.
//
// WHY THIS FILE EXISTS. A test double that is more permissive than the tenant
// converts a live failure into a green test, and this one was: it ignored the
// `fields` selector and the `_queryFilter` outright, so an endpoint that
// mis-projected a read or forgot to filter a query passed here and 500'd (or
// leaked rows) against IDM. The assertions below pin the two directions that
// matter — what the double reproduces faithfully, and what it REFUSES rather
// than approximating.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  callContext,
  type ContextOptions,
  managedStore,
  withIdentityServer,
  withJava,
  withOpenIdm,
} from "./harness.ts";

/** Its own managed object, so the file does not lean on a tenant's schema. */
interface HarnessProbe {
  _id?: string;
  _rev?: string;
  userName: string;
  mail: string;
  sn: string;
  manager?: { _ref: string };
}

declare global {
  interface ManagedObjects {
    "managed/__aic_harness_probe": HarnessProbe;
  }
}

const COLLECTION = "managed/__aic_harness_probe";

function store() {
  return managedStore({
    [COLLECTION]: [
      { _id: "a", _rev: "1", userName: "ada", mail: "ada@x.invalid", sn: "L" },
      { _id: "b", _rev: "1", userName: "bob", mail: "bob@x.invalid", sn: "B" },
    ],
  });
}

test("a fields selector projects, and keeps _id/_rev regardless", () => {
  const row = store().read(`${COLLECTION}/a`, null, ["userName"]);
  assert.deepEqual(row, { _id: "a", _rev: "1", userName: "ada" });
});

test("a fields selector of * opts out of projection", () => {
  const row = store().read(`${COLLECTION}/a`, null, ["*"]);
  assert.equal(Object.keys(row ?? {}).length, 5);
});

test("a read miss is null, never a throw", () => {
  assert.equal(store().read(`${COLLECTION}/nope`), null);
});

test("a read result is a copy, so a handler cannot mutate the store", () => {
  const bound = store();
  const row = bound.read(`${COLLECTION}/a`);
  if (row === null) {
    throw new Error("fixture missing");
  }
  row.userName = "MUTATED";
  assert.equal(bound.read(`${COLLECTION}/a`)?.userName, "ada");
});

test("a _queryFilter term actually filters", () => {
  const page = store().query(COLLECTION, {
    _queryFilter: '/userName eq "ada"',
  });
  assert.equal(page.resultCount, 1);
  assert.equal(page.result[0]?.userName, "ada");
});

test("_queryFilter true returns every row, and fields project them", () => {
  const page = store().query(COLLECTION, { _queryFilter: "true" }, ["mail"]);
  assert.deepEqual(page.result, [
    { _id: "a", _rev: "1", mail: "ada@x.invalid" },
    { _id: "b", _rev: "1", mail: "bob@x.invalid" },
  ]);
});

test("create refuses to upsert, the way openidm.create does", () => {
  assert.throws(
    () => store().create(COLLECTION, "a", { userName: "clash" }),
    /managedStore: create conflicts/
  );
});

test("update bumps the revision and merges", () => {
  const updated = store().update(`${COLLECTION}/a`, null, { sn: "Lovelace" });
  assert.equal(updated._rev, "2");
  assert.equal(updated.sn, "Lovelace");
  assert.equal(updated.userName, "ada");
});

// Everything the double will not approximate. Each of these was previously a
// silent wrong answer.
const refusals: readonly (readonly [string, () => unknown, RegExp])[] = [
  [
    "a relationship path, which needs a graph the double has not got",
    () => store().read(`${COLLECTION}/a`, null, ["manager/userName"]),
    /cannot expand the relationship path/,
  ],
  [
    "a query filter beyond a single equality term",
    () => store().query(COLLECTION, { _queryFilter: '/sn sw "L"' }),
    /only _queryFilter: true and a single/,
  ],
  [
    "a query parameter it does not model, rather than ignoring it",
    () => store().query(COLLECTION, { _queryFilter: "true", _pageSize: 1 }),
    /query parameter _pageSize is not modelled/,
  ],
  [
    "update of a record that is not there",
    () => store().update(`${COLLECTION}/nope`, null, {}),
    /update of a record that does not exist/,
  ],
  [
    "delete of a record that is not there",
    () => store().delete(`${COLLECTION}/nope`, null),
    /delete of a record that does not exist/,
  ],
  [
    "patch, which is not modelled at all",
    () => store().patch(`${COLLECTION}/a`, null, []),
    /patch is not modelled/,
  ],
];

for (const [name, call, message] of refusals) {
  test("refuses " + name, () => assert.throws(call, message));
}

test("withOpenIdm installs and then removes the global binding", () => {
  const had = "openidm" in globalThis;
  const seen = withOpenIdm(store(), () => openidm.read(`${COLLECTION}/a`));
  assert.equal(seen?.userName, "ada");
  assert.equal("openidm" in globalThis, had);
});

test("withIdentityServer installs getProperty and then removes the global", () => {
  const had = "identityServer" in globalThis;
  const seen = withIdentityServer(
    { "esv.demo.region": "eu" },
    () => identityServer.getProperty("esv.demo.region")
  );
  assert.equal(seen, "eu");
  assert.equal("identityServer" in globalThis, had);
});

test("withIdentityServer restores the global when run throws", () => {
  const had = "identityServer" in globalThis;
  assert.throws(
    () =>
      withIdentityServer({ "esv.x": "y" }, () => {
        throw new Error("boom");
      }),
    { message: "boom" }
  );
  assert.equal("identityServer" in globalThis, had);
});

test("withIdentityServer restores a previous binding after run throws", () => {
  withIdentityServer({ "esv.x": "outer" }, () => {
    assert.throws(
      () =>
        withIdentityServer({ "esv.x": "inner" }, () => {
          throw new Error("boom");
        }),
      { message: "boom" }
    );
    assert.equal(identityServer.getProperty("esv.x"), "outer");
  });
});

test("getProperty returns null for a missing name, or the supplied default", () => {
  withIdentityServer({ "esv.demo.region": "eu" }, () => {
    assert.equal(identityServer.getProperty("esv.missing"), null);
    assert.equal(identityServer.getProperty("esv.missing", "fallback"), "fallback");
    assert.equal(
      identityServer.getProperty("esv.demo.region", "fallback"),
      "eu"
    );
  });
});

test("refuses getProperty substitution, which is not modelled", () => {
  assert.throws(
    () =>
      withIdentityServer({ "esv.x": "y" }, () =>
        identityServer.getProperty("esv.x", "z", true)
      ),
    /identityServer: getProperty substitution is not modelled/
  );
});

test("withJava installs and then removes the global bindings", () => {
  const hadJava = "java" in globalThis;
  const hadJavax = "javax" in globalThis;
  const seen = withJava(() =>
    String(java.text.Normalizer.normalize("a", java.text.Normalizer.Form.NFC))
  );
  assert.equal(seen, "a");
  assert.equal("java" in globalThis, hadJava);
  assert.equal("javax" in globalThis, hadJavax);
});

test("withJava restores the globals when run throws", () => {
  const hadJava = "java" in globalThis;
  const hadJavax = "javax" in globalThis;
  assert.throws(
    () =>
      withJava(() => {
        throw new Error("boom");
      }),
    { message: "boom" }
  );
  assert.equal("java" in globalThis, hadJava);
  assert.equal("javax" in globalThis, hadJavax);
});

test("withJava restores a previous binding after run throws", () => {
  withJava(() => {
    const outer = java.text.Normalizer.Form.NFC;
    assert.throws(
      () =>
        withJava(() => {
          throw new Error("boom");
        }),
      { message: "boom" }
    );
    assert.equal(java.text.Normalizer.Form.NFC, outer);
  });
});

test("withJava throws for an unmodelled package", () => {
  withJava(() => {
    assert.throws(
      () => (java as unknown as Record<string, unknown>)["util"],
      /java: this test double does not model java.util/
    );
    assert.throws(
      () =>
        (javax.crypto as unknown as Record<string, unknown>)["Cipher"],
      /java: this test double does not model javax.crypto.Cipher/
    );
  });
});

test("withJava throws for an unmodelled member on a leaf", () => {
  withJava(() => {
    assert.throws(
      () =>
        (java.text.Normalizer as unknown as Record<string, unknown>)[
          "isNormalized"
        ],
      /java: this test double does not model java.text.Normalizer.isNormalized/
    );
    assert.throws(
      () =>
        (java.lang.String as unknown as Record<string, unknown>)["charAt"],
      /java: this test double does not model java.lang.String.charAt/
    );
    assert.throws(
      () =>
        (javax.crypto.Mac as unknown as Record<string, unknown>)["clone"],
      /java: this test double does not model javax.crypto.Mac.clone/
    );
    const mac = javax.crypto.Mac.getInstance("HmacSHA256");
    assert.throws(
      () => (mac as unknown as Record<string, unknown>)["clone"],
      /java: this test double does not model javax.crypto.Mac.clone/
    );
    const key = new javax.crypto.spec.SecretKeySpec(
      new java.lang.String("k").getBytes("UTF-8"),
      "HmacSHA256"
    );
    assert.throws(
      () => (key as unknown as Record<string, unknown>)["getEncoded"],
      /java: this test double does not model javax.crypto.spec.SecretKeySpec.getEncoded/
    );
    const value = new java.lang.String("x");
    assert.throws(
      () => (value as unknown as Record<string, unknown>)["charAt"],
      /java: this test double does not model java.lang.String.charAt/
    );
  });
});

test("withJava throws for an unmodelled Mac algorithm", () => {
  withJava(() => {
    assert.throws(
      () => javax.crypto.Mac.getInstance("HmacMD5"),
      /Mac.getInstance is only modelled/
    );
  });
});

test("withJava throws for getBytes without UTF-8", () => {
  withJava(() => {
    const value = new java.lang.String("x");
    assert.throws(
      () => (value as unknown as { getBytes: () => unknown }).getBytes(),
      /getBytes\(\) with no charset/
    );
    assert.throws(
      () =>
        (value as unknown as { getBytes: (charset: string) => unknown }).getBytes(
          "UTF-16"
        ),
      /only modelled for "UTF-8"/
    );
  });
});

// `false` asks for the behaviour the double DOES model, so refusing it would
// leave a handler that declines substitution explicitly impossible to dispatch.
test("getProperty accepts substitute: false as the modelled case", () => {
  withIdentityServer({ "esv.x": "y" }, () => {
    assert.equal(identityServer.getProperty("esv.x", "z", false), "y");
    assert.equal(identityServer.getProperty("esv.absent", "z", false), "z");
    assert.equal(identityServer.getProperty("esv.absent", undefined, false), null);
  });
});

test("callContext defaults the subject to svc-account", () => {
  const ctx = callContext();
  assert.equal(ctx.security?.authenticationId, "svc-account");
  assert.equal(ctx.security?.authorization.id, "svc-account");
  assert.equal(ctx.security?.authorization.component, "managed/svcacct");
  assert.deepEqual(ctx.security?.authorization.roles, [
    "internal/role/openidm-authorized",
  ]);
});

// A subject naming a collection must not arrive under the service account's
// component, or a handler that tells the two apart passes here and fails live.
test("callContext derives the component from a path-shaped subject", () => {
  const ctx = callContext({ subject: "managed/alpha_user/ada" });
  assert.equal(ctx.security?.authorization.component, "managed/alpha_user");
});

test("callContext takes an explicit component", () => {
  const ctx = callContext({
    subject: "ada",
    component: "managed/bravo_user",
  });
  assert.equal(ctx.security?.authorization.component, "managed/bravo_user");
});

test("callContext sets the subject and roles", () => {
  const ctx = callContext({
    subject: "managed/alpha_user/ada",
    roles: ["internal/role/openidm-admin"],
  });
  assert.equal(ctx.security?.authenticationId, "managed/alpha_user/ada");
  assert.equal(ctx.security?.authorization.id, "managed/alpha_user/ada");
  assert.deepEqual(ctx.security?.authorization.roles, [
    "internal/role/openidm-admin",
  ]);
});

test("callContext omits security when unauthenticated", () => {
  const ctx = callContext({ unauthenticated: true });
  assert.equal(Object.prototype.hasOwnProperty.call(ctx, "security"), false);
});

test("callContext throws if unauthenticated is forced with a subject", () => {
  assert.throws(
    () =>
      callContext({
        unauthenticated: true,
        subject: "ada",
      } as ContextOptions),
    /unauthenticated cannot be combined/
  );
  assert.throws(
    () =>
      callContext({
        unauthenticated: true,
        roles: ["internal/role/openidm-authorized"],
      } as ContextOptions),
    /unauthenticated cannot be combined/
  );
  assert.throws(
    () =>
      callContext({
        unauthenticated: true,
        component: "managed/alpha_user",
      } as ContextOptions),
    /unauthenticated cannot be combined/
  );
});

// `tests/**/*.test.mjs` callers get no type checking at all, so a truthy
// non-boolean would otherwise select the authenticated branch in silence.
test("callContext refuses a non-boolean unauthenticated flag", () => {
  for (const flag of [1, "yes", {}]) {
    assert.throws(
      () => callContext({ unauthenticated: flag } as unknown as ContextOptions),
      /unauthenticated must be a boolean/
    );
  }
  // `false` is the authenticated arm's own default, so it must still pass.
  assert.equal(
    callContext({ unauthenticated: false }).security?.authorization.id,
    "svc-account"
  );
});

/** Never called. Present so `tsc` checks the incoherent combinations. */
export function contextOptionTypes(): void {
  callContext({ subject: "ada" });
  callContext({ roles: ["internal/role/openidm-admin"] });
  callContext({ unauthenticated: true });
  // @ts-expect-error subject cannot combine with unauthenticated
  callContext({ unauthenticated: true, subject: "ada" });
  // @ts-expect-error roles cannot combine with unauthenticated
  callContext({ unauthenticated: true, roles: ["x"] });
  // @ts-expect-error component cannot combine with unauthenticated
  callContext({ unauthenticated: true, component: "managed/alpha_user" });
}
