// Test doubles for the IDM bindings.
//
// Managed file — regenerated by `aic workspace update`.

import { createHmac } from "node:crypto";

import type {
  CrestErrorResponse,
  CrestRequest,
  IdmCallContext,
  IdmLogger,
  JavaSet,
  PatchOperation,
} from "../framework/index.ts";

/** Capture the caller-facing object an endpoint dispatch throws to IDM. */
export function crestErrorFrom(run: () => unknown): CrestErrorResponse {
  try {
    run();
  } catch (thrown) {
    const value = thrown as Record<string, unknown> | null;
    if (typeof value === "object" && value !== null &&
        typeof value["code"] === "number" && typeof value["message"] === "string") {
      return thrown as CrestErrorResponse;
    }
    throw new Error("expected a CREST error response, got " + String(thrown));
  }
  throw new Error("expected a throw");
}

/** A `java.util.Set` stand-in: membership is `.contains`, never `.includes`. */
export function javaSet(values: string[]): JavaSet<string> {
  return {
    contains: (value) => values.indexOf(value) >= 0,
    size: () => values.length,
    isEmpty: () => values.length === 0,
  };
}

export interface CapturedLine {
  level: "trace" | "debug" | "info" | "warn" | "error";
  message: string;
}

export interface RecordingLogger extends IdmLogger {
  lines: CapturedLine[];
}

export function recordingLogger(): RecordingLogger {
  const lines: CapturedLine[] = [];
  const push =
    (level: CapturedLine["level"]) =>
    (message: string): void => {
      lines.push({ level, message });
    };
  return {
    lines,
    trace: push("trace"),
    debug: push("debug"),
    info: push("info"),
    warn: push("warn"),
    error: push("error"),
  };
}

export interface RequestOptions {
  resourcePath?: string;
  query?: Record<string, string>;
  fields?: string[];
  content?: unknown;
  action?: string;
  patchOperations?: PatchOperation[];
  /** Client-supplied id — what a bare `PUT .../{id}` delivers. */
  newResourceId?: string;
}

/** Build a `request` binding for one CREST method. */
export function crestRequest(
  method: CrestRequest["method"],
  options: RequestOptions = {}
): CrestRequest {
  const base = {
    resourcePath: options.resourcePath ?? "",
    additionalParameters: options.query ?? {},
    fields: options.fields ?? [],
  };
  switch (method) {
    case "read":
      return { ...base, method: "read" };
    case "delete":
      return { ...base, method: "delete", revision: null };
    case "create":
      return {
        ...base,
        method: "create",
        newResourceId: options.newResourceId ?? null,
        content: options.content,
      };
    case "update":
      return {
        ...base,
        method: "update",
        revision: null,
        content: options.content,
      };
    case "action":
      return {
        ...base,
        method: "action",
        action: options.action ?? "",
        content: options.content,
      };
    case "patch":
      return {
        ...base,
        method: "patch",
        revision: null,
        patchOperations: options.patchOperations ?? [],
      };
    case "query":
      return {
        ...base,
        method: "query",
        queryFilter: "true",
        queryId: null,
        queryExpression: null,
        pageSize: 0,
        pagedResultsOffset: 0,
        pagedResultsCookie: null,
        sortKeys: [],
      };
  }
}

interface ContextOptionsBase {
  headers?: Record<string, string>;
  scopes?: string[];
  /** Omit the HTTP context entirely — a scheduled/internal caller. */
  internal?: boolean;
}

/**
 * A caller identity for {@link callContext}.
 *
 * `unauthenticated: true` omits `security` entirely. That flag is a
 * discriminant: combining it with `subject`, `roles` or `component` is a type
 * error, and `callContext` also throws if a cast smuggles the combination
 * through.
 *
 * UNVERIFIED SHAPE. What an anonymous IDM caller actually carries has never
 * been probed against a tenant — `docs/api/11-idm-endpoints.md` records the
 * anonymous path as not re-exercised — and IDM has historically sent an
 * anonymous `security` block rather than none at all. So this flag models
 * "absent `security`", which is one of two candidates. Do not trust a handler's
 * `security === undefined` branch on the strength of a green test here.
 */
export type ContextOptions =
  | (ContextOptionsBase & {
      /** `security.authorization.id` and `authenticationId`. */
      subject?: string;
      /** `security.authorization.roles`. */
      roles?: string[];
      /**
       * `security.authorization.component`. Defaults to the collection the
       * subject names, so a handler that discriminates a service account from
       * an end user can be driven both ways.
       */
      component?: string;
      unauthenticated?: false;
    })
  | (ContextOptionsBase & {
      /** Omit `security` — the unauthenticated path. */
      unauthenticated: true;
    });

/**
 * The `component` a subject implies.
 *
 * A subject that names a resource path belongs to that collection, so pinning
 * every caller to the service account's component would hand a handler a
 * pairing the tenant never sends (`managed/alpha_user/ada` under
 * `managed/svcacct`). Anything without a path keeps the observed service-account
 * value — see `docs/api/11-idm-endpoints.md`.
 */
function componentOf(subject: string): string {
  const cut = subject.lastIndexOf("/");
  return cut > 0 ? subject.slice(0, cut) : "managed/svcacct";
}

export function callContext(options: ContextOptions = {}): IdmCallContext {
  // Read through a widened view. The discriminant keeps `subject`/`roles` off
  // one arm's type, and `tests/**/*.test.mjs` callers are untyped altogether —
  // so the runtime checks below are load-bearing, not belt-and-braces.
  const raw = options as ContextOptionsBase & {
    subject?: string;
    roles?: string[];
    component?: string;
    unauthenticated?: unknown;
  };
  if (
    raw.unauthenticated !== undefined &&
    typeof raw.unauthenticated !== "boolean"
  ) {
    // A truthy non-boolean would otherwise fall through to the authenticated
    // branch and silently test the opposite path.
    throw new Error("callContext: unauthenticated must be a boolean");
  }
  const unauthenticated = raw.unauthenticated === true;
  if (
    unauthenticated &&
    (raw.subject !== undefined ||
      raw.roles !== undefined ||
      raw.component !== undefined)
  ) {
    throw new Error(
      "callContext: unauthenticated cannot be combined with subject, roles or component"
    );
  }
  const context: IdmCallContext = {};
  if (!unauthenticated) {
    const subject = raw.subject ?? "svc-account";
    const roles = raw.roles ?? ["internal/role/openidm-authorized"];
    context.security = {
      authenticationId: subject,
      authorization: {
        id: subject,
        component: raw.component ?? componentOf(subject),
        roles,
      },
    };
  }
  if (raw.internal !== true) {
    context.http = {
      method: "GET",
      path: "/openidm/endpoint/demo",
      headers: raw.headers ?? {},
      parameters: {},
    };
  }
  if (raw.scopes !== undefined) {
    context.oauth2 = { scopes: javaSet(raw.scopes) };
  }
  return context;
}

type StoredValue = Record<string, unknown> & { _id: string; _rev: string };

/** Everything the double cannot model throws this, so it is never mistaken
 * for a fault the tenant would raise. */
function unsupported(what: string): never {
  throw new Error("managedStore: " + what);
}

/**
 * Apply a `fields` selector the way the tenant does: only the named members
 * come back, and `_id`/`_rev` come back whatever you asked for (verified
 * 2026-08-17, docs/api/10-managed-objects.md).
 */
function projectRecord(
  record: StoredValue,
  fields: readonly string[] | null | undefined
): StoredValue {
  if (fields === null || fields === undefined || fields.indexOf("*") >= 0) {
    return { ...record };
  }
  const out: StoredValue = { _id: record._id, _rev: record._rev };
  for (const field of fields) {
    if (field.indexOf("/") >= 0) {
      // A relationship path (`manager/userName`) makes the tenant return the
      // EXPANSION, and the double holds no relationship graph to expand.
      unsupported(
        "cannot expand the relationship path " +
          field +
          " — give the handler its own double for that read"
      );
    }
    if (Object.prototype.hasOwnProperty.call(record, field)) {
      out[field] = record[field];
    }
  }
  return out;
}

/** `true`, or a single `field eq "value"` term — anything else is refused. */
function matchesFilter(record: StoredValue, filter: unknown): boolean {
  if (filter === undefined || filter === null || filter === "true") {
    return true;
  }
  if (typeof filter !== "string") {
    unsupported("_queryFilter must be a string");
  }
  const term = /^\/?([A-Za-z_][A-Za-z0-9_]*) eq "([^"]*)"$/.exec(filter.trim());
  if (term === null) {
    unsupported(
      'only _queryFilter: true and a single `field eq "value"` term are ' +
        "modelled, not " +
        filter
    );
  }
  return record[term[1] as string] === term[2];
}

/**
 * An in-memory `openidm` binding for endpoint tests.
 *
 * Keys are managed collection paths and values are their records. The double
 * implements the common CRUD/query behavior; tests needing a special action
 * can override that member on the returned object.
 *
 * IT REFUSES WHAT IT CANNOT MODEL, and that is the point. A double more
 * permissive than the tenant turns a live 500 into a green test: this one
 * previously ignored the `fields` selector and the `_queryFilter` outright, so
 * a projection bug and an unfiltered query both passed. Anything unmodelled now
 * throws a `managedStore:` error naming what to do instead.
 *
 * Not modelled, on purpose: relationship expansion, paging, sort keys, patch
 * and action. `openidm.update`/`delete` against a missing id throw here because
 * IDM's own behaviour for that miss is NOT verified (docs/api/10 records the
 * `read` miss and the `create` conflict only) — inventing a shape would be
 * worse than refusing.
 */
export function managedStore(
  initial: Record<string, StoredValue[]>
): typeof openidm {
  const collections: Record<string, StoredValue[]> = {};
  for (const path of Object.keys(initial)) {
    collections[path] = initial[path]?.map((record) => ({ ...record })) ?? [];
  }
  const splitRecordPath = (path: string): [string, string] => {
    const slash = path.lastIndexOf("/");
    return [path.slice(0, slash), path.slice(slash + 1)];
  };
  const binding = {
    read(
      path: string,
      _params?: unknown,
      fields?: readonly string[] | null
    ): StoredValue | null {
      const [collection, id] = splitRecordPath(path);
      const found = collections[collection]?.find(
        (record) => record._id === id
      );
      // A miss is `null`, never a throw (verified 2026-07-17 and 2026-08-17).
      // The copy matters: handing out the stored object let a handler mutate
      // the store through its own result.
      return found === undefined ? null : projectRecord(found, fields);
    },
    query(
      path: string,
      params?: Record<string, unknown> | null,
      fields?: readonly string[] | null
    ) {
      if (params !== undefined && params !== null) {
        for (const key of Object.keys(params)) {
          if (key !== "_queryFilter") {
            unsupported(
              "query parameter " + key + " is not modelled (only _queryFilter)"
            );
          }
        }
      }
      const filter = params === undefined || params === null
        ? undefined
        : params["_queryFilter"];
      const result = (collections[path] ?? [])
        .filter((record) => matchesFilter(record, filter))
        .map((record) => projectRecord(record, fields));
      return {
        result,
        resultCount: result.length,
        pagedResultsCookie: null,
        totalPagedResults: result.length,
        totalPagedResultsPolicy: "EXACT",
      };
    },
    create(
      path: string,
      newResourceId: string | null,
      content: Record<string, unknown>
    ) {
      const rows = (collections[path] ??= []);
      const id = newResourceId ?? "test-" + (rows.length + 1);
      if (rows.some((record) => record._id === id)) {
        // Verified: `openidm.create` NEVER upserts — it throws
        // PreconditionFailedException (docs/api/10-managed-objects.md).
        unsupported("create conflicts with the existing record " + path + "/" + id);
      }
      const created: StoredValue = { ...content, _id: id, _rev: "1" };
      rows.push(created);
      return { ...created };
    },
    update(
      path: string,
      _revision: string | null,
      content: Record<string, unknown>
    ) {
      const [collection, id] = splitRecordPath(path);
      const rows = (collections[collection] ??= []);
      const index = rows.findIndex((record) => record._id === id);
      const existing = rows[index];
      if (index < 0 || existing === undefined) {
        unsupported("update of a record that does not exist: " + path);
      }
      // Fixtures usually carry a numeric-looking `_rev`; a real IDM revision is
      // opaque, so fall back rather than producing `NaN`.
      const revision = Number(existing._rev);
      const updated: StoredValue = {
        ...existing,
        ...content,
        _id: id,
        _rev: String((Number.isFinite(revision) ? revision : 0) + 1),
      };
      rows[index] = updated;
      return { ...updated };
    },
    patch() {
      return unsupported("patch is not modelled");
    },
    delete(path: string) {
      const [collection, id] = splitRecordPath(path);
      const rows = collections[collection] ?? [];
      const index = rows.findIndex((record) => record._id === id);
      if (index < 0) {
        unsupported("delete of a record that does not exist: " + path);
      }
      return rows.splice(index, 1)[0] as StoredValue;
    },
    action() {
      return unsupported("action is not modelled");
    },
  };
  return binding as unknown as typeof openidm;
}

/** Install an `openidm` test binding for exactly one synchronous callback. */
export function withOpenIdm<T>(binding: typeof openidm, run: () => T): T {
  const globals = globalThis as unknown as Record<string, unknown>;
  const hadPrevious = Object.prototype.hasOwnProperty.call(globals, "openidm");
  const previous = globals["openidm"];
  globals["openidm"] = binding;
  try {
    return run();
  } finally {
    if (hadPrevious) {
      globals["openidm"] = previous;
    } else {
      delete globals["openidm"];
    }
  }
}

/**
 * An in-memory `identityServer` binding for endpoint tests.
 *
 * `getProperty(name)` returns the mapped string, or `defaultValue` when the
 * name is absent, or `null` when neither is present (verified 2026-07-22,
 * docs/api/12-script-bindings-matrix.md). Asking for substitution
 * (`substitute: true`) is not modelled — its effect has not been verified — and
 * throws rather than being ignored. `substitute: false` is the behaviour above,
 * so it passes: refusing it would make a handler that declines substitution
 * explicitly impossible to dispatch at all.
 */
function identityServerBinding(
  properties: Record<string, string>
): typeof identityServer {
  return {
    getProperty(
      name: string,
      defaultValue?: string,
      substitute?: boolean
    ): string | null {
      if (substitute === true) {
        throw new Error(
          "identityServer: getProperty substitution is not modelled"
        );
      }
      if (Object.prototype.hasOwnProperty.call(properties, name)) {
        const value = properties[name];
        return value === undefined ? null : value;
      }
      if (defaultValue !== undefined) {
        return defaultValue;
      }
      return null;
    },
  };
}

/** Install an `identityServer` test binding for exactly one synchronous callback. */
export function withIdentityServer<T>(
  properties: Record<string, string>,
  run: () => T
): T {
  const globals = globalThis as unknown as Record<string, unknown>;
  const hadPrevious = Object.prototype.hasOwnProperty.call(
    globals,
    "identityServer"
  );
  const previous = globals["identityServer"];
  globals["identityServer"] = identityServerBinding(properties);
  try {
    return run();
  } finally {
    if (hadPrevious) {
      globals["identityServer"] = previous;
    } else {
      delete globals["identityServer"];
    }
  }
}

/** Everything the Java double cannot model throws this, so it is never
 * mistaken for a tenant exception. */
function javaUnsupported(what: string): never {
  throw new Error("java: " + what);
}

function toSignedByte(value: number): number {
  const unsigned = value & 0xff;
  return unsigned > 127 ? unsigned - 256 : unsigned;
}

function signedUtf8Bytes(value: string): number[] {
  const encoded = Buffer.from(value, "utf8");
  const out: number[] = [];
  for (let i = 0; i < encoded.length; i += 1) {
    const byte = encoded[i];
    if (byte === undefined) {
      continue;
    }
    out.push(toSignedByte(byte));
  }
  return out;
}

function unsignedBits(bytes: ArrayLike<number>): Buffer {
  const out = Buffer.alloc(bytes.length);
  for (let i = 0; i < bytes.length; i += 1) {
    const value = bytes[i];
    out[i] = value === undefined ? 0 : value & 0xff;
  }
  return out;
}

function isUtf8Charset(charset: unknown): boolean {
  if (typeof charset !== "string") {
    return false;
  }
  const folded = charset.toLowerCase();
  return folded === "utf-8" || folded === "utf8";
}

function isByteArray(value: unknown): value is ArrayLike<number> {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as ArrayLike<number>).length === "number"
  );
}

function isModelledMember(target: object, prop: string): boolean {
  if (Object.prototype.hasOwnProperty.call(target, prop)) {
    return true;
  }
  let proto: object | null = Object.getPrototypeOf(target) as object | null;
  while (
    proto !== null &&
    proto !== Object.prototype &&
    proto !== Function.prototype
  ) {
    if (Object.prototype.hasOwnProperty.call(proto, prop)) {
      return true;
    }
    proto = Object.getPrototypeOf(proto) as object | null;
  }
  return false;
}

/**
 * Proxy a modelled Java value so an unmodelled member throws on access
 * rather than returning `undefined`. The message names the double's gap,
 * not a missing engine member.
 */
function modelled<T extends object>(label: string, value: T): T {
  const handlers: ProxyHandler<object> = {
    get(target, prop, receiver) {
      // `Reflect.get` is typed `any`, which would flow untyped into every
      // caller of the double. Narrow it at the boundary.
      if (typeof prop !== "string") {
        return Reflect.get(target, prop, receiver) as unknown;
      }
      if (isModelledMember(target, prop)) {
        return Reflect.get(target, prop, receiver) as unknown;
      }
      return javaUnsupported(
        "this test double does not model " + label + "." + prop
      );
    },
  };
  if (typeof value === "function") {
    handlers.construct = (target, args) => {
      const instance = Reflect.construct(
        target as new (...ctorArgs: unknown[]) => object,
        args
      );
      if (typeof instance === "object" && instance !== null) {
        return modelled(label, instance);
      }
      return instance;
    };
  }
  return new Proxy(value, handlers) as T;
}

const NFC = { name: "NFC" };
const NFD = { name: "NFD" };
const NFKC = { name: "NFKC" };
const NFKD = { name: "NFKD" };

function formName(form: unknown): "NFC" | "NFD" | "NFKC" | "NFKD" {
  if (form === NFC) {
    return "NFC";
  }
  if (form === NFD) {
    return "NFD";
  }
  if (form === NFKC) {
    return "NFKC";
  }
  if (form === NFKD) {
    return "NFKD";
  }
  return javaUnsupported("Normalizer.Form is not a modelled form");
}

class JavaLangStringValue {
  readonly _value: string;
  constructor(value: unknown) {
    if (typeof value !== "string") {
      javaUnsupported(
        "java.lang.String constructor is only modelled for a JS string"
      );
    }
    this._value = value;
  }
  toString(): string {
    return this._value;
  }
  getBytes(charset?: unknown): number[] {
    if (charset === undefined) {
      javaUnsupported(
        'java.lang.String.getBytes() with no charset works on the engine (platform default); this test double does not model it — pass "UTF-8"'
      );
    }
    if (!isUtf8Charset(charset)) {
      javaUnsupported(
        'java.lang.String.getBytes is only modelled for "UTF-8", not ' +
          String(charset)
      );
    }
    return signedUtf8Bytes(this._value);
  }
}

class SecretKeySpecValue {
  readonly __aicSecretKeySpec = true;
  readonly _bytes: number[];
  constructor(key: unknown, algorithm: unknown) {
    if (!isByteArray(key)) {
      javaUnsupported("SecretKeySpec is only modelled for a byte array key");
    }
    if (typeof algorithm !== "string") {
      javaUnsupported("SecretKeySpec algorithm must be a string");
    }
    this._bytes = [];
    for (let i = 0; i < key.length; i += 1) {
      const value = key[i];
      this._bytes.push(toSignedByte(value === undefined ? 0 : value));
    }
  }
}

function isSecretKeySpec(value: unknown): value is SecretKeySpecValue {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as SecretKeySpecValue).__aicSecretKeySpec === true
  );
}

function nodeHmacAlgorithm(algorithm: unknown): string {
  if (algorithm === "HmacSHA256") {
    return "sha256";
  }
  if (algorithm === "HmacSHA1") {
    return "sha1";
  }
  if (algorithm === "HmacSHA512") {
    return "sha512";
  }
  return javaUnsupported(
    "Mac.getInstance is only modelled for HmacSHA1, HmacSHA256 and HmacSHA512, not " +
      String(algorithm)
  );
}

class MacInstance {
  readonly _algorithm: string;
  _key: number[] | null;
  constructor(algorithm: string) {
    this._algorithm = algorithm;
    this._key = null;
  }
  init(key: unknown): void {
    if (!isSecretKeySpec(key)) {
      javaUnsupported("Mac.init is only modelled for a SecretKeySpec");
    }
    this._key = key._bytes.slice();
  }
  doFinal(input?: unknown): number[] {
    if (this._key === null) {
      javaUnsupported("Mac.doFinal called before init");
    }
    if (input === undefined) {
      javaUnsupported(
        "Mac.doFinal() with no bytes is not modelled — pass the message bytes"
      );
    }
    if (!isByteArray(input)) {
      javaUnsupported("Mac.doFinal is only modelled for a byte array");
    }
    const digest = createHmac(this._algorithm, unsignedBits(this._key))
      .update(unsignedBits(input))
      .digest();
    const out: number[] = [];
    for (let i = 0; i < digest.length; i += 1) {
      const byte = digest[i];
      if (byte === undefined) {
        continue;
      }
      out.push(toSignedByte(byte));
    }
    return out;
  }
  update(): never {
    return javaUnsupported(
      "Mac.update is not modelled — pass the whole message to doFinal"
    );
  }
}

/**
 * An in-memory `java` / `javax` binding for endpoint tests.
 *
 * HMAC is `node:crypto`; normalisation is `String.prototype.normalize`.
 * `doFinal` and `getBytes` hand back **signed** bytes (`-128..127`), the
 * way Rhino surfaces a Java `byte[]` — a double that coerced them unsigned
 * would hide the `& 0xff` bug this surface exists to catch.
 *
 * Observed on the sandbox tenant 2026-08-18 (throwaway endpoint, then
 * deleted): signed `doFinal` bytes, `Normalizer.normalize` returning a
 * `java.lang.String` that is not `===` a JS string, and `openidm.hash`
 * salting per call. The double reproduces the signed-byte and identity
 * traps so a forgotten mask or `String(...)` fails here the same way it
 * would on the tenant. Do not copy this into a `## Verified against`
 * block under `docs/api/`.
 *
 * Anything this double does not model throws a `java:` error naming the
 * gap — including unmodelled members on a leaf (`Normalizer`, a `Mac`
 * instance, `SecretKeySpec`, a `java.lang.String`). That is a statement
 * about the double, not about the engine.
 */
function javaBinding(): { java: typeof java; javax: typeof javax } {
  const binding = {
    java: modelled("java", {
      lang: modelled("java.lang", {
        String: modelled("java.lang.String", JavaLangStringValue),
      }),
      text: modelled("java.text", {
        Normalizer: modelled("java.text.Normalizer", {
          normalize(src: unknown, form: unknown): JavaLangStringValue {
            if (
              typeof src !== "string" &&
              !(src instanceof JavaLangStringValue)
            ) {
              javaUnsupported(
                "Normalizer.normalize is only modelled for a string"
              );
            }
            const js = typeof src === "string" ? src : src._value;
            return modelled(
              "java.lang.String",
              new JavaLangStringValue(js.normalize(formName(form)))
            );
          },
          Form: modelled("java.text.Normalizer.Form", {
            NFC,
            NFD,
            NFKC,
            NFKD,
          }),
        }),
      }),
    }),
    javax: modelled("javax", {
      crypto: modelled("javax.crypto", {
        Mac: modelled("javax.crypto.Mac", {
          getInstance(algorithm: unknown): MacInstance {
            return modelled(
              "javax.crypto.Mac",
              new MacInstance(nodeHmacAlgorithm(algorithm))
            );
          },
        }),
        spec: modelled("javax.crypto.spec", {
          SecretKeySpec: modelled(
            "javax.crypto.spec.SecretKeySpec",
            SecretKeySpecValue
          ),
        }),
      }),
    }),
  };
  return binding as unknown as { java: typeof java; javax: typeof javax };
}

/** Install `java` / `javax` test bindings for exactly one synchronous callback. */
export function withJava<T>(run: () => T): T {
  const globals = globalThis as unknown as Record<string, unknown>;
  const hadJava = Object.prototype.hasOwnProperty.call(globals, "java");
  const hadJavax = Object.prototype.hasOwnProperty.call(globals, "javax");
  const previousJava = globals["java"];
  const previousJavax = globals["javax"];
  const binding = javaBinding();
  globals["java"] = binding.java;
  globals["javax"] = binding.javax;
  try {
    return run();
  } finally {
    if (hadJava) {
      globals["java"] = previousJava;
    } else {
      delete globals["java"];
    }
    if (hadJavax) {
      globals["javax"] = previousJavax;
    } else {
      delete globals["javax"];
    }
  }
}
