// Test doubles for the IDM bindings.
//
// Managed file — regenerated by `aic workspace update`.

import type {
  CrestRequest,
  IdmCallContext,
  IdmLogger,
  JavaSet,
  PatchOperation,
} from "../framework/index.ts";

/** A `java.util.Set` stand-in: membership is `.contains`, never `.includes`. */
export function javaSet(values: string[]): JavaSet<string> {
  return {
    contains: (value) => values.indexOf(value) >= 0,
    size: () => values.length,
    isEmpty: () => values.length === 0,
  };
}

export interface CapturedLine {
  level: "trace" | "debug" | "info" | "warn" | "error";
  message: string;
}

export interface RecordingLogger extends IdmLogger {
  lines: CapturedLine[];
}

export function recordingLogger(): RecordingLogger {
  const lines: CapturedLine[] = [];
  const push =
    (level: CapturedLine["level"]) =>
    (message: string): void => {
      lines.push({ level, message });
    };
  return {
    lines,
    trace: push("trace"),
    debug: push("debug"),
    info: push("info"),
    warn: push("warn"),
    error: push("error"),
  };
}

export interface RequestOptions {
  resourcePath?: string;
  query?: Record<string, string>;
  fields?: string[];
  content?: unknown;
  action?: string;
  patchOperations?: PatchOperation[];
  /** Client-supplied id — what a bare `PUT .../{id}` delivers. */
  newResourceId?: string;
}

/** Build a `request` binding for one CREST method. */
export function crestRequest(
  method: CrestRequest["method"],
  options: RequestOptions = {}
): CrestRequest {
  const base = {
    resourcePath: options.resourcePath ?? "",
    additionalParameters: options.query ?? {},
    fields: options.fields ?? [],
  };
  switch (method) {
    case "read":
      return { ...base, method: "read" };
    case "delete":
      return { ...base, method: "delete", revision: null };
    case "create":
      return {
        ...base,
        method: "create",
        newResourceId: options.newResourceId ?? null,
        content: options.content,
      };
    case "update":
      return {
        ...base,
        method: "update",
        revision: null,
        content: options.content,
      };
    case "action":
      return {
        ...base,
        method: "action",
        action: options.action ?? "",
        content: options.content,
      };
    case "patch":
      return {
        ...base,
        method: "patch",
        revision: null,
        patchOperations: options.patchOperations ?? [],
      };
    case "query":
      return {
        ...base,
        method: "query",
        queryFilter: "true",
        queryId: null,
        queryExpression: null,
        pageSize: 0,
        pagedResultsOffset: 0,
        pagedResultsCookie: null,
        sortKeys: [],
      };
  }
}

export interface ContextOptions {
  headers?: Record<string, string>;
  scopes?: string[];
  /** Omit the HTTP context entirely — a scheduled/internal caller. */
  internal?: boolean;
}

export function callContext(options: ContextOptions = {}): IdmCallContext {
  const context: IdmCallContext = {
    security: {
      authenticationId: "svc-account",
      authorization: {
        id: "svc-account",
        component: "managed/svcacct",
        roles: ["internal/role/openidm-authorized"],
      },
    },
  };
  if (options.internal !== true) {
    context.http = {
      method: "GET",
      path: "/openidm/endpoint/demo",
      headers: options.headers ?? {},
      parameters: {},
    };
  }
  if (options.scopes !== undefined) {
    context.oauth2 = { scopes: javaSet(options.scopes) };
  }
  return context;
}
