// Java helpers and the `withJava` double's behavioural gate.
//
// The HMAC vector is a published one, not a round trip through the same
// code. `bytesToHex` is pinned against both a signed array and its unsigned
// equivalent — the unmasked rendering of the signed values is what
// documents why the helper exists. The `@ts-expect-error` markers are the
// type-level half: `tsc` fails if a rejection stops being a rejection
// (an unused directive is itself an error).
//
// Observed on the sandbox tenant 2026-08-18 (throwaway endpoint, then
// deleted): signed `doFinal` bytes, Java-string identity, `openidm.hash`
// salting per call. Do not copy this into a `## Verified against` block
// under `docs/api/`.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  bytesToHex,
  nfc,
  normalize,
  type JavaBytes,
  type JavaLangString,
} from "../framework/index.ts";
import { withJava } from "./harness.ts";

// HMAC-SHA256("key", "The quick brown fox jumps over the lazy dog")
// — a published vector, not computed from the double under test.
const FOX = "The quick brown fox jumps over the lazy dog";
const FOX_HMAC_SHA256 =
  "f7bc83f430538424b13298e6aa6fb143ef4d59a14946175997479dbc2d1a3cd8";

test("HMAC-SHA256 over a known key/message is the published digest", () => {
  withJava(() => {
    const mac = javax.crypto.Mac.getInstance("HmacSHA256");
    mac.init(
      new javax.crypto.spec.SecretKeySpec(
        new java.lang.String("key").getBytes("UTF-8"),
        "HmacSHA256"
      )
    );
    const digest = mac.doFinal(new java.lang.String(FOX).getBytes("UTF-8"));
    assert.equal(bytesToHex(digest), FOX_HMAC_SHA256);
  });
});

test("doFinal hands back signed bytes, the way Rhino surfaces byte[]", () => {
  withJava(() => {
    const mac = javax.crypto.Mac.getInstance("HmacSHA256");
    mac.init(
      new javax.crypto.spec.SecretKeySpec(
        new java.lang.String("key").getBytes("UTF-8"),
        "HmacSHA256"
      )
    );
    const digest = mac.doFinal(new java.lang.String(FOX).getBytes("UTF-8"));
    // First byte of the vector is 0xf7 = 247 unsigned = -9 signed.
    assert.equal(digest[0], -9);
    assert.ok((digest[0] as number) < 0);
  });
});

function unmaskedHex(bytes: ArrayLike<number>): string {
  let hex = "";
  for (let i = 0; i < bytes.length; i += 1) {
    const value = bytes[i];
    if (value === undefined) {
      continue;
    }
    hex += value.toString(16);
  }
  return hex;
}

test("bytesToHex masks signed bytes; an unmasked rendering differs", () => {
  const signed = [-1, 0, 15, 127, -128];
  const unsigned = [255, 0, 15, 127, 128];
  assert.equal(bytesToHex(signed), "ff000f7f80");
  assert.equal(bytesToHex(unsigned), bytesToHex(signed));
  assert.notEqual(unmaskedHex(signed), bytesToHex(signed));
  assert.equal(unmaskedHex(signed), "-10f7f-80");
});

test("NFC makes a decomposed and a precomposed form compare equal", () => {
  withJava(() => {
    const decomposed = "e\u0301";
    const precomposed = "\u00e9";
    assert.notEqual(decomposed, precomposed);
    assert.equal(nfc(decomposed), nfc(precomposed));
    assert.equal(nfc(decomposed), precomposed);
    assert.equal(
      normalize(decomposed, java.text.Normalizer.Form.NFC),
      nfc(decomposed)
    );
  });
});

test("a Java string prints like a JS string but is not === one", () => {
  withJava(() => {
    const javaStr = java.text.Normalizer.normalize(
      "café",
      java.text.Normalizer.Form.NFC
    );
    assert.equal(typeof javaStr, "object");
    assert.equal(String(javaStr), "café");
    // The brand already rejects `javaStr === "café"` as having no overlap;
    // this pins the double so it cannot start returning a real JS string.
    assert.notStrictEqual(javaStr as unknown, "café");
    assert.equal(String(javaStr).toLowerCase(), "café");
    assert.equal(nfc("e\u0301").toLowerCase(), "\u00e9");
  });
});

/** Never called. Present so `tsc` checks every line in it. */
export function typeTours(): void {
  const javaStr: JavaLangString = java.text.Normalizer.normalize(
    "e\u0301",
    java.text.Normalizer.Form.NFC
  );
  // Our surface omits JS string methods so String(...) is the way out.
  // The engine does expose them; the live trap is identity, not absence.
  // @ts-expect-error a Java string is not a JS string — String(...) or nfc()
  javaStr.toLowerCase(); // eslint-disable-line @typescript-eslint/no-unsafe-call -- the expected error makes this error-typed
  // @ts-expect-error not assignable to string
  const _asString: string = javaStr;
  void _asString;
  // The live trap: not `===` a JS string, even when String(...) of it is.
  // @ts-expect-error a Java string and a JS string have no overlap
  const _same = javaStr === "é";
  void _same;
  const js = String(javaStr);
  const _lower: string = js.toLowerCase();
  void _lower;

  const digested: JavaBytes = javax.crypto.Mac.getInstance(
    "HmacSHA256"
  ).doFinal(new java.lang.String("x").getBytes("UTF-8"));
  const _hex: string = bytesToHex(digested);
  void _hex;
  // Arithmetic on a byte stays a number; if that ever hurts, this fails.
  const _masked: number = digested[0]! & 0xff;
  const _signed: boolean = digested[0]! < 0;
  const _asNumber: number = digested[0]!;
  void _masked;
  void _signed;
  void _asNumber;
  // @ts-expect-error JavaByte.toString is never — bytesToHex is the hex path
  const _unmasked = digested[0]!.toString(16); // eslint-disable-line @typescript-eslint/no-unsafe-assignment -- the expected error makes this error-typed
  void _unmasked;
  const unsigned: number[] = [255];
  // @ts-expect-error a number[] is not a Java byte[] — doFinal returns JavaBytes
  const _needBytes: JavaBytes = unsigned;
  void _needBytes;
  // @ts-expect-error a Java byte[] is not a number[]
  const _needNums: number[] = digested;
  void _needNums;

  const encoded = new java.lang.String("abc").getBytes("UTF-8");
  void encoded;
  // Policy: no-arg getBytes is a platform-charset dependency; we refuse it.
  // The engine accepts it.
  // @ts-expect-error getBytes requires "UTF-8" — the no-arg form is omitted
  new java.lang.String("abc").getBytes();
}

test("the java type tours are declared but never executed", () => {
  assert.equal(typeof typeTours, "function");
});
