// Type-level tests for the `openidm` signatures.
//
// The assertions here are `@ts-expect-error` markers, so `tsc` fails if a line
// that MUST be rejected starts compiling — the only way to gate a type in both
// directions. `npm run type-check` is the real gate; the single runtime test at
// the bottom exists so `node --test` reports the file rather than skipping it.
//
// HERMETIC BY DESIGN. This file declares its OWN managed object rather than
// importing one from `src/generated/managed.ts`: that module is written from a
// live tenant and is absent whenever `aic workspace init` ran without a reachable
// agent, which used to leave the framework's own gate red in a workspace whose
// framework was fine. A fixture also lets the test pin one relationship of each
// cardinality, which no particular tenant is obliged to have.
//
// Nothing here runs against a tenant: `typeTours` is never called, and `openidm`
// does not exist under node. Behaviour these types encode is verified live in
// docs/api/10-managed-objects.md.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import type { CrestQueryResult } from "../framework/index.ts";

/** A relationship reference, shaped as `managed_types.rs` generates one. */
interface ProbeRef {
  _ref: string;
  _refResourceCollection?: string;
  _refResourceId?: string;
}

/**
 * Stands in for a tenant's managed object. `_id`/`_rev` are optional exactly as
 * the generated interfaces leave them — the same interface types an onCreate
 * draft, which has neither yet — so this also checks that {@link StoredRecord}
 * is what puts them back.
 */
interface TypesFixture {
  _id?: string;
  _rev?: string;
  userName: string;
  sn: string;
  mail: string;
  /** Optional in the schema, so a projection returns it as `string | null`. */
  telephoneNumber?: string;
  /** Single-valued: unset comes back as `null`. */
  manager?: ProbeRef;
  /** Multi-valued: unset comes back as `[]`. */
  authzRoles?: ProbeRef[];
}

declare global {
  interface ManagedObjects {
    // Deliberately un-tenant-like, so it cannot collide with a real object and
    // trip declaration merging.
    "managed/__aic_types_fixture": TypesFixture;
  }
}

const FIXTURE = "managed/__aic_types_fixture";

declare const id: string;

/** Never called. Present so `tsc` checks every line in it. */
export function typeTours(): void {
  // --- a plain read is the whole record, with _id/_rev guaranteed -----------
  const whole = openidm.read(`${FIXTURE}/${id}`);
  if (whole !== null) {
    const _id: string = whole._id;
    const _userName: string = whole.userName;
    void _id;
    void _userName;
    // @ts-expect-error not a property of the fixture schema
    void whole.nosuchField;
  }

  // --- a field-restricted read is projected to what was asked for ----------
  const projected = openidm.read(`${FIXTURE}/${id}`, null, ["userName", "mail"]);
  if (projected !== null) {
    // `_id`/`_rev` survive a projection: they come back whatever you ask for.
    const _id: string = projected._id;
    const _rev: string = projected._rev;
    const _mail: string = projected.mail;
    void _id;
    void _rev;
    void _mail;
    // @ts-expect-error `sn` was not in the field list
    void projected.sn;
  }

  // --- a requested member is PRESENT and NULLABLE, never absent ------------
  const selected = openidm.read(`${FIXTURE}/${id}`, null, [
    "userName",
    "telephoneNumber",
  ]);
  if (selected !== null) {
    // Schema-optional: the key is always there, the value may be `null`
    // (verified 2026-08-18). So a null check, never an existence check.
    const _phone: string | null = selected.telephoneNumber;
    void _phone;
    // Schema-required: always has a value, so it is not widened.
    const _userName: string = selected.userName;
    void _userName;
    // @ts-expect-error the value is nullable — `?? ""` or a guard, not a bare use
    const _bad: string = selected.telephoneNumber;
    void _bad;
  }

  // --- `_id` alone still yields `_id` AND `_rev` ---------------------------
  const idOnly = openidm.read(`${FIXTURE}/${id}`, null, ["_id"]);
  if (idOnly !== null) {
    const _rev: string = idOnly._rev;
    void _rev;
    // @ts-expect-error asking for `_id` does not hand back the whole record
    void idOnly.userName;
  }

  // --- `*` opts out of projection -----------------------------------------
  const star = openidm.read(`${FIXTURE}/${id}`, null, ["*"]);
  if (star !== null) {
    const _sn: string = star.sn;
    void _sn;
  }

  // --- a relationship path yields the EXPANSION, not the declared ref ------
  const withManager = openidm.read(`${FIXTURE}/${id}`, null, [
    "manager/userName",
  ]);
  if (withManager !== null) {
    // Nullable: an unset single-valued relationship comes back as `null`.
    const _ref: string | undefined = withManager.manager?._ref;
    void _ref;
    // The target's schema is unknown to these types, so members are index-only.
    const _name: unknown = withManager.manager?.["userName"];
    void _name;
    // @ts-expect-error unset single-valued relationships are null, so guard it
    void withManager.manager._ref;
    // @ts-expect-error `mail` was not requested
    void withManager.mail;
  }

  // --- a MULTI-valued relationship path projects to an array ---------------
  const withRoles = openidm.read(`${FIXTURE}/${id}`, null, ["authzRoles/name"]);
  if (withRoles !== null) {
    // `[]` when unset, never null — so no guard, but an index check instead.
    const _first: string | undefined = withRoles.authzRoles[0]?._ref;
    void _first;
    // @ts-expect-error it is an array, not a single expansion
    void withRoles.authzRoles._ref;
  }

  // --- `_meta` is an expansion too ----------------------------------------
  const withMeta = openidm.read(`${FIXTURE}/${id}`, null, [
    "_meta/lastChanged",
  ]);
  if (withMeta !== null) {
    // `_meta` is itself a relationship, so it is nullable like any other.
    const _changed: unknown = withMeta._meta?.["lastChanged"];
    void _changed;
  }

  // --- a plain `string[]` is rejected, not silently accepted ---------------
  const loose: string[] = ["userName"];
  // @ts-expect-error a field list must be members of the schema, not any string
  openidm.read(`${FIXTURE}/${id}`, null, loose);

  // --- a correctly typed but non-LITERAL list widens to the whole record ----
  const dynamic: ManagedField<TypesFixture>[] = ["userName"];
  const widened = openidm.read(`${FIXTURE}/${id}`, null, dynamic);
  if (widened !== null) {
    // Precision is lost, not correctness: the whole record, never `{}`.
    const _sn: string = widened.sn;
    void _sn;
  }

  // --- query: two-argument form keeps every declared property -------------
  const page = openidm.query(FIXTURE, { _queryFilter: "true" });
  const _first: TypesFixture | undefined = page.result[0];
  void _first;

  // --- query: the third argument projects every row -----------------------
  const thin = openidm.query(FIXTURE, { _queryFilter: "true" }, ["userName"]);
  const row = thin.result[0];
  if (row !== undefined) {
    const _id: string = row._id;
    void _id;
    // @ts-expect-error `mail` was not in the field list
    void row.mail;
  }

  // --- query: `_fields` in params cannot be projected, so rows go partial --
  const opaque = openidm.query(FIXTURE, {
    _queryFilter: "true",
    _fields: "userName",
  });
  const opaqueRow = opaque.result[0];
  if (opaqueRow !== undefined) {
    // Present in the type but possibly absent at runtime — hence `| undefined`.
    const _userName: string | undefined = opaqueRow.userName;
    void _userName;
  }

  // --- a null paging cursor is rejected, because IDM rejects it ------------
  openidm.query(FIXTURE, { _queryFilter: "true", _pagedResultsCookie: "AAA=" });
  openidm.query(FIXTURE, {
    _queryFilter: "true",
    // @ts-expect-error omit the key instead — an explicit null is a live 500
    _pagedResultsCookie: null,
  });

  // --- a query result is NOT an endpoint response -------------------------
  // @ts-expect-error `remainingPagedResults` is optional here and required there
  const _asResponse: CrestQueryResult<TypesFixture> = page;
  void _asResponse;

  // --- an unknown managed path rejects a field list -----------------------
  // @ts-expect-error nothing to check the list against; re-run workspace update
  openidm.read(`managed/no_such_object/${id}`, null, ["userName"]);
}

test("the openidm type tours are declared but never executed", () => {
  assert.equal(typeof typeTours, "function");
});
