// Full OpenAPI 3.1 meta-schema validation. Managed file — regenerated by
// `aic workspace update`. Discovers `src/endpoints/*.ts` so deleting the
// seeded demos (or replacing them with your own) does not redden this file.

import assert from "node:assert/strict";
import { mkdtemp, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

import { validate } from "@hyperjump/json-schema/openapi-3-1";

import { defineEndpoint, route, toOpenApi, v } from "../framework/index.ts";
import unions from "./union-endpoint.ts";

const TESTS_DIR = dirname(fileURLToPath(import.meta.url));
const ENDPOINTS_DIR = join(TESTS_DIR, "..", "src", "endpoints");

const contractFixture = defineEndpoint({
  name: "contract-fixture",
  routes: [
    route({
      method: "update",
      path: "/{id}",
      params: { id: v.string() },
      errors: [409, 422, 502],
      handler: () => ({}),
    }),
  ],
});

function looksLikeEndpoint(value) {
  return (
    typeof value === "function" &&
    value.definition !== null &&
    typeof value.definition === "object" &&
    typeof value.definition.name === "string" &&
    Array.isArray(value.definition.routes)
  );
}

/**
 * Load every `defineEndpoint` default export under `src/endpoints/`.
 * A missing directory is an empty set, not a crash — the README tells the
 * user they may delete the demos.
 */
async function loadEndpoints(dir = ENDPOINTS_DIR) {
  let names;
  try {
    names = await readdir(dir);
  } catch (error) {
    if (error?.code === "ENOENT") {
      return [];
    }
    throw error;
  }
  const loaded = [];
  for (const name of names.sort()) {
    if (!name.endsWith(".ts") || name.endsWith(".d.ts")) {
      continue;
    }
    const module = await import(pathToFileURL(join(dir, name)).href);
    // `tools/build.mjs` bundles EVERY `.ts` here and refuses one whose default
    // export is not a `defineEndpoint()` result, so skipping it silently would
    // hide from this test exactly the file that breaks the build.
    if (!looksLikeEndpoint(module.default)) {
      throw new Error(
        join("src/endpoints", name) +
          ": default export must be the value returned by defineEndpoint()"
      );
    }
    loaded.push({
      fileName: basename(name, ".ts"),
      endpoint: module.default,
    });
  }
  return loaded;
}

test("discovery refuses a file the build would refuse", async () => {
  // The silent skip this replaced hid the one file that breaks `npm run build`.
  const dir = await mkdtemp(join(tmpdir(), "aic-endpoints-"));
  await writeFile(join(dir, "not-an-endpoint.ts"), "export default 42;\n", "utf8");
  await assert.rejects(
    loadEndpoints(dir),
    /default export must be the value returned by defineEndpoint/
  );
});

test("the generated document validates against the OpenAPI 3.1 meta-schema", async () => {
  const discovered = await loadEndpoints();
  const endpoints = [
    ...discovered.map((entry) => entry.endpoint),
    unions,
    contractFixture,
  ];
  for (const endpoint of endpoints) {
    const result = await validate(
      "https://spec.openapis.org/oas/3.1/schema",
      toOpenApi(endpoint.definition)
    );
    assert.equal(result.valid, true, endpoint.definition.name + JSON.stringify(result));
  }
});

test("every discovered endpoint names itself after its file and declares a success response", async (t) => {
  const discovered = await loadEndpoints();
  if (discovered.length === 0) {
    t.diagnostic("no endpoints in src/endpoints — nothing to check");
    return;
  }
  for (const { fileName, endpoint } of discovered) {
    assert.equal(
      endpoint.definition.name,
      fileName,
      fileName + ": endpoint name must match the file name"
    );
    for (const route of endpoint.definition.routes) {
      assert.ok(
        route.response !== undefined && Object.keys(route.response).length > 0,
        fileName + " " + route.method + " " + route.path + " has no success response schema"
      );
    }
  }
});

test("a missing endpoints directory is nothing to check, not a crash", async (t) => {
  const loaded = await loadEndpoints(join(TESTS_DIR, "no-such-endpoints"));
  assert.deepEqual(loaded, []);
  t.diagnostic("no endpoints in src/endpoints — nothing to check");
});
