// Type-level tests for the `openidm` signatures.
//
// The assertions here are `@ts-expect-error` markers, so `tsc` fails if a line
// that MUST be rejected starts compiling — the only way to gate a type in both
// directions. `npm run type-check` is the real gate; the single runtime test at
// the bottom exists so `node --test` reports the file rather than skipping it.
//
// Nothing here runs against a tenant: `typeTours` is never called, and `openidm`
// does not exist under node. Behaviour these types encode is verified live in
// docs/api/10-managed-objects.md.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import type { CrestQueryResult } from "../framework/index.ts";
import type { AlphaUser } from "../src/generated/managed.ts";

declare const id: string;

/** Never called. Present so `tsc` checks every line in it. */
export function typeTours(): void {
  // --- a plain read is the whole record, with _id/_rev guaranteed -----------
  const whole = openidm.read(`managed/alpha_user/${id}`);
  if (whole !== null) {
    const _id: string = whole._id;
    const _userName: string = whole.userName;
    void _id;
    void _userName;
    // @ts-expect-error not a property of the tenant's alpha_user schema
    void whole.nosuchField;
  }

  // --- a field-restricted read is projected to what was asked for ----------
  const projected = openidm.read(`managed/alpha_user/${id}`, null, [
    "userName",
    "mail",
  ]);
  if (projected !== null) {
    // `_id`/`_rev` survive a projection: they come back whatever you ask for.
    const _id: string = projected._id;
    const _rev: string = projected._rev;
    const _mail: string = projected.mail;
    void _id;
    void _rev;
    void _mail;
    // @ts-expect-error `sn` was not in the field list
    void projected.sn;
  }

  // --- `_id` alone still yields `_id` AND `_rev` ---------------------------
  const idOnly = openidm.read(`managed/alpha_user/${id}`, null, ["_id"]);
  if (idOnly !== null) {
    const _rev: string = idOnly._rev;
    void _rev;
    // @ts-expect-error asking for `_id` does not hand back the whole record
    void idOnly.userName;
  }

  // --- `*` opts out of projection -----------------------------------------
  const star = openidm.read(`managed/alpha_user/${id}`, null, ["*"]);
  if (star !== null) {
    const _sn: string = star.sn;
    void _sn;
  }

  // --- a relationship path yields the EXPANSION, not the declared ref ------
  const withManager = openidm.read(`managed/alpha_user/${id}`, null, [
    "manager/userName",
  ]);
  if (withManager !== null) {
    // Nullable: an unset single-valued relationship comes back as `null`.
    const _ref: string | undefined = withManager.manager?._ref;
    void _ref;
    // The target's schema is unknown to these types, so members are index-only.
    const _name: unknown = withManager.manager?.["userName"];
    void _name;
    // @ts-expect-error unset single-valued relationships are null, so guard it
    void withManager.manager._ref;
    // @ts-expect-error `mail` was not requested
    void withManager.mail;
  }

  // --- a MULTI-valued relationship path projects to an array ---------------
  const withRoles = openidm.read(`managed/alpha_user/${id}`, null, [
    "authzRoles/name",
  ]);
  if (withRoles !== null) {
    // `[]` when unset, never null — so no guard, but an index check instead.
    const _first: string | undefined = withRoles.authzRoles[0]?._ref;
    void _first;
    // @ts-expect-error it is an array, not a single expansion
    void withRoles.authzRoles._ref;
  }

  // --- `_meta` is an expansion too ----------------------------------------
  const withMeta = openidm.read(`managed/alpha_user/${id}`, null, [
    "_meta/lastChanged",
  ]);
  if (withMeta !== null) {
    // `_meta` is itself a relationship, so it is nullable like any other.
    const _changed: unknown = withMeta._meta?.["lastChanged"];
    void _changed;
  }

  // --- a plain `string[]` is rejected, not silently accepted ---------------
  const loose: string[] = ["userName"];
  // @ts-expect-error a field list must be members of the schema, not any string
  openidm.read(`managed/alpha_user/${id}`, null, loose);

  // --- a correctly typed but non-LITERAL list widens to the whole record ----
  const dynamic: ManagedField<AlphaUser>[] = ["userName"];
  const widened = openidm.read(`managed/alpha_user/${id}`, null, dynamic);
  if (widened !== null) {
    // Precision is lost, not correctness: the whole record, never `{}`.
    const _sn: string = widened.sn;
    void _sn;
  }

  // --- query: two-argument form keeps every declared property -------------
  const page = openidm.query("managed/alpha_user", { _queryFilter: "true" });
  const _first: AlphaUser | undefined = page.result[0];
  void _first;

  // --- query: the third argument projects every row -----------------------
  const thin = openidm.query("managed/alpha_user", { _queryFilter: "true" }, [
    "userName",
  ]);
  const row = thin.result[0];
  if (row !== undefined) {
    const _id: string = row._id;
    void _id;
    // @ts-expect-error `mail` was not in the field list
    void row.mail;
  }

  // --- query: `_fields` in params cannot be projected, so rows go partial --
  const opaque = openidm.query("managed/alpha_user", {
    _queryFilter: "true",
    _fields: "userName",
  });
  const opaqueRow = opaque.result[0];
  if (opaqueRow !== undefined) {
    // Present in the type but possibly absent at runtime — hence `| undefined`.
    const _userName: string | undefined = opaqueRow.userName;
    void _userName;
  }

  // --- a query result is NOT an endpoint response -------------------------
  // @ts-expect-error `remainingPagedResults` is optional here and required there
  const _asResponse: CrestQueryResult<AlphaUser> = page;
  void _asResponse;

  // --- an unknown managed path rejects a field list -----------------------
  // @ts-expect-error nothing to check the list against; re-run workspace update
  openidm.read(`managed/no_such_object/${id}`, null, ["userName"]);
}

test("the openidm type tours are declared but never executed", () => {
  assert.equal(typeof typeTours, "function");
});
