// OpenAPI 3.1 generation, including the CREST `?_action=` wrinkle.
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  assignPathKeys,
  defineEndpoint,
  queryResult,
  queryRoute,
  route,
  toOpenApi,
  v,
} from "../framework/index.ts";

const endpoint = defineEndpoint({
  name: "widgets",
  summary: "Widgets",
  version: "2.1.0",
  headers: { "x-request-id": v.optional(v.uuid()) },
  routes: [
    queryRoute({
      path: "/",
      query: { limit: v.withDefault(v.integer({ min: 1, max: 100 }), 20) },
      // Declares one ROW; the generator wraps the paging envelope around it.
      response: v.object({ _id: v.string(), name: v.string() }),
      handler: () => queryResult([]),
    }),
    route({
      method: "create",
      path: "/",
      body: v.object({ name: v.string({ maxLength: 64 }) }),
      response: v.object({ reached: v.string() }),
      handler: () => ({ reached: "create" }),
    }),
    route({
      method: "action",
      action: "bulkImport",
      path: "/",
      scopes: ["demo:write"],
      errors: [409, 422, 502],
      body: v.object({ items: v.list(v.string(), { maxItems: 50 }) }),
      handler: () => ({}),
    }),
    route({
      method: "read",
      path: "/{id}",
      params: { id: v.string({ pattern: /^w-/ }) },
      query: { expand: v.optional(v.csv(v.enumOf(["owner", "history"]))) },
      // The response is the VALIDATOR now; the generator reads `.schema`.
      response: v.object({ _id: v.string() }),
      handler: ({ params }) => ({ _id: params.id }),
    }),
    route({
      method: "update",
      path: "/{id}",
      params: { id: v.string() },
      body: v.object({ name: v.string() }),
      response: v.object({ name: v.string() }),
      handler: ({ body }) => body,
    }),
    route({
      method: "read",
      path: "/contracts",
      response: v.object({
        loose: v.oneOf([v.string(), v.integer()]),
        tagged: v.discriminated("type", {
          date: v.object({ type: v.enumOf(["date"]), format: v.string() }),
          string: v.object({
            type: v.enumOf(["string"]),
            minLength: v.integer(),
          }),
        }),
      }),
      handler: () => ({
        loose: "ok",
        tagged: { type: "date" as const, format: "iso" },
      }),
    }),
    route({
      method: "action",
      action: "retire",
      path: "/{id}",
      scopes: ["demo:write"],
      params: { id: v.string() },
      body: v.object({ reason: v.string() }),
      handler: () => ({}),
    }),
  ],
});

const document = toOpenApi(endpoint.definition, {
  serverUrl: "https://t.example",
});
const paths = document["paths"] as Record<string, Record<string, unknown>>;
const base = "/openidm/endpoint/widgets";

function operation(key: string, method: string): Record<string, unknown> {
  const value = paths[key]?.[method];
  assert.ok(value !== undefined, "no " + method + " on " + key);
  return value as Record<string, unknown>;
}

function parameter(key: string, method: string, name: string) {
  const parameters = operation(key, method)["parameters"] as
    Record<string, unknown>[] | undefined;
  const value = parameters?.find((candidate) => candidate["name"] === name);
  assert.ok(value !== undefined, "no parameter " + name);
  return value;
}

const rootGet = operation(base, "get");
const rootPost = operation(base, "post");
const itemGet = operation(base + "/{id}", "get");
const retirePost = operation(base + "/{id}:retire", "post");
const bulkAction = parameter(base + ":bulkImport", "post", "_action");
const createAction = parameter(base, "post", "_action");
const id = parameter(base + "/{id}", "get", "id");
const expand = parameter(base + "/{id}", "get", "expand");

function successSchema(key: string, method: string): Record<string, unknown> {
  const httpMethod: Record<string, string> = {
    read: "get",
    query: "get",
    create: "post",
    action: "post",
    update: "put",
    delete: "delete",
    patch: "patch",
  };
  const responses = operation(key, httpMethod[method] ?? "get")[
    "responses"
  ] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  const status = Object.keys(responses).filter(
    (candidate) => candidate.charAt(0) === "2"
  )[0];
  const schema = responses[status ?? ""]?.content["application/json"].schema;
  assert.ok(schema !== undefined, "no 2xx schema for " + key);
  return schema;
}

type ShapeCase = readonly [name: string, actual: unknown, expected: unknown];
const shapeCases: ShapeCase[] = [
  ["document version", document["openapi"], "3.1.0"],
  ["JSON Schema dialect", document["jsonSchemaDialect"], "https://json-schema.org/draft/2020-12/schema"],
  ["server URL", document["servers"], [{ url: "https://t.example" }]],
  ["document info", document["info"], { title: "Widgets", version: "2.1.0" }],
  ["stable RPC path keys", Object.keys(paths).sort(), [base, base + "/contracts", base + "/{id}", base + "/{id}:retire", base + ":bulkImport"]],
  ["ordinary route is not synthetic", rootGet["x-crest-synthetic-path-key"], undefined],
  ["root POST remains create", rootPost["x-crest-method"], "create"],
  ["synthetic action metadata", [retirePost["x-crest-synthetic-path-key"], retirePost["x-crest-action"], retirePost["x-crest-path"]], [true, "retire", base + "/{id}"]],
  ["action discriminator", [bulkAction["in"], bulkAction["required"], bulkAction["schema"]], ["query", true, { type: "string", enum: ["bulkImport"] }]],
  ["create discriminator", [createAction["in"], createAction["required"], createAction["schema"]], ["query", false, { type: "string", enum: ["create"] }]],
  ["update discriminator", parameter(base + "/{id}", "put", "If-Match"), {
    name: "If-Match",
    in: "header",
    required: true,
    schema: { type: "string" },
    description: "Required for IDM to dispatch this PUT as an update.",
  }],
  ["query discriminator", parameter(base, "get", "_queryFilter")["required"], true],
  ["path parameter", [id["in"], id["required"]], ["path", true]],
  ["CSV query parameter", [expand["required"], expand["style"], expand["explode"]], [false, "form", false]],
  ["required scopes", [retirePost["x-required-scopes"], retirePost["security"]], [["demo:write"], [{ oauth2: ["demo:write"] }]]],
  ["unscoped route", itemGet["security"], undefined],
  ["declared body schema", rootPost["requestBody"], {
    required: true,
    content: { "application/json": { schema: {
      type: "object",
      properties: { name: { type: "string", maxLength: 64 } },
      additionalProperties: false,
      required: ["name"],
    } } },
  }],
];

for (const [name, actual, expected] of shapeCases) {
  test("OpenAPI shape: " + name, () => assert.deepEqual(actual, expected));
}

test("the endpoint-wide header appears on every operation", () => {
  for (const [key, methods] of Object.entries(paths)) {
    for (const method of Object.keys(methods)) {
      assert.equal(parameter(key, method, "x-request-id")["in"], "header");
    }
  }
});

test("a route header override replaces the endpoint header, including by case", () => {
  const tenants = defineEndpoint({
    name: "tenants",
    headers: { "x-tenant": v.optional(v.string()) },
    routes: ({ route }) => [
      route({
        method: "read",
        path: "/",
        headers: { "X-Tenant": v.string() },
        handler: ({ headers }) => ({ tenant: headers["X-Tenant"] }),
      }),
    ],
  });
  const generated = toOpenApi(tenants.definition);
  const generatedPaths = generated["paths"] as Record<
    string,
    Record<string, { parameters: Record<string, unknown>[] }>
  >;
  const parameters =
    generatedPaths["/openidm/endpoint/tenants"]?.["get"]?.parameters ?? [];
  const headers = parameters.filter((entry) => entry["in"] === "header");
  assert.deepEqual(
    headers.map((entry) => [entry["name"], entry["required"]]),
    [["X-Tenant", true]]
  );
});

test("a declared If-Match merges with the one an update synthesises", () => {
  // An author who wants the handler to read the revision must declare the
  // header, and OpenAPI allows one parameter per (name, in) pair — so the
  // synthetic entry tightens the declaration instead of duplicating it.
  const revisions = defineEndpoint({
    name: "revisions",
    routes: ({ route }) => [
      route({
        method: "update",
        path: "/{id}",
        params: { id: v.string() },
        headers: { "if-match": v.optional(v.string()) },
        body: v.object({ name: v.string() }),
        handler: ({ headers }) => ({ rev: headers["if-match"] ?? "" }),
      }),
    ],
  });
  const generated = toOpenApi(revisions.definition);
  const generatedPaths = generated["paths"] as Record<
    string,
    Record<string, { parameters: Record<string, unknown>[] }>
  >;
  const parameters =
    generatedPaths["/openidm/endpoint/revisions/{id}"]?.["put"]?.parameters ??
    [];
  const headers = parameters.filter((entry) => entry["in"] === "header");
  assert.deepEqual(
    headers.map((entry) => [entry["name"], entry["required"]]),
    [["if-match", true]]
  );
});

test("non-empty security scopes only reference an OAuth-capable scheme", () => {
  const components = document["components"] as {
    securitySchemes: Record<string, Record<string, unknown>>;
  };
  for (const methods of Object.values(paths)) {
    for (const value of Object.values(methods)) {
      const security = (value as Record<string, unknown>)["security"] as
        Record<string, string[]>[] | undefined;
      for (const requirement of security ?? []) {
        for (const [name, scopes] of Object.entries(requirement)) {
          if (scopes.length > 0) {
            assert.ok(
              ["oauth2", "openIdConnect"].includes(
                String(components.securitySchemes[name]?.["type"])
              )
            );
          }
        }
      }
    }
  }
  const oauth2 = components.securitySchemes["oauth2"] as {
    flows: { clientCredentials: { scopes: Record<string, string> } };
  };
  assert.deepEqual(oauth2.flows.clientCredentials.scopes, {
    "demo:write": "Required by one or more endpoint routes.",
  });
});

test("a validated operation documents only its framework-produced errors", () => {
  const responses = operation(base + "/{id}", "get")["responses"] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  for (const status of ["400", "500"]) {
    assert.equal(
      responses[status]?.content["application/json"].schema["$ref"],
      "#/components/schemas/CrestError"
    );
  }
  for (const status of ["401", "403", "404", "405", "409", "422", "502"]) {
    assert.equal(responses[status], undefined);
  }
  // The 200 schema comes off the response VALIDATOR, so it carries the members
  // and `required` the validator would enforce — not a hand-written stand-in
  // that could disagree with the handler.
  assert.deepEqual(responses["200"]?.content["application/json"].schema, {
    type: "object",
    properties: { _id: { type: "string" } },
    required: ["_id"],
    additionalProperties: false,
  });
});

test("every operation has exactly the success status its CREST method produces", () => {
  for (const assigned of assignPathKeys(endpoint.definition)) {
    const methods: Record<string, string> = {
      read: "get",
      query: "get",
      create: "post",
      action: "post",
      update: "put",
      patch: "patch",
      delete: "delete",
    };
    const method = methods[assigned.route.method] as string;
    const responses = operation(assigned.key, method)["responses"] as Record<
      string,
      unknown
    >;
    const successes = Object.keys(responses).filter((status) =>
      status.startsWith("2")
    );
    assert.deepEqual(successes, [assigned.route.method === "create" ? "201" : "200"]);
  }
});

test("every resource-shaped response documents the _id IDM adds", () => {
  // Probed 2026-08-18: create/read/update/delete/patch all come back carrying
  // `_id`; an action does not, and a query gets the paging envelope. The
  // VALIDATED schema must stay exactly what the handler returns.
  for (const assigned of assignPathKeys(endpoint.definition)) {
    const method = assigned.route.method;
    const documented = successSchema(assigned.key, method);
    const validated = assigned.route.response?.schema as
      | Record<string, unknown>
      | undefined;
    if (method === "action" || method === "query" || validated === undefined) {
      continue;
    }
    const properties = validated["properties"] as Record<string, unknown>;
    const required = validated["required"] as string[];
    assert.deepEqual(
      documented,
      {
        ...validated,
        properties: { ...properties, _id: { type: "string" } },
        required: required.indexOf("_id") >= 0 ? required : [...required, "_id"],
      },
      method + " " + assigned.key
    );
  }
});

test("a create documents the _id IDM adds without changing handler validation", () => {
  const responses = rootPost["responses"] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  assert.deepEqual(responses["201"]?.content["application/json"].schema, {
    type: "object",
    properties: { reached: { type: "string" }, _id: { type: "string" } },
    required: ["reached", "_id"],
    additionalProperties: false,
  });
  const createRoute = endpoint.definition.routes.find(
    (candidate) => candidate.method === "create"
  );
  assert.deepEqual(createRoute?.response?.schema, {
    type: "object",
    properties: { reached: { type: "string" } },
    required: ["reached"],
    additionalProperties: false,
  });
});

test("a route documents its declared handler error statuses", () => {
  const responses = operation(base + ":bulkImport", "post")[
    "responses"
  ] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  for (const status of ["409", "422", "502"]) {
    assert.equal(
      responses[status]?.content["application/json"].schema["$ref"],
      "#/components/schemas/CrestError"
    );
  }
});

test("CrestError requires only fields every framework error sends", () => {
  const components = document["components"] as {
    schemas: { CrestError: { required: string[] } };
  };
  assert.deepEqual(components.schemas.CrestError.required, ["code", "message"]);
});

test("a query route's 200 schema is the envelope around its declared row", () => {
  // The route declares ONE ROW; the generator wraps it, so the document and the
  // handler's checked return type come from the same declaration.
  const responses = operation(base, "get")["responses"] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  const schema = responses["200"]?.content["application/json"].schema as {
    properties: Record<string, Record<string, unknown>>;
    required: string[];
  };
  assert.deepEqual(schema.properties["result"], {
    type: "array",
    items: {
      type: "object",
      properties: { _id: { type: "string" }, name: { type: "string" } },
      required: ["_id", "name"],
      additionalProperties: false,
    },
  });
  // Every paging member IDM requires is documented, not just `result`.
  assert.deepEqual(schema.required.sort(), [
    "pagedResultsCookie",
    "remainingPagedResults",
    "result",
    "resultCount",
    "totalPagedResults",
    "totalPagedResultsPolicy",
  ]);
});

test("union combinators emit inline schemas with const tags", () => {
  const responses = operation(base + "/contracts", "get")["responses"] as Record<
    string,
    { content: { "application/json": { schema: Record<string, unknown> } } }
  >;
  const schema = responses["200"]?.content["application/json"].schema as {
    properties: Record<string, Record<string, unknown>>;
  };
  assert.deepEqual(schema.properties["loose"]?.["anyOf"], [
    { type: "string" },
    { type: "integer" },
  ]);
  const branches = schema.properties["tagged"]?.["oneOf"] as Array<{
    properties: Record<string, unknown>;
  }>;
  assert.deepEqual(branches.map((branch) => branch.properties["type"]), [
    { const: "date" },
    { const: "string" },
  ]);
  assert.equal(schema.properties["tagged"]?.["discriminator"], undefined);
});

test("operation ids are unique and stable", () => {
  const ids = Object.entries(paths).flatMap(([key, methods]) =>
    Object.keys(methods).map(
      (method) => operation(key, method)["operationId"] as string
    )
  );
  assert.equal(new Set(ids).size, ids.length);
  assert.ok(ids.includes("widgets_action_retire_id"));
});
