// Full OpenAPI 3.1 meta-schema validation. Managed file — regenerated by
// `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { validate } from "@hyperjump/json-schema/openapi-3-1";

import { toOpenApi } from "../framework/index.ts";
import reports from "../src/endpoints/example-reports.ts";
import widgets from "../src/endpoints/example-widgets.ts";
import unions from "./union-endpoint.ts";

test("the generated document validates against the OpenAPI 3.1 meta-schema", async () => {
  for (const endpoint of [widgets, reports, unions]) {
    const result = await validate("https://spec.openapis.org/oas/3.1/schema", toOpenApi(endpoint.definition));
    assert.equal(result.valid, true, endpoint.definition.name + JSON.stringify(result));
  }
});

test("every demo route declares a success response schema", () => {
  for (const endpoint of [widgets, reports]) {
    for (const route of endpoint.definition.routes) {
      assert.ok(route.response !== undefined && Object.keys(route.response).length > 0);
    }
  }
});
