// Routing and dispatch. Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  defineEndpoint,
  isFault,
  parsePath,
  route,
  splitResourcePath,
  v,
  type CrestFault,
} from "../framework/index.ts";
import { callContext, crestRequest, recordingLogger } from "./harness.ts";

function faultFrom(run: () => unknown): CrestFault {
  try {
    run();
  } catch (thrown) {
    assert.ok(isFault(thrown), "expected a CREST fault, got " + String(thrown));
    return thrown;
  }
  throw new Error("expected a throw");
}

const demo = defineEndpoint({
  name: "demo",
  headers: { "x-request-id": v.optional(v.uuid()) },
  routes: [
    route({
      method: "query",
      path: "/",
      query: { limit: v.withDefault(v.integer({ min: 1, max: 10 }), 3) },
      handler: ({ query }) => ({ result: [{ _id: String(query.limit) }] }),
    }),
    route({
      method: "read",
      path: "/{id}",
      params: { id: v.string({ pattern: /^[a-z]+$/ }) },
      handler: ({ params, correlationId }) => ({
        id: params.id,
        correlationId,
      }),
    }),
    route({
      method: "read",
      path: "/daily/{date}",
      params: { date: v.isoDate() },
      handler: ({ params }) => ({ date: params.date }),
    }),
    route({
      method: "read",
      path: "/widget/{id}/summary",
      params: { id: v.string() },
      handler: ({ params }) => ({ summaryOf: params.id }),
    }),
    route({
      method: "create",
      path: "/",
      body: v.object({ name: v.string({ minLength: 1 }) }),
      handler: ({ body }) => ({ created: body.name }),
    }),
    route({
      method: "patch",
      path: "/{id}",
      params: { id: v.string() },
      patches: v.patchOperations({ minItems: 1 }),
      handler: ({ patchOperations }) => ({ ops: patchOperations.length }),
    }),
    route({
      method: "action",
      action: "retire",
      path: "/{id}",
      scopes: ["demo:write"],
      params: { id: v.string() },
      body: v.object({ reason: v.string({ minLength: 1 }) }),
      handler: ({ params, body }) => ({ retired: params.id, why: body.reason }),
    }),
  ],
});

test("parsePath splits literals and captures", () => {
  assert.deepEqual(parsePath("/"), []);
  assert.deepEqual(parsePath("/{id}"), [{ param: "id" }]);
  assert.deepEqual(parsePath("/widget/{id}/summary"), [
    { literal: "widget" },
    { param: "id" },
    { literal: "summary" },
  ]);
});

test("splitResourcePath decodes each segment and drops empties", () => {
  assert.deepEqual(splitResourcePath(""), []);
  assert.deepEqual(splitResourcePath("a/b/c"), ["a", "b", "c"]);
  assert.deepEqual(splitResourcePath("a%2Fb"), ["a/b"]);
  assert.deepEqual(splitResourcePath("bad%"), ["bad%"]);
});

test("the root path routes to the query handler with its defaults applied", () => {
  const result = demo.dispatch(crestRequest("query"), callContext()) as {
    result: { _id: string }[];
  };
  assert.deepEqual(result.result, [{ _id: "3" }]);
});

test("a declared query param overrides the default", () => {
  const result = demo.dispatch(
    crestRequest("query", { query: { limit: "7" } }),
    callContext()
  ) as { result: { _id: string }[] };
  assert.deepEqual(result.result, [{ _id: "7" }]);
});

test("a literal segment beats a same-length capture", () => {
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "daily/2026-08-13" }),
    callContext()
  ) as { date: string };
  assert.equal(result.date, "2026-08-13");
});

test("a capture in the middle of three segments matches", () => {
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "widget/w-abcd/summary" }),
    callContext()
  ) as { summaryOf: string };
  assert.equal(result.summaryOf, "w-abcd");
});

test("an unmatched path is a 404, not a crash", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("read", { resourcePath: "a/b/c/d" }),
      callContext()
    )
  );
  assert.equal(fault.code, 404);
  assert.equal(fault.reason, "Not Found");
});

test("a path that exists under another method is a 405 listing the alternatives", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("update", { resourcePath: "abc", content: {} }),
      callContext()
    )
  );
  assert.equal(fault.code, 405);
  assert.deepEqual((fault.detail as { allowed: string[] }).allowed, [
    "read",
    "patch",
    "action",
  ]);
});

test("an unknown action names the supported ones", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("action", {
        resourcePath: "abc",
        action: "explode",
        content: {},
      }),
      callContext({ scopes: ["demo:write"] })
    )
  );
  assert.equal(fault.code, 404);
  assert.deepEqual((fault.detail as { supported: string[] }).supported, [
    "retire",
  ]);
});

test("a path param failing its pattern is a 400 carrying the issue path", () => {
  const fault = faultFrom(() =>
    demo.dispatch(crestRequest("read", { resourcePath: "ABC" }), callContext())
  );
  assert.equal(fault.code, 400);
  const detail = fault.detail as { issues: { path: string }[] };
  assert.equal(detail.issues[0]?.path, "path.id");
});

test("an out-of-range query int is a 400", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("query", { query: { limit: "99" } }),
      callContext()
    )
  );
  assert.equal(fault.code, 400);
  assert.equal(
    (fault.detail as { issues: { path: string }[] }).issues[0]?.path,
    "query.limit"
  );
});

test("a malformed body is a 400 and never reaches the handler", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("create", { content: { name: "" } }),
      callContext()
    )
  );
  assert.equal(fault.code, 400);
});

test("a missing body is a 400 rather than a 500", () => {
  const fault = faultFrom(() =>
    demo.dispatch(crestRequest("create", {}), callContext())
  );
  assert.equal(fault.code, 400);
  assert.equal(
    (fault.detail as { issues: { path: string }[] }).issues[0]?.path,
    "body"
  );
});

test("a route with scopes refuses a token that lacks them", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("action", {
        resourcePath: "abc",
        action: "retire",
        content: { reason: "obsolete" },
      }),
      callContext({ scopes: ["something:else"] })
    )
  );
  assert.equal(fault.code, 403);
  assert.deepEqual((fault.detail as { missing: string[] }).missing, [
    "demo:write",
  ]);
});

test("a route with scopes refuses a caller with no oauth2 context at all", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("action", {
        resourcePath: "abc",
        action: "retire",
        content: { reason: "obsolete" },
      }),
      callContext()
    )
  );
  assert.equal(fault.code, 403);
});

test("a route with scopes admits a token that carries them", () => {
  const result = demo.dispatch(
    crestRequest("action", {
      resourcePath: "abc",
      action: "retire",
      content: { reason: "obsolete" },
    }),
    callContext({ scopes: ["demo:write", "other"] })
  ) as { retired: string; why: string };
  assert.deepEqual(result, { retired: "abc", why: "obsolete" });
});

test("patch operations are validated before the handler sees them", () => {
  const ok = demo.dispatch(
    crestRequest("patch", {
      resourcePath: "abc",
      patchOperations: [{ operation: "replace", field: "/name", value: "n" }],
    }),
    callContext()
  ) as { ops: number };
  assert.equal(ok.ops, 1);

  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("patch", { resourcePath: "abc", patchOperations: [] }),
      callContext()
    )
  );
  assert.equal(fault.code, 400);
});

test("the x-request-id header becomes the correlation id, case-insensitively", () => {
  const id = "3f1a2b4c-5d6e-4f70-8a9b-0c1d2e3f4a5b";
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "abc" }),
    callContext({ headers: { "X-Request-Id": id } })
  ) as { correlationId: string };
  assert.equal(result.correlationId, id);
});

test("a non-UUID x-request-id is a 400, not a silently ignored header", () => {
  const fault = faultFrom(() =>
    demo.dispatch(
      crestRequest("read", { resourcePath: "abc" }),
      callContext({ headers: { "x-request-id": "nope" } })
    )
  );
  assert.equal(fault.code, 400);
  assert.equal(
    (fault.detail as { issues: { path: string }[] }).issues[0]?.path,
    "header.x-request-id"
  );
});

test("a request without the header still gets a correlation id", () => {
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "abc" }),
    callContext()
  ) as { correlationId: string };
  assert.match(result.correlationId, /^aic-/);
});

test("dispatch works when there is no HTTP context at all", () => {
  const result = demo.dispatch(
    crestRequest("read", { resourcePath: "abc" }),
    callContext({ internal: true })
  ) as { id: string };
  assert.equal(result.id, "abc");
});

test("an unexpected throw becomes an opaque 500 and is logged", () => {
  const logger = recordingLogger();
  const exploding = defineEndpoint({
    name: "boom",
    routes: [
      route({
        method: "read",
        path: "/",
        handler: () => {
          throw new Error("connection string postgres://user:hunter2@db");
        },
      }),
    ],
  });
  const fault = faultFrom(() =>
    exploding.dispatch(crestRequest("read"), callContext(), logger)
  );
  assert.equal(fault.code, 500);
  assert.equal(fault.message, "Internal error");
  assert.equal(fault.detail, undefined);
  const logged = logger.lines.filter((line) => line.level === "error");
  assert.equal(logged.length, 1);
  assert.match(String(logged[0]?.message), /unhandled failure/);
});

test("a bare PUT arrives as a create carrying the client-supplied id", () => {
  // CREST turns `PUT /endpoint/x/w-1` (no If-Match) into a create at the root
  // with `newResourceId: "w-1"` — probed live 2026-08-13.
  const result = demo.dispatch(
    crestRequest("create", { newResourceId: "w-1", content: { name: "n" } }),
    callContext()
  ) as { created: string };
  assert.equal(result.created, "n");
});

test("route() refuses a path capture with no validator", () => {
  assert.throws(
    () =>
      route({
        method: "read",
        path: "/{id}",
        handler: () => ({}),
      }),
    /has no validator/
  );
});

test("route() refuses a validator for a capture that is not in the path", () => {
  assert.throws(
    () =>
      route({
        method: "read",
        path: "/",
        params: { id: v.string() },
        handler: () => ({}),
      }),
    /is not in the path/
  );
});

test("route() refuses an action route with no action name", () => {
  assert.throws(
    () => route({ method: "action", path: "/", handler: () => ({}) }),
    /requires an action name/
  );
});

test("route() refuses an action name on a non-action route", () => {
  assert.throws(
    () =>
      route({
        method: "read",
        path: "/",
        action: "retire",
        handler: () => ({}),
      }),
    /only an action route/
  );
});

test("the endpoint definition survives to build time", () => {
  assert.equal(demo.definition.name, "demo");
  assert.equal(demo.definition.routes.length, 7);
  assert.equal(demo.definition.correlationHeader, "x-request-id");
});
