// The published schema and the enforced parser must agree.
//
// Every validator carries a JSON Schema fragment that the OpenAPI generator uses
// verbatim, and a `parse` the runtime enforces. Nothing checked them against each
// other: `validate.test.ts` asserts schema fragments case by case, so it catches
// the cases it happens to list and misses the rest. Mutation testing on
// 2026-08-19 confirmed the gap — publishing `maxItems` where the runtime enforces
// `minItems` passed type-check, lint, tests and build.
//
// The direction that matters is SCHEMA-ACCEPTS / PARSER-REJECTS: the document
// declares a request valid and the endpoint answers 400. The reverse, parser
// wider than schema, only under-documents what the endpoint would tolerate.
//
// So the property is asymmetric by mode:
//   strict  (JSON bodies, patch values, responses) — both directions must agree
//   coerce  (path, query, header: everything arrives as a string) — one direction,
//           because coercing "5" to 5 is the documented purpose of that mode
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import { registerSchema, validate } from "@hyperjump/json-schema/draft-2020-12";

import * as v from "../framework/validate.ts";

// A validator whose accept-set the schema deliberately does not describe. Keep
// this list SHORT and give every entry a reason — each one is a place where a
// generated client and the endpoint disagree.
const EXEMPT = new Map([
  [
    "patchOperations()",
    // `request.patchOperations` is a Java list, mirrored over the wire as an
    // index-keyed object, so the parser accepts `{ "0": {...} }` as well as an
    // array while the schema documents the array (docs/api/11-idm-endpoints.md).
    // Parser wider than schema: no request is rejected by this.
    "accepts IDM's index-keyed mirror of a Java list",
  ],
]);

const CASES = [
  ["string()", v.string()],
  ["string({minLength,maxLength})", v.string({ minLength: 2, maxLength: 4 })],
  ["string({pattern})", v.string({ pattern: /^[a-z]+$/ })],
  ["integer()", v.integer()],
  ["integer({min,max})", v.integer({ min: 1, max: 10 })],
  ["number()", v.number()],
  ["boolean()", v.boolean()],
  ["enumOf()", v.enumOf(["a", "b"])],
  ["uuid()", v.uuid()],
  ["isoDate()", v.isoDate()],
  ["unknownValue()", v.unknownValue()],
  ["nullable(string())", v.nullable(v.string())],
  ["nullable(integer())", v.nullable(v.integer())],
  ["nullable(enumOf())", v.nullable(v.enumOf(["a"]))],
  ["optional(string())", v.optional(v.string())],
  ["optional(nullable(string()))", v.optional(v.nullable(v.string()))],
  ["withDefault(integer())", v.withDefault(v.integer(), 7)],
  ["list(string())", v.list(v.string())],
  [
    "list(string(),{minItems,maxItems})",
    v.list(v.string(), { minItems: 1, maxItems: 2 }),
  ],
  ["list(object())", v.list(v.object({ a: v.string() }))],
  ["csv(string())", v.csv(v.string())],
  ["csv(integer())", v.csv(v.integer())],
  ["record(string())", v.record(v.string())],
  ["record(list(integer()))", v.record(v.list(v.integer()))],
  ["object({a})", v.object({ a: v.string() })],
  ["object({a?})", v.object({ a: v.optional(v.string()) })],
  ["object({a:withDefault})", v.object({ a: v.withDefault(v.integer(), 7) })],
  [
    "object(allowUnknown:true)",
    v.object({ known: v.string() }, { allowUnknown: true }),
  ],
  [
    "object(allowUnknown:validator)",
    v.object(
      { known: v.string() },
      { allowUnknown: v.string({ maxLength: 8 }) }
    ),
  ],
  ["object(nested)", v.object({ a: v.object({ b: v.list(v.integer()) }) })],
  ["oneOf(scalars)", v.oneOf([v.string(), v.integer()])],
  [
    "oneOf(objects)",
    v.oneOf([
      v.object({ t: v.enumOf(["a"]) }),
      v.object({ t: v.enumOf(["b"]) }),
    ]),
  ],
  [
    "discriminated()",
    v.discriminated("type", {
      a: v.object({ type: v.enumOf(["a"]), x: v.string() }),
      b: v.object({ type: v.enumOf(["b"]), y: v.integer() }),
    }),
  ],
  ["patchOperations()", v.patchOperations()],
];

// Values chosen to sit on the boundaries the validators care about: type edges,
// length/range edges, the string forms a query param really arrives as, and the
// object keys that mutate a prototype.
const VALUES = [
  null,
  true,
  false,
  0,
  1,
  -1,
  1.5,
  11,
  "",
  "a",
  "ab",
  "abcde",
  "A",
  "5",
  "5.5",
  "-3",
  "0",
  "true",
  "null",
  "a,b",
  " a ",
  "2026-08-19",
  "not-a-date",
  "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
  [],
  ["a"],
  ["a", "b"],
  ["a", "b", "c"],
  [1],
  [null],
  [{}],
  [[]],
  {},
  { a: 1 },
  { a: "x" },
  { known: "x" },
  { known: "x", extra: "y" },
  { known: "x", toString: "y" },
  { type: "a", x: "s" },
  { type: "b", y: 1 },
  { type: "c" },
  { "": 1 },
  { a: { b: [1] } },
  [{ operation: "add", field: "/x", value: 1 }],
  { 0: { operation: "add", field: "/x", value: 1 } },
];

// `JSON.parse` so the key is a real own property; a `__proto__` in an object
// literal sets the prototype instead and the key never exists.
const PROTOTYPE_KEYS = [
  '{"__proto__":{"polluted":true}}',
  '{"constructor":1}',
  '{"hasOwnProperty":"x"}',
];

function schemaChecker(name, validator) {
  const uri = "https://aic.test/schema-agreement/" + encodeURIComponent(name);
  registerSchema(
    {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      ...validator.schema,
    },
    uri
  );
  return validate(uri);
}

function parses(validator, value, mode) {
  const issues = [];
  const output = validator.parse(value, "x", issues, mode);
  return { ok: issues.length === 0, output };
}

const POOL = VALUES.concat(PROTOTYPE_KEYS.map((json) => JSON.parse(json)));

test("strict mode: schema and parser accept exactly the same values", async () => {
  const disagreements = [];
  for (const [name, validator] of CASES) {
    if (EXEMPT.has(name)) {
      continue;
    }
    const check = await schemaChecker(name, validator);
    for (const value of POOL) {
      const schemaOk = check(value).valid;
      const { ok: parserOk } = parses(validator, value, "strict");
      if (schemaOk !== parserOk) {
        disagreements.push(
          name +
            " " +
            JSON.stringify(value) +
            ": schema " +
            (schemaOk ? "accepts" : "rejects") +
            " but parser " +
            (parserOk ? "accepts" : "rejects")
        );
      }
    }
  }
  assert.deepEqual(disagreements, []);
});

test("coerce mode: everything the schema accepts, the parser accepts", async () => {
  // Not the reverse: coerce mode exists to turn the strings a path/query/header
  // value arrives as into the declared type, so the parser is deliberately wider.
  const rejected = [];
  for (const [name, validator] of CASES) {
    if (EXEMPT.has(name)) {
      continue;
    }
    const check = await schemaChecker(name + "#coerce", validator);
    for (const value of POOL) {
      if (!check(value).valid) {
        continue;
      }
      if (!parses(validator, value, "coerce").ok) {
        rejected.push(name + " " + JSON.stringify(value));
      }
    }
  }
  assert.deepEqual(rejected, []);
});

test("the property can fail — a divergent schema is caught", async () => {
  // Otherwise both assertions above could pass by never comparing anything.
  const honest = v.list(v.string(), { minItems: 2 });
  const divergent = {
    ...honest,
    schema: { type: "array", items: { type: "string" }, maxItems: 2 },
  };
  const check = await schemaChecker("mutant", divergent);
  const value = ["a"];
  assert.equal(
    check(value).valid,
    true,
    "the divergent schema accepts one item"
  );
  assert.equal(
    parses(divergent, value, "strict").ok,
    false,
    "while the parser still demands two"
  );
});

test("every exemption names a validator that exists", () => {
  const names = new Set(CASES.map(([name]) => name));
  for (const name of EXEMPT.keys()) {
    assert.ok(names.has(name), name + " is exempted but not exercised");
  }
});
