// Guards the compiler options themselves, which no other gate can see.
//
// Widening `lib`, or dropping `noUncheckedIndexedAccess` or
// `exactOptionalPropertyTypes`, breaks NOTHING immediately: every other gate
// stays green, because relaxing a check cannot fail a check. What it does is let
// runtime-impossible code start type-checking later — `Object.entries` where the
// engine has it but ES2017 is not admitted, an unchecked index access where IDM
// hands back `undefined`. Verified by mutation on 2026-08-19: each of those three
// edits passed type-check, lint, tests and build.
//
// `strict: false` is the one that does break the build, and it is asserted here
// anyway, so the reason is recorded rather than rediscovered.
//
// The pinned `lib` matches the verified IDM column of
// `docs/api/12-script-bindings-matrix.md`: the ES2015 collections, `Symbol` and
// `Promise` are present on the endpoint engine; `Proxy` and `Reflect` are not.
// Changing a row here means probing the engine first, not adjusting the test.
//
// Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const PROJECT_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");

const read = (name) =>
  JSON.parse(readFileSync(join(PROJECT_DIR, name), "utf8"));

const ENDPOINT_LIB = [
  "ES5",
  "ES2015.Core",
  "ES2015.Collection",
  "ES2015.Iterable",
  "ES2015.Symbol",
  "ES2015.Symbol.WellKnown",
  "ES2015.Promise",
  "ES2016.Array.Include",
];

test("the endpoint program's lib is pinned to the verified IDM surface", () => {
  assert.deepEqual(read("tsconfig.json").compilerOptions.lib, ENDPOINT_LIB);
});

test("the strictness that makes the types load-bearing is on", () => {
  const options = read("tsconfig.json").compilerOptions;
  for (const flag of [
    "strict",
    "exactOptionalPropertyTypes",
    "noUncheckedIndexedAccess",
    "noImplicitOverride",
    "noImplicitReturns",
    "noFallthroughCasesInSwitch",
    "noPropertyAccessFromIndexSignature",
    "erasableSyntaxOnly",
    "verbatimModuleSyntax",
    "isolatedModules",
  ]) {
    assert.equal(options[flag], true, flag + " must stay enabled");
  }
  // `skipLibCheck: false` is the unusual one — the hand-written .d.ts files in
  // `framework/` are the tenant's contract, so they must be checked.
  assert.equal(options.skipLibCheck, false);
});

test("the test program widens the lib and nothing else", () => {
  const tests = read("tsconfig.tests.json");
  assert.equal(tests.extends, "./tsconfig.json");
  // Tests run under node, so they get a modern lib and node types. Any OTHER
  // override would silently relax a check for the framework sources, which this
  // program also compiles.
  assert.deepEqual(Object.keys(tests.compilerOptions).sort(), ["lib", "types"]);
});
