// Validation combinators. Managed file — regenerated by `aic workspace update`.

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  defineEndpoint,
  route,
  type Issue,
  type ObjectOptions,
  type Shape,
  type Validator,
} from "../framework/index.ts";
import * as v from "../framework/validate.ts";

function run<T>(validator: Validator<T>, input: unknown, mode: "strict" | "coerce" = "strict") {
  const issues: Issue[] = [];
  const value = validator.parse(input, "x", issues, mode);
  return { value, issues };
}

const boundedString = v.string({
  minLength: 2,
  maxLength: 4,
  pattern: /^[a-z]+$/,
});
const boundedInteger = v.integer({ min: 1, max: 100 });
const bool = v.boolean();
const optionalString = v.optional(v.string());
const defaultInteger = v.withDefault(v.integer({ min: 0 }), 20);
const commaList = v.csv(v.string({ minLength: 1 }));
const boundedList = v.list(v.string(), { minItems: 1, maxItems: 2 });
const fixedObject = v.object({
  name: v.string({ minLength: 1 }),
  note: v.optional(v.string()),
});
const union = v.oneOf([v.string({ minLength: 2 }), v.integer({ min: 1 })]);
const overlappingUnion = v.oneOf([v.string(), v.enumOf(["red", "green"])]);
const objectUnion = v.oneOf([
  v.object({ kind: v.enumOf(["a"]), a: v.string() }),
  v.object({ kind: v.enumOf(["b"]), b: v.integer() }),
]);
const tagged = v.discriminated("type", {
  date: v.object({
    type: v.enumOf(["date"]),
    format: v.string({ minLength: 1 }),
  }),
  string: v.object({
    type: v.enumOf(["string"]),
    minLength: v.integer({ min: 0 }),
  }),
});

type Expected = { value?: unknown; messages?: string[]; paths?: string[] };
type ParseCase = readonly [name: string, validator: Validator<unknown>, input: unknown, expected: Expected];

function accepted(
  name: string,
  validator: Validator<unknown>,
  input: unknown,
  value: unknown
): ParseCase {
  return [name, validator, input, { value }];
}

function rejected(
  name: string,
  validator: Validator<unknown>,
  input: unknown,
  message: string,
  path?: string
): ParseCase {
  return [name, validator, input, {
    messages: [message],
    ...(path === undefined ? {} : { paths: [path] }),
  }];
}

const describedPattern = v.string({
  pattern: /^w-/,
  patternDescription: "start with w-",
});
const csvEnum = v.csv(v.enumOf(["owner", "history"]));
const nullableString = v.nullable(v.string());
const maybeString = v.optional(v.nullable(v.string()));
const shortRecord = v.record(v.string({ maxLength: 2 }));
const INTEGER = "expected an integer";
/** An absent optional is ABSENT in the parsed value, not a key holding `undefined`. */
const PARSED_OBJECT = { name: "a" };
const EXPLICIT_UNDEFINED = { name: "a", note: undefined };

const parseCases: ParseCase[] = [
  accepted("string: valid", boundedString, "abc", "abc"),
  rejected("string: minimum", boundedString, "a", "must be at least 2 characters"),
  rejected("string: maximum", boundedString, "abcde", "must be at most 4 characters"),
  rejected("string: pattern", boundedString, "AB", "must match /^[a-z]+$/"),
  rejected("string: wrong type", boundedString, 7, "expected a string"),
  rejected("string: described pattern", describedPattern, "nope", "must start with w-"),
  rejected("integer: strict string", boundedInteger, "42", INTEGER),
  accepted("integer: native number", boundedInteger, 42, 42),
  rejected("integer: fraction", boundedInteger, 1.5, INTEGER),
  rejected("integer: blank", boundedInteger, "", INTEGER),
  rejected("integer: non-numeric", boundedInteger, "nope", INTEGER),
  rejected("integer: minimum", boundedInteger, 0, "must be at least 1"),
  rejected("integer: maximum", boundedInteger, 101, "must be at most 100"),
  accepted("number: fraction", v.number(), 1.5, 1.5),
  rejected("boolean: true string", bool, "true", "expected true or false"),
  rejected("boolean: false string", bool, "false", "expected true or false"),
  accepted("boolean: native", bool, true, true),
  rejected("boolean: invalid string", bool, "yes", "expected true or false"),
  accepted("optional: undefined", optionalString, undefined, undefined),
  rejected("optional: null", optionalString, null, "expected a string"),
  accepted("optional: empty string is a value", optionalString, "", ""),
  accepted("optional: present", optionalString, "x", "x"),
  accepted("nullable: explicit null", nullableString, null, null),
  accepted("nullable: present", nullableString, "x", "x"),
  rejected("nullable: wrong type", nullableString, 7, "expected a string"),
  accepted("nullable+optional: absent", maybeString, undefined, undefined),
  accepted("nullable+optional: null", maybeString, null, null),
  accepted("default: absent", defaultInteger, undefined, 20),
  accepted("default: present", defaultInteger, 3, 3),
  accepted("csv: array", commaList, ["a", "b"], ["a", "b"]),
  rejected("csv: strict string", csvEnum, "owner,nope", "expected a comma-separated list"),
  rejected("list: minimum", boundedList, [], "must have at least 1 items"),
  rejected("list: maximum", boundedList, ["a", "b", "c"], "must have at most 2 items"),
  rejected("list: wrong type", boundedList, "a", "expected an array"),
  accepted("object: declared fields", fixedObject, { name: "a" }, PARSED_OBJECT),
  accepted(
    "object: an explicit undefined is still absent",
    fixedObject,
    EXPLICIT_UNDEFINED,
    PARSED_OBJECT
  ),
  accepted(
    "object: a nullable member keeps its null",
    v.object({ note: v.nullable(v.string()) }),
    { note: null },
    { note: null }
  ),
  accepted(
    "object: a defaulted member is present even when absent",
    v.object({ limit: v.withDefault(v.integer(), 20) }),
    {},
    { limit: 20 }
  ),
  rejected("object: required field", fixedObject, {}, "is required", "x.name"),
  rejected("object: unknown field", fixedObject, { name: "a", extra: 1 }, "is not a known field"),
  rejected("object: wrong type", fixedObject, [], "expected an object"),
  accepted(
    "open object: retains unknown members",
    v.object({ known: v.string() }, { allowUnknown: true }),
    { known: "a", extra: "b", alsoExtra: "c" },
    { known: "a", extra: "b", alsoExtra: "c" }
  ),
  rejected(
    "open object: validates a remainder member at its path",
    v.object({ known: v.string() }, { allowUnknown: v.string({ maxLength: 2 }) }),
    { known: "a", long: "nope" },
    "must be at most 2 characters",
    "x.long"
  ),
  rejected("record: value path", shortRecord, { a: "xyz" }, "must be at most 2 characters", "x.a"),
  rejected("patch: operation name", v.patchOperations(), [{ operation: "frobnicate", field: "/x" }], "must be one of: add, remove, replace, increment, move, copy, transform"),
  rejected("UUID: pattern", v.uuid(), "not-a-uuid", "must be a UUID"),
  rejected("ISO date: pattern", v.isoDate(), "2026-13", "must be a date in YYYY-MM-DD form"),
  rejected("ISO date: calendar", v.isoDate(), "2026-02-29", "must be a date in YYYY-MM-DD form"),
  accepted("ISO date: leap year", v.isoDate(), "2028-02-29", "2028-02-29"),
  accepted("oneOf: first alternative", union, "ok", "ok"),
  accepted("oneOf: second alternative", union, 2, 2),
  accepted("oneOf: overlapping first alternative", overlappingUnion, "red", "red"),
  rejected("oneOf: nothing matches", union, false, "must be one of: string, integer", "x"),
  rejected("oneOf: unique closest branch", objectUnion, { kind: "b", b: "no" }, "expected an integer", "x.b"),
  accepted("nullable oneOf: null", v.nullable(union), null, null),
  accepted("nullable discriminated: null", v.nullable(tagged), null, null),
  accepted("optional oneOf: absent object member", v.object({ choice: v.oneOf([v.optional(v.string()), v.integer()]) }), {}, {}),
  rejected("discriminated: missing tag", tagged, { format: "date" }, "is required", "x.type"),
  rejected("discriminated: unknown tag", tagged, { type: "number" }, "must be one of: date, string", "x.type"),
  rejected("discriminated: branch failure keeps its path", tagged, { type: "date", format: "" }, "must be at least 1 characters", "x.format"),
  rejected("discriminated: inside a list", v.list(tagged), [{ type: "date", format: "" }], "must be at least 1 characters", "x[0].format"),
];

for (const [name, validator, input, expected] of parseCases) {
  test(name, () => {
    const parsed = run(validator, input);
    if ("value" in expected) {
      assert.deepEqual(parsed.value, expected.value);
    }
    if (expected.messages !== undefined) {
      assert.deepEqual(
        parsed.issues.map((issue) => issue.message),
        expected.messages
      );
    }
    if (expected.paths !== undefined) {
      assert.deepEqual(
        parsed.issues.map((issue) => issue.path),
        expected.paths
      );
    }
    if (expected.messages === undefined && expected.paths === undefined) {
      assert.deepEqual(parsed.issues, []);
    }
  });
}

test("enumOf preserves its literal union", () => {
  const validator = v.enumOf(["active", "retired", "draft"]);
  const parsed = run(validator, "retired");
  const narrowed: "active" | "retired" | "draft" = parsed.value;
  assert.equal(narrowed, "retired");
});

test("unions compose in lists, objects, and optional members", () => {
  const validator = v.object({
    choices: v.list(union),
    fields: v.list(tagged),
    fallback: v.optional(union),
    selected: v.optional(tagged),
  });
  const value = {
    choices: ["ok", 2],
    fields: [
      { type: "date", format: "iso" },
      { type: "string", minLength: 1 },
    ],
  };
  assert.deepEqual(run(validator, value), { value, issues: [] });
});

test("union inference narrows discriminated members", () => {
  const parsed = run(tagged, { type: "date", format: "iso" }).value;
  if (parsed.type === "date") {
    const format: string = parsed.format;
    void format;
    // @ts-expect-error the date branch has no string length constraint
    void parsed.minLength;
  } else {
    const minLength: number = parsed.minLength;
    void minLength;
    // @ts-expect-error the string branch has no date format
    void parsed.format;
  }
  const choice: string | number = run(union, 2).value;
  void choice;

  // @ts-expect-error each branch must declare its tag
  v.discriminated("type", { date: v.object({ format: v.string() }) });
  // @ts-expect-error a branch's declared tag must equal its map key
  v.discriminated("type", { date: v.object({ type: v.enumOf(["string"]) }) });
  // @ts-expect-error a discriminated union needs at least one branch
  v.discriminated("type", {});
});

test("coercion remains available for URL and header-shaped inputs", () => {
  assert.deepEqual(run(boundedInteger, "42", "coerce"), {
    value: 42,
    issues: [],
  });
  assert.deepEqual(run(bool, "true", "coerce"), { value: true, issues: [] });
  assert.deepEqual(run(optionalString, "", "coerce"), {
    value: undefined,
    issues: [],
  });
  assert.deepEqual(run(commaList, "a, b ,,c", "coerce"), {
    value: ["a", "b", "c"],
    issues: [],
  });
});

test("stateful regular expressions give stable results across requests", () => {
  const validator = v.string({ pattern: /^a+$/g });
  assert.deepEqual(run(validator, "aaa").issues, []);
  assert.deepEqual(run(validator, "aaa").issues, []);
  assert.equal(run(validator, "bbb").issues.length, 1);
  assert.deepEqual(run(validator, "aaa").issues, []);
});

test("an absent optional does not become a key", () => {
  const parsed = run(fixedObject, { name: "a" }).value as Record<
    string,
    unknown
  >;
  assert.equal("note" in parsed, false);
  assert.deepEqual(Object.keys(parsed), ["name"]);
});

test("object collects every failure", () => {
  const validator = v.object({
    name: v.string({ minLength: 3 }),
    count: v.integer({ min: 1 }),
  });
  assert.equal(run(validator, { name: "a", count: 0 }).issues.length, 2);
});

test("open object retains and validates members in coerce mode", () => {
  assert.deepEqual(
    run(
      v.object({ known: v.string() }, { allowUnknown: v.integer() }),
      { known: "a", count: "42" },
      "coerce"
    ),
    { value: { known: "a", count: 42 }, issues: [] }
  );
});

test("object overloads preserve mixed response and compatibility call shapes", () => {
  const mixed = v.object(
    { n: v.integer(), s: v.string() },
    { allowUnknown: v.string() }
  );
  const endpoint = defineEndpoint({
    name: "mixed-open-response",
    routes: [route({ method: "read", path: "/thing", response: mixed, handler: () => ({ n: 1, s: "a" }) })],
  });
  function wrap<S extends Shape>(shape: S, options: ObjectOptions) {
    return v.object(shape, options);
  }
  const wrapped = wrap({ k: v.string() }, { allowUnknown: true });
  const openOptions: ObjectOptions = { allowUnknown: true };
  const closedOptions: ObjectOptions = {};
  const conditional = v.object({ k: v.string() }, openOptions);
  const conditionalClosed = v.object({ k: v.string() }, closedOptions);
  const parsed = run(mixed, { n: 1, s: "a" }).value;
  const known: number = parsed.n;
  const remainder: string | number | undefined = parsed["other"];
  assert.equal(known, 1);
  assert.equal(remainder, undefined);
  assert.equal(endpoint.definition.name, "mixed-open-response");
  assert.equal(wrapped.schema["type"], "object");
  assert.equal(conditional.schema["type"], "object");
  assert.equal(conditionalClosed.schema["additionalProperties"], false);

  const openUnknown = v.object({ known: v.string() }, { allowUnknown: true });
  const unknownMember: unknown = run(openUnknown, { known: "a" }).value["other"];
  assert.equal(unknownMember, undefined);
  const closedObject = v.object({ known: v.string() });
  // @ts-expect-error a closed object has no index signature
  const closedMember = closedObject.parse({ known: "a" }, "x", [])["other"];  // eslint-disable-line @typescript-eslint/no-unsafe-assignment -- the expected error makes this error-typed
  assert.equal(closedMember, undefined);
});

test("open objects and records report dangerous keys", () => {
  const dangerous = ["__proto__", "constructor", "prototype", "hasOwnProperty", "toString", "valueOf"];
  const validators: Validator<unknown>[] = [
    v.object({}, { allowUnknown: true }),
    v.object({}, { allowUnknown: v.record(v.unknownValue()) }),
    v.record(v.unknownValue()),
  ];
  for (const validator of validators) {
    for (const key of dangerous) {
      const parsed = run(validator, JSON.parse('{"' + key + '":{}}'));
      assert.deepEqual(parsed.issues, [{ path: "x." + key, message: "is not a safe object key" }]);
      assert.equal(Object.getPrototypeOf(parsed.value), Object.prototype);
      assert.equal(Object.prototype.hasOwnProperty.call(parsed.value, key), false);
    }
  }

  const nested = run(
    v.object({}, { allowUnknown: v.record(v.unknownValue()) }),
    JSON.parse('{"outer":{"__proto__":{}}}')
  );
  assert.deepEqual(nested.issues, [
    { path: "x.outer.__proto__", message: "is not a safe object key" },
  ]);
  assert.deepEqual(nested.value, {});
});

test("a null allowUnknown from JavaScript remains closed", () => {
  const fromJavaScript = v.object(
    { known: v.string() },
    { allowUnknown: null } as unknown as ObjectOptions
  );
  assert.equal(fromJavaScript.schema["additionalProperties"], false);
  assert.deepEqual(run(fromJavaScript, { known: "a", extra: 1 }).issues, [
    { path: "x.extra", message: "is not a known field" },
  ]);
});

test("allowUnknown true conserves keys whenever parsing succeeds", () => {
  const validator = v.object({ known: v.string() }, { allowUnknown: true });
  const names = ["alpha", "beta", "gamma", "delta"];
  for (let mask = 0; mask < 16; mask += 1) {
    const source: Record<string, unknown> = { known: "a" };
    for (let index = 0; index < names.length; index += 1) {
      if ((mask & (1 << index)) !== 0) {
        source[names[index] as string] = index;
      }
    }
    const parsed = run(validator, source);
    if (parsed.issues.length === 0) {
      assert.deepEqual(Object.keys(parsed.value), Object.keys(source));
    }
  }
});

test("an optional remainder does not create absent keys in coerce mode", () => {
  const parsed = run(
    v.object({ known: v.string() }, { allowUnknown: v.optional(v.string()) }),
    { known: "a", blank: "", nulled: null },
    "coerce"
  );
  assert.deepEqual(parsed, { value: { known: "a" }, issues: [] });
});

test("record returns every valid member", () => {
  assert.deepEqual(run(v.record(v.string()), { a: "x", b: "y" }).value, {
    a: "x",
    b: "y",
  });
});

test("patch operations accept IDM's index-keyed Java-list mirror", () => {
  const parsed = run(v.patchOperations({ minItems: 1 }), {
    "0": { operation: "replace", field: "/name", value: "n" },
    "1": { operation: "remove", field: "/tags" },
  });
  assert.deepEqual(parsed.issues, []);
  assert.deepEqual(
    parsed.value.map(({ operation, field }) => ({ operation, field })),
    [
      { operation: "replace", field: "/name" },
      { operation: "remove", field: "/tags" },
    ]
  );
});

const schemaCases: readonly (readonly [string, unknown, unknown])[] = [
  ["enum schema lists its alternatives", v.enumOf(["a", "b"]).schema["enum"], ["a", "b"]],
  ["optional marks itself optional", optionalString.isOptional, true],
  ["default reaches JSON Schema", defaultInteger.schema["default"], 20],
  ["object schema lists only required members", v.object({
      name: v.string(),
      note: optionalString,
      limit: defaultInteger,
    }).schema["required"], ["name"]],
  ["object schema rejects extra members", fixedObject.schema["additionalProperties"], false],
  ["object schema permits untyped extra members", v.object({}, { allowUnknown: true }).schema["additionalProperties"], true],
  ["object schema describes validated extra members", v.object({}, { allowUnknown: v.string({ maxLength: 8 }) }).schema["additionalProperties"], { type: "string", maxLength: 8 }],
  ["UUID schema carries a pattern", typeof v.uuid().schema["pattern"], "string"],
  // OpenAPI 3.1 is JSON Schema 2020-12: a union `type`, not `nullable: true`.
  ["nullable widens the schema type", nullableString.schema["type"], ["string", "null"]],
  ["nullable widens an enum too", v.nullable(v.enumOf(["a"])).schema["enum"], ["a", null]],
  ["oneOf emits anyOf for overlapping alternatives", overlappingUnion.schema, { anyOf: [
    { type: "string" },
    { type: "string", enum: ["red", "green"] },
  ] }],
  ["nullable widens a oneOf union too", v.nullable(union).schema, { anyOf: [
    union.schema,
    { type: "null" },
  ] }],
  ["nullable widens a discriminated union too", v.nullable(tagged).schema, { anyOf: [
    tagged.schema,
    { type: "null" },
  ] }],
  ["oneOf forwards optionality", v.oneOf([v.optional(v.string()), v.integer()]).isOptional, true],
  ["nullable is about the value, not presence", nullableString.isOptional, false],
  ["nullable inside optional stays optional", maybeString.isOptional, true],
];

for (const [name, actual, expected] of schemaCases) {
  test(name, () => assert.deepEqual(actual, expected));
}

test("parseShape locates a missing required member", () => {
  const issues: Issue[] = [];
  const parsed = v.parseShape(
    { limit: v.integer(), cursor: v.optional(v.string()) },
    "query",
    (key) => ({ cursor: "abc" })[key as "cursor"],
    issues
  );
  assert.equal(issues[0]?.path, "query.limit");
  assert.equal(parsed.cursor, "abc");
});

test("an open object publishes the keys its runtime refuses", () => {
  // The defect this guards: `additionalProperties: true` with nothing saying
  // which names are refused, so the OpenAPI document promised a request the
  // endpoint answered with 400.
  const open = v.object({}, { allowUnknown: true });
  assert.deepEqual(open.schema["propertyNames"], {
    not: { enum: v.DANGEROUS_OBJECT_KEYS.slice() },
  });
  assert.deepEqual(v.record(v.string()).schema["propertyNames"], {
    not: { enum: v.DANGEROUS_OBJECT_KEYS.slice() },
  });
  // A closed object rejects every unknown key already; saying it twice would be
  // noise in the document.
  assert.equal(v.object({}).schema["propertyNames"], undefined);
});

test("schema and runtime agree on every dangerous key, in both directions", () => {
  const open = v.object({}, { allowUnknown: true });
  const published = (
    open.schema["propertyNames"] as { not: { enum: string[] } }
  ).not.enum;
  for (const key of v.DANGEROUS_OBJECT_KEYS) {
    const issues: v.Issue[] = [];
    open.parse({ [key]: "x" }, "body", issues, "strict");
    assert.equal(issues.length, 1, key + " must be refused at runtime");
    assert.ok(published.includes(key), key + " must be published as refused");
  }
  // …and the list is not simply everything: an ordinary key still gets through.
  const issues: v.Issue[] = [];
  const kept = open.parse({ safeKey: "x" }, "body", issues, "strict");
  assert.deepEqual(issues, []);
  assert.deepEqual(kept, { safeKey: "x" });
});

test("a collection refuses an optional element, and points at nullable", () => {
  // `optional()` inside a collection produced a value the collection's own schema
  // rejects: in coerce mode it maps `null` to `undefined`, so `[null]` parsed to
  // `[undefined]`, which serialises back as `[null]` against `items: {type:"string"}`.
  for (const build of [
    () => v.list(v.optional(v.string())),
    () => v.csv(v.optional(v.string())),
    () => v.record(v.optional(v.string())),
  ]) {
    assert.throws(build, /cannot be optional/);
  }
  // `withDefault` is optional too — it substitutes for an absent input, which is
  // equally meaningless at an index.
  assert.throws(() => v.list(v.withDefault(v.string(), "x")), /cannot be optional/);
});

test("nullable is the element combinator for may-be-empty, and round-trips", () => {
  const rows = v.list(v.nullable(v.string()));
  const issues: v.Issue[] = [];
  assert.deepEqual(rows.parse(["a", null], "body", issues, "strict"), ["a", null]);
  assert.deepEqual(issues, []);
  assert.deepEqual((rows.schema["items"] as Record<string, unknown>)["type"], [
    "string",
    "null",
  ]);
});
