// GENERATED by scripts/gen-binding-types.mjs --library-args — do not edit by
// hand. See the regenerate command at the bottom of this file.
//
// Types a caller can hand a library script. A library sees none of the
// per-context globals (verified 2026-07-29 — docs/api/12-script-bindings-matrix.md),
// so it takes them as arguments, and the argument types have to exist in library
// scope or the factory signature cannot be written. One declaration per binding,
// merged across every next-gen context that can require() a library; where two
// contexts describe the same binding differently, the members are unioned, so a
// member here may not exist in the context that actually calls the library.
//
// `NodeState` is NOT here — library.d.ts hand-writes a better one.
// Applied metadata refinements:
//   - `AccessToken.getField` returns `any`, not metadata's bare `object`.
//   - `AccessToken.setField` accepts `TokenFieldValue`, not metadata's bare `object`.
//   - `Identity.getAttributeValues` adds the typed `AmUserAttribute` overload first.
//   - `Token.getField` returns `any`, not metadata's bare `object`.
//   - Fluent builder methods return their own interface, not metadata's bare `object`.

// A custom access-token field: any JSON-ish scalar, array, or object. Whatever
// you set here lands in the CTS entry, or as a JWT claim for client-based
// tokens — keep it small.
type TokenFieldValue = StringLike | number | boolean | any[] | object;

// OAUTH2_ACCESS_TOKEN_MODIFICATION_NEXT_GEN, OAUTH2_EVALUATE_SCOPE_NEXT_GEN
interface AccessToken {
  getField(key: StringLike): any;
  toMap(): object;
  getPermissions(): object;
  getScope(): any[];
  setPermissions(permissions: object): void;
  setFields(fields: object): void;
  setField(field: StringLike, value: TokenFieldValue): void;
  setNonce(nonce: StringLike): void;
  getNonce(): StringLike;
  getRealm(): StringLike;
  setRealm(realm: StringLike): void;
  setScope(scopes: any[]): void;
  removeRealm(): void;
  getAudience(): any[];
  setId(tokenId: StringLike): void;
  getAuditTrackingId(): StringLike;
  isExpired(): boolean;
  getResourceOwnerId(): StringLike;
  getAuthTimeSeconds(): number;
  getAct(): object;
  getMayAct(): object;
  setAct(value: object): void;
  setMayAct(value: object): void;
  getCustomFields(): object;
  getAuthGrantId(): StringLike;
  getTokenId(): StringLike;
  getAuthLevel(): number;
  getExpiryTime(): number;
  setAuthLevel(authLevel: number): void;
  getClaims(): StringLike;
  getClientId(): StringLike;
  getGrantType(): StringLike;
  getTokenType(): StringLike;
  getConfirmationKey(): object;
  addExtraData(key: StringLike, value: StringLike): void;
  getResourceOwner(): object;
  setClientId(clientId: StringLike): void;
  setResourceOwnerId(resourceOwnerId: StringLike): void;
  getTokenInfo(): object;
  getTokenName(): StringLike;
  setClaims(claims: StringLike): void;
  setExpiryTime(expiryTime: number): void;
  removeConfirmationKey(): void;
  addExtraJsonData(key: StringLike, value: object): void;
  setAuditTrackingId(auditTrackingId: StringLike): void;
  removeAuditTrackingId(): void;
  removePermissions(): void;
  setAuthGrantId(authGrantId: StringLike): void;
  removeAuthGrantId(): void;
  removeClientId(): void;
  removeResourceOwnerId(): void;
  removeScopes(): void;
  setAuthTime(authTime: number): void;
  removeAuthTime(): void;
  removeAuthLevel(): void;
  setTokenName(tokenName: StringLike): void;
  removeTokenName(): void;
  removeNonce(): void;
  removeClaims(): void;
  setTokenType(tokenType: StringLike): void;
  removeTokenType(): void;
  setGrantType(grantType: StringLike): void;
  removeGrantType(): void;
  setConfirmationKey(confirmationKey: object): void;
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE, PINGONE_VERIFY_COMPLETION_DECISION_NODE
interface Action {
  withIdentifiedUser(username: StringLike): Action;
  withIdentifiedAgent(agentName: StringLike): Action;
  goTo(outcome: StringLike): Action;
  suspend(
    callbackTextFormat: StringLike,
    additionalLogic: object,
    maximumSuspendDuration: number
  ): Action;
  suspend(callbackTextFormat: StringLike): Action;
  suspend(callbackTextFormat: StringLike, additionalLogic: object): Action;
  withHeader(header: StringLike): Action;
  withStage(stage: StringLike): Action;
  putSessionProperty(key: StringLike, value: StringLike): Action;
  withDescription(description: StringLike): Action;
  withErrorMessage(errorMessage: StringLike): Action;
  withLockoutMessage(lockoutMessage: StringLike): Action;
  removeSessionProperty(key: StringLike): Action;
  withMaxSessionTime(maxSessionTime: number): Action;
  withMaxIdleTime(maxIdleTime: number): Action;
}

// SCRIPTED_DECISION_NODE
interface CacheManager {
  exists(cacheName: StringLike): boolean;
  named(cacheName: StringLike): object;
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE
interface Callbacks {
  isEmpty(): boolean;
  getNameCallbacks(): any[];
  getPasswordCallbacks(): any[];
  getHiddenValueCallbacks(): object;
  getDeviceProfileCallbacks(): any[];
  getKbaCreateCallbacks(): any[];
  getSelectIdPCallbacks(): any[];
  getTermsAndConditionsCallbacks(): any[];
  getTextInputCallbacks(): any[];
  getStringAttributeInputCallbacks(): any[];
  getNumberAttributeInputCallbacks(): any[];
  getBooleanAttributeInputCallbacks(): any[];
  getConfirmationCallbacks(): any[];
  getLanguageCallbacks(): any[];
  getIdpCallbacks(): any[];
  getValidatedPasswordCallbacks(): any[];
  getValidatedUsernameCallbacks(): any[];
  getHttpCallbacks(): any[];
  getX509CertificateCallbacks(): any[];
  getConsentMappingCallbacks(): any[];
  getChoiceCallbacks(): any[];
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE
interface CallbacksBuilder {
  suspendedTextOutputCallback(messageType: number, message: StringLike): void;
  textInputCallback(prompt: StringLike, defaultText: StringLike): void;
  textInputCallback(prompt: StringLike): void;
  scriptTextOutputCallback(message: StringLike): void;
  languageCallback(language: StringLike, country: StringLike): void;
  idPCallback(
    provider: StringLike,
    clientId: StringLike,
    redirectUri: StringLike,
    scope: any[],
    nonce: StringLike,
    request: StringLike,
    requestUri: StringLike,
    acrValues: any[],
    requestNativeAppForUserInfo: boolean
  ): void;
  idPCallback(
    provider: StringLike,
    clientId: StringLike,
    redirectUri: StringLike,
    scope: any[],
    nonce: StringLike,
    request: StringLike,
    requestUri: StringLike,
    acrValues: any[],
    requestNativeAppForUserInfo: boolean,
    token: StringLike,
    tokenType: StringLike
  ): void;
  httpCallback(
    authRHeader: StringLike,
    negoName: StringLike,
    negoValue: StringLike,
    errorCode: number
  ): void;
  httpCallback(
    authorizationHeader: StringLike,
    negotiationHeader: StringLike,
    errorCode: StringLike
  ): void;
  x509CertificateCallback(
    prompt: StringLike,
    certificate: object,
    requestSignature: boolean
  ): void;
  x509CertificateCallback(prompt: StringLike, certificate: object): void;
  x509CertificateCallback(prompt: StringLike): void;
  consentMappingCallback(
    name: StringLike,
    displayName: StringLike,
    icon: StringLike,
    accessLevel: StringLike,
    titles: any[],
    message: StringLike,
    isRequired: boolean
  ): void;
  consentMappingCallback(
    config: object,
    message: StringLike,
    isRequired: boolean
  ): void;
  deviceProfileCallback(
    metadata: boolean,
    location: boolean,
    message: StringLike
  ): void;
  kbaCreateCallback(
    prompt: StringLike,
    predefinedQuestions: any[],
    allowUserDefinedQuestions: boolean
  ): void;
  selectIdPCallback(providers: object): void;
  termsAndConditionsCallback(
    version: StringLike,
    terms: StringLike,
    createDate: StringLike
  ): void;
  metadataCallback(outputValue: object): void;
  stringAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: StringLike,
    required: boolean,
    policies: object,
    validateOnly: boolean,
    failedPolicies: any[]
  ): void;
  stringAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: StringLike,
    required: boolean
  ): void;
  stringAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: StringLike,
    required: boolean,
    failedPolicies: any[]
  ): void;
  stringAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: StringLike,
    required: boolean,
    policies: object,
    validateOnly: boolean
  ): void;
  numberAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: number,
    required: boolean,
    policies: object,
    validateOnly: boolean,
    failedPolicies: any[]
  ): void;
  numberAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: number,
    required: boolean
  ): void;
  numberAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: number,
    required: boolean,
    failedPolicies: any[]
  ): void;
  numberAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: number,
    required: boolean,
    policies: object,
    validateOnly: boolean
  ): void;
  booleanAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: boolean,
    required: boolean,
    policies: object,
    validateOnly: boolean,
    failedPolicies: any[]
  ): void;
  booleanAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: boolean,
    required: boolean
  ): void;
  booleanAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: boolean,
    required: boolean,
    failedPolicies: any[]
  ): void;
  booleanAttributeInputCallback(
    name: StringLike,
    prompt: StringLike,
    value: boolean,
    required: boolean,
    policies: object,
    validateOnly: boolean
  ): void;
  pollingWaitCallback(waitTime: StringLike, message: StringLike): void;
  confirmationCallback(
    messageType: number,
    options: any[],
    defaultOption: number
  ): void;
  confirmationCallback(
    prompt: StringLike,
    messageType: number,
    options: any[],
    defaultOption: number
  ): void;
  confirmationCallback(
    prompt: StringLike,
    messageType: number,
    optionType: number,
    defaultOption: number
  ): void;
  confirmationCallback(
    messageType: number,
    optionType: number,
    defaultOption: number
  ): void;
  textOutputCallback(messageType: number, message: StringLike): void;
  choiceCallback(
    prompt: StringLike,
    choices: any[],
    defaultChoice: number,
    multipleSelectionsAllowed: boolean
  ): void;
  redirectCallback(
    redirectUrl: StringLike,
    redirectData: object,
    method: StringLike
  ): void;
  redirectCallback(
    redirectUrl: StringLike,
    redirectData: object,
    method: StringLike,
    statusParameter: StringLike,
    redirectBackUrlCookie: StringLike,
    setTrackingCookie: boolean
  ): void;
  redirectCallback(
    redirectUrl: StringLike,
    redirectData: object,
    method: StringLike,
    setTrackingCookie: boolean
  ): void;
  redirectCallback(
    redirectUrl: StringLike,
    redirectData: object,
    method: StringLike,
    statusParameter: StringLike,
    redirectBackUrlCookie: StringLike
  ): void;
  hiddenValueCallback(id: StringLike, value: StringLike): void;
  nameCallback(prompt: StringLike, defaultName: StringLike): void;
  nameCallback(prompt: StringLike): void;
  passwordCallback(prompt: StringLike, echoOn: boolean): void;
  validatedUsernameCallback(
    prompt: StringLike,
    policies: object,
    validateOnly: boolean
  ): void;
  validatedUsernameCallback(
    prompt: StringLike,
    policies: object,
    validateOnly: boolean,
    failedPolicies: any[]
  ): void;
  validatedPasswordCallback(
    prompt: StringLike,
    echoOn: boolean,
    policies: object,
    validateOnly: boolean
  ): void;
  validatedPasswordCallback(
    prompt: StringLike,
    echoOn: boolean,
    policies: object,
    validateOnly: boolean,
    failedPolicies: any[]
  ): void;
}

// OAUTH2_DYNAMIC_CLIENT_REGISTRATION
interface ClientIdentity {
  getName(): StringLike;
  store(): void;
  setAttribute(attributeName: StringLike, attributeValues: any[]): void;
  addAttribute(attributeName: StringLike, attributeValue: StringLike): void;
  setDisplayName(displayName: any[]): object;
  setScope(allowedGrantScopes: any[]): object;
  getAttributeValues(attributeName: StringLike): any[];
  getUniversalId(): StringLike;
  setClientSecret(clientSecret: StringLike): object;
  setClientType(clientType: StringLike): object;
  setDefaultMaxAge(defaultMaxAge: number): object;
  setDefaultMaxAgeEnabled(enforceDefaultMaxAge: boolean): object;
  setJwksCacheTimeout(jwksCacheTimeout: number): object;
  setJwksCacheMissCacheTime(jwksCacheMissCacheTime: number): object;
  setSectorIdentifierUri(sectorIdentifierUri: StringLike): object;
  setClientName(clientName: any[]): object;
  setClientUri(uris: any[]): object;
  setLogoUri(uris: any[]): object;
  setSubjectType(subjectType: StringLike): object;
  setClientSessionURI(clientSessionURI: StringLike): object;
  setResponseTypes(responseTypes: any[]): object;
  setAuthorizationCodeLifeTime(authorizationCodeLifeTime: number): object;
  setRequestUris(requestUris: any[]): object;
  setPolicyUri(uris: any[]): object;
  setIdTokenEncryptionEnabled(idTokenEncryptionEnabled: boolean): object;
  setTreeName(treeName: StringLike): object;
  setAccessTokenLifeTime(accessTokenLifeTime: number): object;
  setRefreshTokenLifeTime(refreshTokenLifeTime: number): object;
  setJwtTokenLifeTime(jwtTokenLifeTime: number): object;
  setContacts(contacts: any[]): object;
  setClaimsRedirectUris(claimsRedirectUris: any[]): object;
  setDefaultAcrValues(defaultAcrValues: any[]): object;
  setGrantTypes(grantTypes: any[]): object;
  setSoftwareVersion(softwareVersion: StringLike): object;
  setBackChannelLogoutUri(uri: StringLike): object;
  setJwks(jwks: StringLike): object;
  setPublicKeySelector(selector: StringLike): object;
  setJwksUri(jwksUri: StringLike): object;
  setX509(x509: StringLike): object;
  setTlsClientAuthX509Cert(x509Cert: StringLike): object;
  setTlsClientAuthSubjectDn(subjectDn: StringLike): object;
  setTlsCertificateBoundAccessTokens(
    useCertificateBoundAccessTokens: boolean
  ): object;
  setTokenEndpointAuthMethod(tokenEndpointAuthMethod: StringLike): object;
  setIdTokenEncryptedResponseEnc(
    idTokenEncryptedResponseEnc: StringLike
  ): object;
  setUserinfoSignedResponseAlg(userinfoSignedResponseAlg: StringLike): object;
  setUserinfoEncryptedResponseAlg(
    userinfoEncryptedResponseAlg: StringLike
  ): object;
  setUserinfoEncryptedResponseEnc(
    userinfoEncryptedResponseEnc: StringLike
  ): object;
  setUserInfoResponseFormat(userInfoResponseFormat: StringLike): object;
  setAuthorizationResponseSigningAlg(signedResponseAlg: StringLike): object;
  setTosUri(uris: any[]): object;
  setRegistrationAccessToken(accessToken: StringLike): object;
  setDefaultScopes(defaultScopes: any[]): object;
  setClientDescription(displayDescription: any[]): object;
  setTokenEndpointAuthSigningAlg(
    tokenEndpointAuthSigningAlgorithm: StringLike
  ): object;
  setAuthorizationEncryptedResponseAlg(
    encryptedResponseAlg: StringLike
  ): object;
  setAuthorizationEncryptedResponseEnc(
    encryptedResponseMethod: StringLike
  ): object;
  setIdTokenSignedResponseAlg(
    idTokenSignedResponseAlgorithm: StringLike
  ): object;
  setIdTokenEncryptedResponseAlg(
    idTokenEncryptedResponseAlgorithm: StringLike
  ): object;
  setRedirectURIs(redirectURIs: any[]): object;
  setPostLogoutRedirectUris(postLogoutRedirectionURIs: any[]): object;
  setRequestObjectSigningAlg(requestObjectSigningAlg: StringLike): object;
  setRequestObjectEncryptionAlg(requestObjectEncryptedAlg: StringLike): object;
  setRequestObjectEncryptionEnc(
    requestParameterEncryptedEnc: StringLike
  ): object;
  setTokenIntroResponseFormatSelector(
    tokenIntrospectionResponseFormat: StringLike
  ): object;
  setIntrospectionSignedResponseAlg(
    tokenIntrospectionSignedResponseAlg: StringLike
  ): object;
  setIntrospectionEncryptedResponseAlg(
    tokenIntrospectionEncryptedResponseAlg: StringLike
  ): object;
  setIntrospectionEncryptedResponseEnc(
    tokenIntrospectionEncryptedResponseEnc: StringLike
  ): object;
  setSoftwareId(softwareIdentity: StringLike): object;
  isAIAgent(): boolean;
}

// DEVICE_MATCH_NODE
interface DeviceProfilesDao {
  getDeviceProfiles(username: StringLike, realm: StringLike): any[];
  saveDeviceProfiles(
    username: StringLike,
    realm: StringLike,
    deviceProfiles: any[]
  ): void;
}

// OAUTH2_ACCESS_TOKEN_MODIFICATION_NEXT_GEN, OAUTH2_AUTHORIZE_ENDPOINT_DATA_PROVIDER_NEXT_GEN, OAUTH2_EVALUATE_SCOPE_NEXT_GEN, OAUTH2_SCRIPTED_JWT_ISSUER_NEXT_GEN, OAUTH2_MAY_ACT_NEXT_GEN, OAUTH2_VALIDATE_SCOPE_NEXT_GEN
interface EmailService {
  send(to: StringLike, subject: StringLike, body: StringLike): void;
  send(
    to: StringLike,
    subject: StringLike,
    body: StringLike,
    mimeType: StringLike
  ): void;
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE, OAUTH2_SCRIPTED_JWT_ISSUER_NEXT_GEN
interface IdRepository {
  getIdentity(userName: StringLike): object;
  createUser(userName: StringLike, password: StringLike): object;
  createUser(
    userName: StringLike,
    password: StringLike,
    attributes: object
  ): object;
}

// OAUTH2_ACCESS_TOKEN_MODIFICATION_NEXT_GEN, OAUTH2_AUTHORIZE_ENDPOINT_DATA_PROVIDER_NEXT_GEN, OAUTH2_EVALUATE_SCOPE_NEXT_GEN, OAUTH2_MAY_ACT_NEXT_GEN, OAUTH2_VALIDATE_SCOPE_NEXT_GEN, OIDC_CLAIMS_NEXT_GEN, SAML2_NAMEID_MAPPER
interface Identity {
  getName(): StringLike;
  store(): void;
  exists(): boolean;
  setAttribute(attributeName: StringLike, attributeValues: any[]): void;
  addAttribute(attributeName: StringLike, attributeValue: StringLike): void;
  // Typed managed-user attribute names first (autocomplete; docs/api/14), then
  // the permissive StringLike fallback for any other attribute.
  getAttributeValues(attributeName: AmUserAttribute): any[];
  getAttributeValues(attributeName: StringLike): any[];
  getUniversalId(): StringLike;
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE
interface Journey {
  name(): StringLike;
  innerJourney(): boolean;
  mustRun(): boolean;
  identityResource(): StringLike;
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE
interface OauthApplication {
  getApplicationId(): StringLike;
  getClientProperties(): object;
  getRequestProperties(): object;
}

// SCRIPTED_DECISION_NODE, DEVICE_MATCH_NODE
interface SamlApplication {
  getAssertion(): object;
  getApplicationId(): StringLike;
  getAuthnRequest(): object;
  getIdpAttributes(): object;
  getSpAttributes(): object;
  getFlowInitiator(): StringLike;
}

// OAUTH2_MAY_ACT_NEXT_GEN
interface Token {
  getField(key: StringLike): any;
  getAct(): object;
  getMayAct(): object;
  setAct(value: object): void;
  setMayAct(value: object): void;
}

// Regenerate:
//   node scripts/gen-binding-types.mjs --library-args \
//     --skip httpClient,jwtAssertion,utils,logger,scriptName,realm,jwtValidator,openidm,secrets,cookieName,policy,systemEnv,nodeState \
//     docs/api/bindings/scripted-decision-next.json \
//     docs/api/bindings/device-match-next.json \
//     docs/api/bindings/oauth2-atm-next.json \
//     docs/api/bindings/oauth2-authz-data-next.json \
//     docs/api/bindings/oauth2-dcr-next.json \
//     docs/api/bindings/oauth2-evaluate-scope-next.json \
//     docs/api/bindings/oauth2-jwt-issuer-next.json \
//     docs/api/bindings/oauth2-may-act-next.json \
//     docs/api/bindings/oauth2-validate-scope-next.json \
//     docs/api/bindings/oidc-claims-next.json \
//     docs/api/bindings/pingone-verify-completion-next.json \
//     docs/api/bindings/saml2-nameid-mapper-next.json \
//     docs/api/bindings/saml2-sp-account-mapper-next.json \
//     docs/api/bindings/social-provider-handler-next.json
//   > src/scripts/templates/am/types/library-args.d.ts
//   (then run the repo's prettier over it)
