import prettierConfig from "eslint-config-prettier";
import prettier from "eslint-plugin-prettier";
import {
  loadManagedQueryFields,
  openidmQueryFilterRule,
} from "../tools/eslint-openidm-query-filter.mjs";

// Lint targets the editable .cjs scripts only. The managed types/ .d.ts files
// are generated by `aic script workspace update` and are not linted.

// AM scripts run on Mozilla Rhino 1.7.14 (both the legacy and next-generation
// engines). The restrictions below are RUNTIME-VERIFIED against the sandbox —
// see docs/api/12-script-bindings-matrix.md and scripts/rhino-script-tester/.
// ecmaVersion is set high enough for the parser to PRODUCE these nodes so they
// can be flagged — parsing support is not runtime permission.
//
// PARSE ERRORS are engine-level: they fail to parse regardless of script kind,
// so they're banned for every AM script. `const` inside a function works and is
// allowed; arrow functions, template literals and ES2015 methods all work.
const rhinoParseErrors = [
  {
    selector: "VariableDeclaration[kind='let']",
    message:
      "'let' is a parse error on Rhino 1.7.14 ('missing ; before statement'). Use 'var' (or 'const' inside a function).",
  },
  {
    selector: "ForStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for-loop initializer is a parse error on Rhino 1.7.14. Use 'var'.",
  },
  {
    selector: "ForInStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for...in initializer is a parse error on Rhino 1.7.14. Use 'var'.",
  },
  {
    selector: "ForOfStatement > VariableDeclaration[kind='const']",
    message:
      "'const' in a for...of initializer is a parse error on Rhino 1.7.14. Use 'var'.",
  },
  {
    selector: "ObjectExpression > Property[shorthand=true]",
    message:
      "Object shorthand ({ a }) is a parse error on Rhino 1.7.14 ('missing : after property id'). Use full { a: a } syntax.",
  },
  {
    selector: "ObjectPattern",
    message:
      "Object destructuring is a parse error on Rhino 1.7.14. Assign properties explicitly.",
  },
  {
    selector: "ArrayPattern",
    message:
      "Array destructuring is a parse error on Rhino 1.7.14. Index elements explicitly.",
  },
  {
    selector: "AssignmentPattern",
    message:
      "Default parameter values are a parse error on Rhino 1.7.14. Assign defaults inside the function body.",
  },
];

// Rhino treats `const` as FUNCTION-scoped for redeclaration: the same name
// declared by two `const`s in one function is a parse error
// ("Redeclaration of const …" → "missing ; before statement"), even when the
// declarations sit in separate, non-nested blocks and don't shadow. This is
// RUNTIME-VERIFIED (next-gen scripted decision, 2026-06-06): two sibling-block
// `const dup` in one function → HTTP 401 / no callback (parse failure); the
// same structure with distinct names runs fine. No single esquery selector can
// express "duplicate within the enclosing function", so this is a custom rule:
// track a stack of const-name sets, one frame per function (Program counts as
// the top-level frame), and report the second declaration of any name. Applied
// to every AM script because it is a parser-level constraint, like `let`.
const noDupConstFunctionScoped = {
  meta: {
    type: "problem",
    docs: {
      description:
        "disallow re-declaring the same const name within one function (Rhino function-scoped const)",
    },
    schema: [],
  },
  create(context) {
    const stack = [];
    const push = function () {
      stack.push(new Set());
    };
    const pop = function () {
      stack.pop();
    };
    return {
      Program: push,
      "Program:exit": pop,
      FunctionDeclaration: push,
      "FunctionDeclaration:exit": pop,
      FunctionExpression: push,
      "FunctionExpression:exit": pop,
      ArrowFunctionExpression: push,
      "ArrowFunctionExpression:exit": pop,
      VariableDeclaration: function (node) {
        if (node.kind !== "const") return;
        const seen = stack[stack.length - 1];
        if (!seen) return;
        for (const decl of node.declarations) {
          if (!decl.id || decl.id.type !== "Identifier") continue;
          if (seen.has(decl.id.name)) {
            context.report({
              node: decl.id,
              message:
                "'{{name}}' const is re-declared in this function. Rhino 1.7.14 scopes const to the whole function, so the name must be unique per function (even across separate blocks). Rename one, or use 'var'.",
              data: { name: decl.id.name },
            });
          } else {
            seen.add(decl.id.name);
          }
        }
      },
    };
  },
};

const LOOP_NODE_TYPES = new Set([
  "ForStatement",
  "ForInStatement",
  "ForOfStatement",
  "WhileStatement",
  "DoWhileStatement",
]);

function isFunctionNode(node) {
  return (
    node &&
    (node.type === "FunctionDeclaration" ||
      node.type === "FunctionExpression" ||
      node.type === "ArrowFunctionExpression")
  );
}

function isLoopInitializer(node) {
  const parent = node.parent;
  return (
    parent &&
    ((parent.type === "ForStatement" && parent.init === node) ||
      (parent.type === "ForInStatement" && parent.left === node) ||
      (parent.type === "ForOfStatement" && parent.left === node))
  );
}

function isInsideLoopBody(node) {
  for (let current = node.parent; current; current = current.parent) {
    if (isFunctionNode(current)) return false;
    if (LOOP_NODE_TYPES.has(current.type)) return true;
  }
  return false;
}

const noConstInLoopBody = {
  meta: {
    type: "problem",
    docs: {
      description:
        "disallow const inside loop bodies where Rhino reads it back as undefined",
    },
    schema: [],
  },
  create(context) {
    return {
      VariableDeclaration(node) {
        if (node.kind !== "const") return;
        if (isLoopInitializer(node)) return;
        if (!isInsideLoopBody(node)) return;

        context.report({
          node,
          message:
            "'const' inside a for/for-in/for-of/while/do-while loop body parses but reads back as undefined on Rhino 1.7.14, including when nested in an if/block. Use 'var'.",
        });
      },
    };
  },
};

// Local plugin housing our runtime-verified custom rules.
const rhinoPlugin = {
  rules: {
    "no-dup-const": noDupConstFunctionScoped,
    "no-const-in-loop-body": noConstInLoopBody,
  },
};

const openidmQueryFilterPlugin = {
  rules: {
    "managed-fields": openidmQueryFilterRule(
      loadManagedQueryFields(
        new URL("./types/managed/query-filter-fields.json", import.meta.url)
      )
    ),
  },
};

// These parse fine but `const` silently reads back `undefined`. This is
// SCOPE-dependent and was only verified in scripted-decision GLOBAL scope, so it
// is applied only to the decision-node folders below — NOT to libraries (which
// are module-scoped and use top-level `const` in the real corpus) or other
// contexts, until probed. See P1 in the review + the lib-const-* probe fixtures.
const decisionConstScopeBugs = [
  {
    selector: "Program > VariableDeclaration[kind='const']",
    message:
      "Top-level 'const' parses but reads back as undefined in a scripted-decision script on Rhino 1.7.14. Use 'var' at the top level.",
  },
];

// Quality rules applied to every script. `no-undef` is OFF: TypeScript (via the
// layered types/ .d.ts files and checkJs) is the source of truth for undefined
// bindings, so we don't duplicate it here. The per-family `globals` blocks below
// document the binding set each family sees and keep tooling consistent.
const scriptRules = {
  ...prettierConfig.rules,
  "no-inner-declarations": "off",
  "no-plusplus": ["warn", { allowForLoopAfterthoughts: true }],
  "no-alert": "error",
  "no-template-curly-in-string": "error",
  "prefer-template": "warn",
  "no-implicit-coercion": "warn",
  curly: "error",
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "require-unicode-regexp": "off",
  "no-undef": "off",
  "no-restricted-syntax": ["error", ...rhinoParseErrors],
  "rhino/no-dup-const": "error",
  "openidm-query-filter/managed-fields": "error",
  "prettier/prettier": "error",
};

// Common bindings present in all next-generation AM scripts (verified).
const commonGlobals = {
  logger: "readonly",
  httpClient: "readonly",
  openidm: "readonly",
  utils: "readonly",
  systemEnv: "readonly",
  realm: "readonly",
  scriptName: "readonly",
};

export default [
  // All AM scripts: Rhino syntax rules + common next-gen bindings.
  {
    files: ["*/**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: { ...commonGlobals },
    },
    plugins: {
      prettier,
      rhino: rhinoPlugin,
      "openidm-query-filter": openidmQueryFilterPlugin,
    },
    rules: scriptRules,
  },
  // Scripted-decision scripts (global scope) additionally ban the const-value
  // bugs verified there. Not applied to libraries/other contexts (unproven).
  {
    files: ["*/decision-node/**/*.cjs", "*/decision-node-legacy/**/*.cjs"],
    rules: {
      "rhino/no-const-in-loop-body": "error",
      "no-restricted-syntax": [
        "error",
        ...rhinoParseErrors,
        ...decisionConstScopeBugs,
      ],
    },
  },
  // Next-generation scripted decision: decision bindings + library require().
  {
    files: ["*/decision-node/**/*.cjs"],
    languageOptions: {
      globals: {
        nodeState: "readonly",
        callbacks: "readonly",
        callbacksBuilder: "readonly",
        requestHeaders: "readonly",
        requestParameters: "readonly",
        requestCookies: "readonly",
        idRepository: "readonly",
        action: "readonly",
        outcome: "writable",
        existingSession: "readonly",
        resumedFromSuspend: "readonly",
        secrets: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "writable",
      },
    },
  },
  // Legacy scripted decision: legacy state + Java interop, NO library require().
  {
    files: ["*/decision-node-legacy/**/*.cjs"],
    languageOptions: {
      globals: {
        nodeState: "readonly",
        callbacks: "readonly",
        requestHeaders: "readonly",
        requestParameters: "readonly",
        idRepository: "readonly",
        action: "readonly",
        outcome: "writable",
        existingSession: "readonly",
        sharedState: "readonly",
        transientState: "readonly",
        JavaImporter: "readonly",
      },
    },
  },
  // Library scripts: CommonJS module mechanics (next-gen only).
  {
    files: ["*/lib/**/*.cjs"],
    languageOptions: {
      globals: {
        require: "readonly",
        module: "readonly",
        exports: "writable",
      },
    },
  },
  // OIDC claims (legacy binding set).
  {
    files: ["*/oidc-claims/**/*.cjs"],
    languageOptions: {
      globals: {
        scopes: "readonly",
        claims: "readonly",
        requestedClaims: "readonly",
        claimObjects: "readonly",
        requestedTypedClaims: "readonly",
        claimsLocales: "readonly",
        requestProperties: "readonly",
        clientProperties: "readonly",
        identity: "readonly",
        session: "readonly",
        JavaImporter: "readonly",
        org: "readonly",
        java: "readonly",
      },
    },
  },
  // The managed types/ .d.ts files are tool-generated; don't lint them.
  { ignores: ["**/types/**"] },
];
