// The IDM script-engine globals, declared for this module-based project.
//
// `request` / `context` / `logger` are read only by the emitted entry shim —
// framework and endpoint code takes them as parameters so it stays unit-testable
// in plain node. `openidm` and `identityServer` are different: nothing injects
// them, so endpoint code calls them as globals and they need full signatures.
//
// The managed-object machinery below mirrors the ambient `.cjs` workspace's
// `idm/types/common.d.ts` deliberately, so that one mental model covers both
// surfaces. It keys on `ManagedObjects`, which `src/generated/managed.ts`
// augments from the tenant's schema.
//
// Ground truth: docs/api/10-managed-objects.md (record shape, `fields` syntax,
// query parameters), docs/api/11-idm-endpoints.md, docs/typescript-endpoints.md.
//
// Managed file — regenerated by `aic workspace update`.

import type {
  CrestQueryResult,
  CrestRequest,
  CrestResource,
  IdmCallContext,
  IdmLogger,
  PatchOperation,
} from "./types.ts";

declare global {
  const request: CrestRequest;
  const context: IdmCallContext;
  const logger: IdmLogger;

  /**
   * Collection path (`managed/alpha_user`) -> the object's interface, for this
   * tenant's managed schema.
   *
   * Declared EMPTY here and augmented by `src/generated/managed.ts`, which
   * `aic workspace update` writes from `GET /openidm/config/managed`. Ambient
   * `.d.ts` files are invisible inside a module graph, so that generated file
   * is a real module carrying a `declare global` block — the augmentation
   * applies because `tsconfig.json` includes `src/**\/*`, not because anything
   * imports it.
   *
   * When the file is absent — workspace scaffolded but `aic workspace update`
   * never run — this stays empty, every conditional below resolves to `never`,
   * and each `openidm` signature falls back to its untyped form. Missing
   * tenant types therefore cost you inference, never a compile error.
   */
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type -- the augmentation seam; see above.
  interface ManagedObjects {}

  type ManagedName = keyof ManagedObjects & string;

  /**
   * A member of a `fields` argument: a schema property, `*`, or a relationship
   * / `_meta` path such as `manager/displayName` or `_meta/lastChanged` (the
   * path and `*` syntax are verified live — docs/api/10-managed-objects.md).
   */
  type ManagedField<T> =
    | (keyof T & string)
    | "*"
    | `${(keyof T & string) | "_meta"}/${string}`
    | "_meta";

  /** Collection path (`managed/<obj>`) -> object interface, else `never`. */
  type ManagedCollectionOf<R extends string> = R extends keyof ManagedObjects
    ? ManagedObjects[R]
    : never;

  /** Record path (`managed/<obj>/<id>`) -> object interface, else `never`. */
  type ManagedRecordOf<R extends string> =
    R extends `managed/${infer N}/${string}`
      ? `managed/${N}` extends keyof ManagedObjects
        ? ManagedObjects[`managed/${N}`]
        : never
      : never;

  /**
   * `fields`: checked against the schema for a known managed path, REJECTED
   * for an unknown `managed/…` path (there is nothing to check it against —
   * re-run `aic workspace update`), free-form for anything else.
   */
  type FieldsArg<T, R extends string> = [T] extends [never]
    ? R extends `managed/${string}`
      ? never
      : string[]
    : ManagedField<T>[];

  /** Write payloads are partial: a patch-like update need not carry every key. */
  type ContentArg<T> = [T] extends [never]
    ? Record<string, unknown>
    : Partial<T>;

  /**
   * The result of a call whose path did not resolve to a managed object. The
   * ambient workspace widens to `any` here; this project stays strict, so an
   * unknown path hands back the generic CREST resource shape instead.
   */
  type RecordResult<T> = [T] extends [never] ? CrestResource : T;

  /**
   * A record the store hands back always carries `_id` and `_rev`: a managed
   * object instance is "`_id` and `_rev` plus its declared properties"
   * (docs/api/10-managed-objects.md). The generated interfaces still leave both
   * optional, because the same interface types an onCreate hook's draft object,
   * which has neither yet.
   */
  type StoredRecord<T> = T & { _id: string; _rev: string };

  /**
   * Parameters a managed-object query honours. `_queryFilter` stays required —
   * IDM rejects a query without one. `_fields`, `_sortKeys` and the paging
   * cursor are all exercised live in docs/api/10-managed-objects.md; offset
   * paging is deliberately not named, because deep offsets can skip or
   * duplicate records and the cursor is the supported walk.
   *
   * The index signature is deliberate: an exact object type here is precisely
   * why `_fields` was once a type error rather than a supported parameter. A
   * misspelled `_queryFilter` is still caught by the required key.
   */
  interface QueryParams {
    _queryFilter: string;
    _fields?: string;
    _sortKeys?: string;
    _pageSize?: number;
    _pagedResultsCookie?: string | null;
    [param: string]: string | number | null | undefined;
  }

  /**
   * IDM's CREST router binding.
   *
   * One generic signature per verb with conditional results, rather than a
   * per-object overload set: a field typo then reports against the offending
   * element, with spelling suggestions, instead of "no overload matches".
   */
  interface OpenIdm {
    read<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      params?: Record<string, string> | null
    ): [ManagedRecordOf<R>] extends [never]
      ? CrestResource | null
      : StoredRecord<ManagedRecordOf<R>> | null;
    // Restricting the returned fields drops the `_id`/`_rev` guarantee: we have
    // not verified that IDM still includes them, so this form keeps them
    // optional.
    read<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      params: Record<string, string> | null | undefined,
      fields: FieldsArg<ManagedRecordOf<R>, R>
    ): [ManagedRecordOf<R>] extends [never]
      ? CrestResource | null
      : ManagedRecordOf<R> | null;

    query<R extends ManagedName | (string & {})>(
      path: R,
      params: QueryParams
    ): CrestQueryResult<RecordResult<ManagedCollectionOf<R>>>;
    query<R extends ManagedName | (string & {})>(
      path: R,
      params: QueryParams,
      fields: FieldsArg<ManagedCollectionOf<R>, R>
    ): CrestQueryResult<RecordResult<ManagedCollectionOf<R>>>;

    create<R extends ManagedName | (string & {})>(
      path: R,
      newResourceId: string | null,
      content: ContentArg<ManagedCollectionOf<R>>,
      params?: Record<string, string> | null
    ): RecordResult<ManagedCollectionOf<R>>;

    update<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      revision: string | null,
      content: ContentArg<ManagedRecordOf<R>>,
      params?: Record<string, string> | null
    ): RecordResult<ManagedRecordOf<R>>;

    patch<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      revision: string | null,
      operations: PatchOperation[],
      params?: Record<string, string> | null
    ): RecordResult<ManagedRecordOf<R>>;

    delete<R extends `${ManagedName}/${string}` | (string & {})>(
      path: R,
      revision: string | null,
      params?: Record<string, string> | null
    ): RecordResult<ManagedRecordOf<R>>;

    /** Named actions are untyped: the payload and result are per-action. */
    action(
      path: string,
      actionName: string,
      content?: Record<string, unknown> | null,
      params?: Record<string, string> | null
    ): unknown;
  }

  const openidm: OpenIdm;

  /** ESV / boot-property lookup. Returns `null` for a missing property. */
  const identityServer: {
    getProperty(
      name: string,
      defaultValue?: string,
      substitute?: boolean
    ): string | null;
  };
}
