// The IDM script-engine globals, declared for this module-based project.
//
// Only the emitted entry shim reads these; framework and endpoint code takes
// `request` / `context` / `logger` as parameters so it stays unit-testable in
// plain node. Kept deliberately small: the exhaustive `openidm` surface lives
// in the workspace's `idm/types/*.d.ts` set for hand-written `.cjs` scripts.
//
// Managed file — regenerated by `aic workspace update`.

import type {
  CrestQueryResult,
  CrestRequest,
  IdmCallContext,
  IdmLogger,
} from "./types.ts";

declare global {
  const request: CrestRequest;
  const context: IdmCallContext;
  const logger: IdmLogger;

  /** IDM's CREST router binding. */
  const openidm: {
    read(
      resourceName: string,
      params?: Record<string, unknown> | null,
      fields?: string[]
    ): Record<string, unknown> | null;
    create(
      resourceContainer: string,
      newResourceId: string | null,
      content: Record<string, unknown>,
      params?: Record<string, unknown> | null,
      fields?: string[]
    ): Record<string, unknown>;
    update(
      resourceName: string,
      rev: string | null,
      content: Record<string, unknown>,
      params?: Record<string, unknown> | null,
      fields?: string[]
    ): Record<string, unknown>;
    patch(
      resourceName: string,
      rev: string | null,
      value: unknown[],
      params?: Record<string, unknown> | null,
      fields?: string[]
    ): Record<string, unknown>;
    delete(
      resourceName: string,
      rev: string | null,
      params?: Record<string, unknown> | null,
      fields?: string[]
    ): Record<string, unknown>;
    query(
      resourceName: string,
      params: Record<string, unknown>,
      fields?: string[]
    ): CrestQueryResult;
    action(
      resource: string,
      actionName: string,
      content?: Record<string, unknown>,
      params?: Record<string, unknown> | null,
      fields?: string[]
    ): unknown;
  };

  /** ESV / boot-property lookup. Returns `null` for a missing property. */
  const identityServer: {
    getProperty(
      name: string,
      defaultValue?: string,
      substitute?: boolean
    ): string | null;
  };
}
