// Java package roots as Rhino surfaces them to an IDM custom endpoint.
//
// Narrow and curated — not a JDK binding. HMAC and Unicode normalisation
// have no JavaScript alternative on this engine, so they are declared.
// `java.util.Set` is already `JavaSet` in `types.ts` (the stand-in for
// `context.oauth2.scopes`) and is not repeated here.
//
// Observed on the sandbox tenant 2026-08-18 (throwaway endpoint, then
// deleted). Two silent traps live in the type system: a Java `byte[]`
// yields signed values (`-128..127`), and `Normalizer.normalize` returns
// a `java.lang.String` that is not `===` a JS `string` even when it
// prints the same (the engine does expose JS string methods on it; this
// surface omits them). `openidm.hash` salts per call, so it cannot stand
// in for HMAC. Do not copy any of this into a `## Verified against`
// block under `docs/api/`.
//
// `java.security.SecureRandom` added 2026-09-10, measured on JDK 21.0.12.1
// the same way (throwaway `endpoint/aicedit-securerandom-probe`, plus
// `POST /openidm/script?_action=eval`). It brings a third silent trap:
// `nextBytes(jsArray)` fills a throwaway copy and leaves the array you
// passed untouched — 20 runs, 20 unchanged, against a control on a real
// `byte[]` that changed in all 20. `JavaBytes` is what makes that a
// compile error.
//
// Managed file — regenerated by `aic workspace update`.

import type { JavaBytes, JavaLangString } from "./java.ts";

declare global {
  namespace java {
    namespace lang {
      /**
       * A Java string. Not assignable to a JS `string`, and not `===`
       * one even when it prints the same. Wrap with `String(...)`, or
       * use `nfc` / `normalize` from `framework/java.ts`.
       */
      type String = JavaLangString;
      const String: new (value: string) => String;

      namespace reflect {
        const Array: {
          /**
           * Allocate a Java array. Declared only for `byte[]` — the one thing
           * TypeScript cannot express and the only argument
           * {@link java.security.SecureRandom.nextBytes} will actually fill.
           */
          newInstance(
            componentType: ByteClass,
            length: number
          ): JavaBytes;
        };
      }

      /** The `byte` primitive class token. `String(...)` of it is `"byte"`. */
      interface ByteClass {
        readonly __javaByteClass: never;
      }
      const Byte: { readonly TYPE: ByteClass };
    }

    namespace text {
      class Normalizer {
        /**
         * Returns a {@link JavaLangString}, not a JS string. It is not
         * `===` the JS string even when `String(...)` of it is. Use
         * `nfc()` / `normalize()`, or `String(...)`.
         */
        static normalize(
          src: string | JavaLangString,
          form: Normalizer.Form
        ): JavaLangString;
      }
      namespace Normalizer {
        interface Form {
          readonly __javaNormalizerForm: never;
        }
        const Form: {
          readonly NFC: Form;
          readonly NFD: Form;
          readonly NFKC: Form;
          readonly NFKD: Form;
        };
      }
    }

    namespace security {
      /**
       * `java.security.SecureRandom`. The no-arg constructor resolves to
       * algorithm `NativePRNG` from provider `SUN` on this tenant — a JVM
       * property, not an AIC guarantee, so do not hard-code it.
       */
      class SecureRandom {
        constructor();

        /** Measured present: `SHA1PRNG`, `NativePRNG`, `DRBG`. */
        static getInstance(algorithm: string): SecureRandom;

        /**
         * Resolves to `NativePRNGBlocking` here: it reads `/dev/random` and
         * **can block** when the host is short of entropy, which in an endpoint
         * is a stall with no timeout you control. Prefer `new SecureRandom()`.
         */
        static getInstanceStrong(): SecureRandom;

        /** Seed bytes from the system entropy source. */
        static getSeed(numBytes: number): JavaBytes;

        /**
         * Returns a {@link JavaLangString}, so `getAlgorithm() === "NativePRNG"`
         * is always false. Wrap with `String(...)` before comparing.
         */
        getAlgorithm(): JavaLangString;

        /**
         * Fill `bytes` in place. A JS array is rejected here for a reason: at
         * runtime Rhino fills a throwaway copy of it and leaves the original
         * untouched, silently.
         */
        nextBytes(bytes: JavaBytes): void;

        /** Seed bytes, possibly from a blocking source. */
        generateSeed(numBytes: number): JavaBytes;

        /** A uniformly random 32-bit `int`. Exact. */
        nextInt(): number;
        /** `0 <= n < bound`. `bound <= 0` throws `IllegalArgumentException`. */
        nextInt(bound: number): number;
        /** `origin <= n < bound` (JDK 17+). */
        nextInt(origin: number, bound: number): number;

        /**
         * LOSSY, ALWAYS. A Java `long` is 64-bit and a JS number keeps 53 bits
         * of mantissa; 100 of 100 measured draws exceeded
         * `Number.MAX_SAFE_INTEGER`, so the low digits are rounding noise and
         * two distinct longs can arrive equal. Never use it for an identifier
         * or a nonce — use {@link nextBytes} and render the bytes. Fine as a
         * seed.
         */
        nextLong(): number;

        /** `0.0 <= n < 1.0`. Exact. */
        nextDouble(): number;
        /** Widened from a Java `float`. Prefer {@link nextDouble}. */
        nextFloat(): number;
        nextBoolean(): boolean;
        /** Normal distribution, mean 0, standard deviation 1. */
        nextGaussian(): number;

        /** Supplements the existing seed rather than replacing it. */
        setSeed(seed: number): void;
        setSeed(seed: JavaBytes): void;
      }
    }
  }

  namespace javax {
    namespace crypto {
      class Mac {
        static getInstance(algorithm: string): Mac;
        init(key: spec.SecretKeySpec): void;
        /**
         * Returns a signed `byte[]` (`-128..127`). Render with `bytesToHex`;
         * a forgotten `& 0xff` still produces hex of the right length.
         */
        doFinal(input: JavaBytes): JavaBytes;
      }
      namespace spec {
        class SecretKeySpec {
          constructor(key: JavaBytes, algorithm: string);
        }
      }
    }
  }
}
