// Java package roots as Rhino surfaces them to an IDM custom endpoint.
//
// Narrow and curated — not a JDK binding. HMAC and Unicode normalisation
// have no JavaScript alternative on this engine, so they are declared.
// `java.util.Set` is already `JavaSet` in `types.ts` (the stand-in for
// `context.oauth2.scopes`) and is not repeated here.
//
// Observed on the sandbox tenant 2026-08-18 (throwaway endpoint, then
// deleted). Two silent traps live in the type system: a Java `byte[]`
// yields signed values (`-128..127`), and `Normalizer.normalize` returns
// a `java.lang.String` that is not `===` a JS `string` even when it
// prints the same (the engine does expose JS string methods on it; this
// surface omits them). `openidm.hash` salts per call, so it cannot stand
// in for HMAC. Do not copy any of this into a `## Verified against`
// block under `docs/api/`.
//
// Managed file — regenerated by `aic workspace update`.

import type { JavaBytes, JavaLangString } from "./java.ts";

declare global {
  namespace java {
    namespace lang {
      /**
       * A Java string. Not assignable to a JS `string`, and not `===`
       * one even when it prints the same. Wrap with `String(...)`, or
       * use `nfc` / `normalize` from `framework/java.ts`.
       */
      type String = JavaLangString;
      const String: new (value: string) => String;
    }

    namespace text {
      class Normalizer {
        /**
         * Returns a {@link JavaLangString}, not a JS string. It is not
         * `===` the JS string even when `String(...)` of it is. Use
         * `nfc()` / `normalize()`, or `String(...)`.
         */
        static normalize(
          src: string | JavaLangString,
          form: Normalizer.Form
        ): JavaLangString;
      }
      namespace Normalizer {
        interface Form {
          readonly __javaNormalizerForm: never;
        }
        const Form: {
          readonly NFC: Form;
          readonly NFD: Form;
          readonly NFKC: Form;
          readonly NFKD: Form;
        };
      }
    }
  }

  namespace javax {
    namespace crypto {
      class Mac {
        static getInstance(algorithm: string): Mac;
        init(key: spec.SecretKeySpec): void;
        /**
         * Returns a signed `byte[]` (`-128..127`). Render with `bytesToHex`;
         * a forgotten `& 0xff` still produces hex of the right length.
         */
        doFinal(input: JavaBytes): JavaBytes;
      }
      namespace spec {
        class SecretKeySpec {
          constructor(key: JavaBytes, algorithm: string);
        }
      }
    }
  }
}
