// Helpers for the Java package roots declared in `java-globals.d.ts`.
//
// A Java `byte[]` surfaced into Rhino is signed (`-128..127`); hex-rendering
// without `& 0xff` still produces a digest of the right length and alphabet.
// `JavaByte.toString` is `never` so `bytes[i]!.toString(16)` is a compile
// error; `bytesToHex` is the conversion that masks. Mixing `JavaBytes` with
// a JS `number[]` is rejected in both directions.
//
// `Normalizer.normalize` returns a `java.lang.String`. On the engine that
// object prints like a JS string and even has JS string methods (`slice` is
// a function), but it is not `===` a JS string. This type omits those
// methods so the only typed ways out are `String(...)` or `getBytes`.
//
// Observed on the sandbox tenant 2026-08-18 (throwaway endpoint, then
// deleted): `Mac.getInstance` / `init` / `doFinal`, `new java.lang.String(s)`,
// `.getBytes("UTF-8")`, signed `doFinal` bytes (HMAC-SHA256 fox vector
// first byte `-9`), `openidm.hash` salts per call, no-arg `getBytes()`
// works (platform charset — we still refuse it), and a Normalizer result
// is a `java.lang.String` that is not `===` the JS string. Do not copy
// any of this into a `## Verified against` block under `docs/api/`.
//
// ES5-safe on purpose: Babel rewrites syntax, not library methods, and the
// emitted bundle is linted for the runtime bans. `indexOf` / concatenation,
// not `includes` / `padStart`.
//
// Managed file — regenerated by `aic workspace update`.

declare const javaByteBrand: unique symbol;
declare const javaLangStringBrand: unique symbol;

/**
 * One element of a Java `byte[]` as Rhino hands it over: a signed byte
 * (`-128..127`), not an unsigned `0..255`.
 *
 * Still a `number` for arithmetic (`byte & 0xff`, `byte < 0`). `toString`
 * is `never` so `bytes[i]!.toString(16)` — the unmasked-hex trap — is a
 * compile error. Use {@link bytesToHex}.
 */
export type JavaByte = number & {
  readonly [javaByteBrand]: void;
  readonly toString: never;
};

/**
 * A Java `byte[]`. Not a `number[]` — the element type is {@link JavaByte} —
 * so a hand-rolled hex loop cannot treat the values as unsigned `number`s,
 * and cannot call `.toString(16)` on an element. Use {@link bytesToHex}.
 */
export interface JavaBytes {
  readonly [index: number]: JavaByte;
  readonly length: number;
}

/**
 * A `java.lang.String`. Not assignable to a JS `string`, and not `===`
 * one even when `String(...)` of it is. The engine does expose JS string
 * methods on it; this type omits them so the only typed ways out are
 * `String(...)` or {@link nfc} / {@link normalize}.
 *
 * `getBytes()` with no charset works on the engine (platform default).
 * Omitting that overload is our policy, not an engine rejection.
 */
export interface JavaLangString {
  readonly [javaLangStringBrand]: void;
  getBytes(charset: "UTF-8"): JavaBytes;
  toString(): string;
}

/**
 * Hex-encode a Java `byte[]`, masking each element with `& 0xff`.
 *
 * Accepts any byte-like array so the unsigned equivalent of a signed
 * `doFinal` result can be shown to produce the same string — that is the
 * test that documents why the helper exists.
 */
export function bytesToHex(bytes: ArrayLike<number>): string {
  let hex = "";
  for (let i = 0; i < bytes.length; i += 1) {
    const value = bytes[i];
    if (value === undefined) {
      continue;
    }
    const pair = (value & 0xff).toString(16);
    hex += pair.length === 1 ? "0" + pair : pair;
  }
  return hex;
}

/**
 * Unicode-normalise `value` and return a JS `string`.
 *
 * `java.text.Normalizer.normalize` returns a {@link JavaLangString}; this
 * is the wrapper that does the `String(...)` conversion so the brand never
 * leaks into user code.
 */
export function normalize(
  value: string,
  form: java.text.Normalizer.Form
): string {
  return String(java.text.Normalizer.normalize(value, form));
}

/** NFC normalisation, returning a JS `string`. */
export function nfc(value: string): string {
  return normalize(value, java.text.Normalizer.Form.NFC);
}
