// Route declaration and dispatch.
//
// A route is keyed by (CREST method, sub-path pattern, action name). The
// sub-path is matched against `request.resourcePath` — the part of the URL
// below `/openidm/endpoint/<name>`, delivered verbatim and un-decoded (`""` at
// the root, `"a/b/c"` three levels down; probed 2026-08-13).
//
// Managed file — regenerated by `aic workspace update`.

import {
  badRequest,
  describeThrowable,
  forbidden,
  isFault,
  methodNotAllowed,
  notFound,
  toCrestFault,
  toCrestResponse,
  type CrestFault,
} from "./errors.ts";
import {
  createRequestLogger,
  describeCaller,
  type RequestLogger,
} from "./logging.ts";
import type {
  CrestMethod,
  CrestQueryResult,
  CrestRequest,
  IdmCallContext,
  IdmLogger,
  PatchOperation,
} from "./types.ts";
import {
  parseShape,
  type InferShape,
  type Issue,
  type JsonSchema,
  type Shape,
  type Validator,
} from "./validate.ts";

/** One piece of a sub-path pattern: a fixed segment or a named capture. */
export type PathSegment = { literal: string } | { param: string };

/** What the handler is handed. Every member is already validated. */
export interface RouteInput<
  P extends Shape,
  Q extends Shape,
  H extends Shape,
  B,
> {
  /** Captures from the sub-path pattern, URL-decoded then validated. */
  params: InferShape<P>;
  /** Non-`_`-prefixed query params, coerced per the declared validators. */
  query: InferShape<Q>;
  /** Declared headers, looked up case-insensitively. */
  headers: InferShape<H>;
  /** The validated request body (`undefined` when the route declares none). */
  body: B;
  /** CREST patch operations — only populated for the `patch` method. */
  patchOperations: PatchOperation[];
  /**
   * The client-supplied resource id on a `create`.
   *
   * A bare `PUT /openidm/endpoint/<name>/<id>` is a CREST **create** with
   * `newResourceId: "<id>"` and an EMPTY `resourcePath`, not an update
   * (probed 2026-08-13; the update route needs an `If-Match` header). So a
   * `create` route declared at `/` receives both call shapes, and this is how
   * it tells them apart.
   */
  newResourceId: string | null;
  /** The raw CREST request, for the fields the framework does not model. */
  request: CrestRequest;
  /** The CREST call chain. Never log it — use `describeCaller`. */
  context: IdmCallContext;
  /** Logger pre-bound to endpoint, route and correlation id. */
  log: RequestLogger;
  /** The `x-request-id` header when supplied, else a generated id. */
  correlationId: string;
}

/**
 * A `query` handler MUST return a CREST query result; anything else fails at
 * runtime with `Script returned unexpected query result structure` (verified
 * 2026-06-04). Encoding that in the return type turns it into a build error.
 */
export type ResultFor<M extends CrestMethod> = M extends "query"
  ? CrestQueryResult<unknown>
  : unknown;

export interface RouteSpec<
  M extends CrestMethod,
  P extends Shape,
  Q extends Shape,
  H extends Shape,
  B,
> {
  method: M;
  /** Sub-path pattern: `"/"`, `"/{widgetId}"`, `"/widget/{widgetId}/summary"`. */
  path: string;
  /** Required for `method: "action"`; the `?_action=` name. */
  action?: string;
  summary?: string;
  description?: string;
  /** OAuth scopes the caller's token must carry, on top of IDM's own gates. */
  scopes?: readonly string[];
  params?: P;
  query?: Q;
  headers?: H;
  body?: Validator<B>;
  /** Validates `request.patchOperations` — only meaningful for `patch`. */
  patches?: Validator<PatchOperation[]>;
  /** JSON Schema for the success body, used by the OpenAPI generator. */
  response?: JsonSchema;
  handler: (input: RouteInput<P, Q, H, B>) => ResultFor<M>;
}

/** A route with its generics erased — what the endpoint and generator hold. */
export interface RouteDefinition {
  method: CrestMethod;
  path: string;
  segments: PathSegment[];
  action: string | undefined;
  summary: string | undefined;
  description: string | undefined;
  scopes: string[];
  params: Shape;
  query: Shape;
  headers: Shape;
  body: Validator<unknown> | undefined;
  patches: Validator<PatchOperation[]> | undefined;
  response: JsonSchema | undefined;
  run(input: RouteInput<Shape, Shape, Shape, unknown>): unknown;
}

/** Split `"/widget/{id}/summary"` into its segments. */
export function parsePath(path: string): PathSegment[] {
  return path
    .split("/")
    .filter((part) => part !== "")
    .map((part) => {
      const captured = /^\{(.+)\}$/.exec(part);
      return captured === null
        ? { literal: part }
        : { param: captured[1] as string };
    });
}

/**
 * Declare one route. The generics are inferred from the validators, so the
 * handler sees `number` for an int query param, `"a" | "b"` for an enum, and
 * `string | undefined` for an optional — with no type annotations to keep in
 * step with the declaration.
 */
export function route<
  M extends CrestMethod,
  P extends Shape = Record<never, never>,
  Q extends Shape = Record<never, never>,
  H extends Shape = Record<never, never>,
  B = undefined,
>(spec: RouteSpec<M, P, Q, H, B>): RouteDefinition {
  if (spec.method === "action" && spec.action === undefined) {
    throw new Error(
      "route " + spec.path + ': method "action" requires an action name'
    );
  }
  if (spec.method !== "action" && spec.action !== undefined) {
    throw new Error(
      "route " + spec.path + ": only an action route may name an action"
    );
  }
  const declared = parsePath(spec.path);
  const params = (spec.params ?? {}) as Shape;
  for (const segment of declared) {
    if (
      "param" in segment &&
      !Object.prototype.hasOwnProperty.call(params, segment.param)
    ) {
      throw new Error(
        "route " +
          spec.path +
          ": path param {" +
          segment.param +
          "} has no validator"
      );
    }
  }
  for (const name of Object.keys(params)) {
    if (
      !declared.some((segment) => "param" in segment && segment.param === name)
    ) {
      throw new Error(
        "route " +
          spec.path +
          ": validator for {" +
          name +
          "} is not in the path"
      );
    }
  }
  return {
    method: spec.method,
    path: spec.path,
    segments: declared,
    action: spec.action,
    summary: spec.summary,
    description: spec.description,
    scopes: spec.scopes === undefined ? [] : spec.scopes.slice(),
    params,
    query: (spec.query ?? {}) as Shape,
    headers: (spec.headers ?? {}) as Shape,
    body: spec.body as Validator<unknown> | undefined,
    patches: spec.patches,
    response: spec.response,
    run: spec.handler as (
      input: RouteInput<Shape, Shape, Shape, unknown>
    ) => unknown,
  };
}

export interface EndpointSpec {
  /** The IDM config id suffix — `endpoint/<name>` and the emitted filename. */
  name: string;
  summary?: string;
  description?: string;
  version?: string;
  /** Headers validated on EVERY route (merged under the route's own). */
  headers?: Shape;
  /** Header used as the log correlation id. Default `x-request-id`. */
  correlationHeader?: string;
  routes: RouteDefinition[];
}

/** The build-time view of an endpoint, consumed by the OpenAPI generator. */
export interface EndpointDefinition {
  name: string;
  summary: string | undefined;
  description: string | undefined;
  version: string;
  headers: Shape;
  correlationHeader: string;
  routes: RouteDefinition[];
}

/**
 * The emitted bundle's default export: a zero-argument function reading the
 * IDM globals, so the generated file can end with `__aicMain.default();` and
 * hand its completion value straight back as the HTTP response body.
 */
export interface EndpointMain {
  (): unknown;
  definition: EndpointDefinition;
  /** Same dispatch, with the bindings injected — how the unit tests drive it. */
  dispatch(
    request: CrestRequest,
    context: IdmCallContext,
    logger?: IdmLogger
  ): unknown;
}

function segmentsMatch(
  segments: PathSegment[],
  actual: string[]
): Record<string, string> | null {
  if (segments.length !== actual.length) {
    return null;
  }
  const captured: Record<string, string> = {};
  for (let index = 0; index < segments.length; index += 1) {
    const segment = segments[index] as PathSegment;
    const value = actual[index] as string;
    if ("literal" in segment) {
      if (segment.literal !== value) {
        return null;
      }
    } else {
      captured[segment.param] = value;
    }
  }
  return captured;
}

/** More literal segments wins, so `/daily/{d}` beats a same-length `/{a}/{b}`. */
function specificity(route: RouteDefinition): number {
  return route.segments.filter((segment) => "literal" in segment).length;
}

function decodeSegment(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch (_error) {
    // A malformed `%` escape is the caller's problem, not a 500: keep the
    // raw segment and let the path-param validator reject it.
    return value;
  }
}

/** Split a raw `resourcePath` into decoded segments. */
export function splitResourcePath(resourcePath: string): string[] {
  return resourcePath
    .split("/")
    .filter((part) => part !== "")
    .map(decodeSegment);
}

function headerLookup(
  context: IdmCallContext
): (name: string) => string | undefined {
  const source = context.http === undefined ? {} : context.http.headers;
  const lowered: Record<string, string> = {};
  for (const key of Object.keys(source)) {
    const value = source[key];
    if (typeof value === "string") {
      lowered[key.toLowerCase()] = value;
    }
  }
  return (name) => lowered[name.toLowerCase()];
}

function bodyOf(request: CrestRequest): unknown {
  if (
    request.method === "create" ||
    request.method === "update" ||
    request.method === "action"
  ) {
    return request.content;
  }
  return undefined;
}

/** Used when a caller drives `dispatch` without a `logger` binding (tests). */
const SILENT_LOGGER: IdmLogger = {
  trace: () => undefined,
  debug: () => undefined,
  info: () => undefined,
  warn: () => undefined,
  error: () => undefined,
};

function generateCorrelationId(): string {
  const random = Math.floor(Math.random() * 0xffffff).toString(16);
  return "aic-" + Date.now().toString(36) + "-" + random;
}

function checkScopes(
  scopes: string[],
  context: IdmCallContext
): CrestFault | null {
  if (scopes.length === 0) {
    return null;
  }
  const oauth2 = context.oauth2;
  if (oauth2 === undefined || oauth2.scopes === undefined) {
    return forbidden("Missing required OAuth scope", { required: scopes });
  }
  const missing: string[] = [];
  for (const scope of scopes) {
    // `context.oauth2.scopes` is a java.util.Set — `.contains`, never
    // `.includes` (docs/api/11-idm-endpoints.md).
    if (!oauth2.scopes.contains(scope)) {
      missing.push(scope);
    }
  }
  if (missing.length > 0) {
    return forbidden("Missing required OAuth scope", { missing });
  }
  return null;
}

/** Human label for a route, used in logs and error detail. */
export function routeLabel(route: RouteDefinition): string {
  const suffix = route.action === undefined ? "" : "?_action=" + route.action;
  return route.method + " " + route.path + suffix;
}

/**
 * Build an endpoint. The returned function is the module's default export; the
 * emitted bundle calls it as its final expression statement.
 */
export function defineEndpoint(spec: EndpointSpec): EndpointMain {
  const definition: EndpointDefinition = {
    name: spec.name,
    summary: spec.summary,
    description: spec.description,
    version: spec.version ?? "1.0.0",
    headers: (spec.headers ?? {}) as Shape,
    correlationHeader: spec.correlationHeader ?? "x-request-id",
    routes: spec.routes.slice(),
  };

  const dispatch = (
    request: CrestRequest,
    context: IdmCallContext,
    logger?: IdmLogger
  ): unknown => {
    const log = createRequestLogger(logger ?? SILENT_LOGGER, {
      endpoint: definition.name,
    });

    const header = headerLookup(context);
    const correlationId =
      header(definition.correlationHeader) ?? generateCorrelationId();
    const requestLog = log.child({ cid: correlationId });

    try {
      const actual = splitResourcePath(request.resourcePath);
      const pathMatches = definition.routes
        .map((candidate) => ({
          route: candidate,
          captured: segmentsMatch(candidate.segments, actual),
        }))
        .filter((entry) => entry.captured !== null)
        .sort(
          (left, right) => specificity(right.route) - specificity(left.route)
        );

      if (pathMatches.length === 0) {
        throw notFound("No route for /" + actual.join("/"), {
          method: request.method,
        });
      }
      const methodMatches = pathMatches.filter(
        (entry) => entry.route.method === request.method
      );
      if (methodMatches.length === 0) {
        const allowed: string[] = [];
        for (const entry of pathMatches) {
          if (allowed.indexOf(entry.route.method) < 0) {
            allowed.push(entry.route.method);
          }
        }
        throw methodNotAllowed(
          "Method " + request.method + " is not supported on this path",
          { allowed }
        );
      }

      let matched = methodMatches[0] as {
        route: RouteDefinition;
        captured: Record<string, string> | null;
      };
      if (request.method === "action") {
        const wanted = request.action;
        const found = methodMatches.find(
          (entry) => entry.route.action === wanted
        );
        if (found === undefined) {
          // No quotes: IDM HTML-escapes the strings in a thrown error.
          throw notFound("Unknown action: " + String(wanted), {
            supported: methodMatches.map((entry) => entry.route.action),
          });
        }
        matched = found;
      }

      const route = matched.route;
      const captured = matched.captured ?? {};
      const routed = requestLog.child({ route: routeLabel(route) });

      // Authorize before validation: validation detail would disclose the
      // request schema to a caller that does not hold the route's scope.
      const denied = checkScopes(route.scopes, context);
      if (denied !== null) {
        routed.warn("scope check failed", { required: route.scopes });
        throw denied;
      }

      const issues: Issue[] = [];
      const params = parseShape(
        route.params,
        "path",
        (key) => captured[key],
        issues
      );
      const query = parseShape(
        route.query,
        "query",
        (key) => request.additionalParameters[key],
        issues
      );
      const headerShape: Shape = { ...definition.headers, ...route.headers };
      const headers = parseShape(headerShape, "header", header, issues);
      let body: unknown = undefined;
      if (route.body !== undefined) {
        const raw = bodyOf(request);
        if (raw === undefined || raw === null) {
          issues.push({ path: "body", message: "is required" });
        } else {
          body = route.body.parse(raw, "body", issues);
        }
      }
      let patches: PatchOperation[] =
        request.method === "patch" ? request.patchOperations : [];
      if (route.patches !== undefined) {
        patches = route.patches.parse(patches, "patchOperations", issues);
      }

      if (issues.length > 0) {
        routed.info("validation failed", { issues: issues.length });
        throw badRequest("Request validation failed", { issues });
      }

      routed.debug("dispatching", describeCaller(context));
      return route.run({
        params,
        newResourceId:
          request.method === "create" ? request.newResourceId : null,
        query,
        headers,
        body,
        patchOperations: patches,
        request,
        context,
        log: routed,
        correlationId,
      });
    } catch (thrown) {
      const fault = toCrestFault(thrown);
      if (!isFault(thrown)) {
        // Unexpected: keep the real reason server-side only.
        requestLog.error("unhandled failure", {
          cause: describeThrowable(thrown),
          code: fault.code,
        });
      } else if (fault.code >= 500) {
        requestLog.error("request failed", { code: fault.code });
      }
      throw toCrestResponse(fault);
    }
  };

  const main = (): unknown => dispatch(request, context, logger);
  const exported = main as EndpointMain;
  exported.definition = definition;
  exported.dispatch = dispatch;
  return exported;
}
