// Java classes reachable from an IDM script.
//
// Narrow and measured — not a JDK binding. Only what has been run against the
// tenant is declared, so an absent class here means "not yet probed", not
// "blocked". Add one the same way: probe it, then declare what the probe
// measured.
//
// IDM has no class allow-list. `/openidm/config/script` declares none — unlike
// AM, which publishes a per-context `allowLists` and enforces it (see
// docs/api/12-script-bindings-matrix.md, "The boundary is per context"). So the
// boundary here is the JVM's, and nothing in this file should be copied to the
// AM workspace, where most of it is hidden.
//
// Measured on the sandbox tenant 2026-09-10, on JDK 21.0.12.1: a throwaway
// `endpoint/aicedit-securerandom-probe` (created and deleted) and
// `POST /openidm/script?_action=eval`. Do not copy any of this into a
// `## Verified against` block under `docs/api/`.
//
// Three measured traps drive the shapes below, and every one of them is silent
// at runtime:
//
//   1. `nextBytes(jsArray)` FILLS NOTHING. Rhino converts the JS array to a
//      fresh Java `byte[]`, fills that, and discards it — the array you passed
//      is untouched. Measured 20 runs: 20 unchanged, against a control on a
//      real `byte[]` that changed in all 20. Hence {@link JavaBytes}, which
//      a `number[]` cannot satisfy.
//   2. `getAlgorithm()` returns a `java.lang.String`, so
//      `rng.getAlgorithm() === "NativePRNG"` is ALWAYS FALSE — and so is
//      `alg === String(alg)`. Hence `JavaString`, which forces `String(...)`.
//   3. `nextLong()` is lossy in every draw. See the method's own note.
//
// Managed file — regenerated by `aic workspace update`.

/**
 * One element of a Java `byte[]` as Rhino hands it over: a SIGNED byte
 * (`-128..127`), never an unsigned `0..255`. Measured over 256 random bytes
 * (min `-127`, max `127`) and a 256-byte `generateSeed` (min `-128`, max
 * `124`).
 *
 * Still a `number` for arithmetic (`byte & 0xff`, `byte < 0`). `toString` is
 * `never` so `bytes[i].toString(16)` — the unmasked-hex trap, which yields
 * `-f` for a negative byte — is a compile error. Mask first; the result of
 * `&` is a plain `number` and renders normally.
 *
 * The workspace sets `noUncheckedIndexedAccess`, so an element read is
 * `JavaByte | undefined` and a `.cjs` file has no `!` to assert it away.
 * Bind it and narrow — this is the loop that compiles:
 *
 *     var hex = "";
 *     for (var i = 0; i < bytes.length; i++) {
 *       var b = bytes[i];
 *       if (b === undefined) { continue; }
 *       var pair = (b & 0xff).toString(16);
 *       hex += pair.length === 1 ? "0" + pair : pair;
 *     }
 *
 * Mirrors `JavaByte` in the TypeScript endpoint project
 * (`typescript/framework/java.ts`) so one mental model covers both.
 */
type JavaByte = number & {
  readonly __javaByte: void;
  readonly toString: never;
};

/**
 * A Java `byte[]` (runtime class `[B`). NOT a JS array — `Array.isArray` is
 * `false` — although Rhino does bolt JS array methods onto it.
 *
 * This is the only thing {@link java.security.SecureRandom.nextBytes} actually
 * fills. There is no JavaScript literal for one; the sole way to make one on
 * this engine is {@link java.lang.reflect.Array.newInstance}:
 *
 *     var bytes = java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE, 32);
 *     new java.security.SecureRandom().nextBytes(bytes);
 */
interface JavaBytes {
  readonly [index: number]: JavaByte;
  readonly length: number;
}

declare namespace java {
  namespace lang {
    /**
     * A `java.lang.Class` token. Opaque — declared only so
     * {@link reflect.Array.newInstance} can be given a component type that
     * fixes the array's element type.
     */
    interface Class<T> {
      readonly __javaClass: T;
    }

    const Byte: {
      /** The `byte` primitive class. `String(java.lang.Byte.TYPE)` is `"byte"`. */
      readonly TYPE: Class<JavaByte>;
    };

    namespace reflect {
      const Array: {
        /**
         * Allocate a Java array. Declared only for `byte[]`, the one case a
         * script cannot express in JavaScript and the one
         * {@link java.security.SecureRandom.nextBytes} requires.
         *
         * `length` 0 is accepted and yields an empty array.
         */
        newInstance(
          componentType: Class<JavaByte>,
          length: number
        ): JavaBytes;
      };
    }
  }

  namespace security {
    /**
     * `java.security.SecureRandom`. Reachable and fully functional in IDM
     * scripts (measured 2026-09-10).
     *
     * The no-arg constructor resolves to algorithm `NativePRNG` from provider
     * `SUN` on this tenant. Do not hard-code that: it is a JVM/provider
     * property, not an AIC guarantee.
     */
    class SecureRandom {
      constructor();

      /**
       * Measured present: `SHA1PRNG`, `NativePRNG`, `DRBG`. An unknown
       * algorithm throws `NoSuchAlgorithmException`, which surfaces as a
       * `JavaException` and is NOT catchable by class — match on the message.
       */
      static getInstance(algorithm: string): SecureRandom;

      /**
       * Resolves to `NativePRNGBlocking` here — it reads `/dev/random` and
       * **can block** when the host is short of entropy. In a request-path
       * script (an endpoint, a managed hook) that is a stall with no timeout
       * you control. Prefer `new SecureRandom()`, which is `NativePRNG` and
       * non-blocking, unless you specifically need a blocking source.
       */
      static getInstanceStrong(): SecureRandom;

      /** Seed bytes from the system entropy source. Static; no instance needed. */
      static getSeed(numBytes: number): JavaBytes;

      /**
       * Returns a `java.lang.String`, NOT a JS string. `getAlgorithm() ===
       * "NativePRNG"` is always false, and so is `alg === String(alg)`. Wrap
       * with `String(...)` before comparing.
       */
      getAlgorithm(): JavaString;

      /**
       * Fill `bytes` in place. The argument must be a real Java `byte[]` from
       * {@link java.lang.reflect.Array.newInstance} — passing a JS array
       * compiles nowhere and, at runtime, silently fills a throwaway copy and
       * leaves yours untouched.
       */
      nextBytes(bytes: JavaBytes): void;

      /** Seed bytes, possibly from a blocking source. Elements are signed. */
      generateSeed(numBytes: number): JavaBytes;

      /** A uniformly random 32-bit `int`. Exact — an `int` fits a JS number. */
      nextInt(): number;

      /** `0 <= n < bound`. `bound <= 0` throws `IllegalArgumentException`. */
      nextInt(bound: number): number;

      /** `origin <= n < bound` (JDK 17+; measured 10..19 for `nextInt(10, 20)`). */
      nextInt(origin: number, bound: number): number;

      /**
       * LOSSY, ALWAYS. A Java `long` is 64-bit; a JS number keeps 53 bits of
       * mantissa. Measured 100 draws, 100 of which exceeded
       * `Number.MAX_SAFE_INTEGER` — the low digits are rounding noise, so two
       * distinct longs can arrive equal.
       *
       * Never use this for an identifier, a nonce, or anything compared for
       * equality. Use {@link nextBytes} and render the bytes instead. It is
       * fine as a seed.
       */
      nextLong(): number;

      /** `0.0 <= n < 1.0`. Exact — a double is a JS number. */
      nextDouble(): number;

      /** `0.0 <= n < 1.0`, widened from a Java `float`. Prefer `nextDouble()`. */
      nextFloat(): number;

      nextBoolean(): boolean;

      /** Normal distribution, mean 0, standard deviation 1. */
      nextGaussian(): number;

      /**
       * Supplements the existing seed; it does not replace it, so this cannot
       * make the sequence reproducible. Reseeding a `SecureRandom` is almost
       * never what you want.
       */
      setSeed(seed: number): void;
      setSeed(seed: JavaBytes): void;
    }
  }
}
